-- GENERATED by render.mjs; edit manifest.json entries and 04_业务模块/ instead.
-- 期权；任务86840；grp_id=01。
-- 本轮只重构前三站；客户、保证金、条款、金额、估值仍沿用原连接/公式。
--
-- 01_公共输入 → 02_核心加工（合约基础 → 标的识别 → 经营分类）
--                              ↓
--                      本脚本补充关联 ← 03_补充资料
--                              ↓
--                      04_金额与输出 → 写入01分区
--
-- 阅读入口：../04_业务模块/01_期权/README.md；核心加工的三个阶段逐条承接，不按合约号重新拼回。
-- 文件原编号表示业务主题，目录编号表示阅读层次；补充资料之间没有串行依赖。
-- @include由render.mjs展开，不是Hive原生语法；本文件不是直接部署版本。
-- 【用途】沿用四个分支原有Hive/MapReduce执行设置；被主脚本首先引用，不包含业务筛选逻辑。
-- 【文件合并】启用Map及MapReduce输出文件合并；目标合并大小和小文件均值阈值均为1 GiB。
-- 【输入切片】使用CombineHiveInputFormat，split最大/最小值均为1 GiB；这是执行参数，不代表数据行粒度。
-- 【边界】实际效果取决于引擎与作业配置；本次仅保留原设置，没有调参或运行验证。
set hive.merge.mapfiles=true ;
set hive.merge.mapredfiles=true;
set hive.merge.size.per.task=1073741824;
set hive.merge.smallfiles.avgsize=1073741824;
set hive.merge.orcfile.stripe.level=false;

set hive.input.format=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat;
set mapreduce.input.fileinputformat.split.maxsize=1073741824;
set mapreduce.input.fileinputformat.split.minsize=1073741824;


WITH
-- 公共视图裁剪加工日
-- 模块职责：把可跨分支复用的视图裁剪到本次加工日，不在此生成最终90列。
-- 输出三组独立CTE：交易账簿 sale_trade、组合计划 sale_bundle_plan、客户 sale_customer。
-- 粒度边界：本模块只过滤快照，不做去重；交易键、组合号、客户号是否唯一需另行验证。
-- 用途：选择本次加工快照的公共资料。
-- 01/02/04保留境内+香港 UNION ALL；03仅境内；不增加去重。
-- 交易范围：主脚本以此为起点；保留book侧账簿键与公司，分别用于落表和互换经营分类。
sale_trade AS (
    SELECT key_otc_trade_id, internal_trade_id, key_instrument_id, key_book_id,
           book_key_book_id, business_type, department, book_name, desk, company
    FROM v_t98_sale_trade_scope
    WHERE busi_date = '${data_day_str}'
),

-- 组合计划：在主脚本按合约 bundle_id LEFT JOIN，计划缺失不会在本模块剔除交易。
sale_bundle_plan AS (
    SELECT bundle_id, key_plan_id, deduction_pattern
    FROM v_t98_sale_bundle_plan
    WHERE busi_date = '${data_day_str}'
),

-- 客户：由客户映射的 outside_ctpty_code 连接 client_id；境内/香港仍为 UNION ALL，不按客户号合并。
sale_customer AS (
    SELECT client_id, abbreviation, corporate_name, Signature_Name, industry, aptitude, commission_rate, client_qualify_review
    FROM v_t98_sale_counterparty
    WHERE busi_date = '${data_day_str}'
)

,
-- 第一站：合约+结构+源类型字典；在此限定合约状态
-- 01期权试点 / 第一站：哪些合约进入加工，以及它们的结构是什么？
-- 输入：加工日合格交易 + 期权合约 + 期权结构 + 源类型字典。
-- 输出 option_base：保留实际连接后的每条记录，不声明“一合约一行”。
--
-- 合格交易 --交易键，INNER--> 期权合约 --交易键，LEFT--> 期权结构
--                                      结构类型/子类型 --LEFT--> 源类型字典
-- 状态范围在这里限定；字典/结构缺失仍保留，多条匹配不去重。
-- 字段显式命名：后续不用再记trade/deal/ds分别存放哪些属性。

option_contract AS (
select * from odata_n_tit.d_ref_otc_option_deal where busi_Date = '${data_day_str}'  --场外交易-期权交易合同要素表
),

option_structure AS (
select * from odata_n_tit.d_ref_option_deal_structure where busi_Date = '${data_day_str}'  --场外交易-期权交易结构表
),

contract_type_dictionary AS (
select *
    from PDATA_N.REF_DW_CD_VAL -- 仓库代码取值；dw_cd_id=仓库代码编号，dw_cd_val=代码取值，dw_cd_val_desc=取值描述
    where dw_cd_id = 'CD382' and remark = 'TITANS场外衍生品合约类型'
),

subtype_dictionary AS (
select *
    from PDATA_N.REF_DW_CD_VAL -- 仓库代码取值；dw_cd_id=仓库代码编号，dw_cd_val=代码取值，dw_cd_val_desc=取值描述
    where dw_cd_id = 'CD381'
),
/**
* 期权业务加工的基础层（option_base）
**/
option_base AS (
    SELECT
        trade.key_otc_trade_id AS trade_id, -- 交易键：后续条款和保证金关联入口
        trade.internal_trade_id AS contract_id, -- 合约编号
        trade.key_instrument_id AS contract_instrument_id, -- 合约工具键：费率及估值关联入口
        trade.key_book_id AS trade_book_id, -- 交易侧账簿键：估值连接使用
        trade.book_key_book_id AS book_id, -- 账簿侧键：目标Book_Agt_Id的原来源
        trade.business_type AS trade_business_type, -- 源业务类型
        trade.department AS book_department, -- 账簿部门
        trade.book_name AS book_name, -- 账簿名
        trade.desk AS book_desk, -- 柜台：经营分类使用
        deal.key_otc_trade_id AS option_trade_id, -- 期权合约交易键
        deal.key_ctpty_id AS counterparty_key, -- 交易对手编号：经客户映射换取外部唯一码
        deal.bundle_id AS bundle_id, -- 组合编号
        deal.private_placement AS private_placement_flag, -- 限售标志
        deal.seller AS seller_id, -- 卖方，关联交易对手ID
        deal.collateral_notional_currency AS collateral_notional_currency, -- 绝对名义本金币种：汇率判断输入
        deal.settlement_currency AS settlement_currency, -- 结算币种
        deal.initial_notional AS initial_notional, -- 初始名义本金（元）
        deal.notional AS notional, -- 名义本金（元）（元数据原注释）
        deal.collateral_notional AS collateral_notional, -- 绝对名义本金（元）
        deal.early_term_date AS early_term_date, -- 提前终止日
        deal.payment_date AS payment_date, -- 兑付日期
        deal.time_to_maturity AS term_days, -- 期限天数
        deal.contr_status AS contract_status, -- 源合约状态
        deal.hedge_type AS hedge_type, -- 对冲类型
        deal.premium AS premium, -- 期权费（元）
        deal.premium_date AS premium_date, -- 期权费支付日
        deal.contract_code AS external_contract_code, -- 外部合约编号
        deal.premium_rate AS premium_rate, -- 期权费率（%）
        ds.key_otc_trade_id AS structure_trade_id, -- 结构交易键（LEFT JOIN缺失时为NULL）
        ds.start_date AS start_date, -- 期初定价日：分类日期及汇率连接使用
        ds.end_date AS end_date, -- 期末定价日
        ds.contract_type AS source_contract_type, -- 期权类型；源字典CONTRACT_TYPE
        ds.contract_sub_type AS source_contract_sub_type, -- 期权子类型；源字典CONTRACT_SUBTYPE
        ds.underlying_ins_id AS underlying_instrument_id, -- 标的内部代码：下一阶段关联入口
        ds.underlying_wind_code AS underlying_wind_code, -- 标的WIND代码，多标的以逗号分隔
        ds.underlying_currency AS underlying_currency, -- 结构标的币种
        ds.init_notl_exchange_rate AS initial_exchange_rate, -- 期初汇率2（名义本金币种对结算币种，计算使用）
        ds.knockout_extra_par AS knockout_extra_par, -- 上涨参与率（元数据原注释）；此字段被输出为敲出参与率
        ds.rebate_not_abs AS rebate_not_abs, -- 敲出收益率（%）
        ds.cross_currency_type AS cross_currency_type, -- 跨币种类型
        ds.fx_rate_model AS fx_rate_model, -- 【AI】汇率模式（元数据原标记）
        sct.dw_cd_val_desc AS source_contract_type_desc, -- 源合约类型字典描述
        ssct.dw_cd_val_desc AS source_contract_sub_type_desc -- 源子类型字典描述
    FROM sale_trade trade  --账簿范围内交易
    inner join option_contract deal  --场外期权交易合同要素表
on deal.key_otc_trade_id = trade.key_otc_trade_id
    left join option_structure ds  --期权交易结构表
on deal.key_otc_trade_id = ds.key_otc_trade_id
    left join contract_type_dictionary sct --TITANS场外衍生品合约类型
on sct.dw_cd_val = ds.contract_type
    left join subtype_dictionary ssct --合约子类型
on ssct.dw_cd_val = ds.contract_sub_type
    where deal.Contr_Status in ('EFFECTIVE', 'EFFECTIVE_PENDING', 'TERMINATED', 'TERMINATING', 'TERMINATING_PENDING')

)

,
-- 第二站：把c/ins/fu/bc及标的字典的关联与取值收进同一模块
-- 01期权试点 / 第二站：这份合约挂钩什么标的？
-- 输入 option_base；输出 option_underlying = 原记录 + 下方7个标的属性。
--
-- b.underlying_instrument_id（结构标的内部代码）
--   +--> 工具池 c：债券展示类型
--   +--> 证券 ins：名称、证券集
--   +--> 期货 fu：期货类型
--   \--> 篮子 bc：成分先关联证券/期货，再按篮子证券内码汇总
--          ↓
--   名称/证券集/期货类型按各字段COALESCE取值；只有NULL回退。
--
-- 分类读classification_ins_family；展示读source_underlying_type，两者不能混用。
-- 整个阶段不对合约行去重/聚合；只有篮子自身按原SQL聚合，保留原重复匹配影响。
-- 下方证券/篮子元数据注释沿用本地目录；带【AI】标记的原注释不作为人工确认定义。

instrument_pool AS (
-- key_instrument_id：标的ID；key_pool_id：标的池ID；interotc_underlying_category：报价系统标的小类。
select * from odata_n_tit.r_cfg_instrument_pool_props -- 配置-标的池标的属性表
    where busi_Date = '${data_day_str}' and KEY_POOL_ID = '10000'
),

instrument_snapshot AS (
select *
        from odata_n_tit.d_ref_instrument -- 证券-证券基本信息
        where busi_Date = '${data_day_str}' 
),

future_properties AS (
select *
        from odata_n_tit.d_ref_future_properties -- 【AI】证券-期货信息表（目录原注释）
        where busi_Date = '${data_day_str}' 
),

/**
* 把“篮子证券 → 篮子成分证券 → 成分证券属性”汇总成一行，形成篮子的标签摘要信息。
一个篮子证券（basket）里面有哪些成分证券，然后把成分证券的信息聚合到一行。
**/
basket_summary AS ( 
select
        bc.key_instrument_id, -- 篮子证券内码：汇总结果的分组键
        concat_ws(';',collect_list(ins.ins_sht_desc)) as ins_sht_desc, -- ins_sht_desc：证券简称；成分简称以分号拼接
        concat_ws(';',collect_list(ins.ins_lng_desc)) as ins_lng_desc, -- ins_lng_desc：证券全名；成分全名以分号拼接
        concat_ws(';',collect_set(ins.ins_family)) as ins_family, -- ins_family：证券集，字典项=INSTRUMENTFAMILY；去重拼接
        concat_ws(';',collect_set(fu.future_type)) as future_type -- future_type：期货类型；去重拼接
    from (
        select *
        from odata_n_tit.d_ref_basket_constituent -- 篮子成分表
        where busi_Date = '${data_day_str}' 
        ) bc
    left join (
        select *
        from odata_n_tit.d_ref_instrument -- 证券-证券基本信息
        where busi_Date = '${data_day_str}'
        ) ins
    on ins.key_instrument_id = bc.underlying_inst_id -- ⭐证券内码 = 篮子成分证券内码（不是篮子内码）
    left join (
        select *
        from odata_n_tit.d_ref_future_properties -- 【AI】证券-期货信息表（目录原注释）
        where busi_Date = '${data_day_str}'
        ) fu
    on fu.key_instrument_id = bc.underlying_inst_id -- 证券内码-期货代码 = 篮子成分证券内码
    group by bc.key_instrument_id -- 按篮子证券内码收回每篮子一行；维表重复匹配仍会影响拼接内容
),

underlying_type_dictionary AS (
select *
    from PDATA_N.REF_DW_CD_VAL -- 仓库代码取值；dw_cd_val=代码取值，dw_cd_val_desc=取值描述
    where dw_cd_id = 'CD128' and remark = 'TITANS场外衍生品标的类型'
),

/**
* 期权标的（underlying）的标准化画像加工
**/
option_underlying AS ( 
    SELECT b.*,
        -- 分类使用的证券集，不能替换成下方BOND改写后的展示类型
        coalesce(bc.ins_family,ins.ins_family) AS classification_ins_family,
        -- 标的名称：篮子优先，单证券回退
        coalesce(bc.ins_sht_desc,ins.ins_sht_desc) AS underlying_name,
        -- 股票市场/非股票分类：沿用证券集与结构标的币种的判断
        case when coalesce(bc.ins_family,ins.ins_family) in ('EQUITY', 'GDR') and b.underlying_currency not in ('HKD', 'USD') then 'OTH_STOCK'
         when coalesce(bc.ins_family,ins.ins_family) in ('EQUITY', 'GDR') and b.underlying_currency = 'HKD' then 'HK_STOCK'
         when coalesce(bc.ins_family,ins.ins_family) in ('EQUITY', 'GDR') and b.underlying_currency = 'USD' then 'US_STOCK'
         when coalesce(bc.ins_family,ins.ins_family) not in ('EQUITY', 'GDR') then 'NON_STOCK'
         else '-' end AS underlying_type,
        -- 展示源类型：bond、篮子用证券集
        if(c.interotc_underlying_category = 'BONDS', 'BOND', coalesce(bc.ins_family,ins.ins_family)) AS source_underlying_type,
        -- 展示源类型描述
        if(c.interotc_underlying_category = 'BONDS', '债券', sutd.dw_cd_val_desc) AS source_underlying_type_desc,
        -- 标的全名：篮子优先
        coalesce(bc.ins_lng_desc,ins.ins_lng_desc) AS underlying_long_name,
        -- 期货类型：篮子优先，期货属性回退
        coalesce(bc.future_type,fu.future_type) AS future_type
    FROM option_base b --期权宽表加工
    left join instrument_pool c
on c.key_instrument_id = b.underlying_instrument_id
    left join instrument_snapshot ins --证券信息
on ins.key_instrument_id = b.underlying_instrument_id
    left join future_properties fu --期货信息
on fu.key_instrument_id = b.underlying_instrument_id
    left join basket_summary bc --篮子主体+成分信息
on bc.key_instrument_id = b.underlying_instrument_id
    left join underlying_type_dictionary sutd --标的类型代码
on sutd.dw_cd_val = coalesce(bc.ins_family,ins.ins_family)
)

,
-- 第三站：逐行生成经营类别代码、名称
/*
* 根据期权标的、合约类型、业务属性，把 option_underlying 里的期权合约划分经营类别，新增 Contr_Type_Cd 和 Contr_Type_Desc。
  - 老合约 → 老分类体系
  - 新合约 → 新分类体系

新口径
      option_underlying
            ↓
      classification_ins_family
            ↓
      EQUITY/GDR → 个股期权
      INDEX/FUND → 指数/ETF期权
      QIS        → 北上 / 现货 / 非现货QIS
      RISKY系    → 限售 / 流通股
      其他       → 其他期权
*/
option_classified AS ( 
    SELECT u.*,
if(
        substring(u.start_date, 1, 10) <= '2025-03-31'
-- 旧口径：按类型及业务属性细分，保持原有顺序。
        ,case when u.source_contract_type = 'AUTOCALL' and u.source_contract_sub_type not in ('SNOWBALL','SECURED') and u.classification_ins_family in ('EQUITY', 'GDR') then 'OPTION_AUTOCALL_STOCK'
              when u.source_contract_type = 'AUTOCALL' and u.source_contract_sub_type not in ('SNOWBALL','SECURED') and u.classification_ins_family not in ('EQUITY', 'GDR') then 'OPTION_AUTOCALL_NONSTOCK'
              when u.source_contract_type = 'AUTOCALL' and u.source_contract_sub_type in ('SNOWBALL','SECURED') then 'OPTION_SNOWBALL_SECURED'
              when u.source_contract_type = 'AIRBAG' and u.classification_ins_family in ('EQUITY', 'GDR') then 'OPTION_AIRBAG_STOCK'
              when u.source_contract_type = 'AIRBAG' and u.classification_ins_family not in ('EQUITY', 'GDR') then 'OPTION_AIRBAG_NONSTOCK'
              when u.source_contract_type in ('RISKY','AIRBAGX') and u.classification_ins_family = 'EQUITY' and u.private_placement_flag = 'Y' then 'OPTION_RISKY_AIRBAGX_PRI_STOCK'
              when u.source_contract_type in ('RISKY','AIRBAGX') and coalesce(u.private_placement_flag,'N') <> 'Y' then 'OPTION_RISKY_AIRBAGX_CIR_STOCK'
              when u.book_desk = 'OTCHK_QIS' and u.classification_ins_family = 'QIS' and u.seller_id = '11613' then 'OPTION_N_CROSS_QTF_STRG_IDX'
              when (u.source_contract_type not in ('AUTOCALL','AIRBAG','RISKY','AIRBAGX') or u.source_contract_type is null) and u.classification_ins_family in ('EQUITY', 'GDR') then 'OPTION_OTHER_STOCK'
              when (u.source_contract_type not in ('AUTOCALL','AIRBAG','RISKY','AIRBAGX') or u.source_contract_type is null) and u.classification_ins_family not in ('EQUITY', 'GDR') then 'OPTION_OTHER_NONSTOCK'
              end
-- 新口径：按下列条件优先级匹配，末尾保留原兜底。
        ,case when u.classification_ins_family in ('EQUITY', 'GDR')
                    and u.source_contract_type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL','CUSTOMISED')
                    and not(u.source_contract_type = 'AUTOCALL' and u.source_contract_sub_type = 'SNOWBALL')
                    then 'OPTION_STOCK'
              when u.classification_ins_family in ('INDEX', 'FUND')
                    and(u.source_contract_type in ('ACCUMULATOR','DECCUMULATOR','AIRBAG') or (u.source_contract_type = 'AUTOCALL' and u.source_contract_sub_type <> 'SNOWBALL'))
                    then 'OPTION_IDX_ETF'
              when u.book_desk = 'OTCHK_QIS' and u.classification_ins_family = 'QIS' and u.seller_id = '11613' then 'OPTION_N_CROSS_QTF_STRG_IDX'
              when u.classification_ins_family = 'QIS' and u.underlying_wind_code not in('GAMMA.WI', 'CHARM.WI') then 'OPTION_QTF_STRG_IDX_SPOT'
              when u.classification_ins_family = 'QIS' and u.underlying_wind_code in('GAMMA.WI', 'CHARM.WI') then 'OPTION_QTF_STRG_IDX_NONSPOT'
              when u.source_contract_type in ('RISKY','AIRBAGX') and u.classification_ins_family = 'EQUITY' and u.private_placement_flag = 'Y' then 'OPTION_RISKY_AIRBAGX_PRI_STOCK'
              when u.source_contract_type in ('RISKY','AIRBAGX') and coalesce(u.private_placement_flag,'N') <> 'Y' then 'OPTION_RISKY_AIRBAGX_CIR_STOCK'
              else 'OPTION_OTHER_NONSTOCK'
              end
    ) as Contr_Type_Cd, -- 合约类型代码
-- B. 经营类别名称：沿用独立条件树；不要只靠代码重新映射中文名。
if(
        substring(u.start_date, 1, 10) <= '2025-03-31'
-- 旧口径：按类型及业务属性细分，保持原有顺序。
        ,case when u.source_contract_type = 'AUTOCALL' and u.source_contract_sub_type not in ('SNOWBALL','SECURED') and u.classification_ins_family in ('EQUITY', 'GDR') then '自动赎回（除保本雪球和保本敲入型雪球）'
              when u.source_contract_type = 'AUTOCALL' and u.source_contract_sub_type not in ('SNOWBALL','SECURED') and u.classification_ins_family not in ('EQUITY', 'GDR') then '自动赎回（除保本雪球和保本敲入型雪球）'
              when u.source_contract_type = 'AUTOCALL' and u.source_contract_sub_type in ('SNOWBALL','SECURED') then '保本雪球和保本敲入型雪球'
              when u.source_contract_type = 'AIRBAG' and u.classification_ins_family in ('EQUITY', 'GDR') then '安全气囊'
              when u.source_contract_type = 'AIRBAG' and u.classification_ins_family not in ('EQUITY', 'GDR') then '安全气囊'
              when u.source_contract_type in ('RISKY','AIRBAGX') and u.classification_ins_family = 'EQUITY' and u.private_placement_flag = 'Y' then 'Risky和安全气囊X（限售股）'
              when u.source_contract_type in ('RISKY','AIRBAGX') and coalesce(u.private_placement_flag,'N') <> 'Y' then 'Risky和安全气囊X（流通股）'
              when u.book_desk = 'OTCHK_QIS' and u.classification_ins_family = 'QIS' and u.seller_id = '11613' then '北上量化策略指数期权'
              when (u.source_contract_type not in ('AUTOCALL','AIRBAG','RISKY','AIRBAGX') or u.source_contract_type is null) and u.classification_ins_family in ('EQUITY', 'GDR') then '其他期权（除Risky和安全气囊X）'
              when (u.source_contract_type not in ('AUTOCALL','AIRBAG','RISKY','AIRBAGX') or u.source_contract_type is null) and u.classification_ins_family not in ('EQUITY', 'GDR') then '其他期权（除Risky和安全气囊X）'
               end 
-- 新口径：按下列条件优先级匹配，末尾保留原兜底。
        ,case when u.classification_ins_family in ('EQUITY', 'GDR')
                    and u.source_contract_type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL','CUSTOMISED')
                    and not(u.source_contract_type = 'AUTOCALL' and u.source_contract_sub_type = 'SNOWBALL')
                    then '个股期权'
              when u.classification_ins_family in ('INDEX', 'FUND')
                    and(u.source_contract_type in ('ACCUMULATOR','DECCUMULATOR','AIRBAG') or (u.source_contract_type = 'AUTOCALL' and u.source_contract_sub_type <> 'SNOWBALL'))
                    then '指数/ETF期权'
              when u.book_desk = 'OTCHK_QIS' and u.classification_ins_family = 'QIS' and u.seller_id = '11613' then '北上量化策略指数期权'
              when u.classification_ins_family = 'QIS' and u.underlying_wind_code not in('GAMMA.WI', 'CHARM.WI') then '量化策略指数期权（现货类）'
              when u.classification_ins_family = 'QIS' and u.underlying_wind_code in('GAMMA.WI', 'CHARM.WI') then '量化策略指数期权（非现货类）'
              when u.source_contract_type in ('RISKY','AIRBAGX') and u.classification_ins_family = 'EQUITY' and u.private_placement_flag = 'Y' then 'Risky和安全气囊X（限售股）'
              when u.source_contract_type in ('RISKY','AIRBAGX') and coalesce(u.private_placement_flag,'N') <> 'Y' then 'Risky和安全气囊X（流通股）'
              else '其他期权'
              end
    ) as Contr_Type_Desc -- 合约类型描述
    FROM option_underlying u
)

,
-- 03_补充资料：并列来源，尚未改为阶段式；实际关联仍在下方
-- 本轮未改的后续来源：客户映射、关联合约属性、保证金参数及保证金互换关系。
-- 仍由主脚本按原连接条件使用；本文件不是新的汇总表，不合并或去重。
-- 从原02_合约及来源属性迁入；客户outside_ctpty_code接公共客户，保证金按交易键接合约。
customer_mapping AS (
-- key_ctpty_id：交易对手ID；outside_ctpty_code：交易对手外部唯一码。
select * from odata_n_tit.d_ref_ctpty_mapping where busi_Date = '${data_day_str}' -- 交易参数-交易对手映射表
),

--关联期权合约关系relatedOption：
    -- 两个 OTC 合约之间存在业务关系：一个合约关联另一个期权合约。
related_contract AS (
select * from odata_n_tit.d_trd_otc_contr_props -- 【AI】交易-场外合约结构-其他属性表
    where busi_Date = '${data_day_str}' and property_name = 'relatedOption'
),

--补充期权/OTC合约的履约保证金参数
margin_parameters AS (
-- margin_balance_init=初始履约保障金额(元)，initial_margin=保证金初始线(%)，basic_margin_rate=基础保证金率，deduction=抵扣模式（现金抵扣等）。
select * from odata_n_tit.d_ref_otc_contr_margin_param -- 【AI】合约-静态履约保证金参数
    where busi_Date = '${data_day_str}'
),

--这个期权合约的保证金管理关联哪些 TRS 合约？
    --用于保证金管理的期权-TRS合约关联关系表（只取长持有型互换（LONG_HOLD_SWAP））
    -- 可能原因：业务上只有 LONG_HOLD_SWAP 承接这类期权保证金
margin_trs_links AS (
-- option_key_otc_trade_id：期权合约ID；trs_key_otc_trade_id：互换合约ID。
select option_key_otc_trade_id, concat_ws(';',collect_set(trs_key_otc_trade_id)) as Marg_Agt_Id
    from (
        select * from odata_n_tit.f_ref_option_margin_trs_relation -- 期权合约与互换合约关联关系表；status：Y-有效，N-无效
        where busi_date = '${data_day_str}' and status = 'Y'
        ) a
    join (
        select * from odata_n_tit.d_ref_trs -- 场外交易-TRS；trs_type：互换类型
        where busi_date = '${data_day_str}' and trs_type = 'LONG_HOLD_SWAP' --只取长持有型互换（LONG_HOLD_SWAP）
        ) b
    on a.trs_key_otc_trade_id = b.key_otc_trade_id
    group by option_key_otc_trade_id
)

,
-- 阅读分组：结算净收取 → 首条计提费率 → 票息 → 敲出/敲入 → 执行价档位 → 参与率档位。
-- 模块输出多个CTE而非一张表：结算按交易连、费率按工具连，其余条款先按交易聚合再连接。
-- 各CTE的输出键见下方；不要把原始条款明细互相JOIN后才聚合，那会改变多条款组合的行数。
-- 用途：期权条款
-- CR/KO/KI/STRIKE/PR 分别按 key_otc_trade_id 聚合；结算保持原有粒度，费率按工具选首条。
-- 加工日：${data_day_str}；复用次数1（任务86840）。
-- 期权结算（ODS）：按交易键连接，提供 NET_PNL → net_coll。
-- 这里没有汇总或选最新；多条结算记录可能扩展主查询行数，不能擅自改成一条。
option_settlement AS (
    select *
    -- key_otc_trade_id：内部合约ID；net_pnl：交易净收取（元）。
    from odata_n_tit.d_TRD_OPTION_DEAL_SETTLEMENT -- 【AI】场外交易-期权交易结算表
    WHERE busi_date = '${data_day_str}'
    ),

-- 【初始】期权权利金计提费率
first_premium_fee AS (
    select *
    from (
        SELECT *, row_number() over(partition by KEY_INSTRUMENT_ID order by CALC_DATE) as rn -- calc_date：计提日期
        FROM odata_n_tit.d_trd_daily_accrual_fee -- 【AI】按日应计提费用表
        where busi_Date = '${data_day_str}' and fee_type = 'ACCRUAL_PREMIUM_FEE' --期权日计提费用类型
        ) t
    where rn = 1
    ),

-- 票息（RODC）：结构化期权产品中的票息条款（coupon / yield component），常见于雪球、自动赎回等带票息收益的产品
-- 按交易键把 COUPON_RATE 转 double 再转 string，去重并用分号拼接。
coupon_terms AS (
    SELECT KEY_OTC_TRADE_ID, concat_ws(';',collect_set(cast(cast(COUPON_RATE as double) as string))) as COUPON_RATE
    FROM odata_n_tit.d_REF_OPTION_DEAL_CR -- 【AI】场外交易-期权合约结构-票息表
    where busi_date = '${data_day_str}'
    group by KEY_OTC_TRADE_ID
    ),

--提取自动赎回类期权（Autocall，雪球等）里的障碍条款（Barrier Terms）。
    -- 敲出（KO）：按交易键取观察日最小/最大值，上下敲出障碍比例分别去重拼接。
    -- 输出模块用 coalesce(上障碍,下障碍)，是优先取非NULL值，不是合并上下障碍。
knockout_terms AS (
    SELECT 
        KEY_OTC_TRADE_ID,
        MIN(substring(OBS_DATE,1,10)) as MIN_OBS_DATE,--OBS_DATE：最小观察日；
        Max(substring(OBS_DATE,1,10)) as Max_OBS_DATE,--OBS_DATE：最大观察日；
        concat_ws(';',collect_set(cast(cast(UP_KO_BARRIER_PCT as double) as string))) as UP_KO_BARRIER_PCT, --上敲出障碍%
        concat_ws(';',collect_set(cast(cast(DOWN_KO_BARRIER_PCT as double) as string))) as DOWN_KO_BARRIER_PCT --下敲出障碍%
    FROM odata_n_tit.d_REF_OP_DEAL_AUTOCALL_KODATE -- 【AI】场外交易-期权敲出观察日及票息信息
    where busi_date = '${data_day_str}'
    GROUP BY KEY_OTC_TRADE_ID
    ),

-- 敲入（KI）：按交易键汇总下敲入障碍比例，转数值后去重拼接。
-- 一行对应一个交易键；多档障碍保留为字符串，不压缩成单个价格。
knockin_terms AS (
    SELECT 
        KEY_OTC_TRADE_ID,
        concat_ws(';',collect_set(cast(cast(DOWN_KI_BARRIER_PCT as double) as string))) as DOWN_KI_BARRIER_PCT --下敲入障碍（%）。
    FROM odata_n_tit.d_REF_OP_DEAL_AUTOCALL_KIDATE -- 【AI】场外交易-期权敲入观察日及票息信息
    where busi_date = '${data_day_str}'
    GROUP BY KEY_OTC_TRADE_ID
    ),

-- 执行价档位（STk）：SEQ=0/1/2 分别生成执行价、下跌保护执行价、封顶价。
-- 每档用 max(if(...,数值,0))；非本档行的0可能影响最大值，不能随意改为NULL。
strike_terms AS (
    select
        KEY_OTC_TRADE_ID,
        max(if(SEQ = '0', cast(STRIKE_PCT as double), 0)) as Strk_PCT,  --普通执行价
        max(if(SEQ = '1', cast(STRIKE_PCT as double), 0)) as DOWN_Strk_PCT, --下保护执行价
        max(if(SEQ = '2', cast(STRIKE_PCT as double), 0)) as UP_Strk_PCT --上封顶执行价
    from odata_n_tit.d_REF_OPTION_DEAL_STRIKE -- 【AI】场外交易-期权合约结构-执行价格
    where busi_date = '${data_day_str}'
    group by KEY_OTC_TRADE_ID
    ),

--把期权结构里的参与率（Participation Rate）按方向拆成向上参与率和向下参与率。
--参与率：标的涨跌幅，有多少比例计入产品收益计算。
    --向上参与：标的上涨→参与收益
    --向下参与：标的下跌→按比例计算损益
-- 参与率档位（pr）：SEQ=0/1 分别生成向上/向下参与率，按交易键聚合。
-- 同样沿用 max(if(...,数值,0))；不把多条参与率求和或取平均。
participation_terms AS (
    SELECT
        KEY_OTC_TRADE_ID,
        max(if(SEQ = '0', cast(participation_rate as double), 0)) as Up_Prtc_rate, --向上参与率
        max(if(SEQ = '1', cast(participation_rate as double), 0)) as Down_Prtc_rate  --向下参与率
    -- KEY_OTC_TRADE_ID：内部合约ID；SEQ：参与率序号；participation_rate：参与率（%）。
    FROM odata_n_tit.d_REF_OPTION_DEAL_PR -- 【AI】场外交易-期权合约结构-参与率表
    WHERE busi_date = '${data_day_str}'
    group by KEY_OTC_TRADE_ID
    )

,
/*
* 从日终估值结果表中，按“工具 + 账簿”找到最新一条估值记录，作为该期权的期初 NPV。

- 【指标字段】期初NPV：
    - 期权没有固定现金流，估值模型（未来各种可能情景→概率加权→折现→当前价值）
    
*/
latest_valuation AS (
    select
        key_instrument_id, -- 证券内码
        initial_npv, -- 期初NPV
        key_book_id, -- 账簿ID
        row_number() over(partition by key_instrument_id,key_book_id order by quote_date desc) as rk --quote_date：计算日期
    from odata_n_tit.d_pos_eod_calc_metrics -- 日终持仓-指标计算结果表；
    where busi_date = '${data_day_str}' and ins_family = 'OTC_OPTION_CONTRACT' --ins_family：证券类型
    )


insert overwrite table T98_OTC_DERI_COMP_SALE_INFO partition(busi_date = '${data_day_str}', grp_id = '01')
SELECT
-- 字段映射：这是主脚本 SELECT 的表达式清单，不是可以独立执行的SQL。
-- 落表按位置对应90个非分区字段，不能调整顺序；busi_date/grp_id 在主脚本分区子句指定。
-- 经营分类和标的属性已经在上游阶段完成；这里只排列90列，金额仍引用10模块。
-- 行末中文名取自本目录目标DDL；空串、NULL、字符串0分别沿用源表达式，不统一替换。
-- 01 身份与客户：确定合约编号及交易对手。
enriched.contract_id as Agt_Id, -- 合约编号
'OPTION' as Busi_Type, -- 业务类型
rcm.outside_ctpty_code as Cutp_Pty_Id, -- 交易对手客户编号
cp.abbreviation as Cutp_Pty_Shor_Name, -- 交易对手当事人简称
cp.corporate_name as Cutp_Pty_Full_Name, -- 交易对手当事人名称
cp.Signature_Name as Sign_Prd_Name, -- 代签产品名称
cp.industry as Indt_Cd, -- 行业代码
cp.aptitude as Corp_Qual, -- 企业资质
-- 经营分类：直接读取09阶段结果；下面另列源合约类型。
enriched.Contr_Type_Cd AS Contr_Type_Cd, -- 已由09阶段生成
 enriched.Contr_Type_Desc AS Contr_Type_Desc,
-- 02 源系统类型：保留源类型及字典描述，与经营分类并列展示。
enriched.source_contract_type as Src_Contr_Type, -- 源合约类型
enriched.source_contract_type_desc as Src_Contr_Type_Desc, -- 源合约类型描述
enriched.source_contract_sub_type as Src_Sub_Contr_Type, -- 源合约子类型
enriched.source_contract_sub_type_desc as Src_Sub_Contr_Type_Desc, -- 源合约子类型描述
-- 03 标的及方向：标的来源因分支而异，参见本分支03或07模块。
enriched.underlying_instrument_id as Undrl_Ins_Id, -- 标的ID
enriched.underlying_wind_code as Undrl_Wd_Cd, -- 标的万得代码
enriched.underlying_name as Undrl_Name, -- 标的名称
enriched.underlying_type as Undrl_Type, -- 标的类型
'' as Undrl_Type_Desc, -- 标的类型描述
enriched.source_underlying_type as Src_Undrl_Type, -- 源标的类型
enriched.source_underlying_type_desc as Src_Undrl_Type_Desc, -- 源标的类型描述
if(enriched.private_placement_flag = 'Y', '1', '0') as Res_Flag, -- 限售标志
'0' as IPO_Flag, -- IPO标志
if(enriched.seller_id in ('10161','10142'), '2', '1') as Buy_Sell_Dir_Cd, -- 买卖方向代码
-- 04 人民币汇率与本金：展开10模块的4列计算结果。
/*
本文件字段的实际来源（左侧为本文件字段，右侧为源表字段）

enriched：主脚本中option_classified的别名，不是物理表。
以下字段在02_合约基础引入，经03_标的及篮子、09_经营分类原值传递：

  odata_n_tit.d_ref_otc_option_deal（期权交易合同要素表）
    enriched.collateral_notional_currency ← collateral_notional_currency  绝对名义本金币种
    enriched.settlement_currency          ← settlement_currency           结算币种
    enriched.initial_notional             ← initial_notional              初始名义本金
    enriched.notional                     ← notional                      名义本金
    enriched.collateral_notional          ← collateral_notional           绝对名义本金
    enriched.early_term_date               ← early_term_date               提前终止日

  odata_n_tit.d_ref_option_deal_structure（期权交易结构表）
    enriched.initial_exchange_rate ← init_notl_exchange_rate  期初汇率：名义本金币种对结算币种
    enriched.start_date            ← start_date              期初定价日
    enriched.end_date              ← end_date                期末定价日

mid：主脚本中odata_n_tit.d_ref_rmb_midrate的别名（本SQL用于取人民币中间价）。
    mid.MIDRATE    ← midrate     中间价
    mid.currency   ← currency    币种
    mid.quote_date ← quote_date  报价日期
    上述三个字段的元数据注释均带【AI】标记。
    连接条件：mid.currency = enriched.collateral_notional_currency
              mid.quote_date = enriched.start_date（取期初定价日，不是加工日）

计算口径
1、汇率 Cny_Ex_Rate
    CNY名义本金 → 1
    结算币种CNY → initial_exchange_rate
    其他 → mid.MIDRATE
2、初始名本
    汇率 * initial_notional
3、动态名本
    Dyna_Nom_Prin = Cny_Ex_Rate × 计入区间内 notional（区间外直接取0）
    计入区间：start_date（期初定价日） ≤ 加工日 ≤ coalesce(early_term_date, end_date)
    结束日优先取提前终止日，为NULL时取期末定价日；区间外取0，区间内notional为空也取0。
4、绝对名本
    汇率 × collateral_notional


    
*/
case
        when enriched.collateral_notional_currency = 'CNY' then 1
        when enriched.settlement_currency = 'CNY' then enriched.initial_exchange_rate
        else mid.MIDRATE
        end as Cny_Ex_Rate, -- 人民币汇率
(case
        when enriched.collateral_notional_currency = 'CNY' then 1
        when enriched.settlement_currency = 'CNY' then enriched.initial_exchange_rate
        else mid.MIDRATE
        end
    ) * enriched.initial_notional as Init_Nom_Prin, -- 初始名义本金
(case
        when enriched.collateral_notional_currency = 'CNY' then 1
        when enriched.settlement_currency = 'CNY' then enriched.initial_exchange_rate
        else mid.MIDRATE
        end
    ) * if('${data_day_str}' between substring(enriched.start_date, 1, 10) and substring(coalesce(enriched.early_term_date,enriched.end_date), 1, 10), coalesce(enriched.notional,0), 0) as Dyna_Nom_Prin, -- 动态名义本金
(case
        when enriched.collateral_notional_currency = 'CNY' then 1
        when enriched.settlement_currency = 'CNY' then enriched.initial_exchange_rate
        else mid.MIDRATE
        end
    ) * enriched.collateral_notional as Absl_Nom_Prin, -- 绝对名义本金

-- 05 生命周期：起止日、提前终止日、兑付日及状态码。
substring(enriched.start_date, 1, 10) as Strt_Pric_Date, -- 期初定价日
substring(enriched.end_date, 1, 10) as End_Pric_Date, -- 期末定价日
substring(enriched.early_term_date, 1, 10) as Early_Term_Date, -- 提前终止日
substring(enriched.payment_date, 1, 10) as Earn_Pymt_Date, -- 收益兑付日
enriched.term_days as Term_Days, -- 期限天数
case when enriched.contract_status in ('EFFECTIVE', 'EFFECTIVE_PENDING', 'TERMINATING', 'TERMINATING_PENDING') then '101'
         when enriched.contract_status = 'TERMINATED' then '226'
         end as Agt_Stat_Cd, -- 协议状态代码
-- 06 内部关联与费用：流水号、组合、保证金及费率。
enriched.trade_id as Inr_Seri_No, -- 内部流水号
enriched.contract_instrument_id as Otc_Seri_No, -- 场外合约流水号
enriched.bundle_id as bndl_id, -- 组合编号
rel.property_value as Rel_Agt_Id, -- 关联合约编号
mrg.Initial_Margin as Init_Marg_Prop, -- 初始保证金比例
mrg.MARGIN_BALANCE_INIT as init_Marg_Bal, -- 初始保证金
mp.deduction_pattern as Ddct_Ptrn, -- 抵扣模式
cp.commission_rate as cms_rate, -- 佣金费率
null as fixed_rate, -- 固定腿利率
fee.fee_rate, -- 实际费率
-- 07 期权专属字段：没有来源的分支按原SQL填NULL，不代表业务值为0。
enriched.hedge_type as Hedg_Type_Cd, -- 对冲类型代码
enriched.premium AS Opt_Fee, -- 期权费
substring(enriched.premium_date, 1, 10) as Opt_Fee_Paid_Date, -- 期权费支付日期
enriched.knockout_extra_par as KO_Prtc_rate, -- 敲出参与率
    enriched.rebate_not_abs as KO_Yield, -- 敲出收益率
    ODS.NET_PNL as net_coll, -- 交易净收取
    RODC.COUPON_RATE as Coup_Rate, -- 票息
KO.Min_OBS_DATE, -- 最小观察日
KO.Max_OBS_DATE, -- 最大观察日
pr.Up_Prtc_rate, -- 向上参与率
    pr.Down_Prtc_rate, -- 向下参与率
    KI.DOWN_KI_BARRIER_PCT as KI_Barr_PCT, -- 敲入障碍价
    coalesce(KO.UP_KO_BARRIER_PCT,KO.DOWN_KO_BARRIER_PCT) as KO_Barr_PCT, -- 敲出障碍价
    STk.Strk_PCT, -- 执行价
    STk.DOWN_Strk_PCT, -- 下跌保护执行价格
    STk.UP_Strk_PCT, -- 封顶价格
-- 08 加工留痕：保留源代码与调度占位符，不在本地替换参数。
    'TIT' AS Data_Src_Cd, -- 数据来源代码
UPPER('${filename}') AS Task_Name, -- 任务名
'${data_day_str}' AS Data_Etl_Date, -- 数据加载日期
'${data_day_str}' AS Data_Upt_Date, -- 数据更新日期
'${data_today}' AS Data_Time, -- 数据时间
-- 09 扩展属性：部门、估值、客户、账簿、卖方及跨币种字段。
enriched.book_department as Book_Bel_Dept, -- 账簿所属部门
calc.initial_npv as Bgng_Npv, -- 期初NPV
enriched.contract_status as Src_Agt_Stat_Cd, -- 源合约状态
enriched.underlying_long_name as Undrl_Long_Name, -- 标的长名称
cp.client_qualify_review as Qual_Revw_Flag, -- 客户资质复核标志
enriched.external_contract_code as Ext_Comp_No, -- 外部合约编号
enriched.counterparty_key as Key_Cutp_Id, -- Titans客户编号
coalesce(enriched.underlying_currency,'') as Undrl_Curr, -- 标的币种
null as Intr_Marg, -- 利差
mrg.basic_margin_rate as Base_Marg_Rate, -- 基础保证金率
mr.Marg_Agt_Id, -- 保证金合约编号
    enriched.premium_rate as Opt_Fee_Rate, -- 期权费率
    enriched.book_id as Book_Agt_Id, -- 账簿协议编号
enriched.book_name, -- 账簿名称
enriched.book_desk as Cntr, -- 柜台
IF(NVL(TRIM(enriched.seller_id),'')='','',CONCAT('TIT060-',enriched.seller_id)) as Sler_Cutp_Pty_Id, -- 销售方交易对手当事人编号
enriched.future_type as Futr_Type, -- 期货类型
enriched.trade_business_type as Agt_Clas_Cd, -- 协议分类代码
enriched.cross_currency_type as Cros_Crrc_Type_Cd, -- 跨币种类型代码
'' as Float_Base_Rate, -- 浮动基础利率
'' as Float_Undrl_Cd, -- 浮动腿标的代码
'' as Flot_Intrt_Ulmt, -- 浮动利率上限
null as Comp_Usag_Cd, -- 合约用途代码
enriched.settlement_currency as Sett_Crrc_Cd, -- 结算币种代码
enriched.fx_rate_model as Ex_Rate_Model -- 汇率模式

FROM option_classified enriched
-- 汇率：币种+结构起始日，仍不另加加工日过滤。
left join odata_n_tit.d_ref_rmb_midrate mid -- 表注释缺失；按本SQL用途：人民币中间价来源 
on enriched.collateral_notional_currency = mid.currency -- 绝对名义本金币种 = 【AI】币种
and enriched.start_date = mid.quote_date -- 期初定价日 = 【AI】报价日期；midrate原注释为【AI】中间价
-- 客户映射：内部客户键 → 外部客户号；客户资料cp仍在下方连接。
left join customer_mapping rcm
ON enriched.counterparty_key = rcm.key_ctpty_id
-- 关联合约与保证金：沿用原交易键/组合号，不新增去重。
left join related_contract rel
on rel.key_otc_trade_id = enriched.trade_id
left join margin_parameters mrg
on mrg.key_otc_trade_id = enriched.trade_id
left join margin_trs_links mr
on mr.option_key_otc_trade_id = enriched.trade_id
LEFT JOIN sale_bundle_plan mp
    ON mp.bundle_id = enriched.bundle_id
-- 条款与结算：保留原粒度；结算可能多行，不能当成一合约一行。
left join option_settlement ODS
on enriched.trade_id = ODS.KEY_OTC_TRADE_ID
left join first_premium_fee fee
on fee.key_instrument_id = enriched.contract_instrument_id
left join coupon_terms RODC
on enriched.trade_id = RODC.KEY_OTC_TRADE_ID
LEFT JOIN knockout_terms KO
ON enriched.trade_id = KO.KEY_OTC_TRADE_ID
LEFT JOIN knockin_terms KI
ON enriched.trade_id = KI.KEY_OTC_TRADE_ID
left join strike_terms STk
on enriched.trade_id = STk.KEY_OTC_TRADE_ID
left join participation_terms pr
on enriched.trade_id = pr.KEY_OTC_TRADE_ID
-- 公共客户：境内及香港匹配结果均保留。
LEFT JOIN sale_customer cp
on rcm.outside_ctpty_code = cp.client_id
-- 估值：工具+交易侧账簿+rk=1在ON中判断，缺失估值不剔除合约。
left join latest_valuation calc
on enriched.contract_instrument_id = calc.key_instrument_id and enriched.trade_book_id = calc.key_book_id and calc.rk = 1
;
