-- GENERATED by render.mjs; edit manifest.json entries and 04_业务模块/ instead.
-- 【加工主线】合格交易 → TRS合约 → 结构腿/非结构腿 → 初始及当日持仓 → 分类及本金 → 落表。
-- 【结果粒度】持仓按腿汇总，但主查询同时连接两类腿；多腿或多条客户/报备信息可能扩展行数。
-- 阅读入口：../04_业务模块/02_普通互换/README.md；本文件看连接与筛选，11_输出字段.sql看90列映射。
-- 维护：只改主脚本/模块，运行 node render.mjs --write 02_普通互换 更新完整SQL；原始快照不改。
-- 运行：@include不是Hive语法，需先展开；公共视图需预先建立。
-- 普通互换；任务86841；grp_id=02
-- 【用途】沿用四个分支原有Hive/MapReduce执行设置；被主脚本首先引用，不包含业务筛选逻辑。
-- 【文件合并】启用Map及MapReduce输出文件合并；目标合并大小和小文件均值阈值均为1 GiB。
-- 【输入切片】使用CombineHiveInputFormat，split最大/最小值均为1 GiB；这是执行参数，不代表数据行粒度。
-- 【边界】实际效果取决于引擎与作业配置；本次仅保留原设置，没有调参或运行验证。
set hive.merge.mapfiles=true ;
set hive.merge.mapredfiles=true;
set hive.merge.size.per.task=1073741824;
set hive.merge.smallfiles.avgsize=1073741824;
set hive.merge.orcfile.stripe.level=false;

set hive.input.format=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat;
set mapreduce.input.fileinputformat.split.maxsize=1073741824;
set mapreduce.input.fileinputformat.split.minsize=1073741824;


-- 一、准备模块：下列文件定义命名CTE；编号是主题导航，不表示数据库物理执行顺序。
WITH
/*
01 / 先准备：今天要加工哪些交易，用哪一份客户和组合资料？

三组资料分别回答不同问题，在主脚本中各自关联：
  sale_trade       → 交易属于哪个账簿、部门、公司？提供合约编号与交易键。
  sale_bundle_plan → 合约所属组合采用什么抵扣模式？
  sale_customer    → 交易对手叫什么、属于什么行业、具备什么资质？

本模块只把公共视图裁剪到加工日；互换合约和状态范围在主脚本确定。
“交易键”“组合号”“客户号”是不同对象的连接入口，不可互换。
*/

-- 交易及账簿：key_otc_trade_id 接互换合约；internal_trade_id 输出合约编号。
-- book_key_book_id 输出账簿协议编号；department/company 参与经营分类。
sale_trade AS (
    SELECT key_otc_trade_id, internal_trade_id, key_instrument_id, key_book_id,
           book_key_book_id, business_type, department, book_name, desk, company
    FROM v_t98_sale_trade_scope
    WHERE busi_date = '${data_day_str}'
),

-- 组合计划：在主脚本按合约 bundle_id LEFT JOIN，计划缺失不会在本模块剔除交易。
sale_bundle_plan AS (
    SELECT bundle_id, key_plan_id, deduction_pattern
    FROM v_t98_sale_bundle_plan
    WHERE busi_date = '${data_day_str}'
),

-- 客户：互换的 key_ctpty_id 先经02模块换成 outside_ctpty_code，再接这里的 client_id。
-- 公共客户视图保留境内与香港 UNION ALL；本模块不按客户号合并或去重。
sale_customer AS (
    SELECT client_id, abbreviation, corporate_name, Signature_Name, industry, aptitude, commission_rate, client_qualify_review
    FROM v_t98_sale_counterparty
    WHERE busi_date = '${data_day_str}'
)

,
/*
02 / 先认识“这一份互换合约”，再补客户与附属资料

合约整体回答：和谁交易、什么类型、何时开始结束、采用什么币种。
标的明细和本金规模通过“合约 → 结构腿 → 初始持仓／当日持仓”取得。
“普通互换”是当前加工分支的名称；这里不按trs_type限定成某一种产品。
主脚本用交易键INNER JOIN互换合约，并保留指定的生效、终止及待处理状态。

三组键分别连接不同对象：
  trade.internal_trade_id              → 输出的主合约编号Agt_Id
  rt.key_otc_trade_id（内部交易流水号） → 合约报备、属性、保证金参数、腿
  rt.key_ctpty_id（交易对手编号）       → 客户映射 → 外部客户号 → 客户资料

两种“关联合约”也要分开：
  relatedOption属性值 → Rel_Agt_Id：源属性直接给出的关联合约编号。
  有效的期权—互换关系 → Marg_Agt_Id：本互换关联哪些期权，按互换键汇总。
两者的来源、取值方式和用途不同；本SQL没有用其中一套反推另一套关系。

以下8个CTE是并列资料，在主脚本分别连接，不在本文件中拼成一张宽表。
*/

-- rt：互换合约；key_otc_trade_id为内部交易键，key_ctpty_id为交易对手编号。
-- trs_type=互换类型，start_date/end_date=期初/期末定价日，contr_status=合约状态。
-- 本金金额来自腿的历史持仓：初始金额汇总“期初价×初始数量”，当日金额汇总“期初价×当日数量”。
-- 对应文件为07_初始持仓.sql、08_当日持仓.sql；本合约提供币种和期初汇率，供10_本金与汇率.sql换算。
-- seller原义为“卖方，关联交易对手ID”，不是销售人员；bundle_id为组合编号。
-- contract_code为“合约编号（对外）”，输出Ext_Comp_No；与交易表输出的Agt_Id分开保留。
trs_contract AS (
    select * from odata_n_tit.d_ref_trs where busi_Date = '${data_day_str}' -- 场外交易-TRS
),

-- TOCR：合约报备信息；actual_settlement_date原义“实际结算日”，输出为Early_Term_Date（提前终止日）。
-- 按内部合约ID连接，不选最新、不聚合；多条报备记录会保留多个匹配。
settlement_report AS (
    select * from odata_n_tit.d_trd_otc_contr_report where busi_Date = '${data_day_str}' -- 交易-合约报备信息
),

-- 将 OTC 合约里的内部交易对手 ID，转换成公共客户体系的客户 ID，方便统一客户识别。
-- key_ctpty_id（内部交易对手ID）→ outside_ctpty_code（外部唯一码）→ 公共客户client_id。
customer_mapping AS (
    select * from odata_n_tit.d_ref_ctpty_mapping where busi_Date = '${data_day_str}' -- 交易参数-交易对手映射表
),

-- 当前 OTC 合约关联的另一个合约编号。
related_contract AS (
    select * from odata_n_tit.d_trd_otc_contr_props -- 【AI】交易-场外合约结构-其他属性表
    where busi_Date = '${data_day_str}' and property_name = 'relatedOption'
),

-- 提取 OTC 合约的静态履约保证金参数。
-- initial_margin=保证金初始线(%)，margin_balance_init=初始履约保障金额(元)，basic_margin_rate=基础保证金率。
margin_parameters AS (
    select * from odata_n_tit.d_ref_otc_contr_margin_param -- 【AI】合约-静态履约保证金参数
    where busi_Date = '${data_day_str}'
),

-- 有效关联（Y）按互换合约ID汇总期权合约ID，分号拼接为Marg_Agt_Id。
-- 注意方向：trs_key_otc_trade_id是互换键，option_key_otc_trade_id是期权键。
-- 和期权分支不同：这里不追加LONG_HOLD_SWAP类型限制；collect_set去重后再拼接。
margin_option_links AS (
    select trs_key_otc_trade_id, concat_ws(';',collect_set(option_key_otc_trade_id)) as Marg_Agt_Id
    from odata_n_tit.f_ref_option_margin_trs_relation -- 期权合约与互换合约关联关系表
    where busi_date = '${data_day_str}' and status = 'Y'
    group by trs_key_otc_trade_id
),

-- sct：CD382合约类型字典；dw_cd_val=代码，dw_cd_val_desc=中文描述。
-- 例如CALL_SWAP=多头互换、PUT_SWAP=空头互换、LEND_SWAP=借券互换。
-- 这些是源类型描述；09模块还会结合标的、账簿等属性生成经营分类。
-- 例示码值来自本地CD382快照，备注限定TITANS场外衍生品合约类型，记录业务日期2023-04-27。
contract_type_dictionary AS (
    select *
    from PDATA_N.REF_DW_CD_VAL -- 仓库代码取值
    where dw_cd_id = 'CD382' and remark = 'TITANS场外衍生品合约类型'
),

-- sutd：CD128标的类型字典；按his_ini.ins_family连接，保留主脚本的原关联。
underlying_type_dictionary AS (
    select *
    from PDATA_N.REF_DW_CD_VAL -- 仓库代码取值
    where dw_cd_id = 'CD128' and remark = 'TITANS场外衍生品标的类型'
)

,
/*
06 / 一份互换为什么还要拆“腿”？

在这套模型中，合约保存客户、期限、类型等整体信息；
腿把挂钩标的的持仓与固定/浮动利率条款分开登记。

互换合约（key_otc_trade_id）
  ├─ 结构腿（key_leg_id）→ 初始持仓／当日持仓 → 标的与本金金额
  │                       IPO/限售属性从结构腿本身取得
  └─ 非结构腿           → 固定利率 / 浮动利率挂钩标的 / 利差 / 利率上限

注意两个“标的”：结构腿持仓中的标的是资产证券；
浮动腿 underlying_ins_id 的元数据释义是“浮动利率挂钩标的”。
后者输出 Float_Undrl_Cd，不要拿它替换持仓证券的 Undrl_Ins_Id。

关键字段原义：key_leg_id=LEG全局顺序号；key_otc_trade_id=内部交易流水号；
leg_type=LEG类型（字典项TRS_LEG_TYPE）；fixed_rate=固定利率；
spread=利差；floating_rate_cap=浮动利率上限。元数据未标明这些利率的单位。
*/

-- 结构腿（rtl）：只保留 leg_type=STRUCTURE_LEG_TYPE，通过交易键连接合约。
-- key_leg_id 是后续初始持仓入口；IPO、限售标志也来自结构腿，不来自利率腿。
-- private_placement原注释“是否限售”；ipo_type原注释“【AI】限售类型”，
-- 但本SQL把ipo_type用于IPO_Flag及南下IPO分类，字段原注释与消费用途分开理解。
structure_legs AS (
    select *
    from odata_n_tit.d_ref_trs_leg -- 场外交易-TRS-leg基本信息
    where busi_Date = '${data_day_str}' and leg_type = 'STRUCTURE_LEG_TYPE'
    ),

-- 非结构腿（rtl_f）：原条件是 leg_type != STRUCTURE_LEG_TYPE，不等于只筛固定/浮动腿。
-- 输出时再分别判断 FIXED_LEG_TYPE/FLOAT_LEG_TYPE；NULL leg_type 不满足这里的不等式。
-- 两类腿各自按交易键连接；如两侧均多条，主查询仍可能形成多对多组合，未新增消重。
-- 输出字段：固定腿的fixed_rate → fixed_rate；浮动腿的fixed_rate → Float_Base_Rate。
-- 浮动腿也读取同名fixed_rate是现有映射，不表示这里重新计算了市场浮动利率。
interest_legs AS (
    select *
    from odata_n_tit.d_ref_trs_leg -- 场外交易-TRS-leg基本信息
    where busi_Date = '${data_day_str}' and leg_type != 'STRUCTURE_LEG_TYPE'
    )

,
/*
07 / 这条结构腿挂钩哪些资产，初始规模有多大？

期权分支直接读取合约上的initial_notional；普通互换在这里从持仓明细汇总：
  ① ranked_initial_positions  历史排序：每个“腿 + 标的”按源业务日从早到晚编号
    ↓
  ② first_initial_positions   选初始记录：每组只取rk=1
    ↓
  ③ initial_position_details  补标的属性：证券、工具池、期货类型和类型字典
    ↓
  ④ initial_position          按腿汇总：初始本金 = Σ（期初交易价 × 初始数量）
                                       同时拼出标的代码、名称、类型、币种

此处输出两类信息：持仓金额供10_本金与汇率.sql折算人民币；
标的属性供09_经营分类.sql判断类别，并在11_输出字段.sql展示。

两个日期分开看：
  busi_date     → 本次读取的加工日快照；本地元数据备注为空，含义按本SQL过滤用途说明。
  src_busi_date → 【AI】源业务日期；用它决定每个“腿 + 标的”的先后顺序。
最早记录按每个标的分别选，可能来自不同日期，并非全腿统一的某一天持仓；
若某标的后来才出现，它在可见历史中的首条记录也可能被选中。
*/

-- ① 历史排序：还保留所有历史记录，只增加每组内部的先后编号。
-- “初始”限于当前快照可见历史；日期并列未加裁决键。
ranked_initial_positions AS (
    select *,row_number() over(partition by key_leg_id, underlying_ins_id order by src_busi_date) as rk
    from odata_n_tit.d_pos_trs_leg_his_pos -- 【AI】持仓-TRS浮动及结构化腿历史持仓
    where busi_Date = '${data_day_str}'
    ),

-- ② 选初始记录：一行对应一个“腿 + 标的”；此时尚未补维表、未汇总本金。
first_initial_positions AS (
    select *
    from ranked_initial_positions
    where rk = 1
    ),

-- ③ 补标的属性：t仍是初始持仓；只把下一步会用到的字段列出来。
-- 证券、工具池、期货属性按加工日取值；类型字典按CD128及备注限定，不带日期条件。
-- 保留原LEFT JOIN及其多条匹配；此步不去重，匹配放大仍会传递到本金汇总。
initial_position_details AS (
    SELECT
        t.key_leg_id as key_leg_id, -- 按腿汇总键；历史持仓表元数据备注为空
        t.underlying_ins_id as underlying_ins_id, -- 【AI】持仓证券内码
        t.wind_code as wind_code, -- 【AI】持仓WIND代码
        t.ins_sht_desc as ins_sht_desc, -- 【AI】证券简称；仍取持仓表，不改取证券表
        t.Init_Price as Init_Price, -- 【AI】期初交易价
        t.Init_Quantity as Init_Quantity, -- 【AI】初始数量
        c.interotc_underlying_category as interotc_underlying_category, -- 工具池标的小类；识别BONDS
        d.ins_family as ins_family, -- 证券集；经营分类与展示使用
        d.currency as currency, -- 证券表币种，不是持仓表同名currency
        d.ins_lng_desc as ins_lng_desc, -- 证券全名
        sutd.dw_cd_val_desc as dw_cd_val_desc, -- 各标的证券集先查字典
        f.future_type as future_type -- 期货类型
    FROM first_initial_positions t
    left join (
        select * from odata_n_tit.r_cfg_instrument_pool_props -- 配置-标的池标的属性表
        where busi_Date = '${data_day_str}' and KEY_POOL_ID = '10000'
        ) c
    on c.key_instrument_id = t.underlying_ins_id -- 连接的是持仓证券内码，不是key_leg_id
    left join (
        select * from odata_n_tit.d_ref_instrument where busi_Date = '${data_day_str}' -- 证券-证券基本信息
        ) d
    on d.key_instrument_id = t.underlying_ins_id
    left join (
        select * from odata_n_tit.d_ref_future_properties where busi_Date = '${data_day_str}' -- 【AI】证券-期货信息表
        ) f
    on f.key_instrument_id = t.underlying_ins_id
    left join (
        select *
        from PDATA_N.REF_DW_CD_VAL -- 仓库代码取值；CD128限定TITANS场外衍生品标的类型
        where dw_cd_id = 'CD128' and remark = 'TITANS场外衍生品标的类型'
        ) sutd
    on sutd.dw_cd_val = d.ins_family
    ),

-- ④ 按腿汇总：p是上一步补完属性的明细；现在才把多标的合并为一行。
-- initial_position在主脚本中别名为his_ini；his_ini.Nom_Prin就是这里算出的初始持仓金额。
-- collect_list保留重复、collect_set去重；各列未指定顺序，不能按分号位置逐项配对。
initial_position AS (
    SELECT
        p.key_leg_id,
        concat_ws(';',collect_list(p.underlying_ins_id)) as underlying_ins_id,
        concat_ws(';',collect_list(p.wind_code)) as wind_code,
        concat_ws(';',collect_list(p.ins_sht_desc)) as ins_sht_desc,
        concat_ws(';',collect_set(p.interotc_underlying_category)) as interotc_underlying_category,
        concat_ws(';',collect_set(p.ins_family)) as ins_family,
        concat_ws(';',collect_set(p.currency)) as currency,
        concat_ws(';',collect_set(p.ins_lng_desc)) as ins_lng_desc,
        concat_ws(';',collect_set(p.dw_cd_val_desc)) as dw_cd_val_desc,
        concat_ws(';',collect_set(p.future_type)) as future_type,
        sum(p.Init_Price * p.Init_Quantity) as Nom_Prin -- 初始本金；尚未乘人民币汇率
    FROM initial_position_details p
    group by key_leg_id -- 一行一条腿，不保证主查询最终一合约一行
    )

,
/*
08 / 今天这条结构腿按期初价格计量的规模是多少？

本文件读取源业务日为加工日的持仓，按腿计算当日金额：
  当日持仓金额 = Σ（该条持仓记录的Init_Price期初交易价 × Quantity当日数量）。
与07_初始持仓.sql的区别：初始持仓选每个标的最早记录、用Init_Quantity初始数量。

价格取当日记录自身的Init_Price，不关联初始持仓的价格，也不使用当前市价。

两个条件同时成立：快照busi_date是加工日，src_busi_date的日期部分也是加工日。
如果没有当天记录，不会自动找前一个交易日的持仓延续。
*/

-- daily_position在主脚本中别名为his_dy；his_dy.Nom_Prin供10_本金与汇率.sql计算动态本金。
-- 实际连接链：结构腿 → 初始持仓his_ini → 当日持仓his_dy；没有初始结果就无法匹配当日结果。
-- 本模块不生成无记录的腿；缺失金额补0、乘汇率均在10_本金与汇率.sql完成。
daily_position AS (
    SELECT
        key_leg_id, -- 腿键；一行对应一条腿
        sum(Init_Price * Quantity) as Nom_Prin -- 【AI】期初交易价 × 【AI】数量；尚未折算人民币
    FROM odata_n_tit.d_pos_trs_leg_his_pos -- 【AI】持仓-TRS浮动及结构化腿历史持仓
    where busi_Date = '${data_day_str}' and substring(src_busi_date,1,10) = '${data_day_str}'
    group by key_leg_id
    )


-- 二、写入当前分支：仅覆盖指定加工日+grp_id分区；四个分支分开写入，不在此UNION。
insert overwrite table T98_OTC_DERI_COMP_SALE_INFO partition(busi_date = '${data_day_str}', grp_id = '02')
-- 三、装配目标字段：列顺序与统一DDL一致；输出文件内再引用经营分类、本金与汇率的表达式。
SELECT
/*
11 / 把不同对象的信息放进同一份销售合约资料

先按“从谁取值”阅读，再看目标字段：
  trade / rt → 合约身份、日期、源类型、账簿及币种
  rcm / cp   → 客户编号与客户资料
  his_ini    → 结构腿初始持仓的标的摘要与金额；his_dy → 当日持仓金额
  rtl        → 结构腿的IPO、限售属性
  rtl_f      → 非结构腿的固定/浮动利率、利差及利率挂钩标的
  rel / mrg / mr / mp / TOCR → 关联合约、保证金、组合抵扣模式及实际结算日

这是主脚本SELECT的表达式清单，按目标表位置输出90个非分区字段；
busi_date/grp_id由主脚本指定。经营分类、本金与汇率两个文件通过include嵌入，不是独立结果表。
行末中文名取自目标DDL；涉及原字段与目标名称不一致的地方在下方补充说明。
*/
-- 01 身份与客户：确定合约编号及交易对手。
trade.internal_trade_id as Agt_Id, -- 合约编号
'TRS' as Busi_Type, -- 业务类型
rcm.outside_ctpty_code as Cutp_Pty_Id, -- 交易对手客户编号
cp.abbreviation as Cutp_Pty_Shor_Name, -- 交易对手当事人简称
cp.corporate_name as Cutp_Pty_Full_Name, -- 交易对手当事人名称
cp.Signature_Name as Sign_Prd_Name, -- 代签产品名称
cp.industry as Indt_Cd, -- 行业代码
cp.aptitude as Corp_Qual, -- 企业资质
-- 经营分类：展开09_经营分类.sql的代码、名称两列；与后面的源合约类型分开保留。
/*
09 / 这份互换在销售经营口径中归到哪一类？

源合约类型回答“系统登记成什么产品”；经营分类把合约按报表口径分组。
例如旧规则把CALL_SWAP（多头互换）、PUT_SWAP（空头互换）都归为“多空互换”。
所以Contr_Type_Cd/Desc与Src_Contr_Type/Desc在11模块同时保留，不能混为一套类型。

输入地图：
  02合约 rt      → trs_type互换类型、START_DATE期初定价日、contract_use合约用途
  01交易 trade   → department账簿部门、company公司
  06结构腿 rtl   → ipo_type（本SQL作IPO判断）、Private_Placement限售判断
  07初始持仓 his_ini → ins_family证券集、currency证券币种、interotc_underlying_category工具池标的小类
  02字典 sct     → dw_cd_val_desc源合约类型名称，仅旧01使用

先选版本，再按顺序取首个命中；不是用加工日切换：
  substring(rt.START_DATE, 1, 10) <= '2025-03-31' → 旧01～旧12
  其余（包括START_DATE为NULL）                  → 新01～新07

规则对照（编号与下方代码、名称两段CASE对应）：
  下列简写仅为阅读，不是新增SQL条件：
  股票 = ins_family IN ('EQUITY','GDR')；非IPO = ipo_type为'N'或NULL；
  非限售 = Private_Placement为'N'或NULL；空串不等于NULL。

  旧规则 / 条件 → 分类代码 → 中文名称
  旧01 OTC_HK部门 + CROSS_LEND_SWAP/HK_LONG_HOLD_SWAP/N_CROSS_FUTURE_SWAP/N_CROSS_QFII_SWAP
       → TRS_拼接源类型 → sct.dw_cd_val_desc（源类型字典名称）
  旧02 N_CROSS_SWAP → TRS_N_STOCK → 北上A股
  旧03 CALL_SWAP/PUT_SWAP → TRS_LONG_SHORT → 多空互换
  旧04 S_CROSS_FUTURE_SWAP → TRS_S_CROSS_FUTURES → 南下期货
  旧05 S_CROSS_SWAP + 工具池标的小类BONDS → TRS_S_CROSS_BOND → 南下债券
  旧06 S_CROSS_SWAP + 股票 + 币种非CNY + IPO='Y' → TRS_S_IPO → 南下IPO
  旧07 S_CROSS_SWAP + 股票 + 币种非CNY + 非IPO + 限售='Y'
       → TRS_S_STOCK_LIMITED → 南下跨境互换（限售股）
  旧08 S_CROSS_SWAP + 股票 + 币种HKD + 非IPO + 非限售
       → TRS_S_CROSS_HK → 南下跨境港股
  旧09 S_CROSS_SWAP + 股票 + 币种非HKD且非CNY + 非IPO + 非限售
       → TRS_S_CROSS_OTHER → 南下跨境-其他股票市场
  旧10 GFS_HK公司 + FEE_SWAP + 用途REBATE_INTEREST → FEE_SWAP_HK → 费用合约
  旧11 GFS_HK公司 + INDEX_ENHANCE_SWAP → TRS_N_CROSS_INDEX_ENHANCE → 北上指数增强
  旧12 其余 → TRS_OTHER_SWAP → 其它互换类型

  新规则 / 条件 → 分类代码 → 中文名称
  新01 LEND_SWAP + 股票 → TRS_SHORT_SELL → 借券互换
  新02 证券集QIS → TRS_S_CROSS_QTF_STRG_IDX → 南下量化策略指数互换
  新03 S_CROSS_FUTURE_SWAP → TRS_S_CROSS_FUTURES → 南下期货
  新04 S_CROSS_SWAP/S_CROSS_OPTION_SWAP + 股票 + 币种非CNY + IPO='Y'
       → TRS_S_IPO → 南下IPO
  新05 S_CROSS_SWAP/S_CROSS_OPTION_SWAP + 股票 + 非IPO
       → TRS_S_CROSS_STOCK → 南下跨境股票
  新06 GFS_HK公司 + INDEX_ENHANCE_SWAP → TRS_N_CROSS_INDEX_ENHANCE → 北上指数增强
  新07 其余 → TRS_OTHER_SWAP → 其它互换类型

三处不要凭中文名称补条件：
  新02没有限定公司或互换类型；QIS命中后，不再继续匹配南下期货等后续规则。
  新05没有限定币种或限售标志，不要把旧08/09的条件搬进来。
  his_ini的类型/币种可能为分号拼接多值；SQL按整个字符串比较，不逐标的判断。

下方只输出代码、名称两列表达式，不增加JOIN；保留独立条件树和原优先级。
旧01的名称取字典，不能把全部名称改成由分类代码固定映射。
*/
-- A. 经营类别代码：下面分别列出旧口径和新口径。
if(
    substring(rt.START_DATE, 1, 10) <= '2025-03-31'
    -- 旧口径：按类型及业务属性细分，保持原有顺序。
    ,case
        -- 旧01
        when trade.department = 'OTC_HK'
            and rt.trs_type in ('CROSS_LEND_SWAP','HK_LONG_HOLD_SWAP','N_CROSS_FUTURE_SWAP','N_CROSS_QFII_SWAP')
            then concat('TRS_',rt.trs_type)
        -- 旧02
        when rt.trs_type = 'N_CROSS_SWAP'
            then 'TRS_N_STOCK'
        -- 旧03
        when rt.trs_type in ('CALL_SWAP', 'PUT_SWAP')
            then 'TRS_LONG_SHORT'
        -- 旧04
        when rt.trs_type = 'S_CROSS_FUTURE_SWAP'
            then 'TRS_S_CROSS_FUTURES'
        -- 旧05
        when rt.trs_type = 'S_CROSS_SWAP'
            and his_ini.interotc_underlying_category = 'BONDS'
            then 'TRS_S_CROSS_BOND'
        -- 旧06
        when rt.trs_type = 'S_CROSS_SWAP'
            and his_ini.ins_family in ('EQUITY', 'GDR')
            and his_ini.currency != 'CNY'
            and rtl.ipo_type = 'Y'
            then 'TRS_S_IPO' -- 非CNY股票且IPO；条件没有进一步限定必须为HKD
        -- 旧07
        when rt.trs_type = 'S_CROSS_SWAP'
            and his_ini.ins_family in ('EQUITY', 'GDR')
            and his_ini.currency != 'CNY'
            and (rtl.ipo_type = 'N' or rtl.ipo_type is null)
            and rtl.Private_Placement = 'Y'
            then 'TRS_S_STOCK_LIMITED'
        -- 旧08
        when rt.trs_type = 'S_CROSS_SWAP'
            and his_ini.ins_family in ('EQUITY', 'GDR')
            and his_ini.currency = 'HKD'
            and (rtl.ipo_type = 'N' or rtl.ipo_type is null)
            and (rtl.Private_Placement = 'N' or rtl.Private_Placement is null)
            then 'TRS_S_CROSS_HK'
        -- 旧09
        when rt.trs_type = 'S_CROSS_SWAP'
            and his_ini.ins_family in ('EQUITY', 'GDR')
            and his_ini.currency not in ('HKD','CNY')
            and (rtl.ipo_type = 'N' or rtl.ipo_type is null)
            and (rtl.Private_Placement = 'N' or rtl.Private_Placement is null)
            then 'TRS_S_CROSS_OTHER'
        -- 旧10
        when trade.company = 'GFS_HK'
            and rt.trs_type = 'FEE_SWAP'
            and rt.contract_use = 'REBATE_INTEREST'
            then 'FEE_SWAP_HK'
        -- 旧11
        when trade.company = 'GFS_HK'
            and rt.trs_type = 'INDEX_ENHANCE_SWAP'
            then 'TRS_N_CROSS_INDEX_ENHANCE'
        -- 旧12 / 兜底
        else 'TRS_OTHER_SWAP'
    end
    -- 新口径：按下列条件优先级匹配，末尾保留原兜底。
    ,case
        -- 新01
        when rt.trs_type = 'LEND_SWAP'
            and his_ini.ins_family in ('EQUITY', 'GDR')
            then 'TRS_SHORT_SELL'
        -- 新02
        when his_ini.ins_family = 'QIS'
            then 'TRS_S_CROSS_QTF_STRG_IDX'
        -- 新03
        when rt.trs_type = 'S_CROSS_FUTURE_SWAP'
            then 'TRS_S_CROSS_FUTURES'
        -- 新04
        when rt.trs_type in ('S_CROSS_SWAP', 'S_CROSS_OPTION_SWAP')
            and his_ini.ins_family in ('EQUITY', 'GDR')
            and his_ini.currency != 'CNY'
            and rtl.ipo_type = 'Y'
            then 'TRS_S_IPO'
        -- 新05
        when rt.trs_type in ('S_CROSS_SWAP', 'S_CROSS_OPTION_SWAP')
            and his_ini.ins_family in ('EQUITY', 'GDR')
            and (rtl.ipo_type = 'N' or rtl.ipo_type is null)
            then 'TRS_S_CROSS_STOCK'
        -- 新06
        when trade.company = 'GFS_HK'
            and rt.trs_type = 'INDEX_ENHANCE_SWAP'
            then 'TRS_N_CROSS_INDEX_ENHANCE'
        -- 新07 / 兜底
        else 'TRS_OTHER_SWAP'
    end
) as Contr_Type_Cd, -- 合约类型代码
-- B. 经营类别名称：沿用独立条件树；不要只靠代码重新映射中文名。
if(
    substring(rt.START_DATE, 1, 10) <= '2025-03-31'
    -- 旧口径：按类型及业务属性细分，保持原有顺序。
    ,case
        -- 旧01
        when trade.department = 'OTC_HK'
            and rt.trs_type in ('CROSS_LEND_SWAP','HK_LONG_HOLD_SWAP','N_CROSS_FUTURE_SWAP','N_CROSS_QFII_SWAP')
            then sct.dw_cd_val_desc
        -- 旧02
        when rt.trs_type = 'N_CROSS_SWAP'
            then '北上A股'
        -- 旧03
        when rt.trs_type in ('CALL_SWAP', 'PUT_SWAP')
            then '多空互换'
        -- 旧04
        when rt.trs_type = 'S_CROSS_FUTURE_SWAP'
            then '南下期货'
        -- 旧05
        when rt.trs_type = 'S_CROSS_SWAP'
            and his_ini.interotc_underlying_category = 'BONDS'
            then '南下债券'
        -- 旧06
        when rt.trs_type = 'S_CROSS_SWAP'
            and his_ini.ins_family in ('EQUITY', 'GDR')
            and his_ini.currency != 'CNY'
            and rtl.ipo_type = 'Y'
            then '南下IPO'
        -- 旧07
        when rt.trs_type = 'S_CROSS_SWAP'
            and his_ini.ins_family in ('EQUITY', 'GDR')
            and his_ini.currency != 'CNY'
            and (rtl.ipo_type = 'N' or rtl.ipo_type is null)
            and rtl.Private_Placement = 'Y'
            then '南下跨境互换（限售股）'
        -- 旧08
        when rt.trs_type = 'S_CROSS_SWAP'
            and his_ini.ins_family in ('EQUITY', 'GDR')
            and his_ini.currency = 'HKD'
            and (rtl.ipo_type = 'N' or rtl.ipo_type is null)
            and (rtl.Private_Placement = 'N' or rtl.Private_Placement is null)
            then '南下跨境港股'
        -- 旧09
        when rt.trs_type = 'S_CROSS_SWAP'
            and his_ini.ins_family in ('EQUITY', 'GDR')
            and his_ini.currency not in ('HKD','CNY')
            and (rtl.ipo_type = 'N' or rtl.ipo_type is null)
            and (rtl.Private_Placement = 'N' or rtl.Private_Placement is null)
            then '南下跨境-其他股票市场'
        -- 旧10
        when trade.company = 'GFS_HK'
            and rt.trs_type = 'FEE_SWAP'
            and rt.contract_use = 'REBATE_INTEREST'
            then '费用合约'
        -- 旧11
        when trade.company = 'GFS_HK'
            and rt.trs_type = 'INDEX_ENHANCE_SWAP'
            then '北上指数增强'
        -- 旧12 / 兜底
        else '其它互换类型'
    end
    -- 新口径：按下列条件优先级匹配，末尾保留原兜底。
    ,case
        -- 新01
        when rt.trs_type = 'LEND_SWAP'
            and his_ini.ins_family in ('EQUITY', 'GDR')
            then '借券互换'
        -- 新02
        when his_ini.ins_family = 'QIS'
            then '南下量化策略指数互换'
        -- 新03
        when rt.trs_type = 'S_CROSS_FUTURE_SWAP'
            then '南下期货'
        -- 新04
        when rt.trs_type in ('S_CROSS_SWAP', 'S_CROSS_OPTION_SWAP')
            and his_ini.ins_family in ('EQUITY', 'GDR')
            and his_ini.currency != 'CNY'
            and rtl.ipo_type = 'Y'
            then '南下IPO'
        -- 新05
        when rt.trs_type in ('S_CROSS_SWAP', 'S_CROSS_OPTION_SWAP')
            and his_ini.ins_family in ('EQUITY', 'GDR')
            and (rtl.ipo_type = 'N' or rtl.ipo_type is null)
            then '南下跨境股票'
        -- 新06
        when trade.company = 'GFS_HK'
            and rt.trs_type = 'INDEX_ENHANCE_SWAP'
            then '北上指数增强'
        -- 新07 / 兜底
        else '其它互换类型'
    end
) as Contr_Type_Desc, -- 合约类型描述

-- 02 源系统类型：保留源类型及字典描述，与经营分类并列展示。
rt.trs_type as Src_Contr_Type, -- 源合约类型
sct.dw_cd_val_desc as Src_Contr_Type_Desc, -- 源合约类型描述
'' as Src_Sub_Contr_Type, -- 源合约子类型
'' as Src_Sub_Contr_Type_Desc, -- 源合约子类型描述
-- 03 标的及方向：展示初始持仓的标的摘要；当日持仓只参与动态本金。
-- 个股/篮子按证券表币种区分市场；本金换算则用合约币种选择汇率。
his_ini.underlying_ins_id as Undrl_Ins_Id, -- 标的ID
his_ini.wind_code as Undrl_Wd_Cd, -- 标的万得代码
his_ini.ins_sht_desc as Undrl_Name, -- 标的名称
case when his_ini.ins_family in ('EQUITY', 'GDR', 'BASKET') and his_ini.currency not in ('HKD', 'USD') then 'OTH_STOCK'
         when his_ini.ins_family in ('EQUITY', 'GDR', 'BASKET') and his_ini.currency = 'HKD' then 'HK_STOCK'
         when his_ini.ins_family in ('EQUITY', 'GDR', 'BASKET') and his_ini.currency = 'USD' then 'US_STOCK'
         when his_ini.ins_family not in ('EQUITY', 'GDR', 'BASKET') then 'NON_STOCK'
         else '-' end as Undrl_Type, -- 标的类型
'' as Undrl_Type_Desc, -- 标的类型描述
if(his_ini.interotc_underlying_category = 'BONDS', 'BOND', his_ini.ins_family) as Src_Undrl_Type, -- 源标的类型
if(his_ini.interotc_underlying_category = 'BONDS', '债券', his_ini.dw_cd_val_desc) as Src_Undrl_Type_Desc, -- 源标的类型描述
if(rtl.PRIVATE_PLACEMENT = 'Y', '1', '0') as Res_Flag, -- 限售标志
if(rtl.IPO_Type = 'Y', '1', '0') as IPO_Flag, -- IPO标志；来源ipo_type的元数据原注释为“【AI】限售类型”
if(rt.seller in ('10161','10142'), '1', '2') as Buy_Sell_Dir_Cd, -- 买卖方向代码；这里的1/2分支与期权的2/1相反，不能照搬
-- 04 人民币汇率与本金：展开10_本金与汇率.sql；持仓金额乘合约汇率。
/*
10 / 本金 = 持仓算出的金额 × 合约提供的人民币换算汇率

先分清分工：持仓提供“价格和数量”，合约提供“币种和汇率”。
本文件不再选持仓、不再按腿求和，只使用已算好的两份金额。
下文的07、08是同目录文件名的编号，不是表名、月份或业务代码。

一、SQL里的三个别名从哪里来？
  his_ini.Nom_Prin：初始持仓金额
    07_初始持仓.sql → initial_position结果 → 主脚本别名his_ini
    源表：odata_n_tit.d_pos_trs_leg_his_pos（【AI】持仓-TRS浮动及结构化腿历史持仓）
    当前快照内，每个“腿＋标的”取最早源业务日记录，补标的属性后按腿汇总：
    SUM(Init_Price × Init_Quantity)，即期初交易价 × 初始数量之和。

  his_dy.Nom_Prin：当日持仓金额
    08_当日持仓.sql → daily_position结果 → 主脚本别名his_dy
    源表同上，但只选源业务日为加工日的记录，按腿汇总：
    SUM(Init_Price × Quantity)，即当日记录自身的期初交易价 × 当日数量之和。
    它不取初始持仓结果中的价格，也不使用当天市价。

  rt：互换合约
    02_合约及来源属性.sql → trs_contract结果 → 主脚本别名rt
    源表：odata_n_tit.d_ref_trs（场外交易-TRS）。
    提供下面的三个币种字段及两个期初汇率字段，不在这里提供本金金额。

二、先选一个汇率R，再计算初始、动态本金
  按顺序取第一个满足的条件：
  ① currency（合约币种）为CNY         → R = 1
  ② base_currency（本币币种）为CNY    → R = base_init_exchange_rate
  ③ settlement_currency（结算币种）为CNY → R = settle_init_exchange_rate
  都不满足 → R = NULL；没有另查市场汇率，也没有取倒数。
  base_init_exchange_rate原注释为“【AI】期初汇率(本币对标的币种)”；
  settle_init_exchange_rate为“结算期初汇率”。这里只按原SQL直接使用，不另推导方向。

  Cny_Ex_Rate   人民币汇率     = R
  Init_Nom_Prin 初始名义本金   = 初始持仓金额 × R
  Dyna_Nom_Prin 动态名义本金   = 当日持仓金额 × R（当日金额为NULL时先补0）
  Absl_Nom_Prin 绝对名义本金   = 固定字符串'0.0'，不是对某个金额取绝对值

三、贯穿示例（假设单一标的、无重复匹配，且满足上述②、所选汇率为0.9）
  初始记录：期初价10 × 初始数量100 = 1000 → 初始名义本金1000 × 0.9 = 900
  当日记录：期初价10 × 当日数量60  =  600 → 动态名义本金 600 × 0.9 = 540
  “动态”在此体现当日数量；不是用当天市价重估，也没有额外套合约起止日期判断。

缺失处理：初始金额不补0；当日金额补0不代表实际持仓一定为0。
汇率为NULL时，两种本金都仍为NULL，包括0 × NULL。
*/

-- ① 输出选中的汇率。下面两项金额重复同一个CASE，是同一换算规则，不是三种汇率。
CASE WHEN RT.CURRENCY = 'CNY' THEN 1 
         WHEN RT.BASE_CURRENCY = 'CNY' THEN RT.BASE_INIT_EXCHANGE_RATE 
         WHEN RT.SETTLEMENT_CURRENCY = 'CNY' THEN RT.SETTLE_INIT_EXCHANGE_RATE
         end as Cny_Ex_Rate, -- 人民币汇率

-- ② 初始持仓金额 × 上述汇率。
his_ini.Nom_Prin * CASE WHEN RT.CURRENCY = 'CNY' THEN 1 
         WHEN RT.BASE_CURRENCY = 'CNY' THEN RT.BASE_INIT_EXCHANGE_RATE 
         WHEN RT.SETTLEMENT_CURRENCY = 'CNY' THEN RT.SETTLE_INIT_EXCHANGE_RATE
         end as Init_Nom_Prin, -- 初始名义本金

-- ③ 当日持仓金额（缺失先补0）× 上述汇率。
coalesce(his_dy.Nom_Prin, 0) * CASE WHEN RT.CURRENCY = 'CNY' THEN 1 
         WHEN RT.BASE_CURRENCY = 'CNY' THEN RT.BASE_INIT_EXCHANGE_RATE 
         WHEN RT.SETTLEMENT_CURRENCY = 'CNY' THEN RT.SETTLE_INIT_EXCHANGE_RATE
         end as Dyna_Nom_Prin, -- 动态名义本金

-- ④ 原分支固定值，不新增计算。
'0.0' as Absl_Nom_Prin, -- 绝对名义本金

-- 05 生命周期：起止日、提前终止日、兑付日及状态码。
substring(rt.START_DATE, 1, 10) as Strt_Pric_Date, -- 期初定价日
substring(rt.End_Date, 1, 10) as End_Pric_Date, -- 期末定价日
substring(tocr.Actual_Settlement_Date, 1, 10) as Early_Term_Date, -- 提前终止日；原字段是合约报备中的“实际结算日”
substring(rt.Payment_Date, 1, 10) as Earn_Pymt_Date, -- 收益兑付日
rt.Time_To_Maturity as Term_Days, -- 期限天数
case when rt.contr_status in ('EFFECTIVE', 'EFFECTIVE_PENDING', 'TERMINATING', 'TERMINATING_PENDING') then '101'
         when rt.contr_status = 'TERMINATED' then '226'
         end as Agt_Stat_Cd, -- 协议状态代码
-- 06 内部关联与费用：流水号、组合、保证金及费率。
trade.key_otc_trade_id as Inr_Seri_No, -- 内部流水号
trade.key_instrument_id as Otc_Seri_No, -- 场外合约流水号
rt.bundle_id as bndl_id, -- 组合编号
rel.property_value as Rel_Agt_Id, -- 关联合约编号；当前互换的relatedOption属性值，与下方Marg_Agt_Id来源不同
mrg.Initial_Margin as Init_Marg_Prop, -- 初始保证金比例
mrg.MARGIN_BALANCE_INIT as init_Marg_Bal, -- 初始保证金
mp.deduction_pattern as Ddct_Ptrn, -- 抵扣模式
cp.commission_rate as cms_rate, -- 佣金费率
case when rtl_f.leg_type = 'FIXED_LEG_TYPE' then rtl_f.fixed_rate end as fixed_rate, -- 固定腿利率；仅FIXED_LEG_TYPE时取值
null as fee_rate, -- 实际费率
-- 07 共享目标表中的期权条款栏位：本分支没有关联期权条款，下面按原SQL填NULL。
-- 即使relatedOption有关联合约，也没有据它读取票息、敲入/敲出等条款。
null as Hedg_Type_Cd, -- 对冲类型代码
null AS Opt_Fee, -- 期权费
null as Opt_Fee_Paid_Date, -- 期权费支付日期
null as KO_Prtc_rate, -- 敲出参与率
null as KO_Yield, -- 敲出收益率
null as net_coll, -- 交易净收取
null as Coup_Rate, -- 票息
null as Min_OBS_DATE, -- 最小观察日
null as Max_OBS_DATE, -- 最大观察日
null as Up_Prtc_rate, -- 向上参与率
null as Down_Prtc_rate, -- 向下参与率
null as KI_Barr_PCT, -- 敲入障碍价
null as KO_Barr_PCT, -- 敲出障碍价
null as Strk_PCT, -- 执行价
null as DOWN_Strk_PCT, -- 下跌保护执行价格
null as UP_Strk_PCT, -- 封顶价格
-- 08 加工留痕：保留源代码与调度占位符，不在本地替换参数。
'TIT' AS Data_Src_Cd, -- 数据来源代码
UPPER('${filename}') AS Task_Name, -- 任务名
'${data_day_str}' AS Data_Etl_Date, -- 数据加载日期
'${data_day_str}' AS Data_Upt_Date, -- 数据更新日期
'${data_today}' AS Data_Time, -- 数据时间
-- 09 扩展属性：部门、估值、客户、账簿、卖方及跨币种字段。
trade.department as Book_Bel_Dept, -- 账簿所属部门
null as Bgng_Npv, -- 期初NPV
rt.contr_status as Src_Agt_Stat_Cd, -- 源合约状态
his_ini.ins_lng_desc as Undrl_Long_Name, -- 标的长名称
cp.client_qualify_review as Qual_Revw_Flag, -- 客户资质复核标志
rt.contract_code as Ext_Comp_No, -- 外部合约编号
rt.key_ctpty_id as Key_Cutp_Id, -- Titans客户编号
coalesce(his_ini.currency,'') as Undrl_Curr, -- 标的币种；初始持仓从证券表汇总，不是rt的合约币种
rtl_f.spread as Intr_Marg, -- 利差；这里直接读取已连接非结构腿的spread，未再限定腿类型
mrg.basic_margin_rate as Base_Marg_Rate, -- 基础保证金率
mr.Marg_Agt_Id, -- 保证金合约编号；有效关联关系中的期权交易键，去重后分号拼接
null as Opt_Fee_Rate, -- 期权费率
trade.book_key_book_id as Book_Agt_Id, -- 账簿协议编号
trade.Book_Name, -- 账簿名称
trade.Desk as Cntr, -- 柜台
IF(NVL(TRIM(rt.seller),'')='','',CONCAT('TIT060-',rt.seller)) as Sler_Cutp_Pty_Id, -- 销售方交易对手当事人编号
his_ini.future_type as Futr_Type, -- 期货类型
trade.business_type as Agt_Clas_Cd, -- 协议分类代码
rt.cross_currency_type as Cros_Crrc_Type_Cd, -- 跨币种类型代码
case when rtl_f.leg_type = 'FLOAT_LEG_TYPE' then rtl_f.fixed_rate end as Float_Base_Rate, -- 浮动基础利率；原字段仍叫fixed_rate，没有另查市场利率
case when rtl_f.leg_type = 'FLOAT_LEG_TYPE' then rtl_f.underlying_ins_id end as Float_Undrl_Cd, -- 浮动腿标的代码；原义“浮动利率挂钩标的”，与持仓证券分开
case when rtl_f.leg_type = 'FLOAT_LEG_TYPE' then rtl_f.floating_rate_cap end as Flot_Intrt_Ulmt, -- 浮动利率上限
rt.contract_use as Comp_Usag_Cd, -- 合约用途代码
rt.SETTLEMENT_CURRENCY as Sett_Crrc_Cd, -- 结算币种代码
rt.fx_rate_model as Ex_Rate_Model -- 汇率模式

-- 四、连接加工主线：INNER JOIN决定必须具备的记录；LEFT JOIN保留缺失侧，除非最终WHERE另行限制。
FROM sale_trade trade
inner join trs_contract rt
ON rt.key_otc_trade_id = trade.key_otc_trade_id
-- 腿：结构腿负责标的和IPO/限售属性；非结构腿负责固定/浮动利率及利差。
left join structure_legs rtl
ON rtl.key_otc_trade_id = rt.key_otc_trade_id
left join interest_legs rtl_f
ON rtl_f.key_otc_trade_id = rt.key_otc_trade_id
left join settlement_report TOCR
ON TOCR.KEY_OTC_TRADE_ID = rt.KEY_OTC_TRADE_ID
-- 客户链：合约内部客户键 → 客户映射 → 公共客户；LEFT JOIN不强制要求客户资料完整。
left join customer_mapping rcm
ON rt.key_ctpty_id = rcm.key_ctpty_id
-- 初始持仓：结构腿key_leg_id → 每腿初始本金和标的汇总。
left join initial_position his_ini
ON his_ini.key_leg_id = rtl.key_leg_id
-- 当日持仓：通过his_ini.key_leg_id关联；不要改成直接连rtl，这会改变初始持仓缺失时的结果。
left join daily_position his_dy
ON his_dy.key_leg_id = his_ini.key_leg_id
-- 合约附加属性：关联合约与保证金按交易键连接，组合计划按bundle_id连接。
left join related_contract rel
on rel.key_otc_trade_id = trade.key_otc_trade_id
left join margin_parameters mrg
on mrg.key_otc_trade_id = trade.key_otc_trade_id
left join margin_option_links mr
on mr.trs_key_otc_trade_id = trade.key_otc_trade_id
LEFT JOIN sale_bundle_plan mp
    ON mp.bundle_id = rt.bundle_id
-- 客户展示资料：由外部客户号取简称/全称/资质等；境内和香港同号时仍保留原匹配结果。
LEFT JOIN sale_customer cp
on rcm.outside_ctpty_code = cp.client_id
left join contract_type_dictionary sct
on sct.dw_cd_val = rt.trs_type
left join underlying_type_dictionary sutd
on sutd.dw_cd_val = his_ini.ins_family
-- 五、最终范围：保留EFFECTIVE、EFFECTIVE_PENDING、TERMINATED、TERMINATING、TERMINATING_PENDING。
-- 此条件包含已终止状态，不能简单理解为“仅存续合约”。
where rt.Contr_Status in ('EFFECTIVE', 'EFFECTIVE_PENDING', 'TERMINATED', 'TERMINATING', 'TERMINATING_PENDING')
;
