-- GENERATED by render.mjs; edit manifest.json entries and 04_业务模块/ instead.
/*
金仕达 / 把三类资料接成销售基础记录（任务86842，grp_id=03）

02 确认书排序 → 选最新 ─────────────────────── a ─┐
03 持仓排序 → 选最新 → 补证券 → 按确认书汇总 ─ ins ┤
01 加工日的境内客户 ───────────────────────── cp ┤
02 源合约类型字典 ────────────────────────── sct ┘
                                                  ↓
                         本脚本按键连接、筛范围 → 11分类/本金/90列输出

接起来靠三组键，不靠名字：
  a.key_trade_comfirm_id（确认书ID）= ins.key_trade_comfirm_id
  a.counterparty_id（交易对手）= cp.client_id（客户编号）
  a.trs_type（互换类型）= sct.dw_cd_val（字典代码）

确认书ID不是主合约编号；客户/字典重复匹配可能扩展行数，不保证一确认书一行。
阅读入口：../04_业务模块/03_金仕达/README.md；@include不是Hive语法。
*/
-- 【用途】沿用四个分支原有Hive/MapReduce执行设置；被主脚本首先引用，不包含业务筛选逻辑。
-- 【文件合并】启用Map及MapReduce输出文件合并；目标合并大小和小文件均值阈值均为1 GiB。
-- 【输入切片】使用CombineHiveInputFormat，split最大/最小值均为1 GiB；这是执行参数，不代表数据行粒度。
-- 【边界】实际效果取决于引擎与作业配置；本次仅保留原设置，没有调参或运行验证。
set hive.merge.mapfiles=true ;
set hive.merge.mapredfiles=true;
set hive.merge.size.per.task=1073741824;
set hive.merge.smallfiles.avgsize=1073741824;
set hive.merge.orcfile.stripe.level=false;

set hive.input.format=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat;
set mapreduce.input.fileinputformat.split.maxsize=1073741824;
set mapreduce.input.fileinputformat.split.minsize=1073741824;


-- 一、准备资料：各文件内部按步骤阅读；编号是业务主题，不是数据库物理执行顺序。
WITH
-- 本分支只复用公共客户，不使用“合格OTC交易及账簿”或“组合计划”视图。
-- 实际来源：odata_n_ois.o_otc_derivative_counterparty（衍生品交易对手维护表）。
-- 公共视图已限定delete_flag=0、department非HK；这里再取加工日和MAINLAND来源。
-- 确认书a.counterparty_id → 客户client_id；不经过TITANS客户映射，不按客户号去重。
sale_customer AS (
    SELECT client_id, -- 客户编号
           abbreviation, -- 简称
           corporate_name, -- 公司名称
           Signature_Name, -- 代签产品名称
           industry, -- 所属行业
           aptitude, -- 资质
           commission_rate, -- 佣金费率；源注释未标明单位
           client_qualify_review -- 客户资质复核
    FROM v_t98_sale_counterparty -- 公共交易对手视图，定义见sql/02_公共视图
    WHERE busi_date = '${data_day_str}'
      AND customer_source = 'MAINLAND'
)

,
/*
02 / 哪条确认书记录进入后续加工？
输入：odata_n_tit.d_ks_trade_comfirm_info（交易确认书信息表）的加工日快照。
步骤：给每张确认书的历史记录排序 → 每张确认书只取最新一条。
输出：latest_confirmation，主脚本别名a；另外提供合约类型字典sct。

三个编号：
  key_trade_comfirm_id = 金仕达交易确认书ID（排序键、标的连接键、目标Agt_Id）。
  contract_code       = 主合约编号（输出Inr_Seri_No和Ext_Comp_No，不代替确认书ID）。
  counterparty_id     = 交易对手（直接连接境内客户client_id）。
*/

/* 第一步：排序
   busi_date是读取快照的日期；business_date是确认书记录的业务日期。
   rn=1表示当前快照里该确认书最新的一条，不是“最新有效的一条”。
*/
ranked_confirmations AS (
    select *,
        row_number() over(
            partition by key_trade_comfirm_id
            order by business_date desc
        ) as rn
    from odata_n_tit.d_ks_trade_comfirm_info -- 交易确认书信息表
    where busi_date = '${data_day_str}'
),

/* 第二步：每张确认书取1条
   本步输出仍包含合约状态、日期、本金等原字段。
   状态与起始日是否满足报表范围，在主脚本再判断；不可提前到排序前。
*/
latest_confirmation AS (
    select *
    from ranked_confirmations t
    where t.rn = 1
),

-- 并列输入：源互换类型的中文名，不参与挑选最新确认书。
-- a.trs_type（互换类型）→ sct.dw_cd_val（代码）→ dw_cd_val_desc（中文描述）。
contract_type_dictionary AS (
    select *
    from PDATA_N.REF_DW_CD_VAL -- 仓库代码取值
    where dw_cd_id = 'CD382' and remark = 'TITANS场外衍生品合约类型'
)
-- business_date并列时，原SQL没有第二排序键；本次不增加裁决规则。

,
/*
03 / 一张确认书挂钩哪些标的？
输入：odata_n_tit.d_ks_trs_eod_postion（日终持仓表视图）的加工日快照。
本文件名称保留原业务主题编号；实际不读取期权篮子成分表。

持仓记录
  → ① 按“确认书+标的”排序
  → ② 每个标的只取最新记录
  → ③ 补证券全名、证券集、币种和类型中文名
  → ④ 按确认书拼出标的清单
输出underlying_summary，主脚本别名ins。本金不在这里算，见11。
*/

/* ① 排序：同一标的的哪一天持仓较新？
   key_trade_comfirm_id：金仕达交易确认书编号ID。
   underlying_wind_code：底层资产WIND代码。
   src_busi_date：持仓日期（源头BUSI_DATE）；不是本次读取的快照日busi_date。
*/
ranked_positions AS (
    select *,
        row_number() over(
            partition by key_trade_comfirm_id, underlying_wind_code
            order by src_busi_date desc
        ) as rn
    from odata_n_tit.d_ks_trs_eod_postion -- 日终持仓表视图（元数据名称）
    where busi_date = '${data_day_str}'
),

/* ② 取最新：每“确认书+WIND代码”保留1条
   各标的分别选最新，可能不是同一天；不要求持仓日=加工日，也不检查数量非零。
   日期并列时没有第二排序键。
*/
latest_positions AS (
    select
        x.key_trade_comfirm_id, -- 交易确认书ID
        x.underlying_wind_code as un_code, -- 底层资产WIND代码
        x.wind_name as un_name -- 底层资产证券名称
    from ranked_positions x
    where x.rn = 1
),

/* ③ 补资料：持仓只有代码和名称，还需要证券类别、币种等信息
   b = 上一步的持仓标的；d = 证券基本信息；sutd = CD128标的类型字典。
   用WIND代码连接，不是证券内码；多条证券/字典匹配会保留，不在此去重。
*/
position_details AS (
    select
        b.key_trade_comfirm_id as key_trade_comfirm_id, -- 确认书ID
        b.un_code as un_code, -- 持仓中的WIND代码
        b.un_name as un_name, -- 持仓中的名称
        d.ins_lng_desc as ins_lng_desc, -- 证券全名
        d.ins_family as ins_family, -- 证券集，决定股票/非股票分类
        d.currency as currency, -- 证券币种，参与市场分类
        sutd.dw_cd_val_desc as dw_cd_val_desc -- 源标的类型中文描述
    from latest_positions b
    left join (
        select * from odata_n_tit.d_ref_instrument where busi_Date = '${data_day_str}' -- 证券-证券基本信息
    ) d
        on d.wind_code = b.un_code
    left join (
        select *
        from PDATA_N.REF_DW_CD_VAL -- 仓库代码取值
        where dw_cd_id = 'CD128' and remark = 'TITANS场外衍生品标的类型'
    ) sutd
        on sutd.dw_cd_val = d.ins_family
),

/* ④ 汇总：每确认书输出1组标的清单
   p = 上一步补齐的标的资料，字段来源见③，不是新的物理表。
   名称/代码用分号保留列表；类型/币种用逗号去重拼接。均无排序保证，不能按位置配对。
*/
underlying_summary AS (
    select
        p.key_trade_comfirm_id, -- 汇总键，也是接回确认书的键
        '' as Undrl_Ins_Id, -- 标的内部ID：本分支固定空串
        concat_ws(';',collect_list(p.un_code)) as Undrl_Wd_Cd, -- 标的WIND代码
        concat_ws(';',collect_list(p.un_name)) as Undrl_Name, -- 持仓来源的名称
        concat_ws(';',collect_list(p.ins_lng_desc)) as Undrl_Long_Name, -- 证券全名
        -- 股票/GDR/篮子按币种分市场；其他证券集为非股票，信息不足时为'-'。
        concat_ws(',',collect_set(case
            when p.ins_family in ('EQUITY', 'GDR', 'BASKET') and p.currency not in ('HKD', 'USD') then 'OTH_STOCK'
            when p.ins_family in ('EQUITY', 'GDR', 'BASKET') and p.currency = 'HKD' then 'HK_STOCK'
            when p.ins_family in ('EQUITY', 'GDR', 'BASKET') and p.currency = 'USD' then 'US_STOCK'
            when p.ins_family not in ('EQUITY', 'GDR', 'BASKET') then 'NON_STOCK'
            else '-' end)) as Undrl_Type,
        '' as Undrl_Type_Desc, -- 标的类型描述：固定空串
        concat_ws(',',collect_set(p.ins_family)) as Src_Undrl_Type, -- 源证券集
        concat_ws(',',collect_set(p.dw_cd_val_desc)) as Src_Undrl_Type_Desc, -- 类型中文描述
        concat_ws(',',collect_set(coalesce(p.currency,''))) as Undrl_Curr -- 标的币种
    from position_details p
    group by p.key_trade_comfirm_id
)
-- 主脚本还要求Undrl_Wd_Cd非NULL；没有匹配本汇总的确认书会被剔除，但空字符串不等于NULL。


-- 二、写入当前分支：仅覆盖指定加工日+grp_id分区；四个分支分开写入，不在此UNION。
insert overwrite table T98_OTC_DERI_COMP_SALE_INFO partition(busi_date = '${data_day_str}', grp_id = '03')
-- 三、装配目标字段：列顺序与统一DDL一致；分类、本金和固定值均在11中说明。
SELECT
/*
本文件是90个输出字段的表达式清单；主脚本负责FROM/JOIN及分区写入，列顺序不能改变。

用到的别名和实际来源
  a   → 02的latest_confirmation → odata_n_tit.d_ks_trade_comfirm_info（交易确认书信息表）
        key_trade_comfirm_id=确认书ID；contract_code=主合约编号；counterparty_id=交易对手。
        trs_type=互换类型；notional=名义本金；dynamic_notional=动态名义本金；mgr_rate=履保比例。
  ins → 03的underlying_summary → odata_n_tit.d_ks_trs_eod_postion（日终持仓表视图）
        按确认书汇总标的；证券全名、证券集和币种补自odata_n_tit.d_ref_instrument。
  cp  → 01的境内客户 → odata_n_ois.o_otc_derivative_counterparty（衍生品交易对手维护表）
  sct → 02的CD382字典 → pdata_n.ref_dw_cd_val（仓库代码取值），dw_cd_val_desc为源类型中文描述。

先读三处业务规则：下方“经营分类” → “04 本金” → “09 固定账簿等输出”。
其余多为字段直取或固定空值，保留中文释义，但不新增计算层。
分类和本金规则短，直接保留在下方，不另拆09/10文件。
*/
-- 01 身份与客户：确定合约编号及交易对手。
a.key_trade_comfirm_id as Agt_Id, -- 目标合约编号：实际取交易确认书ID，不是主合约编号
'TRS' as Busi_Type, -- 业务类型
a.counterparty_id as Cutp_Pty_Id, -- 交易对手客户编号
cp.abbreviation as Cutp_Pty_Shor_Name, -- 交易对手当事人简称
cp.corporate_name as Cutp_Pty_Full_Name, -- 交易对手当事人名称
cp.Signature_Name as Sign_Prd_Name, -- 代签产品名称
cp.industry as Indt_Cd, -- 行业代码
cp.aptitude as Corp_Qual, -- 企业资质
-- 经营分类（用a.trs_type，不是标的类型）：
--   B_LONG_SHORT_SWAP → TRS_KINGSTAR_SWAP / 金仕达多空互换
--   其他             → TRS_LONG_SHORT / 多空互换
-- 没有期权/普通互换的2025日期分界；源类型本身仍在下一组字段中保留。
if(a.trs_type = 'B_LONG_SHORT_SWAP', 'TRS_KINGSTAR_SWAP', 'TRS_LONG_SHORT') as Contr_Type_Cd, -- 合约类型代码
if(a.trs_type = 'B_LONG_SHORT_SWAP', '金仕达多空互换', '多空互换') as Contr_Type_Desc, -- 合约类型描述
-- 02 源系统类型：保留源类型及字典描述，与经营分类并列展示。
a.trs_type as Src_Contr_Type, -- 源合约类型
sct.dw_cd_val_desc as Src_Contr_Type_Desc, -- 源合约类型描述
'' as Src_Sub_Contr_Type, -- 源合约子类型
'' as Src_Sub_Contr_Type_Desc, -- 源合约子类型描述
-- 03 标的及方向：标的来自03的持仓汇总；不是直接用确认书中的同名标的字段。
ins.Undrl_Ins_Id, -- 标的ID
ins.Undrl_Wd_Cd, -- 标的万得代码
ins.Undrl_Name, -- 标的名称
ins.Undrl_Type, -- 标的类型
ins.Undrl_Type_Desc, -- 标的类型描述
ins.Src_Undrl_Type, -- 源标的类型
ins.Src_Undrl_Type_Desc, -- 源标的类型描述
'0' as Res_Flag, -- 限售标志
'0' as IPO_Flag, -- IPO标志
if(a.seller in ('GFS','GFZQ'), '1', '2') as Buy_Sell_Dir_Cd, -- 买卖方向代码：按源seller（卖方）判断
-- 04 本金：直接取确认书，不用03的持仓数量/价格反算，也不增加期权式的日期区间判断。
-- B_LONG_SHORT_SWAP的初始本金与动态本金同取dynamic_notional；其他类型初始本金取notional。
-- 不换算、不补0；Cny_Ex_Rate=NULL不代表汇率为1，末尾固定CNY也不能证明源金额已换算。
null as Cny_Ex_Rate, -- 人民币汇率
if(
    a.trs_type = 'B_LONG_SHORT_SWAP',
    a.dynamic_notional, -- 金仕达多空互换：初始本金也取源动态名义本金
    a.notional          -- 其他：取源名义本金
) as Init_Nom_Prin, -- 初始名义本金
a.dynamic_notional as Dyna_Nom_Prin, -- 动态名义本金
'0.0' as Absl_Nom_Prin, -- 绝对名义本金
-- 05 生命周期：起止日、提前终止日、兑付日及状态码。
substring(a.start_date, 1, 10) as Strt_Pric_Date, -- 期初定价日
substring(a.end_date, 1, 10) as End_Pric_Date, -- 期末定价日
substring(a.early_termination_date, 1, 10) as Early_Term_Date, -- 提前终止日
substring(a.Payment_Date, 1, 10) as Earn_Pymt_Date, -- 收益兑付日
a.Time_To_Maturity as Term_Days, -- 期限天数
case when a.contr_status in ('EFFECTIVE', 'EFFECTIVE_PENDING', 'TERMINATING', 'TERMINATING_PENDING') then '101'
         when a.contr_status = 'TERMINATED' then '226'
         end as Agt_Stat_Cd, -- 协议状态代码
-- 06 内部关联与费用：流水号、组合、保证金及费率。
a.contract_code as Inr_Seri_No, -- 目标内部流水号：实际取主合约编号
null as Otc_Seri_No, -- 场外合约流水号
null as bndl_id, -- 组合编号
null as Rel_Agt_Id, -- 关联合约编号
a.MGR_RATE as Init_Marg_Prop, -- 源“履保比例”→目标初始保证金比例；源注释未标明单位
null as init_Marg_Bal, -- 初始保证金
null as Ddct_Ptrn, -- 抵扣模式
cp.commission_rate as cms_rate, -- 佣金费率
null as fixed_rate, -- 固定腿利率
null as fee_rate, -- 实际费率
-- 07 期权专属字段：本分支下面这些列都填NULL，没有隐藏的条款计算。
-- 读业务逻辑时可直接跳到08；这些占位列为保持统一90列顺序而保留。
null as Hedg_Type_Cd, -- 对冲类型代码
null as Opt_Fee, -- 期权费
null as Opt_Fee_Paid_Date, -- 期权费支付日期
null as KO_Prtc_rate, -- 敲出参与率
null as KO_Yield, -- 敲出收益率
null as net_coll, -- 交易净收取
null as Coup_Rate, -- 票息
null as Min_OBS_DATE, -- 最小观察日
null as Max_OBS_DATE, -- 最大观察日
null as Up_Prtc_rate, -- 向上参与率
null as Down_Prtc_rate, -- 向下参与率
null as KI_Barr_PCT, -- 敲入障碍价
null as KO_Barr_PCT, -- 敲出障碍价
null as Strk_PCT, -- 执行价
null as DOWN_Strk_PCT, -- 下跌保护执行价格
null as UP_Strk_PCT, -- 封顶价格
-- 08 加工留痕：保留源代码与调度占位符，不在本地替换参数。
'TIT' AS Data_Src_Cd, -- 原SQL固定来源码；不表示此分支从TITANS合约表起算
UPPER('${filename}') AS Task_Name, -- 任务名
'${data_day_str}' AS Data_Etl_Date, -- 数据加载日期
'${data_day_str}' AS Data_Upt_Date, -- 数据更新日期
'${data_today}' AS Data_Time, -- 数据时间
-- 09 扩展属性与固定值：区分“有源字段”与“报表写死的值”。
-- 来源字段：a提供状态、主合约编号；ins提供标的全名/币种；cp提供客户资质复核。
-- 固定值：部门OTC，下面的账簿/柜台/销售方，以及末尾的结算币种CNY。
'OTC' as Book_Bel_Dept, -- 账簿所属部门
null as Bgng_Npv, -- 期初NPV
a.contr_status as Src_Agt_Stat_Cd, -- 源合约状态
ins.Undrl_Long_Name, -- 标的长名称
cp.client_qualify_review as Qual_Revw_Flag, -- 客户资质复核标志
a.contract_code as Ext_Comp_No, -- 主合约编号也写入目标外部合约编号
'' as Key_Cutp_Id, -- Titans客户编号
ins.Undrl_Curr, -- 标的币种
null as Intr_Marg, -- 利差
null as Base_Marg_Rate, -- 基础保证金率
null as Marg_Agt_Id, -- 保证金合约编号
null as Opt_Fee_Rate, -- 期权费率
-- 金仕达账簿/柜台/卖方为原脚本固定值，不通过公共交易账簿视图查出；Data_Src_Cd仍沿用TIT。
'10023' as Book_Agt_Id, -- 账簿协议编号
'OTC-互换-金仕达合约' as Book_Name, -- 账簿名称
'PORTFOLIO_SWAP' as Cntr, -- 柜台
'TIT060-10142' as Sler_Cutp_Pty_Id, -- 销售方交易对手当事人编号
'' as Futr_Type, -- 期货类型
'' as Agt_Clas_Cd, -- 协议分类代码
'' as Cros_Crrc_Type_Cd, -- 跨币种类型代码
'' as Float_Base_Rate, -- 浮动基础利率
'' as Float_Undrl_Cd, -- 浮动腿标的代码
'' as Flot_Intrt_Ulmt, -- 浮动利率上限
null as Comp_Usag_Cd, -- 合约用途代码
'CNY' as Sett_Crrc_Cd, -- 固定结算币种代码，不读取a.settlement_currency
null as Ex_Rate_Model -- 汇率模式

-- 四、连接加工主线：确认书a → 持仓标的ins / 境内客户cp / 类型字典sct。
from latest_confirmation a
-- 标的：以确认编号连接；末尾WHERE还要求标的万得代码非NULL，因此未匹配标的的确认会被剔除。
left join underlying_summary ins
on ins.key_trade_comfirm_id = a.key_trade_comfirm_id
-- 客户：a.counterparty_id直接连接境内客户；不经过TITANS客户编号映射。
LEFT JOIN sale_customer cp
on a.counterparty_id = cp.client_id
left join contract_type_dictionary sct
on sct.dw_cd_val = a.trs_type
-- 五、最终范围：保留EFFECTIVE、EFFECTIVE_PENDING、TERMINATED、TERMINATING、TERMINATING_PENDING。
-- 此条件包含已终止状态，不能简单理解为“仅存续合约”。
where a.Contr_Status in ('EFFECTIVE', 'EFFECTIVE_PENDING', 'TERMINATED', 'TERMINATING', 'TERMINATING_PENDING')
-- 额外门槛：起始日和标的万得代码必须非NULL；不额外剔除空字符串。
    and a.start_date is not null and ins.Undrl_Wd_Cd is not null
;
