-- GENERATED by render.mjs; edit manifest.json entries and 04_业务模块/ instead.
/*
04 指定FAST TRS / 任务220650 / grp_id=04
阅读入口：../04_业务模块/04_指定FAST_TRS/README.md

交易trade ──交易键──→ 北上极速合约rt（N_CROSS_DMA_SWAP）
         ├─工具键──→ 初始持仓dy：各标的最早日终记录 → 标的摘要、初始本金
         └─工具键──→ 当日持仓np：当日日终记录     → 动态本金

两份持仓分别直连交易，不经过结构腿，也不彼此依赖连接。
客户、报备、保证金和组合计划在下面补入；主查询未按合约去重。
维护模块后运行 node render.mjs --write 04_指定FAST_TRS 更新完整SQL；
@include不是Hive语法，执行前需展开并预先建立公共视图。
*/
-- 【用途】沿用四个分支原有Hive/MapReduce执行设置；被主脚本首先引用，不包含业务筛选逻辑。
-- 【文件合并】启用Map及MapReduce输出文件合并；目标合并大小和小文件均值阈值均为1 GiB。
-- 【输入切片】使用CombineHiveInputFormat，split最大/最小值均为1 GiB；这是执行参数，不代表数据行粒度。
-- 【边界】实际效果取决于引擎与作业配置；本次仅保留原设置，没有调参或运行验证。
set hive.merge.mapfiles=true ;
set hive.merge.mapredfiles=true;
set hive.merge.size.per.task=1073741824;
set hive.merge.smallfiles.avgsize=1073741824;
set hive.merge.orcfile.stripe.level=false;

set hive.input.format=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat;
set mapreduce.input.fileinputformat.split.maxsize=1073741824;
set mapreduce.input.fileinputformat.split.minsize=1073741824;


-- 一、准备模块：下列文件定义命名CTE；编号是主题导航，不表示数据库物理执行顺序。
WITH
/*
01 / 复用交易账簿、客户与组合计划的公共资料

公共视图定义在../../02_公共视图/，这里仅选加工日快照：
  v_t98_sale_trade_scope  → sale_trade：交易＋账簿；排除测试账簿10022/10019，限定OTC/OTC_HK部门。
  v_t98_sale_counterparty → sale_customer：境内客户＋香港客户，沿用UNION ALL。
  v_t98_sale_bundle_plan  → sale_bundle_plan：组合＋保证金计划，提供抵扣模式。
这三份结果在主脚本分别连接；客户和计划不是交易必备资料，也不在这里去重。
*/

-- 交易键key_otc_trade_id接FAST合约；工具键key_instrument_id接初始与当日持仓汇总。
sale_trade AS (
    SELECT key_otc_trade_id, internal_trade_id, key_instrument_id, key_book_id,
           book_key_book_id, business_type, department, book_name, desk, company
    FROM v_t98_sale_trade_scope
    WHERE busi_date = '${data_day_str}'
),

-- 组合计划：在主脚本按合约 bundle_id LEFT JOIN，计划缺失不会在本模块剔除交易。
sale_bundle_plan AS (
    SELECT bundle_id, key_plan_id, deduction_pattern
    FROM v_t98_sale_bundle_plan
    WHERE busi_date = '${data_day_str}'
),

-- 客户：由客户映射的 outside_ctpty_code 连接 client_id；境内/香港仍为 UNION ALL，不按客户号合并。
sale_customer AS (
    SELECT client_id, abbreviation, corporate_name, Signature_Name, industry, aptitude, commission_rate, client_qualify_review
    FROM v_t98_sale_counterparty
    WHERE busi_date = '${data_day_str}'
)

,
/*
02 / 先限定北上极速合约，再补客户和附属资料

范围：d_ref_fast_trs中trs_type='N_CROSS_DMA_SWAP'的加工日快照。
本地CD382字典中该代码对应“北上极速”；这不是全部FAST互换的通用加工。
合约提供类型、日期、状态和客户入口；本金另读北上极速腿历史持仓表。
下面各项在主脚本分别连接，不在这里合成一张宽表。
*/

-- rt：极速互换合约；key_otc_trade_id（合约ID）连接交易，start_date/end_date为期初/期末定价日。
-- seller为卖方，非销售人员；contract_code输出外部合约编号，bundle_id连接组合计划。
-- key_ctpty_id在本SQL中用作客户映射键；本地字段备注为STOCK_DIV_MODE，明显与用途不符，暂不采作释义。
fast_contract AS (
    select * from odata_n_tit.d_ref_fast_trs -- 极速互换合约要素表
    where busi_Date = '${data_day_str}' and trs_type = 'N_CROSS_DMA_SWAP'    
    ),

-- TOCR：Actual_Settlement_Date原义“实际结算日”，在本输出中命名为提前终止日；按交易键连接，不选最新。
settlement_report AS (
    select * from odata_n_tit.d_trd_otc_contr_report where busi_Date = '${data_day_str}' -- 交易-合约报备信息
    ),

-- 客户编号桥接（rcm）：内部 key_ctpty_id → outside_ctpty_code → 公共客户 client_id。
customer_mapping AS (
    select * from odata_n_tit.d_ref_ctpty_mapping where busi_Date = '${data_day_str}' -- 交易参数-交易对手映射表
    ),

-- 关联合约属性（rel）：只取 property_name=relatedOption，通过交易键连接。
-- property_value 直接输出 Rel_Agt_Id；保留源记录数量，不将多值合成一条。
related_contract AS (
    select * from odata_n_tit.d_trd_otc_contr_props -- 【AI】交易-场外合约结构-其他属性表
    where busi_Date = '${data_day_str}' and property_name = 'relatedOption'
    ),

-- mrg：通过交易键接保证金参数；initial_margin=【AI】保证金初始线(%)，
-- margin_balance_init=【AI】初始履约保障金额(元)，basic_margin_rate=【AI】基础保证金率。
-- margin_internal_trade_id直接输出保证金合约编号；与普通互换汇总关联期权交易键的来源不同。
margin_parameters AS (
    select * from odata_n_tit.d_ref_otc_contr_margin_param -- 【AI】合约-静态履约保证金参数
    where busi_Date = '${data_day_str}'
    ),

-- 源合约类型字典（sct）：代码域 CD382，并限定 TITANS场外衍生品合约类型。
-- 按 dw_cd_val 连接源类型取中文描述；字典无加工日过滤，也未新增唯一性约束。
contract_type_dictionary AS (
    select *
    from PDATA_N.REF_DW_CD_VAL -- 仓库代码取值
    where dw_cd_id = 'CD382' and remark = 'TITANS场外衍生品合约类型'
    )

,
/*
07 / 初始本金和展示标的，怎样从历史持仓中选出来？

源表：odata_n_tit.d_pos_fast_trs_leg_his_pos（北上极速腿历史持仓表）。
只读加工日快照中的EOD_POSITION（日终持仓），按“合约工具键＋标的代码”找最早记录。

  历史排序 → 每个标的选最早一条 → 补标的资料和类型 → 按合约工具键汇总
                                                       ├─ 初始本金
                                                       └─ 展示标的摘要

关键字段：
  key_instrument_id → 本持仓表注释为“合约ID”，接交易表的同名工具键。
  wind_code         → 标的代码，用它区分同一合约下的标的；不是按underlying_ins_id分组排序。
  src_busi_date     → 持仓日期（源头的busi_date），决定最早记录。
  busi_date         → 数据日期，这里用于限定本次加工快照。
  dynamic_notional  → 动态名义本金（标的币种）。取最早记录上的这个字段，汇总为初始本金；
                      没有改取notional，也没有重算期初价格×数量。

“最早”按各标的分别选，不一定是同一个日期；后来加入的标的也可能纳入。
最终initial_position在主脚本中别名为dy：这里dy表示初始结果，不是当日持仓。
*/

-- ① 历史排序：同一合约工具键、同一WIND代码，从早到晚编号；同日并列未加裁决键。
ranked_initial_positions AS (
    SELECT *,row_number() over(partition by key_instrument_id, wind_code order by src_busi_date) as rk
    FROM odata_n_tit.d_pos_fast_trs_leg_his_pos -- 北上极速腿历史持仓表
    where busi_Date = '${data_day_str}' and position_type = 'EOD_POSITION'
    ),

-- ② 选最早记录：每个“合约工具键＋标的代码”一行，还没有汇总本金。
first_initial_positions AS (
    SELECT *
    FROM ranked_initial_positions
    where rk = 1
    ),

-- ③ 补标的资料：dy为所选持仓，d为证券基本信息；两边的类型、币种来源要分开。
-- 持仓WIND代码 → 证券WIND代码 → 证券内码 → 期货属性；字典按证券表的证券集取中文名。
-- 保留LEFT JOIN的多条匹配，不去重；因此后面的本金汇总可能受维表重复影响。
initial_position_details AS (
    SELECT
        dy.key_instrument_id as key_instrument_id, -- 合约侧工具键，不是下方证券表的证券内码
        dy.underlying_ins_id as underlying_ins_id, -- 标的ID
        dy.wind_code as wind_code, -- 标的代码
        dy.ins_sht_desc as ins_sht_desc, -- 标的简称，取持仓表
        d.ins_lng_desc as ins_lng_desc, -- 证券全名，取证券基本信息
        -- 标的市场分类：持仓的类型＋证券表的币种；不是按持仓币种判断HK/US。
        -- OTH_STOCK=其他股票市场，HK_STOCK=港股，US_STOCK=美股，NON_STOCK=非股票；“-”为未匹配。
        case when dy.ins_family in ('EQUITY', 'GDR', 'BASKET') and d.currency not in ('HKD', 'USD') then 'OTH_STOCK'
             when dy.ins_family in ('EQUITY', 'GDR', 'BASKET') and d.currency = 'HKD' then 'HK_STOCK'
             when dy.ins_family in ('EQUITY', 'GDR', 'BASKET') and d.currency = 'USD' then 'US_STOCK'
             when dy.ins_family not in ('EQUITY', 'GDR', 'BASKET') then 'NON_STOCK'
             else '-' end as underlying_type,
        dy.ins_family as ins_family, -- 源标的类型：持仓表的标的类型
        sutd.dw_cd_val_desc as dw_cd_val_desc, -- 源类型描述却按证券表ins_family查字典，原SQL并非同一来源
        dy.currency as currency, -- 展示币种取持仓表，不是上述市场分类使用的证券表币种
        f.future_type as future_type, -- 期货类型
        dy.dynamic_notional as dynamic_notional -- 所选最早记录的动态名义本金（标的币种）
    FROM first_initial_positions dy
    left join (
        select * from odata_n_tit.d_ref_instrument where busi_Date = '${data_day_str}' -- 证券-证券基本信息
        ) d
    on d.wind_code = dy.wind_code
    left join (
        select * from odata_n_tit.d_ref_future_properties where busi_Date = '${data_day_str}' -- 【AI】证券-期货信息表
        ) f
    on f.key_instrument_id = d.key_instrument_id
    left join (
        select *
        from PDATA_N.REF_DW_CD_VAL -- 仓库代码取值
        where dw_cd_id = 'CD128' and remark = 'TITANS场外衍生品标的类型'
        ) sutd
    on sutd.dw_cd_val = d.ins_family
    ),

-- ④ 按合约工具键汇总：p是上一步明细；本金已经由源系统提供，本步只求和。
-- 名称/代码用分号、类型/币种用逗号；各列独立收集且无指定顺序，不能按位置配对。
-- collect_list保留重复，collect_set去重；不等于对本金明细去重。
initial_position AS (
    select
        p.key_instrument_id,
        concat_ws(';',collect_list(p.underlying_ins_id)) as Undrl_Ins_Id,
        concat_ws(';',collect_list(p.wind_code)) as Undrl_Wd_Cd,
        concat_ws(';',collect_list(p.ins_sht_desc)) as Undrl_Name,
        concat_ws(';',collect_list(p.ins_lng_desc)) as Undrl_Long_Name,
        concat_ws(',',collect_set(p.underlying_type)) as Undrl_Type,
        '' as Undrl_Type_Desc,
        concat_ws(',',collect_set(p.ins_family)) as Src_Undrl_Type,
        concat_ws(',',collect_set(p.dw_cd_val_desc)) as Src_Undrl_Type_Desc,
        concat_ws(',',collect_set(coalesce(p.currency,''))) as Undrl_Curr,
        concat_ws(',',collect_set(p.future_type)) as future_type,
        sum(p.dynamic_notional) as Init_Nom_Prin -- 初始名义本金；未在此换汇
    FROM initial_position_details p
    group by p.key_instrument_id
    )

,
/*
08 / 当天的动态本金是多少？

只保留同时满足三个条件的持仓：
  数据日期busi_date = 加工日；
  持仓类型position_type = EOD_POSITION（日终持仓）；
  源持仓日期src_busi_date的日期部分 = 加工日。

再按key_instrument_id（本表注释：合约ID）汇总dynamic_notional。
这是读取源系统提供的金额，不是普通互换的“期初价格×当日数量”计算。
与07_初始持仓.sql不同：不选最早记录、不补证券资料、不去重。

结果daily_position在主脚本中别名为np，直接接交易表的key_instrument_id；
不经过初始持仓结果。没有当天记录时也不延续前日，输出处再对缺失金额补'0'。
*/
daily_position AS (
    select key_instrument_id, sum(dynamic_notional) as Dyna_Nom_Prin -- 动态名义本金（标的币种）之和
    from odata_n_tit.d_pos_fast_trs_leg_his_pos -- 北上极速腿历史持仓表
    where busi_date = '${data_day_str}' and position_type = 'EOD_POSITION' and substring(src_busi_date,1,10) = '${data_day_str}'
    group by key_instrument_id
    )


-- 二、写入当前分支：仅覆盖指定加工日+grp_id分区；四个分支分开写入，不在此UNION。
insert overwrite table T98_OTC_DERI_COMP_SALE_INFO partition(busi_date = '${data_day_str}', grp_id = '04')
-- 三、输出字段：分类直接用FAST源类型；本金来源与固定汇率在10_本金与汇率.sql解释。
SELECT
/*
11 / 把合约、持仓和客户资料放入销售主信息的90个字段

  trade / rt → 交易身份、账簿、合约类型及期限
  dy         → 初始持仓汇总：展示标的＋初始本金（别名dy不是当日）
  np         → 当日持仓汇总：动态本金
  rcm / cp   → 客户编号映射及客户展示资料
  TOCR / rel / mrg / mp → 报备日期、关联合约、保证金与组合抵扣模式

本文件为主脚本SELECT表达式清单，金额部分引用10_本金与汇率.sql。
行末中文名取自目标DDL；NULL、空串和字符串0沿用原值，不能互换。
*/
-- 01 身份与客户：确定合约编号及交易对手。
trade.internal_trade_id as Agt_Id, -- 合约编号
'TRS' as Busi_Type, -- 业务类型
rcm.outside_ctpty_code as Cutp_Pty_Id, -- 交易对手客户编号
cp.abbreviation as Cutp_Pty_Shor_Name, -- 交易对手当事人简称
cp.corporate_name as Cutp_Pty_Full_Name, -- 交易对手当事人名称
cp.Signature_Name as Sign_Prd_Name, -- 代签产品名称
cp.industry as Indt_Cd, -- 行业代码
cp.aptitude as Corp_Qual, -- 企业资质
-- 经营分类直接等于源类型：N_CROSS_DMA_SWAP；名称按CD382字典取得，本地记录为“北上极速”。
-- 没有普通互换的新旧CASE分类规则，因此不另建经营分类文件；字典缺失时名称仍为NULL。
rt.trs_type as Contr_Type_Cd, -- 合约类型代码
sct.dw_cd_val_desc as Contr_Type_Desc, -- 合约类型描述
-- 02 源系统类型：保留源类型及字典描述，与经营分类并列展示。
rt.trs_type as Src_Contr_Type, -- 源合约类型
sct.dw_cd_val_desc as Src_Contr_Type_Desc, -- 源合约类型描述
'' as Src_Sub_Contr_Type, -- 源合约子类型
'' as Src_Sub_Contr_Type_Desc, -- 源合约子类型描述
-- 03 标的及方向：展示07_初始持仓.sql的标的摘要，不是当日持仓名单。
dy.Undrl_Ins_Id, -- 标的ID
dy.Undrl_Wd_Cd, -- 标的万得代码
dy.Undrl_Name, -- 标的名称
dy.Undrl_Type, -- 标的类型
dy.Undrl_Type_Desc, -- 标的类型描述
dy.Src_Undrl_Type, -- 源标的类型
dy.Src_Undrl_Type_Desc, -- 源标的类型描述
'0' as Res_Flag, -- 限售标志固定值，本SQL未读取实际限售属性
'0' as IPO_Flag, -- IPO标志固定值，本SQL未读取实际IPO属性
if(rt.seller in ('10161','10142'), '1', '2') as Buy_Sell_Dir_Cd, -- 买卖方向代码
-- 04 本金：两个持仓金额的来源、选日差异与未换汇边界见下方引用文件。
/*
10 / 两个本金都来自dynamic_notional，区别在“选哪天的持仓”

实际来源：odata_n_tit.d_pos_fast_trs_leg_his_pos（北上极速腿历史持仓表）。
dynamic_notional的字段注释是“动态名义本金（标的币种）”。
本分支不使用合约表d_ref_fast_trs上的notional/dynamic_notional，
也不在这里重算价格×数量；合约上的同名字段注释是结算币种，不能混作同一来源。

  07_初始持仓.sql → initial_position，主脚本别名dy
    每个“合约工具键＋WIND代码”取最早日终记录，补标的资料后求和。
    dy.Init_Nom_Prin = SUM(最早记录的dynamic_notional)

  08_当日持仓.sql → daily_position，主脚本别名np
    取源持仓日期等于加工日的日终记录，直接按合约工具键求和。
    np.Dyna_Nom_Prin = SUM(当日记录的dynamic_notional)

示例（无重复匹配、同一币种）：
  标的A最早金额100、标的B最早金额200 → 初始本金300；
  当日A金额80、B金额150             → 动态本金230。
  初始记录可以来自不同日期；初始金额缺失不补0，当日金额为NULL则输出处补'0'。

与普通互换不同：这里不选择期初汇率、不乘汇率，也不增加合约起止日期判断。
Cny_Ex_Rate固定输出字符串'1'，只说明这段SQL未换汇；
结合“标的币种”的源字段注释，不能直接宣称金额已折成人民币。
原SQL按合约工具键直接求和，没有按币种分别汇总；上游币种约束或换算口径仍需另核实。
*/

'1' as Cny_Ex_Rate, -- 固定输出1，本分支不做汇率计算
dy.Init_Nom_Prin, -- 初始名义本金：最早持仓金额汇总，缺失保持NULL
coalesce(np.Dyna_Nom_Prin,'0') as Dyna_Nom_Prin, -- 动态名义本金：当日汇总，缺失补'0'不证明实际无持仓
'0.0' as Absl_Nom_Prin, -- 固定值，不是对某个本金取绝对值

-- 05 生命周期：起止日、提前终止日、兑付日及状态码。
substring(rt.START_DATE, 1, 10) as Strt_Pric_Date, -- 期初定价日
substring(rt.End_Date, 1, 10) as End_Pric_Date, -- 期末定价日
substring(tocr.Actual_Settlement_Date, 1, 10) as Early_Term_Date, -- 目标“提前终止日”取报备表的实际结算日
'' as Earn_Pymt_Date, -- 收益兑付日
rt.Time_To_Maturity as Term_Days, -- 期限天数
case when rt.contr_status in ('EFFECTIVE', 'EFFECTIVE_PENDING', 'TERMINATING', 'TERMINATING_PENDING') then '101'
         when rt.contr_status = 'TERMINATED' then '226'
         end as Agt_Stat_Cd, -- 协议状态代码
-- 06 内部关联与费用：流水号、组合、保证金及费率。
trade.key_otc_trade_id as Inr_Seri_No, -- 内部流水号
trade.key_instrument_id as Otc_Seri_No, -- 场外合约流水号；同一个工具键也用于接持仓
rt.bundle_id as bndl_id, -- 组合编号
rel.property_value as Rel_Agt_Id, -- 关联合约编号
mrg.Initial_Margin as Init_Marg_Prop, -- 初始保证金比例
mrg.MARGIN_BALANCE_INIT as init_Marg_Bal, -- 初始保证金
mp.deduction_pattern as Ddct_Ptrn, -- 抵扣模式
cp.commission_rate as cms_rate, -- 佣金费率
null as fixed_rate, -- 固定腿利率
null as fee_rate, -- 实际费率
-- 07 期权专属字段：没有来源的分支按原SQL填NULL，不代表业务值为0。
null as Hedg_Type_Cd, -- 对冲类型代码
null AS Opt_Fee, -- 期权费
null as Opt_Fee_Paid_Date, -- 期权费支付日期
null as KO_Prtc_rate, -- 敲出参与率
null as KO_Yield, -- 敲出收益率
null as net_coll, -- 交易净收取
null as Coup_Rate, -- 票息
null as Min_OBS_DATE, -- 最小观察日
null as Max_OBS_DATE, -- 最大观察日
null as Up_Prtc_rate, -- 向上参与率
null as Down_Prtc_rate, -- 向下参与率
null as KI_Barr_PCT, -- 敲入障碍价
null as KO_Barr_PCT, -- 敲出障碍价
null as Strk_PCT, -- 执行价
null as DOWN_Strk_PCT, -- 下跌保护执行价格
null as UP_Strk_PCT, -- 封顶价格
-- 08 加工留痕：保留源代码与调度占位符，不在本地替换参数。
'TIT' AS Data_Src_Cd, -- 数据来源代码
UPPER('${filename}') AS Task_Name, -- 任务名
'${data_day_str}' AS Data_Etl_Date, -- 数据加载日期
'${data_day_str}' AS Data_Upt_Date, -- 数据更新日期
'${data_today}' AS Data_Time, -- 数据时间
-- 09 扩展属性：部门、估值、客户、账簿、卖方及跨币种字段。
trade.department as Book_Bel_Dept, -- 账簿所属部门
null as Bgng_Npv, -- 期初NPV
rt.contr_status as Src_Agt_Stat_Cd, -- 源合约状态
dy.Undrl_Long_Name, -- 标的长名称
cp.client_qualify_review as Qual_Revw_Flag, -- 客户资质复核标志
rt.contract_code as Ext_Comp_No, -- 外部合约编号
rt.key_ctpty_id as Key_Cutp_Id, -- Titans客户编号
coalesce(dy.Undrl_Curr,'') as Undrl_Curr, -- 持仓币种汇总；与合约结算币种、证券表市场分类币种分开
null as Intr_Marg, -- 利差
mrg.basic_margin_rate as Base_Marg_Rate, -- 基础保证金率
mrg.margin_internal_trade_id as Marg_Agt_Id, -- 保证金参数表直接提供的保证金合约编号
null as Opt_Fee_Rate, -- 期权费率
trade.book_key_book_id as Book_Agt_Id, -- 账簿协议编号
trade.Book_Name, -- 账簿名称
trade.Desk as Cntr, -- 柜台
IF(NVL(TRIM(rt.seller),'')='','',CONCAT('TIT060-',rt.seller)) as Sler_Cutp_Pty_Id, -- 销售方交易对手当事人编号
dy.future_type as Futr_Type, -- 期货类型
trade.business_type as Agt_Clas_Cd, -- 协议分类代码
rt.cross_currency_type as Cros_Crrc_Type_Cd, -- 跨币种类型代码
'' as Float_Base_Rate, -- 浮动基础利率
'' as Float_Undrl_Cd, -- 浮动腿标的代码
'' as Flot_Intrt_Ulmt, -- 浮动利率上限
null as Comp_Usag_Cd, -- 合约用途代码
rt.SETTLEMENT_CURRENCY as Sett_Crrc_Cd, -- 结算币种代码
null as Ex_Rate_Model -- 汇率模式

-- 四、实际连接：交易必须匹配指定FAST合约；后续LEFT JOIN不因资料缺失而剔除合约。
FROM sale_trade trade
inner join fast_contract rt
ON rt.key_otc_trade_id = trade.key_otc_trade_id
left join settlement_report TOCR
ON TOCR.KEY_OTC_TRADE_ID = rt.KEY_OTC_TRADE_ID
-- 客户链：合约内部客户键 → 客户映射 → 公共客户；LEFT JOIN不强制要求客户资料完整。
left join customer_mapping rcm
ON rt.key_ctpty_id = rcm.key_ctpty_id
-- 当日本金：直接按交易工具键连接np，不依赖初始持仓是否存在。
left join daily_position np
on np.key_instrument_id = trade.key_instrument_id
-- 初始本金与标的：同样直接按交易工具键连接dy；注意原别名dy在此表示初始而非当日。
left join initial_position dy
ON dy.key_instrument_id = trade.key_instrument_id
-- 合约附加属性：关联合约与保证金按交易键连接，组合计划按bundle_id连接。
left join related_contract rel
on rel.key_otc_trade_id = trade.key_otc_trade_id
left join margin_parameters mrg
on mrg.key_otc_trade_id = trade.key_otc_trade_id
LEFT JOIN sale_bundle_plan mp
    ON mp.bundle_id = rt.bundle_id
-- 客户展示资料：由外部客户号取简称/全称/资质等；境内和香港同号时仍保留原匹配结果。
LEFT JOIN sale_customer cp
on rcm.outside_ctpty_code = cp.client_id
left join contract_type_dictionary sct
on sct.dw_cd_val = rt.trs_type
-- 五、最终范围：保留EFFECTIVE、EFFECTIVE_PENDING、TERMINATED、TERMINATING、TERMINATING_PENDING。
-- 此条件包含已终止状态，不能简单理解为“仅存续合约”。
where rt.Contr_Status in ('EFFECTIVE', 'EFFECTIVE_PENDING', 'TERMINATED', 'TERMINATING', 'TERMINATING_PENDING')
;
