-- GENERATED by render.mjs; edit 00–07 modules or their referenced parameter SQL.
/*
118141 / 从“合约×计提日”的输入，算到销售收入日报。
这是阅读层次，不声明数据库物理执行顺序；不改变原查询的连接、窗口和字段顺序。

合约主信息 + 逐日金额 + 五路经营参数 + 人员机构
  → contract_day_income：原始当日收入
  → adjusted_day_income：扣金仕达系统费用 / 期权结束日保底调整
  → allocated_day_income：本金分配、收入分配、累计
  → 日报输出：保持原字段顺序与字符串转换

先沿普通期权读02、04、06；参数来源疑问再回到03相应材料。
@include由同目录render.mjs展开；这里只组织一条完整查询，不执行上游生产脚本。
*/

WITH contract_day_income AS (
    -- 第一阶段：输入如何汇合、原始当日收入怎样算，完整SELECT在01。
-- 输入：合约快照info、逐日金额det、五路参数、管理关系m。
-- 一行意图是合约的一个计提日；连接右侧多条记录时会扩行，不能承诺键唯一。
-- 输出：原始收入Curr_Prvs_Sales_Income及资料，供主脚本第二阶段T直接使用。
-- 参数并列补入同一层，不是先算价差再把收入拿去算基准。

select
    -- 合约身份、客户及标的展示：来自合约主信息info，不在此重建交易身份。
    info.Agt_Id, -- 合约编号：本层主体身份
    info.Busi_Type, -- 业务类型：期权OPTION／互换TRS
    info.Cutp_Pty_Id, -- 客户编号：客户类型级价差的匹配键之一
    info.Cutp_Pty_Shor_Name,
    info.Cutp_Pty_Full_Name,
    info.Sign_Prd_Name,
    info.Contr_Type_Cd, -- 经营分类后的合约类型：选类型参数、判断期权保底
    info.Contr_Type_Desc,
    info.Src_Contr_Type, -- 源合约类型：先判断AIRBAG等特殊收入分支
    info.Src_Contr_Type_Desc,
    info.Src_Sub_Contr_Type,
    info.Src_Sub_Contr_Type_Desc,
    '' as Undrl_Ins_Id,
    info.Undrl_Wd_Cd,
    info.Undrl_Name,
    info.Undrl_Type,
    info.Src_Undrl_Type,
    -- 选出的价差/基准展示值：计算类型与数值各自回退，空串不等于NULL。
    IF(
        coalesce(s_sp.Spread_Calculation, c_sp.Spread_Calculation) = 'ANNUALIZED',
        coalesce(s_sp.Annualized_Spread, c_sp.Annualized_Spread), ''
    ) AS Annu_Sprd, -- 年化价差：展示系数，不是收入金额
    IF(
        coalesce(s_sp.Spread_Calculation, c_sp.Spread_Calculation) = 'ABSOLUTE',
        coalesce(s_sp.Absolute_Spread, c_sp.Absolute_Spread), ''
    ) AS Absl_Sprd, -- 绝对价差系数
    IF(
        coalesce(s_ba.BASE_CALCULATION, c_ba.BASE_CALCULATION) = 'ANNUALIZED',
        coalesce(s_ba.BASE_AWARD_RATE, c_ba.BASE_AWARD_RATE), ''
    ) AS Annu_Base, -- 年化基准系数
    IF(
        coalesce(s_ba.BASE_CALCULATION, c_ba.BASE_CALCULATION) = 'ABSOLUTE',
        coalesce(s_ba.BASE_AWARD_RATE, c_ba.BASE_AWARD_RATE), ''
    ) AS Absl_Base, -- 绝对基准系数
    -- 金额来自107491明细det；初始本金来自合约主信息info。
    info.Init_Nom_Prin, -- 初始名义本金：绝对方式收入、保底门槛使用
    coalesce(det.Dyna_Nom_Prin, 0) as Dyna_Nom_Prin, -- 展示本金补0；02公式仍直接使用det原值
    sum(if(
        det.busi_date BETWEEN info.Strt_Pric_Date AND coalesce(info.Early_Term_Date, info.End_Pric_Date),
        coalesce(det.Dyna_Nom_Prin, 0), 0
    )) OVER (
        PARTITION BY info.agt_id, info.Contr_Type_Cd ORDER BY det.busi_date
    ) as Accum_Dyna_Nom_Prin, -- 逐日有效动态本金之和；这里未除天数，不是日均
    if(info.grp_id = '01', det.Dyna_Nom_Prin, 0) as Absl_Nom_Prin, -- 本任务仅期权取动态本金，其他分组为0
    sum(if(
        det.busi_date BETWEEN info.Strt_Pric_Date AND coalesce(info.Early_Term_Date, info.End_Pric_Date),
        coalesce(det.Dyna_Nom_Prin, 0), 0
    )) OVER (
        PARTITION BY info.agt_id, info.Contr_Type_Cd ORDER BY det.busi_date
    ) as Accum_Absl_Nom_Prin, -- 原式仍累加动态本金，不是上一列Absl_Nom_Prin的求和
/*
02 / 选择这一条合约日的原始收入规则。
位置：01_合约日与资料.sql的SELECT；输入资料已经在该层通过03参数匹配及管理关系JOIN提供。
输出：Curr_Prvs_Sales_Income，随后进入04调整，再进入06分配累计；不是已支付金额。

按下列优先级取第一个命中，不将四份模块的结果相加：
  02.1 特殊类型：AIRBAG抵扣/保证金关联，以及关联LONG_HOLD_SWAP置零
  02.2 金仕达：利息、交易收入成本和用资字段乘成本率
  02.3 普通期权：价差＋基准，四种年化/绝对组合
  02.4 普通互换：价差＋基准，四种年化/绝对组合

四个文件都是本CASE内部的WHEN/THEN片段，不是四张结果表；不要另建JOIN或UNION。
@include由render.mjs展开，完整SQL仍是一条查询。
末尾不补ELSE：没有匹配规则时，原始收入仍为NULL。
*/

CASE
-- 02.1 / 原始收入CASE的第1—4支；由02实际引用，后面才判断金仕达及普通业务。
-- 本片段只有WHEN/THEN，不独立SELECT、不另包CASE，不单独执行。
-- info：PDATA_N.T98_OTC_DERI_COMP_SALE_INFO（合约销售基础）。
--   Ddct_Ptrn=组合履保方案抵扣模式；Marg_Agt_Id=保证金关联合约编号集合。
--   Init_Marg_Prop=初始保证金比例；Base_Marg_Rate=基础保证金率。
-- det：PDATA_N.T98_OTC_DERI_COMP_SALE_ADTNL_DET（107491逐日明细）。
--   Dyna_Nom_Prin=当前计提日本金；fee_rate=按工具和日期延续的计提费率。
-- cc：T99_DERI_COMP_TYPE_FND_COST_REF.Fnd_Cost（成本参数），由03按类型＋期初日匹配。
-- 不额外判断起止日期；抵扣先置0，缺成本时非抵扣公式不补0，基础保证金率为1时不保护除零。
-- 本例：无关联168、有关联159；来源、日期差异和后续分配见10_AIRBAG与关联保证金收入贯通.md。

    -- A / 特殊类型优先：抵扣判断来自组合履保方案，不是收入分配比例。
    WHEN info.Src_Contr_Type in ('AIRBAGX','AIRBAGM','AIRBAGL')
        and Ddct_Ptrn = 'DEDUCTION'
        THEN 0  --抵扣则为0
    WHEN info.Src_Contr_Type in ('AIRBAGX','AIRBAGM','AIRBAGL')
        and coalesce(Ddct_Ptrn,'') != 'DEDUCTION'
        and coalesce(info.Marg_Agt_Id,'') = ''
        -- 无保证金关联合约：先用本金×(1−初始保证金比例)，再算费率与成本率之差。
        THEN det.Dyna_Nom_Prin * (1 - Init_Marg_Prop)
            * (det.fee_rate/1.06 - cc.capital_cost) / 365 * 0.3
    WHEN info.Src_Contr_Type in ('AIRBAGX','AIRBAGM','AIRBAGL')
        and coalesce(Ddct_Ptrn,'') != 'DEDUCTION'
        and coalesce(info.Marg_Agt_Id,'') != ''
        -- 有关联：基础保证金率参与内外两处；分母为0时原式没有保护，不约分改写。
        THEN det.Dyna_Nom_Prin * (1 - Base_Marg_Rate)
            * (det.fee_rate*(1 - Init_Marg_Prop)/(1 - Base_Marg_Rate)/1.06 - cc.capital_cost)
            /365 *0.3
    WHEN info.Src_Contr_Type = 'LONG_HOLD_SWAP'
        and coalesce(info.Marg_Agt_Id,'') != ''
        THEN 0

-- 02.2 / 原始收入CASE的第5支；只有未命中前面的特殊类型时，才判断金仕达。
-- 本片段只有WHEN/THEN，由02实际引用，不独立执行。
-- det来自PDATA_N.T98_OTC_DERI_COMP_SALE_ADTNL_DET（107491逐日明细）：
--   Inta=源accrued_interest取反；Trd_Cms=profit；Trd_Cms_Cost=fee_cost；Fnd_Cost=occupy_cost。
--   源表均为ODATA_N_TIT.D_KS_TRADE_COMFIRM_INFO（交易确认书信息表）。
--   利息/用资可延续，交易收入成本仅匹配当天；Fnd_Cost在这里作为乘成本率的基数。
-- cc.capital_cost来自T99_DERI_COMP_TYPE_FND_COST_REF.Fnd_Cost，是另一条OIS成本参数。
-- 本式无起止日IF，也不将缺成本补0；0.94、0.5的制度依据不由SQL本身证明。
-- 本例KS_A原始1,500、KS_B原始3,000；还要交给04按同日占比分摊系统费用。
-- 从源字段到日报的完整算例：11_金仕达收入与系统费用贯通.md。

    -- B / 金仕达：det.Fnd_Cost来自occupy_cost，作计费基数；cc是OIS成本率，不是同一个量。
    WHEN info.Contr_Type_Cd = 'TRS_KINGSTAR_SWAP'
        THEN (det.Inta * 0.94 + det.Trd_Cms - det.Trd_Cms_Cost
            - det.Fnd_Cost * cc.capital_cost/365) * 0.5

-- 02.3 / 普通期权：未命中特殊类型、金仕达后，再按价差/基准组合选这四支。
-- 本片段由02的同一个CASE引用，不独立执行；输出仍是原始收入，不是保底后金额。
-- info.Init_Nom_Prin来自PDATA_N.T98_OTC_DERI_COMP_SALE_INFO（合约销售基础）；
-- det.Dyna_Nom_Prin来自PDATA_N.T98_OTC_DERI_COMP_SALE_ADTNL_DET（107491逐日明细），不取展示列补0值。
-- s_sp/c_sp：合约价差/客户类型价差；s_ba/c_ba：合约基准/类型基准，均由03并列接入。
-- 年化项：动态本金×所选系数÷365，起止日都包含；绝对项：初始本金×系数，只在期初日计算。
-- 类型与系数分别COALESCE，不是整套回退；0不回退。所有分支未命中时，02没有ELSE，返回NULL。
-- 本页普通期权100元原始日收入，如何变成结束日3,450元：见README和04_收入调整.sql。

    -- C / 普通期权：价差年化、基准年化；贯穿算例命中此支，365万元×(.006+.004)÷365=100。
    WHEN info.Busi_Type = 'OPTION'
        and coalesce(s_sp.Spread_Calculation, c_sp.Spread_Calculation, 'ABSOLUTE') = 'ANNUALIZED'
        and coalesce(s_ba.BASE_CALCULATION, c_ba.BASE_CALCULATION) = 'ANNUALIZED'
        THEN IF(
            det.busi_date BETWEEN info.Strt_Pric_Date AND coalesce(info.Early_Term_Date, info.End_Pric_Date),
            det.Dyna_Nom_Prin * coalesce(s_sp.Annualized_Spread, c_sp.Annualized_Spread, 0) / 365
            + det.Dyna_Nom_Prin * coalesce(s_ba.BASE_AWARD_RATE, c_ba.BASE_AWARD_RATE, 0) / 365,
            0
        )
    -- 价差年化＋基准绝对：价差每天算，基准只在期初算一次。
    WHEN info.Busi_Type = 'OPTION'
        and coalesce(s_sp.Spread_Calculation, c_sp.Spread_Calculation, 'ABSOLUTE') = 'ANNUALIZED'
        and coalesce(s_ba.BASE_CALCULATION, c_ba.BASE_CALCULATION) = 'ABSOLUTE'
        THEN IF(
            det.busi_date BETWEEN info.Strt_Pric_Date AND coalesce(info.Early_Term_Date, info.End_Pric_Date),
            det.Dyna_Nom_Prin * coalesce(s_sp.Annualized_Spread, c_sp.Annualized_Spread, 0) / 365,
            0
        )
        + IF(
            det.busi_date = info.Strt_Pric_Date,
            info.Init_Nom_Prin * coalesce(s_ba.BASE_AWARD_RATE, c_ba.BASE_AWARD_RATE, 0),
            0
        )
    -- 价差绝对＋基准年化：价差只在期初算一次，基准每天算。
    WHEN info.Busi_Type = 'OPTION'
        and coalesce(s_sp.Spread_Calculation, c_sp.Spread_Calculation, 'ABSOLUTE') = 'ABSOLUTE'
        and coalesce(s_ba.BASE_CALCULATION, c_ba.BASE_CALCULATION) = 'ANNUALIZED'
        THEN IF(
            det.busi_date = info.Strt_Pric_Date,
            info.Init_Nom_Prin * coalesce(s_sp.Absolute_Spread, c_sp.Absolute_Spread, 0),
            0
        )
        + IF(
            det.busi_date BETWEEN info.Strt_Pric_Date AND coalesce(info.Early_Term_Date, info.End_Pric_Date),
            det.Dyna_Nom_Prin * coalesce(s_ba.BASE_AWARD_RATE, c_ba.BASE_AWARD_RATE, 0) / 365,
            0
        )
    -- 两项绝对：只在期初计算，其他日期均为0。
    WHEN info.Busi_Type = 'OPTION'
        and coalesce(s_sp.Spread_Calculation, c_sp.Spread_Calculation, 'ABSOLUTE') = 'ABSOLUTE'
        and coalesce(s_ba.BASE_CALCULATION, c_ba.BASE_CALCULATION) = 'ABSOLUTE'
        THEN IF(
            det.busi_date = info.Strt_Pric_Date,
            info.Init_Nom_Prin * coalesce(s_sp.Absolute_Spread, c_sp.Absolute_Spread, 0),
            0
        )
        + IF(
            det.busi_date = info.Strt_Pric_Date,
            info.Init_Nom_Prin * coalesce(s_ba.BASE_AWARD_RATE, c_ba.BASE_AWARD_RATE, 0),
            0
        )

-- 02.4 / 普通互换：未命中前面的特殊类型、金仕达和期权分支，才进入这四支。
-- 本片段由02的同一个CASE引用，不独立执行；普通公式没有统一扣资金成本。
-- info.Init_Nom_Prin来自PDATA_N.T98_OTC_DERI_COMP_SALE_INFO（合约销售基础）：初始持仓金额×汇率。
-- det.Dyna_Nom_Prin来自PDATA_N.T98_OTC_DERI_COMP_SALE_ADTNL_DET（107491逐日明细）：
--   期初日取初始本金；结束后归0；其余日期按历史日结构腿持仓金额×汇率，不沿用主信息当日持仓。
-- s_sp/c_sp：合约价差/客户类型价差；s_ba/c_ba：合约基准/类型基准，具体匹配见03。
-- 年化用动态本金且含起止日；绝对用初始本金且只算期初日；类型、系数分别NULL回退。
-- 减仓后本例收入100→80→50；调整、分配、累计及四种组合见09_普通互换收入贯通.md。

    -- D / 普通互换：同样保留年化/绝对四种组合；并不统一扣资金成本。
    WHEN info.Busi_Type = 'TRS'
        and coalesce(s_sp.Spread_Calculation, c_sp.Spread_Calculation, 'ABSOLUTE') = 'ANNUALIZED'
        and coalesce(s_ba.BASE_CALCULATION, c_ba.BASE_CALCULATION) = 'ANNUALIZED'
        THEN IF(
            det.busi_date BETWEEN info.Strt_Pric_Date AND coalesce(info.Early_Term_Date, info.End_Pric_Date),
            det.Dyna_Nom_Prin * coalesce(s_sp.Annualized_Spread, c_sp.Annualized_Spread, 0) / 365
            + det.Dyna_Nom_Prin * coalesce(s_ba.BASE_AWARD_RATE, c_ba.BASE_AWARD_RATE, 0) / 365,
            0
        )
    -- 价差年化＋基准绝对：每日价差，期初另加初始本金×绝对基准。
    WHEN info.Busi_Type = 'TRS'
        and coalesce(s_sp.Spread_Calculation, c_sp.Spread_Calculation, 'ABSOLUTE') = 'ANNUALIZED'
        and coalesce(s_ba.BASE_CALCULATION, c_ba.BASE_CALCULATION) = 'ABSOLUTE'
        THEN IF(
            det.busi_date BETWEEN info.Strt_Pric_Date AND coalesce(info.Early_Term_Date, info.End_Pric_Date),
            det.Dyna_Nom_Prin * coalesce(s_sp.Annualized_Spread, c_sp.Annualized_Spread, 0) / 365,
            0
        )
        + IF(
            det.busi_date = info.Strt_Pric_Date,
            info.Init_Nom_Prin * coalesce(s_ba.BASE_AWARD_RATE, c_ba.BASE_AWARD_RATE, 0),
            0
        )
    -- 价差绝对＋基准年化：期初价差，每日动态本金×年化基准。
    WHEN info.Busi_Type = 'TRS'
        and coalesce(s_sp.Spread_Calculation, c_sp.Spread_Calculation, 'ABSOLUTE') = 'ABSOLUTE'
        and coalesce(s_ba.BASE_CALCULATION, c_ba.BASE_CALCULATION) = 'ANNUALIZED'
        THEN IF(
            det.busi_date = info.Strt_Pric_Date,
            info.Init_Nom_Prin * coalesce(s_sp.Absolute_Spread, c_sp.Absolute_Spread, 0),
            0
        )
        + IF(
            det.busi_date BETWEEN info.Strt_Pric_Date AND coalesce(info.Early_Term_Date, info.End_Pric_Date),
            det.Dyna_Nom_Prin * coalesce(s_ba.BASE_AWARD_RATE, c_ba.BASE_AWARD_RATE, 0) / 365,
            0
        )
    -- 两项绝对：只在期初用初始本金计算，其他日期0。
    WHEN info.Busi_Type = 'TRS'
        and coalesce(s_sp.Spread_Calculation, c_sp.Spread_Calculation, 'ABSOLUTE') = 'ABSOLUTE'
        and coalesce(s_ba.BASE_CALCULATION, c_ba.BASE_CALCULATION) = 'ABSOLUTE'
        THEN IF(
            det.busi_date = info.Strt_Pric_Date,
            info.Init_Nom_Prin * coalesce(s_sp.Absolute_Spread, c_sp.Absolute_Spread, 0),
            0
        )
        + IF(
            det.busi_date = info.Strt_Pric_Date,
            info.Init_Nom_Prin * coalesce(s_ba.BASE_AWARD_RATE, c_ba.BASE_AWARD_RATE, 0),
            0
        )

END AS Curr_Prvs_Sales_Income,

    -- 此处End_Pric_Date已改成“提前终止日优先”；04的结束日保底使用这个结果。
    -- COALESCE只回退NULL，提前终止日为空串时不会使用原期末日。
    info.Strt_Pric_Date,
    coalesce(info.Early_Term_Date, info.End_Pric_Date) as End_Pric_Date,
    info.Strt_Pric_Date as Accrued_Strt_Date,
    coalesce(info.Early_Term_Date, info.End_Pric_Date) as Accrued_End_Date,
    info.Early_Term_Date,
    info.Earn_Pymt_Date,
    info.Agt_Stat_Cd,
    -- 归属资料来自105743的管理关系m：经办角色与三组介绍人分开保留。
    m.Main_Oper_User_Id,
    m.Main_Oper_Name,
    m.Main_Oper_Emp_Id,
    m.Intro_Oper_User_Id,
    m.Intro_Oper_Name,
    m.Intro_Oper_Emp_Id,
    m.Inr_Org_Id_1 as Intro_Inr_Org_Id_1,
    m.Inr_Org_Name_1 as Intro_Inr_Org_Name_1,
    m.Div_Org_Id_1,
    m.Div_Org_Name_1,
    m.Cust_Mngr_User_Id_1,
    m.Cust_Mngr_Name_1,
    m.Cust_Mngr_Emp_Id_1,
    m.Allo_Prop_1, -- 第1组介绍关系收入分配比例；06直接相乘
    m.Inr_Org_Id_2 as Intro_Inr_Org_Id_2,
    m.Inr_Org_Name_2 as Intro_Inr_Org_Name_2,
    m.Div_Org_Id_2,
    m.Div_Org_Name_2,
    m.Cust_Mngr_User_Id_2,
    m.Cust_Mngr_Name_2,
    m.Cust_Mngr_Emp_Id_2,
    m.Allo_Prop_2, -- 第2组介绍关系收入分配比例
    m.Inr_Org_Id_3 as Intro_Inr_Org_Id_3,
    m.Inr_Org_Name_3 as Intro_Inr_Org_Name_3,
    m.Div_Org_Id_3,
    m.Div_Org_Name_3,
    m.Cust_Mngr_User_Id_3,
    m.Cust_Mngr_Name_3,
    m.Cust_Mngr_Emp_Id_3,
    m.Allo_Prop_3, -- 第3组介绍关系收入分配比例
    -- 计提日=明细所属日；不是本次加工日，后续窗口按它排序。
    det.busi_date as Accrued_Date,
    coalesce(Additional_Reward,0) as Adtnl_Rwd, -- 03合约基准s_ba带出的额外奖励；单独展示，不加进收入公式
    det.fee_rate,
    1 - info.Init_Marg_Prop as Fin_Rati,
    info.Intr_Marg,
    info.Res_Flag,
    info.Opt_Fee_Rate,
    if(info.Ex_Rate_Model in ('SHENZHEN_HONGKONG_STOCK_CONNECT','SHANGHAI_HONGKONG_STOCK_CONNECT'),info.Ex_Rate_Model,null) as Ex_Rate_Model,
    if(nvl(m.Cust_Mngr_Emp_Stat_Desc_1, '') = '', m.Cust_Mngr_Emp_Stat_Desc_1, if(m.Cust_Mngr_Emp_Stat_Desc_1 = '在职', '是', '否')) as Cust_Mngr_Is_Actv_1,  -- 客户经理是否在职_1
    if(nvl(m.Cust_Mngr_Emp_Stat_Desc_2, '') = '', m.Cust_Mngr_Emp_Stat_Desc_2, if(m.Cust_Mngr_Emp_Stat_Desc_2 = '在职', '是', '否')) as Cust_Mngr_Is_Actv_2,  -- 客户经理是否在职_2
    if(nvl(m.Cust_Mngr_Emp_Stat_Desc_3, '') = '', m.Cust_Mngr_Emp_Stat_Desc_3, if(m.Cust_Mngr_Emp_Stat_Desc_3 = '在职', '是', '否')) as Cust_Mngr_Is_Actv_3   -- 客户经理是否在职_3
-- 主体范围：本次加工日的合约快照，先排除费用互换、FAST分组和香港部门。
from (
    select * from PDATA_N.T98_OTC_DERI_COMP_SALE_INFO -- 场外衍生品合约销售基础信息
    where busi_date = '${yyyy-MM-dd}' and Src_Contr_Type != 'FEE_SWAP'  --销售收入不计算“费用互换”
        and grp_id != '04' and Book_Bel_Dept != 'OTC_HK'  --极速合约暂不计算，香港合约单独计算
    ) info
-- 按合约接入逐日本金费用；INNER JOIN意味着没有明细的合约不进入结果。
-- 原SQL没有在这里限定det分区，也没按计提日去重，不擅加日期条件。
inner join PDATA_N.T98_OTC_DERI_COMP_SALE_ADTNL_DET det -- 场外衍生品合约销售收入附加明细
on info.agt_id = det.agt_id
/*
给01的合约日补五路参数，保持原LEFT JOIN顺序。
info=合约主信息；det=逐日金额。参数匹配后供02的同层收入CASE使用。

                       合约号 + det计提日 → s_sp 合约级价差
info/det（同一主体） ─── 客户+合约类型+期初定价日 → c_sp 客户类型级价差
                       合约号 → s_ba 合约级基准
                       合约类型+期初定价日 → c_ba 类型级基准
                       合约类型+期初定价日 → cc 资金成本率

五路是并列资料，不串行加工金额。短模块沿用已核对版本；
展开后仍在01原SELECT的FROM区，没有另造中间宽表或重新JOIN。
*/
-- 03 合约价差有效期（118141的LEFT JOIN片段，不是独立SQL）
-- 输入：01写出的合约价差T99，以及info合约主信息、det逐日本金费用。
-- 本文件：把每份合约的生效版本转成日期区间，再用“合约号＋计提日”匹配。
-- 得到：s_sp，某份合约在某个计提日适用的计算类型和两个价差系数。
-- 下一步：05将s_sp与04并行匹配的c_sp逐字段比较，选择用于收入的价差。
--
-- 贯穿例：T99.Inr_Comp_No=A1、Agt_Id=I1，0.006从2026-09-15生效；加工日09-22。
-- 若无更晚版本，本条展开09-15至09-22。A1的09-14匹配不到，09-15/16匹配到0.006。
-- info.Agt_Id=A1与原合约号Inr_Comp_No相连；T99.Agt_Id=I1非空只用于入选，不作连接键。

LEFT JOIN (
    SELECT
        Contract_Code, -- 原OIS合约号：本例A1
        Spread_Calculation, -- 价差计算类型：年化／绝对
        Annualized_Spread, -- 年化价差系数
        Absolute_Spread, -- 绝对价差系数
        date_add(strt_date, pos) AS busi_date -- 该版本适用的每个计提日
    FROM (
        SELECT
            Inr_Comp_No AS Contract_Code, -- 01中的A.CONTRACT_CODE，未转换的原合约号
            -- 仅计算类型空串转NULL；两个系数字段的空串仍原样保留。
            IF(Sprd_Calc_Type = '', null, Sprd_Calc_Type) AS Spread_Calculation,
            Annu_Sprd_Coef AS Annualized_Spread, -- 原A.ANNUALIZED_SPREAD
            Absl_Sprd_Coef AS Absolute_Spread, -- 原A.ABSOLUTE_SPREAD
            Vld_Date AS strt_date, -- 原A.EFFECTIVE_DATE，本版本生效日
            -- 本行生效日 → 下一条生效日前一天；最后一条 → 加工日。
            date_sub(
                lead(Vld_Date, 1, date_add('${yyyy-MM-dd}', 1)) OVER (
                    PARTITION BY Inr_Comp_No
                    ORDER BY Vld_Date
                ),
                1
            ) AS end_Date
        FROM PDATA_N.T99_DERI_COMP_SPRD_COEF_REF -- 衍生品合约价差系数参考信息
        WHERE src_tbl = 'ODATA_N_OIS.O_CONTRACT_SPREAD_RATE'
          AND Del_Flag = '0'
          AND coalesce(Coef_Type, '') != 'INR'
          AND Agt_Id != ''
    ) x
    -- 日期位置0..两日之差：正常非负区间包含首尾，每个位置形成一条参数日记录。
    LATERAL VIEW posexplode(split(space(datediff(end_date, strt_date)), ' ')) y AS pos, val
) s_sp
    ON s_sp.CONTRACT_CODE = info.Agt_Id
   AND s_sp.busi_date = det.busi_date

-- 连接含义：LEFT JOIN保留没有合约参数的合约日，05可继续使用客户侧字段。
-- 版本仅按原合约号分组、按Vld_Date排序，没有再按类型/系数大类分组，也无同日版本决胜键。
-- “非INR”包含Coef_Type的NULL/空串，不能改成仅CROSS；异常倒置区间的Hive行为未在本专题验证。

-- 04 客户类型价差适用期（118141的LEFT JOIN片段，不是独立SQL）
-- 输入：02写出的客户类型价差T99，以及info合约主信息中的客户号、类型和期初定价日。
-- 本文件：展开“哪些期初定价日适用”的参数区间，按客户＋类型＋合约期初日匹配。
-- 得到：c_sp，适用于这份合约的客户侧计算类型和两个价差系数；不按逐日计提日换档。
-- 下一步：05与03的合约侧字段一起选择；03与本文件是两路并行输入，不是前后覆盖。
--
-- 贯穿例：客户C1/OPTION_STOCK的0.002适用于2026-09-01至09-30期初的合约。
-- A1期初日09-10在区间内；无论正在算09-14、15还是16，客户侧都能匹配到0.002。
-- 但05是否采用它，还取决于相应日期有没有合约侧价差。

LEFT JOIN (
    SELECT
        CLIENT_ID, -- 客户编号：本例C1
        CONTRACT_TYPE, -- 合约类型代码：本例OPTION_STOCK
        CONTRACT_TYPE_NAME, -- 合约类型名称
        Spread_Calculation, -- 价差计算类型
        Annualized_Spread, -- 年化价差系数：本例0.002
        Absolute_Spread, -- 绝对价差系数
        date_add(strt_date, pos) AS busi_date -- 此处是可适用的合约期初日，不是det计提日
    FROM (
        SELECT
            Pty_Id AS CLIENT_ID, -- 原OIS CLIENT_ID
            Src_Comp_Type_Cd AS CONTRACT_TYPE, -- 原OIS CONTRACT_TYPE
            Src_Comp_Type_Desc AS CONTRACT_TYPE_NAME,
            IF(Calc_Type = '', null, Calc_Type) AS Spread_Calculation, -- 仅类型空串转NULL
            Annu_Sprd_Coef AS Annualized_Spread,
            Absl_Sprd_Coef AS Absolute_Spread,
            -- 两个上下限来自OIS CONTRACT_START_DATE_MIN/MAX；极值日期按原规则替换。
            IF(Bgng_Prcg_Date_Llmt = '1900-01-01', '2019-01-01', Bgng_Prcg_Date_Llmt) AS strt_date,
            IF(Bgng_Prcg_Date_Ulmt = '2999-12-31', '${yyyy-MM-dd}', Bgng_Prcg_Date_Ulmt) AS end_Date
        FROM PDATA_N.T99_DERI_CUTP_COMP_TYPE_SPRD_COEF_REF -- 衍生品对手方合约类型价差系数参考信息
        WHERE src_tbl = 'ODATA_N_OIS.O_CTPTY_CROSS_SELL_COEFFICIENT'
          AND Del_Flag = '0'
    ) x
    -- 正常非负区间逐日展开，首尾都包括；参数区间重叠时可匹配多条，不在这里择一。
    LATERAL VIEW posexplode(split(space(datediff(end_date, strt_date)), ' ')) y AS pos, val
) c_sp
    ON c_sp.CLIENT_ID = info.Cutp_Pty_Id
   AND c_sp.CONTRACT_TYPE = info.Contr_Type_Cd
   AND c_sp.busi_date = info.Strt_Pric_Date

-- 客户号直接取合约主信息info.Cutp_Pty_Id，不沿用105743管理归属中的特殊客户换号。
-- 本段未读取Vld_Date，也未按其选最新；未附加标的类型/当事人类别/业务类型等匹配条件。
-- 没有参数时合约仍由LEFT JOIN保留；展示与金额怎样处理缺失，继续看05。

-- 03 / 这份销售合约能匹配到哪条单笔基准？
-- 位置：118141的03_参数匹配引用本JOIN，展开在01_合约日与资料的FROM中。
-- 输入：info合约主信息；133055写入的合约T99。输出别名s_ba，供同层展示及收入CASE使用。
-- 本例：T99身份TIT_DEMO非空 → 保留；原号OPT_DEMO = info.Agt_Id → 匹配年化0.004。
-- 本段是主查询的一部分，不能独立执行。LEFT JOIN缺失时保留原合约日。

-- ① 从合约T99取可用配置；编号转换与参数改名保持原值。
LEFT JOIN (
    SELECT
        Inr_Comp_No AS Contract_Code, -- 原OIS合约号，不是本表转换后的Agt_Id
        Calc_Type AS BASE_CALCULATION, -- 年化／绝对
        Base_Yield AS BASE_AWARD_RATE, -- 基础收益率
        IF(Adtnl_Rwd = '', 0, Adtnl_Rwd) AS additional_reward, -- 空串改0，NULL仍为NULL
        Adtnl_Rwd_Flag AS have_additional_reward -- 取出标志，但后续收入CASE未使用
    FROM PDATA_N.T99_DERI_COMP_BASE_COEF_REF -- 衍生品合约基础系数参考信息
    -- 来源限133055交叉销售分区，不读133054的INR分区。
    -- 本例Del_Flag=0、Agt_Id=TIT_DEMO通过筛选；无日期/更新时间择一条件。
    WHERE src_tbl = 'ODATA_N_OIS.O_CONTRACT_BASE_RATE'
      AND Del_Flag = '0'
      AND Agt_Id != ''
) s_ba
    -- ② 配回销售合约：用原合约号OPT_DEMO，不是转换后的TIT_DEMO。
    -- 同号多条配置会扩行，参数选择COALESCE不会消除这些重复。
    ON s_ba.CONTRACT_CODE = info.Agt_Id

-- 04 / 按合约类型维护的基准，能否用于这份合约？
-- 位置：与03并列，由118141的03_参数匹配引用，展开在01_合约日与资料的FROM中。
-- 输入：info合约主信息；133056写入的类型T99。输出c_ba，供同层展示及收入CASE使用。
-- 阅读顺序：①类型配置x → ②展开可适用的期初日 → ③用类型+合约期初日匹配。
--
-- README变例：OPTION_STOCK / 绝对0.003 / 9月16—30日 → 15条日期记录。
-- OPT_DEMO是OPTION_STOCK、期初9月18日，匹配其中9月18日这条。
-- 算9月19日收入时仍用期初9月18日匹配，本JOIN没有使用det计提日，也没有客户键。
-- 本段依赖主查询，不能独立执行；LEFT JOIN缺失时保留合约日。
LEFT JOIN (
    -- ② 将一条配置的日期区间展开；pos=0..14时，本例得到9月16..30日。
    SELECT
        CONTRACT_TYPE, -- 合约类型代码
        CONTRACT_TYPE_NAME, -- 合约类型名称
        BASE_CALCULATION, -- 年化／绝对
        BASE_AWARD_RATE, -- 基准系数
        date_add(strt_date, pos) AS busi_date -- 区间中的每个可适用日期
    FROM (
        -- ① 准备类型配置x：范围与系数来自02，先过滤来源、删除标志和部门。
        -- 只处理日期哨兵，不按Vld_Date生效日选版本，不使用业务/标的类型列匹配。
        SELECT
            Src_Comp_Type_Cd AS CONTRACT_TYPE,
            Src_Comp_Type_Desc AS CONTRACT_TYPE_NAME,
            Calc_Type AS BASE_CALCULATION,
            Base_Yield AS BASE_AWARD_RATE,
            -- 哨兵下限1900改为2019，上限2999改为运行日；展开范围仍是有限区间。
            IF(Bgng_Prcg_Date_Llmt = '1900-01-01', '2019-01-01', Bgng_Prcg_Date_Llmt) AS strt_date,
            IF(Bgng_Prcg_Date_Ulmt = '2999-12-31', '${yyyy-MM-dd}', Bgng_Prcg_Date_Ulmt) AS end_Date
        FROM PDATA_N.T99_DERI_COMP_TYPE_BASE_COEF_REF -- 衍生品合约类型基础系数参考信息
        WHERE src_tbl = 'ODATA_N_OIS.O_BUS_TYPE_BASE_RATE'
          AND Del_Flag = '0'
          AND Src_Dept_No = 'OTC'
    ) x
    -- ② 日期展开的实际位置：两日之差N → 空格拆分 → pos=0..N → date_add取日期。
    -- 正常非负区间含首尾；空值、逆向区间的Hive行为未由本地示例验证。
    LATERAL VIEW posexplode(split(space(datediff(end_date, strt_date)), ' ')) y AS pos, val
) c_ba
    -- ③ 用经营类别+期初日配回合约。c_ba.busi_date是可适用期初日，不是计提日。
    -- 重叠区间可能同时命中，原SQL不择一；合约基准有值也不能阻止本JOIN扩行。
    ON c_ba.CONTRACT_TYPE = info.Contr_Type_Cd
   AND c_ba.busi_date = info.Strt_Pric_Date

/*
02 / 合约用哪条成本参数？按“合约类型 + 期初定价日”选，不按每个计提日切换。

T99参数（src_tbl指定OIS来源、未删除、源部门OTC）
  → 起息起止日形成逐日适用区间（正常区间包含两端）
  → 合约类型 = info.Contr_Type_Cd
  → 区间内日期 = info.Strt_Pric_Date（合约期初定价日）
  → cc.capital_cost（资金成本率参数）

别名：info=合约主信息T98；det=逐日本金费用T98；cc=本段成本参数。
这里的cc.busi_date是区间展开日期，不是源配置快照日期。
不按T99.Busi_Type、标的类型或Vld_Date匹配；不做LEAD版本选择，不取最新一条。
没有默认0：LEFT JOIN未匹配时cc.capital_cost为NULL。
本段是118141的JOIN片段，需要放回原主查询；不是独立可执行SQL。
*/

left join (
    select
        CONTRACT_TYPE, -- 源合约类型
        CAPITAL_COST, -- T99.Fnd_Cost原值
        date_add(strt_date, pos) as busi_date -- 区间内逐日日期
    from (
        select
            Src_Comp_Type_Cd as CONTRACT_TYPE,
            Fnd_Cost as CAPITAL_COST,
            if(Intr_Strt_Date = '1900-01-01','2019-01-01',Intr_Strt_Date) as strt_date,
            if(Intr_End_Date = '2999-12-31','${yyyy-MM-dd}',Intr_End_Date) as end_Date
        from PDATA_N.T99_DERI_COMP_TYPE_FND_COST_REF -- 衍生品合约类型资金成本参考信息
        where src_tbl = 'ODATA_N_OIS.G_BUS_TYPE_CAPITAL_COST'
            and Del_Flag = '0'
            and Src_Dept_No = 'OTC'
    ) x
    -- 将正常起止区间展开：pos从0开始，每一行对应一天；不是求平均。
    lateral view posexplode(split(space(datediff(end_date, strt_date)), ' ')) y as pos, val
) cc
on cc.CONTRACT_TYPE = info.Contr_Type_Cd
    and cc.busi_date = info.Strt_Pric_Date


-- 归属按当前加工日取快照，按合约号连接；多条归属仍可扩行。
left join (
    select * from PDATA_N.T98_OTC_COMP_MNG_RELA_INFO -- 场外合约管理关系
    where busi_Date = '${yyyy-MM-dd}'
    ) m
on m.Agt_Id = info.Agt_Id
-- 最终机构范围：至少一组不为空且不是8846，或合约属于原白名单。
-- WHERE写在LEFT JOIN之后，因此缺归属且不在白名单的合约日会被排除。
where coalesce(if(m.Inr_Org_Id_1 = '', '8846', m.Inr_Org_Id_1), '8846') != '8846'
    or coalesce(if(m.Inr_Org_Id_2 = '', '8846', m.Inr_Org_Id_2), '8846') != '8846'
    or coalesce(if(m.Inr_Org_Id_3 = '', '8846', m.Inr_Org_Id_3), '8846') != '8846'
    or info.agt_id in ('OPT-OTC20220163','OPT-OTC20220128','OPT-OTC20220148','OPT-OTC20220162','OPT-OTC20220153','OPT-OTC20220089-1','OPT-OTC20220155','OPT-OTC20220126','OPT-OTC20220147','OPT-OTC20220129')

),
adjusted_day_income AS (
    -- 第二阶段：保留每条原始合约日，再补调整后收入；不重新拼接本金/参数。
    SELECT T.*,
/*
输入：主脚本T=第一阶段contract_day_income，actl=05按合约汇总的历史部门所得收入。
输出：Curr_Prvs_Sales_Income_n（调整后的当日收入），进入06分配和累计。

金仕达：按“该类型全部合约同一天的原始收入总和”分摊，不是本合约累计。
  分母为0/NULL时原式没有保护，不能把结果想成固定每合约扣同一笔。
期权保底：判断累计原始收入是否小于初始本金×0.001；仅结束日替换当天金额。
  结束日T.End_Pric_Date已在01优先取提前终止日，NULL才回退原期末日。
  公式减历史部门所得收入，再减核算截止日之后全分区的原收入，最后加回当天原收入；
  没有GREATEST保底下限，不能保证调整当天一定非负。
*/

case
--金仕达分摊150万的系统费用
when Contr_Type_Cd = 'TRS_KINGSTAR_SWAP'
    THEN Curr_Prvs_Sales_Income
        - Curr_Prvs_Sales_Income/sum(Curr_Prvs_Sales_Income) over(partition by Contr_Type_Cd, Accrued_Date)
            * 1500000 / 365 * 0.5
-- 个股期权、指数/ETF期权考虑保底，保底系数0.1%
-- 判断条件实际比较“累计原始收入”，不是原注释所说的“累计实发+当季应发”。
when Contr_Type_Cd in('OPTION_STOCK', 'OPTION_IDX_ETF')
    and End_Pric_Date = Accrued_Date
    and coalesce(sum(Curr_Prvs_Sales_Income) over(partition by Agt_Id order by Accrued_Date),0) < Init_Nom_Prin * 0.001

    THEN Init_Nom_Prin * 0.001
        - coalesce(actl.Dev_Dept_Rwd, 0)
        - sum(if(Accrued_Date > coalesce(actl.Qtr_End_Date,'2025-03-31'), Curr_Prvs_Sales_Income,0)) over(partition by Agt_Id)
        + Curr_Prvs_Sales_Income
else Curr_Prvs_Sales_Income
end as Curr_Prvs_Sales_Income_n

    FROM contract_day_income T
/*
用途：为04提供actl.Dev_Dept_Rwd（历史部门所得收入合计）及actl.Qtr_End_Date（最大核算结束日）。
来源：T98_OTC_DERI_UNDRL_INCOME_RWD_SUM，场外衍生品收入奖励汇总。
按Contr_Id汇总，不按人员机构输出。WHERE按本次加工日、OIS来源及结算期筛选。
只连接核算截止日早于当前合约结束日的结果；无匹配时04将金额补0、核算截止日回退2025-03-31。
这是原SQL的历史奖励输入，不在此生成上游奖励记录；08解释其生产。
*/

left join(
    -- 原注释称“累计实发收入”；实际SUM部门所得收入，未核实资金支付。
    select
        Contr_Id,
        sum(Dev_Dept_Rwd) as Dev_Dept_Rwd,
        max(Sett_End_Date) as Qtr_End_Date
    from PDATA_N.T98_OTC_DERI_UNDRL_INCOME_RWD_SUM
    where busi_date = '${yyyy-MM-dd}' and src_tbl = 'ODATA_N_OIS.G_CROSS_INCOME_REWARD'
        -- 本例2026年第三季度加工，上限202603；本季核算码不纳入，202502为固定下限。
        and Sett_Time >= '202502' and Sett_Time < concat('${yyyy}0', quarter('${yyyy-MM-dd}'))
    group by Contr_Id
    ) actl
on t.Agt_Id = actl.Contr_Id and actl.Qtr_End_Date < t.End_Pric_Date

),
allocated_day_income AS (
    -- 第三阶段：06的FROM明确接adjusted_day_income；累计在调整之后计算。
-- 输入：主脚本第二阶段adjusted_day_income，仍保留原别名X。
-- 输出：本金归属、三组当日收入、累计收入及日期，交给07做最终字段输出。
-- gfgreatest是default自定义函数，知识库记载“返回传入参数最大值”；不是在这里重定义UDF。

select
    Agt_Id,
    Busi_Type,
    Cutp_Pty_Id,
    Cutp_Pty_Shor_Name,
    Cutp_Pty_Full_Name,
    Sign_Prd_Name,
    Contr_Type_Cd,
    Contr_Type_Desc,
    Src_Contr_Type,
    Src_Contr_Type_Desc,
    Src_Sub_Contr_Type,
    Src_Sub_Contr_Type_Desc,
    Undrl_Ins_Id,
    Undrl_Wd_Cd,
    Undrl_Name,
    Undrl_Type,
    Src_Undrl_Type,
    Annu_Sprd,
    Absl_Sprd,
    Annu_Base,
    Absl_Base,
    -- 本金40/60：引入经办人存在才拆；不是三组介绍人的收入比例。
    Init_Nom_Prin,
    IF(Intro_Oper_User_Id IS NULL or Intro_Oper_User_Id = '', Init_Nom_Prin * 1, Init_Nom_Prin * 0.4) AS Init_Nom_Prin_Main,  -- 只看引入经办ID是否NULL/空串；不要求主经办ID非空
    IF(Intro_Oper_User_Id IS NULL or Intro_Oper_User_Id = '', Init_Nom_Prin * 0, Init_Nom_Prin * 0.6) AS Init_Nom_Prin_Intro,
    Dyna_Nom_Prin,
    IF(Intro_Oper_User_Id IS NULL or Intro_Oper_User_Id = '', Dyna_Nom_Prin * 1, Dyna_Nom_Prin * 0.4) AS Dyna_Nom_Prin_Main,
    IF(Intro_Oper_User_Id IS NULL or Intro_Oper_User_Id = '', Dyna_Nom_Prin * 0, Dyna_Nom_Prin * 0.6) AS Dyna_Nom_Prin_Intro,
    Accum_Dyna_Nom_Prin,
    Absl_Nom_Prin,
    IF(Intro_Oper_User_Id IS NULL or Intro_Oper_User_Id = '', Absl_Nom_Prin * 1, Absl_Nom_Prin * 0.4) AS Absl_Nom_Prin_Main,
    IF(Intro_Oper_User_Id IS NULL or Intro_Oper_User_Id = '', Absl_Nom_Prin * 0, Absl_Nom_Prin * 0.6) AS Absl_Nom_Prin_Intro,
    Accum_Absl_Nom_Prin,
    -- 收入使用04调整后金额，再分别乘105743传来的三组Allo_Prop。
    -- 无比例时单组当日收入为NULL；不自动补0或归一化。
    Curr_Prvs_Sales_Income_n as Curr_Prvs_Sales_Income,
    Curr_Prvs_Sales_Income_n * Allo_Prop_1 AS Curr_Prvs_Sales_Income_1,
    Curr_Prvs_Sales_Income_n * Allo_Prop_2 AS Curr_Prvs_Sales_Income_2,
    Curr_Prvs_Sales_Income_n * Allo_Prop_3 AS Curr_Prvs_Sales_Income_3,
    -- 日期沿用01改写后的结束日；提前终止标志只检查Early_Term_Date有无值。
    Strt_Pric_Date,
    End_Pric_Date,
    Strt_Pric_Date as Accrued_Strt_Date,
    Accrued_End_Date,
    Earn_Pymt_Date,
    datediff(if(Accrued_Date > End_Pric_Date, End_Pric_Date, Accrued_Date), Strt_Pric_Date) + 1 AS Actl_Days,  -- 截止日不晚于合约结束日，天数+1含首尾；未给负天数设下限
    IF(Early_Term_Date IS NULL OR Early_Term_Date = '', '0', '1') AS Is_Preterm_Flag,
    Early_Term_Date,
    Agt_Stat_Cd,
    Main_Oper_User_Id,
    Main_Oper_Name,
    Main_Oper_Emp_Id,
    Intro_Oper_User_Id,
    Intro_Oper_Name,
    Intro_Oper_Emp_Id,
    Intro_Inr_Org_Id_1,
    Intro_Inr_Org_Name_1,
    Div_Org_Id_1,
    Div_Org_Name_1,
    Cust_Mngr_User_Id_1,
    Cust_Mngr_Name_1,
    Cust_Mngr_Emp_Id_1,
    Allo_Prop_1,
    Intro_Inr_Org_Id_2,
    Intro_Inr_Org_Name_2,
    Div_Org_Id_2,
    Div_Org_Name_2,
    Cust_Mngr_User_Id_2,
    Cust_Mngr_Name_2,
    Cust_Mngr_Emp_Id_2,
    Allo_Prop_2,
    Intro_Inr_Org_Id_3,
    Intro_Inr_Org_Name_3,
    Div_Org_Id_3,
    Div_Org_Name_3,
    Cust_Mngr_User_Id_3,
    Cust_Mngr_Name_3,
    Cust_Mngr_Emp_Id_3,
    Allo_Prop_3,
    Accrued_Date,
    from_unixtime(unix_timestamp(),'yyyy-MM-dd HH:mm:ss') AS Data_Time,
    -- 先把调整后当日收入SUM累计，再与0取大；不是先把每天负收入截为0。
    -- 窗口按合约+合约类型，按计提日排序；同日多行未在此去重，也未指定ROWS。
    default.gfgreatest(
        sum(coalesce(Curr_Prvs_Sales_Income_n, 0)) OVER (
            PARTITION BY agt_id, Contr_Type_Cd ORDER BY accrued_date
        ), 0
    ) AS Accum_prvs_sales_income,
    default.gfgreatest(
        sum(coalesce(Curr_Prvs_Sales_Income_n * Allo_Prop_1, 0)) OVER (
            PARTITION BY agt_id, Contr_Type_Cd ORDER BY accrued_date
        ), 0
    ) AS Accum_prvs_sales_income_1,
    default.gfgreatest(
        sum(coalesce(Curr_Prvs_Sales_Income_n * Allo_Prop_2, 0)) OVER (
            PARTITION BY agt_id, Contr_Type_Cd ORDER BY accrued_date
        ), 0
    ) AS Accum_prvs_sales_income_2,
    default.gfgreatest(
        sum(coalesce(Curr_Prvs_Sales_Income_n * Allo_Prop_3, 0)) OVER (
            PARTITION BY agt_id, Contr_Type_Cd ORDER BY accrued_date
        ), 0
    ) AS Accum_prvs_sales_income_3,
    Adtnl_Rwd,
    if(Src_Contr_Type in ('AIRBAGX','AIRBAGM','AIRBAGL'), fee_rate, null) as fee_rate,
    if(Src_Contr_Type in ('AIRBAGX','AIRBAGM','AIRBAGL'), Fin_Rati, null) as Fin_Rati,
    Intr_Marg,
    Res_Flag,
    Opt_Fee_Rate,
    Ex_Rate_Model,
    Cust_Mngr_Is_Actv_1,  -- 客户经理是否在职_1
    Cust_Mngr_Is_Actv_2,  -- 客户经理是否在职_2
    Cust_Mngr_Is_Actv_3,  -- 客户经理是否在职_3
    '${yyyy-MM-dd}' as busi_date
FROM adjusted_day_income X

)
-- 最外层仅按原字段顺序输出、转换类型，不再计算另一套收入。
-- 输入：06的allocated_day_income（原别名castTable）；输出日报字段。
-- 原文多数字段CAST为String，末尾部分字段保持原类型；完整保留顺序与转换。
-- busi_date=本次加工日；Accrued_Date=该条收入归属日；Data_Time=运行时刻。

SELECT
    CAST( Agt_Id AS String ) Agt_Id,
    CAST( Busi_Type AS String ) Busi_Type,
    CAST( Cutp_Pty_Id AS String ) Cutp_Pty_Id,
    CAST( Cutp_Pty_Shor_Name AS String ) Cutp_Pty_Shor_Name,
    CAST( Cutp_Pty_Full_Name AS String ) Cutp_Pty_Full_Name,
    CAST( Sign_Prd_Name AS String ) Sign_Prd_Name,
    CAST( Contr_Type_Cd AS String ) Contr_Type_Cd,
    CAST( Contr_Type_Desc AS String ) Contr_Type_Desc,
    CAST( Src_Contr_Type AS String ) Src_Contr_Type,
    CAST( Src_Contr_Type_Desc AS String ) Src_Contr_Type_Desc,
    CAST( Src_Sub_Contr_Type AS String ) Src_Sub_Contr_Type,
    CAST( Src_Sub_Contr_Type_Desc AS String ) Src_Sub_Contr_Type_Desc,
    CAST( Undrl_Ins_Id AS String ) Undrl_Ins_Id,
    CAST( Undrl_Wd_Cd AS String ) Undrl_Wd_Cd,
    CAST( Undrl_Name AS String ) Undrl_Name,
    CAST( Undrl_Type AS String ) Undrl_Type,
    CAST( Src_Undrl_Type AS String ) Src_Undrl_Type,
    CAST( Annu_Sprd AS String ) Annu_Sprd,
    CAST( Absl_Sprd AS String ) Absl_Sprd,
    CAST( Annu_Base AS String ) Annu_Base,
    CAST( Absl_Base AS String ) Absl_Base,
    CAST( Init_Nom_Prin AS String ) Init_Nom_Prin,
    CAST( Init_Nom_Prin_Main AS String ) Init_Nom_Prin_Main,
    CAST( Init_Nom_Prin_Intro AS String ) Init_Nom_Prin_Intro,
    CAST( Dyna_Nom_Prin AS String ) Dyna_Nom_Prin,
    CAST( Dyna_Nom_Prin_Main AS String ) Dyna_Nom_Prin_Main,
    CAST( Dyna_Nom_Prin_Intro AS String ) Dyna_Nom_Prin_Intro,
    CAST( Accum_Dyna_Nom_Prin AS String ) Accum_Dyna_Nom_Prin,
    CAST( Absl_Nom_Prin AS String ) Absl_Nom_Prin,
    CAST( Absl_Nom_Prin_Main AS String ) Absl_Nom_Prin_Main,
    CAST( Absl_Nom_Prin_Intro AS String ) Absl_Nom_Prin_Intro,
    CAST( Accum_Absl_Nom_Prin AS String ) Accum_Absl_Nom_Prin,
    CAST( Curr_Prvs_Sales_Income AS String ) Curr_Prvs_Sales_Income,
    CAST( Curr_Prvs_Sales_Income_1 AS String ) Curr_Prvs_Sales_Income_1,
    CAST( Curr_Prvs_Sales_Income_2 AS String ) Curr_Prvs_Sales_Income_2,
    CAST( Curr_Prvs_Sales_Income_3 AS String ) Curr_Prvs_Sales_Income_3,
    CAST( Strt_Pric_Date AS String ) Strt_Pric_Date,
    CAST( End_Pric_Date AS String ) End_Pric_Date,
    CAST( Accrued_Strt_Date AS String ) Accrued_Strt_Date,
    CAST( Accrued_End_Date AS String ) Accrued_End_Date,
    CAST( Earn_Pymt_Date AS String ) Earn_Pymt_Date,
    CAST( Actl_Days AS String ) Actl_Days,
    CAST( Is_Preterm_Flag AS String ) Is_Preterm_Flag,
    CAST( Early_Term_Date AS String ) Early_Term_Date,
    CAST( Agt_Stat_Cd AS String ) Agt_Stat_Cd,
    CAST( Main_Oper_User_Id AS String ) Main_Oper_User_Id,
    CAST( Main_Oper_Name AS String ) Main_Oper_Name,
    CAST( Main_Oper_Emp_Id AS String ) Main_Oper_Emp_Id,
    CAST( Intro_Oper_User_Id AS String ) Intro_Oper_User_Id,
    CAST( Intro_Oper_Name AS String ) Intro_Oper_Name,
    CAST( Intro_Oper_Emp_Id AS String ) Intro_Oper_Emp_Id,
    CAST( Intro_Inr_Org_Id_1 AS String ) Intro_Inr_Org_Id_1,
    CAST( Intro_Inr_Org_Name_1 AS String ) Intro_Inr_Org_Name_1,
    CAST( Div_Org_Id_1 AS String ) Div_Org_Id_1,
    CAST( Div_Org_Name_1 AS String ) Div_Org_Name_1,
    CAST( Cust_Mngr_User_Id_1 AS String ) Cust_Mngr_User_Id_1,
    CAST( Cust_Mngr_Name_1 AS String ) Cust_Mngr_Name_1,
    CAST( Cust_Mngr_Emp_Id_1 AS String ) Cust_Mngr_Emp_Id_1,
    CAST( Allo_Prop_1 AS String ) Allo_Prop_1,
    CAST( Intro_Inr_Org_Id_2 AS String ) Intro_Inr_Org_Id_2,
    CAST( Intro_Inr_Org_Name_2 AS String ) Intro_Inr_Org_Name_2,
    CAST( Div_Org_Id_2 AS String ) Div_Org_Id_2,
    CAST( Div_Org_Name_2 AS String ) Div_Org_Name_2,
    CAST( Cust_Mngr_User_Id_2 AS String ) Cust_Mngr_User_Id_2,
    CAST( Cust_Mngr_Name_2 AS String ) Cust_Mngr_Name_2,
    CAST( Cust_Mngr_Emp_Id_2 AS String ) Cust_Mngr_Emp_Id_2,
    CAST( Allo_Prop_2 AS String ) Allo_Prop_2,
    CAST( Intro_Inr_Org_Id_3 AS String ) Intro_Inr_Org_Id_3,
    CAST( Intro_Inr_Org_Name_3 AS String ) Intro_Inr_Org_Name_3,
    CAST( Div_Org_Id_3 AS String ) Div_Org_Id_3,
    CAST( Div_Org_Name_3 AS String ) Div_Org_Name_3,
    CAST( Cust_Mngr_User_Id_3 AS String ) Cust_Mngr_User_Id_3,
    CAST( Cust_Mngr_Name_3 AS String ) Cust_Mngr_Name_3,
    CAST( Cust_Mngr_Emp_Id_3 AS String ) Cust_Mngr_Emp_Id_3,
    CAST( Allo_Prop_3 AS String ) Allo_Prop_3,
    CAST( Accrued_Date AS String ) Accrued_Date,
    CAST( Data_Time AS String ) Data_Time,
    CAST( Accum_prvs_sales_income AS String ) Accum_prvs_sales_income,
    CAST( Accum_prvs_sales_income_1 AS String ) Accum_prvs_sales_income_1,
    CAST( Accum_prvs_sales_income_2 AS String ) Accum_prvs_sales_income_2,
    CAST( Accum_prvs_sales_income_3 AS String ) Accum_prvs_sales_income_3,
    CAST( Adtnl_Rwd AS String ) Adtnl_Rwd,
    CAST( fee_rate AS String ) fee_rate,
    CAST( Fin_Rati AS String ) Fin_Rati,
    Intr_Marg,
    Res_Flag,
    Opt_Fee_Rate,
    Ex_Rate_Model,
    Cust_Mngr_Is_Actv_1,
    Cust_Mngr_Is_Actv_2,
    Cust_Mngr_Is_Actv_3,
    CAST( busi_date AS String ) busi_date
FROM allocated_day_income castTable

