-- task_id: 105135
-- hiveDb: temp
-- source: SQL_MCP
-- sqlStatus: AVAILABLE
-- scriptPath: BigData-dm_scrm_n/ecrm/cust_analysis_report/dm_scrm_n.wt_list_corp_equi_fin.py
-- observed_at: 2026-09-04T02:08:28.073Z

-- createSql
create table wt_list_corp_equi_fin_temp as select a.secu_id , a.corp_id , a.list_date , a.fin_type , a.iss_num , a.iss_price , a.fin_net , b.main_uw_name , c.ivst_proj , c.iss_plan_funds_ivst , c.funds_has_ivst from (
  select corp_id,
  secu_id,
  list_date,
  '新股发行' fin_type,
  new_stk_iss_cnt iss_num,
  iss_price,
  round(if(coll_fnd != '', coll_fnd, 0) - if(iss_fare != '', iss_fare, 0), 2) fin_net from pdata_news_n.t02_stk_iss where src_id = 'wd' and grp_id in('01','02')
)
a left join ( select secu_id , concat_ws(',', collect_set(all_main_uw_names)) main_uw_name from pdata_news_n.t02_scr_main_uw_info where src_id = 'wd' and grp_id = '01' and iss_type = '首发' group by secu_id ) b on b.secu_id = a.secu_id left join ( select corp_id , ivst_proj , iss_plan_funds_ivst , funds_has_ivst , ann_date from pdata_news_n.t02_co_cptl_usag where src_id = 'wd' and fin_evt_type = 'ipo' ) c on c.corp_id = a.corp_id ;

-- querySql
insert into table wt_list_corp_equi_fin_temp select a.secu_id      , c.corp_id      , a.list_date      , a.fin_type      , a.iss_num      , a.iss_price      , a.fin_net      , b.main_uw_name      , d.ivst_proj      , d.iss_plan_funds_ivst      , d.funds_has_ivst from (          select secu_id               , list_date                                                                 , list_ann_date                                   usag_ann_dt               , '配股'                                            fin_type                  , allot_amt_act                                   iss_num                   , allot__pric                                     iss_price                 , round((allot_coll_fnd - allot_fare) / 10000, 2) fin_net                   , allot_reg_date                                                       from pdata_news_n.t02_stk_allot_info          where src_id = 'wd'            and grp_id = '01'            and allot_prog = '实施'      ) a          inner join      (          select corp_id               , secu_id          from pdata_news_n.t02_scr_base_info          where src_id = 'wd'      ) c on c.secu_id = a.secu_id          left join      (          select secu_id               , concat_ws(',', collect_set(all_main_uw_names)) main_uw_name               , iss_date               from pdata_news_n.t02_scr_main_uw_info          where src_id = 'wd'            and grp_id = '01'            and iss_type = '配股'          group by secu_id             , iss_date      ) b on b.secu_id = a.secu_id and a.allot_reg_date = b.iss_date          left join      (          select corp_id               , ivst_proj                         , iss_plan_funds_ivst               , funds_has_ivst                    , ann_date                     from pdata_news_n.t02_co_cptl_usag          where src_id = 'wd'            and fin_evt_type = '配股'      ) d on d.corp_id = c.corp_id and d.ann_date = a.usag_ann_dt ;

insert into table wt_list_corp_equi_fin_temp select a.secu_id      , a.corp_id      , a.list_date      , a.fin_type      , a.iss_num      , a.iss_price      , a.fin_net      , a.all_uw main_uw_name      , b.ivst_proj      , b.iss_plan_funds_ivst      , b.funds_has_ivst from (          select secu_id               , corp_id               , ipo_ann_date                                                         list_date                 , inc_ann_date                                                         usag_ann_dt               , if(grp_id = '03', '优先股', if(iss_type = '439006000', '定向增发', '公开增发')) fin_type                  , iss_amt                                                              iss_num                   , iss_pric                                                             iss_price                 , round((if(coll_fnd != '', coll_fnd, 0) - if(iss_fee != '', iss_fee, 0)) / 10000,                       2)                                                             fin_net                   , all_uw          from pdata_news_n.t02_stk_iss_inc          where src_id = 'wd'            and grp_id in ('01','02', '03')            and plan_prog  in ('80','3')      ) a          left join      (          select corp_id               , ivst_proj                         , iss_plan_funds_ivst               , funds_has_ivst                    , ann_date                     from pdata_news_n.t02_co_cptl_usag          where src_id = 'wd'            and fin_evt_type = '增发'      ) b on b.corp_id = a.corp_id and b.ann_date = a.usag_ann_dt ;

insert into table wt_list_corp_equi_fin_temp select a.secu_id      , a.corp_id      , a.list_date      , a.fin_type      , a.iss_num      , a.iss_price      , a.fin_net      , a.list_refr main_uw_name      , c.ivst_proj      , c.iss_plan_funds_ivst      , c.funds_has_ivst from (          select secu_id               , corp_id               , list_date                                                      , '可转债'                                fin_type                  , iss_num                                                        , osh_prio_plac_pric                   iss_price                 , round(iss_scal - iss_fee / 10000, 2) fin_net                   , list_refr                                                      , list_ntc_date as                     usag_ann_dt          from pdata_news_n.t02_bond_cnv_iss          where src_id = 'wd'            and is_co_bond = '1'      ) a          left join      (          select corp_id               , ivst_proj                         , iss_plan_funds_ivst               , funds_has_ivst                    , ann_date                     from pdata_news_n.t02_co_cptl_usag          where src_id = 'wd'            and fin_evt_type = '可转债'      ) c on c.corp_id = a.corp_id and c.ann_date = a.usag_ann_dt ;

insert overwrite table wt_list_corp_equi_fin partition (busi_date = '2023-09-20') select t1.corp_id                                            , t2.corp_name                                          , t1.abbr_name                                          , t1.stk_cd                                             , t1.stk_type                                           , t3.list_date      , t3.fin_type      , t3.iss_num      , t3.iss_price      , t3.fin_net      , t3.main_uw_name      , t3.ivst_proj      , round(t3.iss_plan_funds_ivst/10000,4)      , round(t3.funds_has_ivst/10000,4)      , substr(current_timestamp(), 1, 19) rec_down_time from (          select euid,                 corp_id,                 concat_ws('|', collect_set(stk_cd))    stk_cd,                 concat_ws('|', collect_set(abbr_name)) abbr_name,                 concat_ws('|', collect_set(stk_type))  stk_type          from (                   select entpr_id        euid,                          corp_id,                          src_sys_prdno,                          abbr_name,                          case                              when remark = 'a股' then '1'                              when remark = '港股' then '2'                              when remark = '股转' then '3'                              when remark = 'b股' then '4'                              else '' end stk_type,                          scr_cd          stk_cd                   from dm_mast_n.corp_busi_stkinfo_s                   where busi_date = '2023-09-20'                     and list_stat_cd = '1'                     and remark != '美股'                       distribute by euid                       , corp_id sort by stk_type               ) a          group by euid,                   corp_id      ) t1          left join      (          select entpr_id   euid               , entpr_name corp_name          from dm_mast_n.corp_busi_base_info_s          where busi_date = '2023-09-20'            and listing_flg = '1'      ) t2 on t1.euid = t2.euid          join wt_list_corp_equi_fin_temp t3 on t3.corp_id = t1.corp_id ;

drop table if exists wt_list_corp_equi_fin_temp;
