-- GENERATED by ../render.mjs; edit the branch main SQL and its includes.
-- 230204普通互换客户创收：01合约日主体，02~06并列补充；09输出内接07净创收与08毛佣金。
-- 07 CASE顺序：固定利率跨境互换 → 浮动利率跨境互换 → 多头持券 → 指数增强 → 0。
-- 08毛佣金只是另一输出，净佣金已进入前两分支，不再把08加到07上。
-- 下列include保持原SQL全部token顺序，不改成CTE、不额外去重或过滤。
-- 外层74列投影顺序，不计算金额；FROM括号在00主脚本结尾闭合。
SELECT Agt_Id,
	Busi_Type,
	Cutp_Pty_Id,
	Cutp_Pty_Shor_Name,
	Cutp_Pty_Full_Name,
	Sign_Prd_Name,
	USCC,
	Contr_Type_Cd,
	Contr_Type_Desc,
	Src_Contr_Type,
	Src_Contr_Type_Desc,
	Src_Sub_Contr_Type,
	Src_Sub_Contr_Type_Desc,
	Undrl_Wd_Cd,
	Undrl_Name,
	Init_Nom_Prin,
	Dyna_Nom_Prin,
	Curr_Rev,
	Opt_Npv_Curr_Rev,
	Strt_Pric_Date,
	End_Pric_Date,
	Is_Preterm_Flag,
	Early_Term_Date,
	Agt_Stat_Cd,
	Accrued_Date,
	Inr_Seri_No,
	otc_seri_no,
	Book_Agt_Id,
	Cntr,
	Cros_Crrc_Type_Cd,
	fixed_rate,
	Flot_Intrt_Ulmt,
	Float_Base_Rate,
	Intr_Marg,
	Float_Undrl_Cd,
	Undrl_Curr,
	Bgng_Npv,
	prop_group,
	Opt_Fee_Rate,
	Init_Marg_Prop,
	Base_Marg_Rate,
	Marg_Agt_Id,
	FUND_COST_RATE,
	MARGIN_FIXED_RATE,
	COMMISSION_COST,
	SPREAD,
	LONG_FIXED_RATE,
	CAPITAL_COST,
	Cms_Mode_Cd,
	Trd_Fee_Rate,
	Bgng_Vol,
	Peshr_Cms,
	Nom_Prin_Chg_Delta,
	Occu_Qty,
	Divd_Tax_Amt,
	intrt,
	ir,
	Tdy_Yield,
	Simu_Hedg_Pal,
	prop_ratio,
	Map_Undrl_Cd,
	Undrl_Tdy_Yield,
	Undrl_Simu_Hedg_Pal,
	Sett_Crrc_Cd,
	mid_price,
	OTHER_Prvs_Fee,
	PREMIUM_Prvs_Fee,
	Data_Time,
	Trd_Cms,
	Rev_Contr_Type_Cd,
	Agt_Clas_Cd,
	Src_Undrl_Type,
	busi_date,
	grp_id FROM (

select
-- SELECT完整74列由本片段接入07、08两个公式；其余列保留原值、转换或NULL占位。
-- info=01主合约；det逐日明细、cp客户及短输入在00；u/pd/evt/cr/co分别由02~06提供查询体，不是名为info的物理表。
-- 初始本金输出info，动态本金展示补0；07息差直接读det动态本金，不使用展示列补0后的值。
    info.Agt_Id,  --合约编号
    info.Busi_Type,  --业务类型
    info.Cutp_Pty_Id,  --交易对手客户编号
    info.Cutp_Pty_Shor_Name,  --交易对手当事人简称
    info.Cutp_Pty_Full_Name,  --交易对手当事人名称
    info.Sign_Prd_Name,  --代签产品名称
    cp.USCC,  --统一社会信用代码
    info.Contr_Type_Cd,  --合约类型代码
    info.Contr_Type_Desc,  --合约类型描述
    info.Src_Contr_Type,  --源合约类型
    info.Src_Contr_Type_Desc,  --源合约类型描述
    info.Src_Sub_Contr_Type,  --源合约子类型
    info.Src_Sub_Contr_Type_Desc,  --源合约子类型描述
    info.Undrl_Wd_Cd,  --标的万得代码
    info.Undrl_Name,  --标的名称
    info.Init_Nom_Prin,  --初始名义本金
    coalesce(det.Dyna_Nom_Prin, 0) as Dyna_Nom_Prin,  --动态名义本金
-- 实际SELECT表达式：info=01主合约，u=02标的盈亏池，evt=04开平仓/分红，cr=05参考利率，co=06成本。
-- det逐日明细、sh最新腿、mid结算币种汇率、fr浮动指数、ins标的分类、x上传分配的实际查询与全部ON均在00。
-- 前两分支=本金息差/365＋净佣金。净佣金先选开仓/平仓、按金额/按股，再gfgreatest(...,0)。
-- 佣金模式1按金额；10按股。按股开仓乘Init_Rate，平仓不乘；开仓日即使有平仓事件仍优先开仓。
-- gfgreatest/gfleast对正常数值分别取大/小；平台UDF的NULL与非法值行为未由资料证明。
case
    -- 1. 固定COMPOSITE：逐日本金×固定净息差/365，再加扣成本并截零的佣金。
    when info.Agt_Clas_Cd = 'TRS_SAC_OTC'
        and ((info.Src_Contr_Type = 'S_CROSS_SWAP' and info.Src_Undrl_Type = 'EQUITY') or info.Src_Contr_Type = 'S_CROSS_OPTION_SWAP')
        and info.Cros_Crrc_Type_Cd = 'COMPOSITE'
    then det.Dyna_Nom_Prin * (
        coalesce(info.fixed_rate,0) - co.FUND_COST_RATE + co.MARGIN_FIXED_RATE
    ) / 365
    + default.gfgreatest(
        case
            when info.Strt_Pric_Date = det.busi_date and sh.Cms_Mode_Cd = '1'
            then info.Init_Nom_Prin * (sh.Trd_Fee_Rate - co.COMMISSION_COST)
            when info.Strt_Pric_Date = det.busi_date and sh.Cms_Mode_Cd = '10'
            then sh.Bgng_Vol * (sh.Peshr_Cms - 0.03) * sh.Init_Rate * coalesce(mid.mid_price,1)
            when sh.Cms_Mode_Cd = '1'
            then coalesce(evt.Nom_Prin_Chg_Delta,0) * (sh.Trd_Fee_Rate - co.COMMISSION_COST)  * coalesce(mid.mid_price,1)
            when sh.Cms_Mode_Cd = '10'
            then coalesce(evt.Occu_Qty,0) * (sh.Peshr_Cms - 0.03) * coalesce(mid.mid_price,1)
        end,0)

    -- 2. FLEXO：参考指数+利差，先取下限再封顶，随后扣利差/成本并加保证金固定利率。
    when info.Agt_Clas_Cd = 'TRS_SAC_OTC'
        and ((info.Src_Contr_Type = 'S_CROSS_SWAP' and info.Src_Undrl_Type = 'EQUITY') or info.Src_Contr_Type = 'S_CROSS_OPTION_SWAP')
        and info.Cros_Crrc_Type_Cd = 'FLEXO'
    then det.Dyna_Nom_Prin * (default.gfleast(
        coalesce(cast(info.Flot_Intrt_Ulmt as double),100),
        default.gfgreatest(cast(info.Float_Base_Rate as double),
            cast(fr.intrt as double)/100 + cast(info.Intr_Marg as double))
    ) - co.SPREAD - coalesce(cr.ir/100,0) + co.MARGIN_FIXED_RATE) / 365
    + default.gfgreatest(
        case
            when info.Strt_Pric_Date = det.busi_date and sh.Cms_Mode_Cd = '1'
            then info.Init_Nom_Prin * (sh.Trd_Fee_Rate - co.COMMISSION_COST)
            when info.Strt_Pric_Date = det.busi_date and sh.Cms_Mode_Cd = '10'
            then sh.Bgng_Vol * (sh.Peshr_Cms - 0.03) * sh.Init_Rate * coalesce(mid.mid_price,1)
            when sh.Cms_Mode_Cd = '1'
            then coalesce(evt.Nom_Prin_Chg_Delta,0) * (sh.Trd_Fee_Rate - co.COMMISSION_COST)  * coalesce(mid.mid_price,1)
            when sh.Cms_Mode_Cd = '10'
            then coalesce(evt.Occu_Qty,0) * (sh.Peshr_Cms - 0.03)  * coalesce(mid.mid_price,1)
        end,0)

    -- 3. 多头持券：日息差＋分红税额×汇率，不加前两分支的净佣金。
    when info.Agt_Clas_Cd = 'TRS_SAC_OTC' and info.Src_Contr_Type = 'LONG_HOLD_SWAP' and info.Src_Undrl_Type = 'EQUITY'
    then det.Dyna_Nom_Prin * (info.fixed_rate - co.FIXED_RATE) / 365 + coalesce(evt.Divd_Tax_Amt,0) * coalesce(mid.mid_price,1)

    -- 4. 指数增强：合格10016合约按动态本金占比分配u+x盈亏池；无零分母保护。
    when info.book_agt_id = '10016' and coalesce(ins.undrl_clas, info.undrl_wd_cd) in ('000905.SH','000852.SH','000016.SH','000300.SH','8841431.WI') and info.Src_Contr_Type = 'INDEX_ENHANCE_SWAP'

    then coalesce(det.Dyna_Nom_Prin, 0)
        / sum(if(
            info.book_agt_id = '10016'
            and coalesce(ins.undrl_clas, info.undrl_wd_cd) in ('000905.SH','000852.SH','000016.SH','000300.SH','8841431.WI')
            and info.Src_Contr_Type = 'INDEX_ENHANCE_SWAP',
            coalesce(det.Dyna_Nom_Prin, 0),0
        )) over(partition by coalesce(ins.undrl_clas, info.undrl_wd_cd),det.busi_date)
        * (coalesce(u.Tdy_Yield, 0)+coalesce(x.Tdy_Yield, 0))
        * coalesce(mid.mid_price,1)
    else 0
end AS Curr_Rev,

    0 as Opt_Npv_Curr_Rev,  --当日期权NPV计提创收
    info.Strt_Pric_Date,  --期初定价日
    coalesce(info.Early_Term_Date, info.End_Pric_Date) as End_Pric_Date,  --期末定价日
    IF(info.Early_Term_Date IS NULL OR info.Early_Term_Date = '', '0', '1') AS Is_Preterm_Flag,  --是否终止标志
    info.Early_Term_Date,  --提前终止日
    info.Agt_Stat_Cd,  --协议状态代码
    det.busi_date as Accrued_Date,  --计提日期
    info.Inr_Seri_No,  --内部流水号
    info.otc_seri_no,  --场外合约流水号
    info.Book_Agt_Id,  --账簿协议编号
    info.Cntr,  --柜台
    info.Cros_Crrc_Type_Cd,  --跨币种类型代码
    info.fixed_rate,  --固定腿利率
    info.Flot_Intrt_Ulmt,  --浮动利率上限
    info.Float_Base_Rate,  --浮动基础利率
    info.Intr_Marg,  --利差
    info.Float_Undrl_Cd,  --浮动腿标的代码
    info.Undrl_Curr,  --标的币种
    info.Bgng_Npv,  --期初NPV
    null as prop_group,  --关联合约分组
    info.Opt_Fee_Rate,  --期权预估期权费率
    info.Init_Marg_Prop,  --初保线
    info.Base_Marg_Rate,  --基保线
    null as Marg_Agt_Id,  --拆货基合约编号
    co.FUND_COST_RATE,  --资金成本利率
    co.MARGIN_FIXED_RATE,  --保证金固定利率
    co.COMMISSION_COST,  --佣金成本
    co.SPREAD,  --利差
    co.FIXED_RATE as LONG_FIXED_RATE,  --多头持券固定利率成本
    null as CAPITAL_COST,  --用资利率
    sh.Cms_Mode_Cd,  --佣金模式代码
    sh.Trd_Fee_Rate,  --交易费率
    sh.Bgng_Vol,  --期初数量
    sh.Peshr_Cms,  --每股佣金（标的币种）
    evt.Nom_Prin_Chg_Delta,  --名义本金变动（结算币种）
    evt.Occu_Qty,  --发生数量（结算币种）
    evt.Divd_Tax_Amt,  --分红税金额（结算币种）
    fr.intrt/100 as intrt,  --浮动利率
    cr.ir/100 as ir,  --资金成本浮动利率
    pd.Tdy_Yield,  --当日盈亏（结算币种）
    null as Simu_Hedg_Pal,  --模拟对冲盈亏（结算币种）
    if(info.book_agt_id = '10016' and coalesce(ins.undrl_clas, info.undrl_wd_cd) in ('000905.SH','000852.SH','000016.SH','000300.SH','8841431.WI') and info.Src_Contr_Type = 'INDEX_ENHANCE_SWAP',coalesce(det.Dyna_Nom_Prin, 0)/sum(if(info.book_agt_id = '10016' and coalesce(ins.undrl_clas, info.undrl_wd_cd) in ('000905.SH','000852.SH','000016.SH','000300.SH','8841431.WI') and info.Src_Contr_Type = 'INDEX_ENHANCE_SWAP',coalesce(det.Dyna_Nom_Prin, 0),0)) over(partition by coalesce(ins.undrl_clas, info.undrl_wd_cd),det.busi_date),null) as prop_ratio,  --分摊比例
    coalesce(ins.undrl_clas, info.undrl_wd_cd) as Map_Undrl_Cd,  --匹配标的代码
    coalesce(u.Tdy_Yield, 0)+coalesce(x.Tdy_Yield, 0) as Undrl_Tdy_Yield,  --标的当日盈亏（结算币种）
    null as Undrl_Simu_Hedg_Pal,  --标的模拟对冲盈亏（结算币种）
    info.Sett_Crrc_Cd,  --结算币种
    coalesce(mid.mid_price,1) as mid_price,  --人民币中间汇率
    null as OTHER_Prvs_Fee,  --按日计提其他费
    null as PREMIUM_Prvs_Fee,  --按日计提期权费
    from_unixtime(unix_timestamp(),'yyyy-MM-dd HH:mm:ss') AS Data_Time,  --数据时间
-- 独立展示毛佣金：未扣COMMISSION_COST或每股0.03，也没有gfgreatest截零。
-- 07前两分支已经加净佣金，不能把此列再加到Curr_Rev形成所谓总创收。
-- sh为按腿最新持仓参数；evt为事件日汇总。开仓条件优先，其他日才用事件金额/数量。
    case when info.Strt_Pric_Date = det.busi_date and sh.Cms_Mode_Cd = '1' then info.Init_Nom_Prin * sh.Trd_Fee_Rate
            when info.Strt_Pric_Date = det.busi_date and sh.Cms_Mode_Cd = '10' then sh.Bgng_Vol * sh.Peshr_Cms * sh.Init_Rate * coalesce(mid.mid_price,1)
            when sh.Cms_Mode_Cd = '1' then coalesce(evt.Nom_Prin_Chg_Delta,0) * sh.Trd_Fee_Rate  * coalesce(mid.mid_price,1)
            when sh.Cms_Mode_Cd = '10' then coalesce(evt.Occu_Qty,0) * sh.Peshr_Cms * coalesce(mid.mid_price,1) end as Trd_Cms,  --交易佣金收入

    case when info.Agt_Clas_Cd = 'TRS_SAC_OTC' and ((info.Src_Contr_Type = 'S_CROSS_SWAP' and info.Src_Undrl_Type = 'EQUITY') or info.Src_Contr_Type = 'S_CROSS_OPTION_SWAP') then 'S_CROSS_SWAP'
          when info.Agt_Clas_Cd = 'TRS_SAC_OTC' and info.Src_Contr_Type = 'LONG_HOLD_SWAP' and info.Src_Undrl_Type = 'EQUITY' then 'LONG_HOLD_SWAP'
          when info.book_agt_id = '10016' and coalesce(ins.undrl_clas, info.undrl_wd_cd) in ('000905.SH','000852.SH','000016.SH','000300.SH','8841431.WI') and info.Src_Contr_Type = 'INDEX_ENHANCE_SWAP' then 'INDEX_ENHANCE_SWAP'
          end as Rev_Contr_Type_Cd,  --创收合约类型
    info.Agt_Clas_Cd,  --协议类型代码
    info.Src_Undrl_Type,  --源标的类型
    '${yyyy-MM-dd}' as busi_date,  --业务日期
    '02' as grp_id  --分组标识

-- 连接主线：FROM / JOIN / ON直接保留在这里；复杂输入在括号内引用查询体。
-- 合约快照info：读取范围在01；与逐日明细det按合约号相接才形成合约日。
from (
-- 本文件只选info主合约；det/cp/ins的查询与连接在00，连接后才形成合约日。
-- info：报告日合约主信息，grp_id=02、OTC、排除TRS_INNER、有效结束日不早于2022。
-- det：107491合约逐日明细；只用明细自身起止日过滤，再按Agt_Id INNER JOIN。
-- 不在本任务再限制det日期<=报告日，也不以info提前终止日重新截断det；缺明细的合约不出现。
-- cp：公司客户OIS来源、报告日、未删除，按客户编号补USCC；ins：证券基础资料按标的工具编号补标的分类。
-- 这里合约号Agt_Id连接det；后续事件用Inr_Seri_No、持仓盈亏用Otc_Seri_No，三者不可互换。
-- 本文件提供info查询体；外层JOIN与ON在00主脚本，实际公式继续在收入模块。
select * from PDATA_N.T98_OTC_DERI_COMP_SALE_INFO
    where busi_date = '${yyyy-MM-dd}' and grp_id = '02' and Agt_Clas_Cd != 'TRS_INNER'
        and Book_Bel_Dept = 'OTC' and coalesce(Early_Term_Date, End_Pric_Date) >= '2022-01-01'

) info

-- 逐日本金det：只用明细自身起止日过滤；缺明细不生成合约日。
inner join (
    select * from PDATA_N.T98_OTC_DERI_COMP_SALE_ADTNL_DET
    where busi_date between Strt_Pric_Date and End_Pric_Date
    ) det
on info.agt_id = det.agt_id

-- 客户cp：T01_CORP_CUST法人客户，交易对手客户编号取USCC；多匹配仍会扩行。
left join (
    select * from PDATA_N.T01_CORP_CUST
    where src_tbl = 'ODATA_N_OIS.O_OTC_DERIVATIVE_COUNTERPARTY' and busi_date = '${yyyy-MM-dd}' and DEL_FLAG = '0'
    ) cp
on cp.pty_id = info.Cutp_Pty_Id

-- 证券资料ins：按标的工具号补分类，参与指数增强领取范围和窗口键。
left join (
    select * from pdata_news_n.t02_tit_scr_base_info
    where src_id = 'TIT' and grp_id = '01'
    ) ins
on ins.in_code = info.Undrl_Ins_Id

-- 标的盈亏池u：复杂账簿／标的归集留在模块，下方ON保留实际领取范围。
left join (
-- 本文件生产u标的盈亏池；上传分配x的直接查询和连接在00，不在本文件汇总。
-- u：独立从11个指定账簿汇总标的日盈亏；x：query_upload.otc_rev_allocated上传分配额。
-- 盈亏池账簿范围不等于收入领取者范围：领取者只限10016、指定5标的、INDEX_ENHANCE_SWAP。
-- 先以账簿Map_Undrl_Cd优先，空串/NULL才回退证券undrl_clas；通过交易产品关系→结构腿→腿持仓确定备用工具。
-- u按标的+历史持仓日聚合；x原样连接无聚合无去重，多条上传会扩行、改变窗口分母。
-- 后续07将u+x整体按合格合约的逐日本金占比分摊，不是把11个账簿的合约一起当分母。
-- 本文件提供u查询体；外层JOIN与ON在00主脚本，实际公式继续在收入模块。
select
        nvl(if(rb.Map_Undrl_Cd='',null,rb.Map_Undrl_Cd),ins.undrl_clas) as Map_Undrl_Cd,
        sum(b.Tdy_Yield) as Tdy_Yield,
        b.busi_date
    from (
        select * from PDATA_N.T98_OTC_BOOK_HOLD_SUM
        where src_tbl = 'ODATA_N_TIT.D_POS_POSITION_DAILY' and busi_date >= '2022-01-01'
        ) b
    inner join (
        select * from PDATA_N.T03_OTC_DERI_BOOK_ADTNL_INFO
        where src_tbl = 'ODATA_N_TIT.D_REF_BOOK' and busi_date = '${yyyy-MM-dd}'
            and Book_Agt_Id in ('10016','10015','10014','10008','10012','10162','10190','10191','10192','10193','10202')
        ) rb
    on rb.Book_Agt_Id = b.Book_Agt_Id
    left join (
        select * from PDATA_N.T03_AGT_PRD_RELA_H
        where SRC_TBL = 'ODATA_N_TIT.D_TRD_OTC_TRADE' and Agt_Prd_Rela_Type_Cd = '01'
            and strt_date <= '${yyyy-MM-dd}' and end_date > '${yyyy-MM-dd}'
        ) tot
    on b.Src_Prd_Id = tot.Src_Prd_Id
    left join (
        select *
        from PDATA_N.T03_OTC_SWAP_COMP_LEG_INFO
        where src_tbl = 'ODATA_N_TIT.D_REF_TRS_LEG' and busi_date = '${yyyy-MM-dd}' and Swap_Comp_Leg_Type_Cd = 'STRUCTURE_LEG_TYPE'
        ) leg
    on leg.Swap_Comp_Agt_Id = tot.Agt_Id 
    left join (
        select * from PDATA_N.T03_OTC_SWAP_COMP_HOLD_INFO
        where src_tbl = 'ODATA_N_TIT.D_POS_TRS_LEG_HIS_POS' and busi_date >= '2022-01-01'
        ) leg_pos
    on leg_pos.Leg_Glbl_Seq_No = leg.Leg_Glbl_Seq_No and leg_pos.busi_date = b.busi_date
    left join (
        select * from pdata_news_n.t02_tit_scr_base_info
        where src_id = 'TIT' and grp_id = '01'
        ) ins
    on ins.in_code = coalesce(leg_pos.Src_Prd_Id, b.Src_Prd_Id)
    where nvl(if(rb.Map_Undrl_Cd='',null,rb.Map_Undrl_Cd),ins.undrl_clas) in ('000905.SH','000852.SH','000016.SH','000300.SH','8841431.WI')
    group by b.busi_date, nvl(if(rb.Map_Undrl_Cd='',null,rb.Map_Undrl_Cd),ins.undrl_clas)

) u
on det.busi_date = u.busi_date and coalesce(ins.undrl_clas, info.undrl_wd_cd) = u.Map_Undrl_Cd and info.book_agt_id = '10016' and info.Src_Contr_Type = 'INDEX_ENHANCE_SWAP'

-- 上传分配额x：与盈亏池并列补入，仍限定10016指数增强；不去重上传行。
left join query_upload.otc_rev_allocated x
on det.busi_date = x.Accrued_Date and coalesce(ins.undrl_clas, info.undrl_wd_cd) = x.undrl_wd_cd and info.book_agt_id = '10016' and info.Src_Contr_Type = 'INDEX_ENHANCE_SWAP'

-- 合约持仓盈亏pd：场外流水号＋账簿＋计提日，Tdy_Yield供09直接展示；07不直接取其金额，多匹配仍可能影响窗口。
left join (
-- 本文件读取pd合约持仓盈亏；mid汇率查询和两路ON条件均在00。
-- pd：账簿持仓汇总，按场外流水号+账簿+计提日读取本合约日盈亏，本分支主要供展示。
-- mid：人民币中间汇率，按info.Sett_Crrc_Cd结算币种+det计提日读取，缺失时公式按1。
-- fixed/FLEXO的本金息差段未再乘mid；事件佣金、按股佣金、分红与指数池才按各自公式换算。
-- 本文件提供pd查询体；外层JOIN与ON在00主脚本，实际公式继续在收入模块。
select * from PDATA_N.T98_OTC_BOOK_HOLD_SUM
    where src_tbl = 'ODATA_N_TIT.D_POS_POSITION_DAILY'

) pd
on info.otc_seri_no = pd.Src_Prd_Id and det.busi_date = pd.busi_date and info.Book_Agt_Id = pd.Book_Agt_Id

-- 汇率mid：人民币中间汇率报价，按结算币种＋计提日接入。
left join (
    select default.datekey2date(trd_dt) as trd_dt, src_crrc_cd, mid_price
    from pdata_news_n.t02_fxr_cfets_quot
    where src_id = 'TIT' and grp_id = '01'
    ) mid
on mid.src_crrc_cd = info.Sett_Crrc_Cd and mid.trd_dt = det.busi_date

-- 开仓参数sh：每条腿最新记录rk=1，再按合约内部号连接；不保证一合约一腿。
left join (--开仓
    select Swap_Comp_Agt_Id, Cms_Mode_Cd, Trd_Fee_Rate, Peshr_Cms, Bgng_Vol, Init_Rate, row_number() over(partition by Leg_Glbl_Seq_No order by busi_date desc) as rk
    from PDATA_N.T03_OTC_SWAP_COMP_HOLD_INFO
    where SRC_TBL = 'ODATA_N_TIT.D_POS_TRS_LEG_HIS_POS'
    ) sh
on sh.Swap_Comp_Agt_Id = info.Inr_Seri_No and sh.rk = 1

-- 平仓／分红evt：模块按内部合约号＋事件日聚合，再连接当前合约日。
left join (
-- 本文件生产evt平仓/分红事件汇总；sh最新腿查询另在00，二者不是串行步骤。
-- sh：互换腿历史持仓，每条Leg_Glbl_Seq_No按日期倒序取rk=1，再按内部流水号连接合约。
-- “最新”是源中该腿最新，并无<=计提日限制；一合约多腿仍可能多条，不能说已做到每合约唯一。
-- evt：持仓变动明细＋状态代码3的存续变动事件，按内部合约号+事件日汇总。
-- CLOSE_STOCKS/EARLY_TERMINATION/TERMINATION汇总绝对数量×价格×rate与绝对数量×rate；不是直接取本金余额的前日差。
-- DIVIDEND_STOCKS汇总分红税额×rate。rate与后续mid不是同一层：这里先形成结算币种金额，公式再按mid转换。
-- 07与08均先判断期初定价日，开仓日即使有evt也优先使用开仓公式，不把两段相加。
-- 本文件提供evt查询体；外层JOIN与ON在00主脚本，实际公式继续在收入模块。
--平仓
    select
        tes.Swap_Comp_Agt_Id,
        sum(if(Evt_Type_Cd in ('CLOSE_STOCKS','EARLY_TERMINATION','TERMINATION'),coalesce(abs(tes.Occu_Qty)*tes.Pric*tes.rate,0),0)) as Nom_Prin_Chg_Delta,
        sum(if(Evt_Type_Cd in ('CLOSE_STOCKS','EARLY_TERMINATION','TERMINATION'),coalesce(abs(tes.Occu_Qty)*tes.rate,0),0)) as Occu_Qty,
        sum(if(Evt_Type_Cd = 'DIVIDEND_STOCKS',coalesce(tes.Divd_Tax_Amt,0)*tes.rate,0)) as Divd_Tax_Amt,
        te.Evt_Date
    from (
        select * from PDATA_N.T05_OTC_SWAP_COMP_HOLD_CHG_DET
        where SRC_TBL = 'ODATA_N_TIT.D_TRD_TRS_EVENT_STRUC_DETAIL'
        ) tes
    join (
        select * from PDATA_N.T05_OTC_COMP_DURA_CHG_EVT
        where src_tbl = 'ODATA_N_TIT.D_TRD_TRS_EVENT' and Evt_Stat_Cd = '3'
            and Evt_Type_Cd in ('CLOSE_STOCKS','EARLY_TERMINATION','TERMINATION','DIVIDEND_STOCKS')
        ) te
    on tes.Dura_Chg_Src_Id = te.Src_Id and tes.Swap_Comp_Agt_Id = te.Otc_Comp_Agt_Id
    group by tes.Swap_Comp_Agt_Id, te.Evt_Date

) evt
on evt.Swap_Comp_Agt_Id = info.Inr_Seri_No and evt.Evt_Date = det.busi_date

-- 参考利率cr：补日加工留在模块，币种与计提日匹配见下方ON。
left join (
-- cr：参考成本利率，HIBOR1M→HKD、SOFR→USD、TONAR→JPY，从各报价日填到下次报价日前一天。
-- 本文件生产cr；连接键是info.Undrl_Curr标的币种+det计提日，与00的mid汇率结算币种不同。
-- fr查询另在00：浮动腿参考指数利率，rec_id按'-'取首段匹配info.Float_Undrl_Cd，日期精确匹配，不补非交易日。
-- cr.ir与fr.intrt进公式都除100；自定义datekey2date与日历语义不能由普通日期测试替代。
-- 本文件提供cr查询体；外层JOIN与ON在00主脚本，实际公式继续在收入模块。
--补非交易日数据，主表有新增货币告警，跟业务确认
    select Curr, ir, date_add(trd_dt, pos) as trd_dt
    from (
        select default.datekey2date(trd_dt) as trd_dt, 
            case scr_cd when 'HIBOR1M' then 'HKD'
                        when 'SOFR' then 'USD'
                        when 'TONAR' then 'JPY'
                        end as Curr, ir,
            lead(default.datekey2date(trd_dt), 1, date_add('${yyyy-MM-dd}',1)) over(partition by scr_cd order by default.datekey2date(trd_dt)) as next_date
        from pdata_news_n.t02_ira_ibor
        where src_id = 'WD' and scr_cd in ('HIBOR1M','SOFR','TONAR') and trd_dt >= '20201201'
        ) t
    lateral view posexplode(split(space(datediff(next_date, trd_dt)-1), ' ')) t as pos, val

) cr
on cr.Curr = info.Undrl_Curr and cr.trd_dt = det.busi_date

-- 浮动指数fr：指数编号＋计提日直接匹配，这一输入没有随cr一起补日。
left join (
    select split(rec_id,'-')[0] as Undrl_Id, intrt, default.datekey2date(trd_dt) as trd_dt
    from pdata_news_n.t02_ira_indx_info
    where src_id = 'TIT' and grp_id = '01'
    ) fr
on fr.Undrl_Id = info.Float_Undrl_Cd and fr.trd_dt = det.busi_date

-- 生效成本co：按计提日＋合约类型映射匹配，没有币种键；不要改成报告日最新参数。
left join (
-- OIS客户创收系数，仅S_CROSS_SWAP与LONG_HOLD_SWAP、报告日快照、is_del=N。
-- 每个合约类型+系数类型按effective_date排列，下一次生效日前一天结束；逐日展开后透视为5列。
-- 有该类型/日期分组但缺某系数：SUM(CASE...ELSE0)可得到0；整个co行未匹配则五项都NULL，不能混同。
-- 同日重复有效配置未去重，也无币种筛选；存在重复时先后与SUM结果需实数核验。
-- S_CROSS_OPTION_SWAP映射到S_CROSS_SWAP参数，其余保留原类型；按det计提日而非报告日匹配。
-- 本文件提供co查询体；外层JOIN与ON在00主脚本，实际公式继续在收入模块。
select
        contract_type,
        sum(case when coefficient_type = 'FUND_COST_RATE' then value else 0 end) as FUND_COST_RATE,
        sum(case when coefficient_type = 'SPREAD' then value else 0 end) as SPREAD,
        sum(case when coefficient_type = 'MARGIN_FIXED_RATE' then value else 0 end) as MARGIN_FIXED_RATE,
        sum(case when coefficient_type = 'FIXED_RATE' then value else 0 end) as FIXED_RATE,
        sum(case when coefficient_type = 'COMMISSION_COST' then value else 0 end) as COMMISSION_COST,
        busi_date
    from (
        select
            contract_type,
            coefficient_type,
            value,
            date_add(strt_date, pos) as busi_date
        from (
            select
                contract_type,
                coefficient_type,
                value,
                effective_date as strt_date,
                date_sub(lead(effective_date, 1, date_add('${yyyy-MM-dd}', 1)) over(partition by contract_type,coefficient_type order by effective_date), 1) as end_Date
            from odata_n_ois.g_client_revenue_coefficient
            where busi_date = '${yyyy-MM-dd}' and is_del = 'N' and contract_type in ('S_CROSS_SWAP','LONG_HOLD_SWAP')
            ) x
        lateral view posexplode(split(space(datediff(end_date, strt_date)), ' ')) y as pos, val
        ) t
    group by contract_type, busi_date

) co
on co.busi_date = det.busi_date and co.contract_type = if(info.Src_Contr_Type = 'S_CROSS_OPTION_SWAP','S_CROSS_SWAP',info.Src_Contr_Type)

) castTable
