-- GENERATED by ../render.mjs; edit the branch main SQL and its includes.
-- 231146：三路标签UNION ALL并列叠加，不以创收日报客户为全局唯一底座。
-- 01规模排名；02历史交易类型及特征；04垫资候选（内部引用03月计数）。
-- 最外层rn<=10只筛有排名的01；其他分支rn=NULL通过。最终不统一去重。
SELECT company_name,
	company_id,
	tag_name,
	busi_date FROM (
	 SELECT
    t0.company_name                    -- 公司名称
    ,t0.company_id                     -- 公司ID
    ,t0.tag_name                       -- 标签
    ,'${yyyy-MM-dd}' as busi_date      -- 业务日期
from (
    
-- 来源：DM_OTC_N.OTC_REV_DAILY_RPT 合约创收日报。
-- 取报告快照中的当日计提规模，按客户名称+USCC+业务类型求和；无grp_id筛选。
-- Dyna_Nom_Prin=动态本金；DENSE_RANK按规模名次，保留前十名次而非固定十个客户。
    SELECT
        Cutp_Pty_Full_Name as company_name
        ,USCC as company_id
        ,case when Busi_Type = 'OPTION' then '前十大期权客户'
              when Busi_Type = 'TRS' then '前十大互换客户'
         end as tag_name
        ,dense_rank() over(partition by Busi_Type order by sum(cast(Dyna_Nom_Prin as double)) desc) as rn
    from DM_OTC_N.OTC_REV_DAILY_RPT
    where busi_date = '${yyyy-MM-dd}'
      and Accrued_Date = '${yyyy-MM-dd}'
      and Busi_Type in ('OPTION', 'TRS')
    group by Cutp_Pty_Full_Name, USCC, Busi_Type


    UNION ALL
    
    
-- 来源：创收日报起始日记录；T98_OTC_DERI_COMP_SALE_INFO 合约主信息提供同名客户限售个股信号。
-- Init_Nom_Prin=初始本金，平均的是入选行；没有按Agt_Id去重，也没额外筛日期或grp_id。
-- Contr_Type_Desc=合约类型描述，原文字直接成为标签；高换手仅检查是否存在grp03，不算换手率。
-- t98_tag仅按客户名匹配，证据可以来自不同合约；金额小标签与定增/高换手可同时出现。
    SELECT
        s.company_name
       ,s.company_id
       ,t.tag_name
       ,null as rn
    from (
        SELECT
            r.Cutp_Pty_Full_Name as company_name
           ,r.USCC as company_id
           ,concat(
                -- 交易类型数组（已去重）
                collect_set(r.Contr_Type_Desc),
                -- 其他标签数组
                    array(
                        case when max(case when t98_tag.Cutp_Pty_Full_Name is not 
                                           null then 1 else 0 end) > 0 
                             then '定增客户' 
                             else null 
                        end,
                        case when avg(cast(r.Init_Nom_Prin as double)) < 1000000 
                             then '单笔交易小' 
                             else null 
                        end,
                        case when sum(case when r.grp_id = '03' then 1 else 0 end) > 0 
                             then '高换手' 
                             else null 
                        end
                    )
            ) as tag_arr
        from DM_OTC_N.OTC_REV_DAILY_RPT r
        -- 关联T98判断是否满足"定增客户"条件(个股+限售)
        left join (
            SELECT distinct Cutp_Pty_Full_Name
            from pdata_n.T98_OTC_DERI_COMP_SALE_INFO t98
            where t98.busi_date = '${yyyy-MM-dd}'
              and t98.grp_id in ('01','02','03')
              and t98.Src_Undrl_Type = 'EQUITY'
              and t98.Res_Flag = '1'
        ) t98_tag
            on r.Cutp_Pty_Full_Name = t98_tag.Cutp_Pty_Full_Name
        where r.busi_date = '${yyyy-MM-dd}'
          and r.Strt_Pric_Date = r.Accrued_Date
        group by r.Cutp_Pty_Full_Name, r.USCC
    ) s
    lateral view outer explode(s.tag_arr) t as tag_name
    where t.tag_name is not null


    UNION ALL
    
    
-- 输入03每个管理人每个有记录月份的候选履保日期数。
-- ROWS 2 PRECEDING是最近至多3行，不保证连续3个自然月；一个月已3天同样可命中。
-- 只有本分支SELECT DISTINCT去重管理人标签，00 UNION ALL不会替其他分支全局去重。
    SELECT distinct
        t2.company_name
        ,t2.company_id
        ,'有垫资' as tag_name
        ,null as rn
    from (
        select
            t1.company_name
            ,t1.company_id
            ,t1.mon
            ,t1.month_cnt
            ,sum(t1.month_cnt) over(
                partition by t1.company_name, t1.company_id 
                order by t1.mon 
                rows between 2 preceding and current row           -- 最近至多3个有记录月份，未补自然月
            ) as rolling_3mon_cnt                                 -- 记录月份窗口累计次数
        from (
            -- Step1: 交易对手(Pty_Id)→T01链路→管理人(c.ORG_FULL_NAME_CH)
            --       筛选 Defr_Days>=2 的记录 → 按 (公司,月份) 聚合
            --       统计原始Perf_Marg_Date不同值，未截成自然日；相同字段值的多交易对手记录只计一次
-- m=T03_OTC_DERI_COMP_COMB_MARG_CALL_INFO 组合追保信息：Perf_Marg_Date履保日期、Defr_Days递延天数。
-- h=T01_PTY_RELA_H 当事人关系历史；c=T01_CORP_CUST 法人客户。
-- m.Pty_Id交易对手→h.Rela_Pty_Id关联方→c.PTY_ID管理人，取报告日有效关系，不按历史事件日回溯关系。
-- 上年1月1日至报告日，Defr_Days>=2仅作为本标签候选；按原始履保日期去重，不数追保行数。
-- 没有符合条件的月份不会自动补零；这影响04的ROWS窗口含义。
            SELECT
                c.ORG_FULL_NAME_CH as company_name                -- 管理人名称
                ,c.USCC as company_id
                ,substr(m.Perf_Marg_Date, 1, 7) as mon            -- 截取到月(yyyy-MM)
                ,count(distinct m.Perf_Marg_Date) as month_cnt    -- 当月入选履保日期字段不同值数，未截自然日
            from PDATA_N.T03_OTC_DERI_COMP_COMB_MARG_CALL_INFO m
            inner join pdata_n.T01_PTY_RELA_H h
                on m.Pty_Id = h.Pty_Id                            -- 交易对手ID
                and h.SRC_TBL = 'ODATA_N_TIT.D_REF_CTPTY_MAPPING'
                and h.STRT_DATE <= '${yyyy-MM-dd}'
                and h.END_DATE > '${yyyy-MM-dd}'
            inner join pdata_n.T01_CORP_CUST c
                on h.Rela_Pty_Id = c.PTY_ID                      -- 映射到管理人
                and c.BUSI_DATE = '${yyyy-MM-dd}'
                and c.SRC_TBL = 'ODATA_N_OIS.O_OTC_DERIVATIVE_COUNTERPARTY'
            where m.Busi_Date = '${yyyy-MM-dd}'
              and m.Perf_Marg_Date >= '${yyyy,-1y}-01-01'
              and m.Perf_Marg_Date <= '${yyyy-MM-dd}'
              and m.Src_Tbl = 'ODATA_N_TIT.G_MARGIN_CALL_SETTING'
              and cast(m.Defr_Days as int) >= 2                  -- 递延天数>=2进入本标签候选，不证明实际资金垫付
            group by c.ORG_FULL_NAME_CH, c.USCC,
                     substr(m.Perf_Marg_Date, 1, 7)               -- ← 按 (公司, 月) 一步聚合


        ) t1
    ) t2
    where t2.rolling_3mon_cnt >= 3                               -- 存在任意记录月份窗口累计>=3次



) t0
where t0.rn <= 10 or t0.rn is null 
	) castTable
