-- GENERATED by ../render.mjs; edit the branch main SQL and its includes.
-- 228241：公司开仓记录为底座，并列补交易类型排名和估值统计。
-- t1=02开仓统计；t2=03类型前二；t3=04估值匹配样本，后者再引用05。
-- 最终只按公司ID和期间连接，不擅加名称条件；外层字段顺序保持原文。
SELECT company_name,
	company_id,
	time_period,
	weekly_trd_freq,
	avg_trd_amount,
	trd_win_rate,
	yield_rate,
	swap_first_trd_type,
	swap_second_trd_type,
	swap_first_trd_count,
	swap_second_trd_count,
	busi_date FROM (
	 
-- 在这里输出频率、平均规模、胜率、收益率；不在此重新生成样本。
-- t1来自创收日报起始日记录；t3来自这些记录与当前主合约、当前腿估值的内连接。
-- 所有除法保持原式，未加零分母保护；频率不是简单除52。
SELECT
    t1.company_name                    -- 公司名称
    ,t1.company_id                     -- 公司ID
    ,t1.time_period                    -- 时间区间（近一年/历史）
    -- 每周交易频率 = 交易笔数 / 周数
    -- 标签“近一年”的分母实际从上年1月1日算到报告日，不是本年年初。
    -- 历史：从本快照入选开仓记录的最早日期算到报告日，不证明真实首次交易。
    ,t1.trd_count / case when t1.time_period = '近一年' 
                          then datediff('${yyyy-MM-dd}', '${yyyy,-1y}-01-01') / 7.0
                          else datediff('${yyyy-MM-dd}', t1.min_accrued_date) / 7.0 end as weekly_trd_freq  -- 每周交易频率(笔)
    ,t1.avg_trd_amount                 -- 单笔平均交易规模
    -- 胜率分子数盈利匹配行；分母数估值匹配后的不同合约。重复匹配时口径并不等价。
    ,t3.win_count / t3.total_count as trd_win_rate  -- 交易胜率
    -- 收益率分子来自t3估值匹配样本；分母来自t1全部入选开仓行，不保证同一集合。
    ,t3.total_pnl / t1.total_init_nom as yield_rate  -- 收益率
    ,t2.swap_first_trd_type            -- 互换业务笔数第一业务类型
    ,t2.swap_second_trd_type           -- 互换业务笔数第二业务类型
    ,t2.swap_first_trd_count           -- 互换业务第一交易笔数
    ,t2.swap_second_trd_count          -- 互换业务第二交易笔数
    ,'${yyyy-MM-dd}' as busi_date      -- 业务日期


from (
-- 输入：DM_OTC_N.OTC_REV_DAILY_RPT 场外衍生品合约创收日报。
-- Agt_Id=合约号；Init_Nom_Prin=初始本金；Accrued_Date=计提日；Strt_Pric_Date=期初定价日。
-- 每条起始日记录展开近一年/历史标签后按各标签筛选，无grp_id限制。
-- COUNT DISTINCT按合约去重，但AVG/SUM不去重；重复开仓行会改变金额而不改变笔数。

    -- 主查询：按公司+时间区间统计交易基本信息
    SELECT
        Cutp_Pty_Full_Name as company_name
        ,USCC as company_id
        ,time_period
        ,count(distinct Agt_Id) as trd_count           -- 交易笔数
        ,avg(Init_Nom_Prin) as avg_trd_amount          -- 单笔平均交易规模
        ,sum(Init_Nom_Prin) as total_init_nom           -- 总期初名义本金
        ,min(Accrued_Date) as min_accrued_date          -- 公司级实际计提开始日期（历史区间用）
    from DM_OTC_N.OTC_REV_DAILY_RPT
    -- 展开时间区间：近一年、历史
    lateral view explode(array('近一年', '历史')) t as time_period
    where busi_date = '${yyyy-MM-dd}'
      and Busi_Type = 'TRS'                      -- 筛选互换业务
      and Accrued_Date = Strt_Pric_Date          -- 只统计新开仓交易
      -- 根据时间区间筛选计提日期
      and ((time_period = '近一年' and Accrued_Date between '${yyyy,-1y}-01-01' and '${yyyy-MM-dd}')
           or (time_period = '历史' and Accrued_Date <= '${yyyy-MM-dd}'))
    group by USCC, Cutp_Pty_Full_Name, time_period


) t1
-- 关联：按笔数排序的前两大互换业务类型
left join (
-- 与02使用相同入选条件，但另按Contr_Type_Desc（合约类型描述）分组。
-- 每类型内部数不同合约，ROW_NUMBER排序后横向放成前两列。
-- 笔数相同没有第二排序键，不能声称并列业务中哪一个稳定第一。

    SELECT
        company_id
        ,company_name
        ,time_period
        ,max(case when rn = 1 then Contr_Type_Desc end) as swap_first_trd_type   -- 第一业务类型
        ,max(case when rn = 2 then Contr_Type_Desc end) as swap_second_trd_type  -- 第二业务类型
        ,max(case when rn = 1 then trd_count end) as swap_first_trd_count        -- 第一业务类型笔数
        ,max(case when rn = 2 then trd_count end) as swap_second_trd_count       -- 第二业务类型笔数
    from (
        SELECT
            USCC as company_id
            ,Cutp_Pty_Full_Name as company_name
            ,time_period
            ,Contr_Type_Desc
            ,count(distinct Agt_Id) as trd_count
            -- 按笔数降序排序，取前两名
            ,row_number() over(partition by USCC, Cutp_Pty_Full_Name, time_period 
                               order by count(distinct Agt_Id) desc) as rn
        from DM_OTC_N.OTC_REV_DAILY_RPT
        lateral view explode(array('近一年', '历史')) t as time_period
        where busi_date = '${yyyy-MM-dd}'
          and Busi_Type = 'TRS'
          and Accrued_Date = Strt_Pric_Date -- 只统计新开仓交易
          and ((time_period = '近一年' and Accrued_Date between '${yyyy,-1y}-01-01' and '${yyyy-MM-dd}')
               or (time_period = '历史' and Accrued_Date <= '${yyyy-MM-dd}'))
        group by USCC, Cutp_Pty_Full_Name, time_period, Contr_Type_Desc
    ) t
    where rn <= 2  -- 只取前两名
    group by company_id, company_name, time_period


) t2 on t1.company_id = t2.company_id 
     and t1.time_period = t2.time_period
-- 关联：计算交易胜率和收益率
left join (
-- r=创收日报开仓记录；s=T98_OTC_DERI_COMP_SALE_INFO 合约主信息；v=05按合约内部号聚合的腿估值。
-- 两次INNER JOIN：缺主合约或估值的记录不进入胜率分母，但可能仍进入02本金分母。
-- 本模块按USCC+期间聚合，没有客户名分组；分子盈利行数，分母不同Agt_Id，未做一合约一行保证。

    -- 计算交易胜率和收益率所需数据
    SELECT
        USCC as company_id
        ,time_period
        ,count(distinct Agt_Id) as total_count          -- 客户合约数
        ,sum(case when pnl > 0 then 1 else 0 end) as win_count  -- 盈亏>0的交易总数
        ,sum(pnl) as total_pnl                          -- 总收益金额
    from (
        SELECT
            r.USCC
            ,r.Agt_Id
            ,time_period
            ,v.pnl
        from DM_OTC_N.OTC_REV_DAILY_RPT r
        -- 关联合约基本信息表，获取内部流水号
        inner join pdata_n.T98_OTC_DERI_COMP_SALE_INFO s
            on r.Agt_Id = s.Agt_Id
            and s.busi_date = '${yyyy-MM-dd}'
            and s.grp_id = '02'  -- 互换业务分组
        -- 关联互换合约估值信息表，获取盈亏数据
        inner join (
-- PDATA_N.T98_OTC_SWAP_COMP_LEG_VALU_INFO：场外互换合约腿估值信息。
-- Swap_Comp_Agt_Id匹配主合约Inr_Seri_No（内部流水号），不是直接匹配日报Agt_Id。
-- Lcrrc_Accum_Unrlz_Yield=本币累计未实现收益；Lcrrc_Accum_Rlz_Yield=本币累计已实现收益。
-- 先在同一行相加再SUM；任何一项NULL，该行加法即NULL，不是逐项自动补0。
-- 当前报告日累计估值，不是按标签起止日做收益差分；SRC_TBL限定TIT腿估值来源。

            SELECT
                Swap_Comp_Agt_Id
                -- 总收益 = 累计未实现收益 + 累计已实现收益
                ,sum(Lcrrc_Accum_Unrlz_Yield + Lcrrc_Accum_Rlz_Yield) as pnl
            from pdata_n.T98_OTC_SWAP_COMP_LEG_VALU_INFO
            where SRC_TBL = 'ODATA_N_TIT.D_POS_TRS_LEG_VALUATION'
              and busi_date = '${yyyy-MM-dd}'
            group by Swap_Comp_Agt_Id


        ) v on s.Inr_Seri_No = v.Swap_Comp_Agt_Id
        lateral view explode(array('近一年', '历史')) t as time_period
        where r.busi_date = '${yyyy-MM-dd}'
          and r.Busi_Type = 'TRS'
          and r.Accrued_Date = r.Strt_Pric_Date
          and ((time_period = '近一年' and r.Accrued_Date between '${yyyy,-1y}-01-01' and '${yyyy-MM-dd}')
               or (time_period = '历史' and r.Accrued_Date <= '${yyyy-MM-dd}'))
    ) t
    group by USCC, time_period


) t3 on t1.company_id = t3.company_id 
     and t1.time_period = t3.time_period 
	) castTable
