/*
输入：08的allocated_daily_report；输出：原118141的92列，字段顺序不变。
这里主要做原有String转换，不新增业务计算，也不再筛选计提日。
原任务快照仅提供SELECT；下游目标为dm_otc_n.otc_sale_daily_rpt。
*/
SELECT
    CAST( Agt_Id AS String ) Agt_Id,
    CAST( Busi_Type AS String ) Busi_Type,
    CAST( Cutp_Pty_Id AS String ) Cutp_Pty_Id,
    CAST( Cutp_Pty_Shor_Name AS String ) Cutp_Pty_Shor_Name,
    CAST( Cutp_Pty_Full_Name AS String ) Cutp_Pty_Full_Name,
    CAST( Sign_Prd_Name AS String ) Sign_Prd_Name,
    CAST( Contr_Type_Cd AS String ) Contr_Type_Cd,
    CAST( Contr_Type_Desc AS String ) Contr_Type_Desc,
    CAST( Src_Contr_Type AS String ) Src_Contr_Type,
    CAST( Src_Contr_Type_Desc AS String ) Src_Contr_Type_Desc,
    CAST( Src_Sub_Contr_Type AS String ) Src_Sub_Contr_Type,
    CAST( Src_Sub_Contr_Type_Desc AS String ) Src_Sub_Contr_Type_Desc,
    CAST( Undrl_Ins_Id AS String ) Undrl_Ins_Id,
    CAST( Undrl_Wd_Cd AS String ) Undrl_Wd_Cd,
    CAST( Undrl_Name AS String ) Undrl_Name,
    CAST( Undrl_Type AS String ) Undrl_Type,
    CAST( Src_Undrl_Type AS String ) Src_Undrl_Type,
    CAST( Annu_Sprd AS String ) Annu_Sprd,
    CAST( Absl_Sprd AS String ) Absl_Sprd,
    CAST( Annu_Base AS String ) Annu_Base,
    CAST( Absl_Base AS String ) Absl_Base,
    CAST( Init_Nom_Prin AS String ) Init_Nom_Prin,
    CAST( Init_Nom_Prin_Main AS String ) Init_Nom_Prin_Main,
    CAST( Init_Nom_Prin_Intro AS String ) Init_Nom_Prin_Intro,
    CAST( Dyna_Nom_Prin AS String ) Dyna_Nom_Prin,
    CAST( Dyna_Nom_Prin_Main AS String ) Dyna_Nom_Prin_Main,
    CAST( Dyna_Nom_Prin_Intro AS String ) Dyna_Nom_Prin_Intro,
    CAST( Accum_Dyna_Nom_Prin AS String ) Accum_Dyna_Nom_Prin,
    CAST( Absl_Nom_Prin AS String ) Absl_Nom_Prin,
    CAST( Absl_Nom_Prin_Main AS String ) Absl_Nom_Prin_Main,
    CAST( Absl_Nom_Prin_Intro AS String ) Absl_Nom_Prin_Intro,
    CAST( Accum_Absl_Nom_Prin AS String ) Accum_Absl_Nom_Prin,
    CAST( Curr_Prvs_Sales_Income AS String ) Curr_Prvs_Sales_Income,
    CAST( Curr_Prvs_Sales_Income_1 AS String ) Curr_Prvs_Sales_Income_1,
    CAST( Curr_Prvs_Sales_Income_2 AS String ) Curr_Prvs_Sales_Income_2,
    CAST( Curr_Prvs_Sales_Income_3 AS String ) Curr_Prvs_Sales_Income_3,
    CAST( Strt_Pric_Date AS String ) Strt_Pric_Date,
    CAST( End_Pric_Date AS String ) End_Pric_Date,
    CAST( Accrued_Strt_Date AS String ) Accrued_Strt_Date,
    CAST( Accrued_End_Date AS String ) Accrued_End_Date,
    CAST( Earn_Pymt_Date AS String ) Earn_Pymt_Date,
    CAST( Actl_Days AS String ) Actl_Days,
    CAST( Is_Preterm_Flag AS String ) Is_Preterm_Flag,
    CAST( Early_Term_Date AS String ) Early_Term_Date,
    CAST( Agt_Stat_Cd AS String ) Agt_Stat_Cd,
    CAST( Main_Oper_User_Id AS String ) Main_Oper_User_Id,
    CAST( Main_Oper_Name AS String ) Main_Oper_Name,
    CAST( Main_Oper_Emp_Id AS String ) Main_Oper_Emp_Id,
    CAST( Intro_Oper_User_Id AS String ) Intro_Oper_User_Id,
    CAST( Intro_Oper_Name AS String ) Intro_Oper_Name,
    CAST( Intro_Oper_Emp_Id AS String ) Intro_Oper_Emp_Id,
    CAST( Intro_Inr_Org_Id_1 AS String ) Intro_Inr_Org_Id_1,
    CAST( Intro_Inr_Org_Name_1 AS String ) Intro_Inr_Org_Name_1,
    CAST( Div_Org_Id_1 AS String ) Div_Org_Id_1,
    CAST( Div_Org_Name_1 AS String ) Div_Org_Name_1,
    CAST( Cust_Mngr_User_Id_1 AS String ) Cust_Mngr_User_Id_1,
    CAST( Cust_Mngr_Name_1 AS String ) Cust_Mngr_Name_1,
    CAST( Cust_Mngr_Emp_Id_1 AS String ) Cust_Mngr_Emp_Id_1,
    CAST( Allo_Prop_1 AS String ) Allo_Prop_1,
    CAST( Intro_Inr_Org_Id_2 AS String ) Intro_Inr_Org_Id_2,
    CAST( Intro_Inr_Org_Name_2 AS String ) Intro_Inr_Org_Name_2,
    CAST( Div_Org_Id_2 AS String ) Div_Org_Id_2,
    CAST( Div_Org_Name_2 AS String ) Div_Org_Name_2,
    CAST( Cust_Mngr_User_Id_2 AS String ) Cust_Mngr_User_Id_2,
    CAST( Cust_Mngr_Name_2 AS String ) Cust_Mngr_Name_2,
    CAST( Cust_Mngr_Emp_Id_2 AS String ) Cust_Mngr_Emp_Id_2,
    CAST( Allo_Prop_2 AS String ) Allo_Prop_2,
    CAST( Intro_Inr_Org_Id_3 AS String ) Intro_Inr_Org_Id_3,
    CAST( Intro_Inr_Org_Name_3 AS String ) Intro_Inr_Org_Name_3,
    CAST( Div_Org_Id_3 AS String ) Div_Org_Id_3,
    CAST( Div_Org_Name_3 AS String ) Div_Org_Name_3,
    CAST( Cust_Mngr_User_Id_3 AS String ) Cust_Mngr_User_Id_3,
    CAST( Cust_Mngr_Name_3 AS String ) Cust_Mngr_Name_3,
    CAST( Cust_Mngr_Emp_Id_3 AS String ) Cust_Mngr_Emp_Id_3,
    CAST( Allo_Prop_3 AS String ) Allo_Prop_3,
    CAST( Accrued_Date AS String ) Accrued_Date,
    CAST( Data_Time AS String ) Data_Time,
    CAST( Accum_prvs_sales_income AS String ) Accum_prvs_sales_income,
    CAST( Accum_prvs_sales_income_1 AS String ) Accum_prvs_sales_income_1,
    CAST( Accum_prvs_sales_income_2 AS String ) Accum_prvs_sales_income_2,
    CAST( Accum_prvs_sales_income_3 AS String ) Accum_prvs_sales_income_3,
    CAST( Adtnl_Rwd AS String ) Adtnl_Rwd,
    CAST( fee_rate AS String ) fee_rate,
    CAST( Fin_Rati AS String ) Fin_Rati,
    Intr_Marg,
    Res_Flag,
    Opt_Fee_Rate,
    Ex_Rate_Model,
    Cust_Mngr_Is_Actv_1,
    Cust_Mngr_Is_Actv_2,
    Cust_Mngr_Is_Actv_3,
    CAST( busi_date AS String ) busi_date
FROM allocated_daily_report castTable
