-- GENERATED by render.mjs; edit 00_主脚本.sql and numbered modules instead.
/*
118141 / 交叉销售收入日报：把“每天的本金”变成“每天归属的销售收入”
先看本文件，再跟读《一份期权走完主线.md》。不需要先读完所有参数专题。

01 合约及人员范围 ───────┐
107491 逐日本金与费用 ───┼→ 04 合约逐日输入
02 价差 / 03 基准与成本 ─┘        ↓
                         05 普通期权、普通互换计算
                                 ↓
                         06 特殊业务优先，形成原始收入
                                 ↓
                         07 奖励汇总 → 保底 / 系统费用调整
                                 ↓
                         08 人员分配与累计
                                 ↓
                         09 输出原有92个字段

每个模块定义命名结果，下一模块直接引用；不是独立执行的SQL片段。
@include由render.mjs展开，不是Hive原生语法；完整SQL.sql为展开后的阅读版。
冻结证据只有SELECT，没有INSERT：本文件也不虚构写入语句。
平台目标为dm_otc_n.otc_sale_daily_rpt；不连接或执行生产任务。
*/
WITH
/*
先准备当日两份资料，本模块还没有展开历史日。
sale_contracts：合约主信息；剔除费用互换、04组FAST及香港账簿。
sale_management：合约经营关系；提供经办人、引入机构、客户经理及分配比例。
下一步04用Agt_Id把它们和107491的逐日明细连接。
注意：这里的busi_date是加工日，04中det.busi_date才是收入归属日。
*/
-- PDATA_N.T98_OTC_DERI_COMP_SALE_INFO：场外衍生品合约销售收入基本信息表。
sale_contracts AS (
    select * from PDATA_N.T98_OTC_DERI_COMP_SALE_INFO
    where busi_date = '${yyyy-MM-dd}' and Src_Contr_Type != 'FEE_SWAP'  --销售收入不计算“费用互换”
        and grp_id != '04' and Book_Bel_Dept != 'OTC_HK'  --极速合约暂不计算，香港合约单独计算
)
,
-- PDATA_N.T98_OTC_COMP_MNG_RELA_INFO：合约经营关系；本脚本取本次加工日快照。
sale_management AS (
    select * from PDATA_N.T98_OTC_COMP_MNG_RELA_INFO
    where busi_Date = '${yyyy-MM-dd}'
)

,
/*
两种价差输入，不在这里选出最终比例：
  合约级：按内部合约号 + 每个计提日匹配，允许合约存续中更换系数。
  客户级：按客户 + 合约类型 + 合约开始日匹配，选定的是开仓时适用规则。
04才把两者接到同一行，并逐项做COALESCE；不能理解为整行二选一。
ANNUALIZED=年化，ABSOLUTE=绝对；比例不在这里除100。
*/
-- T99_DERI_COMP_SPRD_COEF_REF：合约价差系数。
-- 下一生效日前一天为本段结束日；最后一段延续到加工日。
contract_spread_days AS (
    select
        Contract_Code,
        Spread_Calculation,
        Annualized_Spread,
        Absolute_Spread,
        date_add(strt_date, pos) as busi_date
    from (
        select
            Inr_Comp_No as Contract_Code,
            if(Sprd_Calc_Type = '', null, Sprd_Calc_Type) as Spread_Calculation,
            Annu_Sprd_Coef as Annualized_Spread,
            Absl_Sprd_Coef as Absolute_Spread,
            Vld_Date as strt_date,
            date_sub(lead(Vld_Date, 1, date_add('${yyyy-MM-dd}', 1)) over(partition by Inr_Comp_No order by Vld_Date), 1) as end_Date
        from PDATA_N.T99_DERI_COMP_SPRD_COEF_REF
        where src_tbl = 'ODATA_N_OIS.O_CONTRACT_SPREAD_RATE' and Del_Flag = '0' and coalesce(Coef_Type, '') != 'INR' and Agt_Id != ''
        ) x
    lateral view posexplode(split(space(datediff(end_date, strt_date)), ' ')) y as pos, val
)
,
-- T99_DERI_CUTP_COMP_TYPE_SPRD_COEF_REF：客户/合约类型价差系数。
-- 展开的是“合约开始日适用区间”，不是再次展开每份合约的计提日。
customer_spread_days AS (
    select
        CLIENT_ID,
        CONTRACT_TYPE,
        CONTRACT_TYPE_NAME,
        Spread_Calculation,
        Annualized_Spread,
        Absolute_Spread,
        date_add(strt_date, pos) as busi_date
    from (
        select
            Pty_Id as CLIENT_ID,
            Src_Comp_Type_Cd as CONTRACT_TYPE,
            Src_Comp_Type_Desc as CONTRACT_TYPE_NAME,
            if(Calc_Type = '', null, Calc_Type) as Spread_Calculation,
            Annu_Sprd_Coef as Annualized_Spread,
            Absl_Sprd_Coef as Absolute_Spread,
            if(Bgng_Prcg_Date_Llmt = '1900-01-01','2019-01-01',Bgng_Prcg_Date_Llmt) as strt_date,
            if(Bgng_Prcg_Date_Ulmt = '2999-12-31','${yyyy-MM-dd}',Bgng_Prcg_Date_Ulmt) as end_Date
        from PDATA_N.T99_DERI_CUTP_COMP_TYPE_SPRD_COEF_REF
        where src_tbl = 'ODATA_N_OIS.O_CTPTY_CROSS_SELL_COEFFICIENT' and Del_Flag = '0'
        ) x
    lateral view posexplode(split(space(datediff(end_date, strt_date)), ' ')) y as pos, val
)

,
/*
基准和资金成本不是同一种输入：
  合约基准 ─┐
            ├→ 04逐项优先选择 → 05普通业务的基准收入
  类型基准 ─┘
  类型资金成本 → 04匹配 → 06气囊/金仕达公式扣成本
本模块没有把成本从所有业务收入中统一扣一次。

合约基准按合约号连接，没有日期条件。
类型基准、类型成本按合约类型 + 合约开始日连接，不按每个计提日重选。
*/
-- T99_DERI_COMP_BASE_COEF_REF：合约基准系数；附加奖励也由此带出。
contract_baselines AS (
    select
        Inr_Comp_No as Contract_Code,
        Calc_Type as BASE_CALCULATION,
        Base_Yield as BASE_AWARD_RATE,
        if(Adtnl_Rwd = '', 0, Adtnl_Rwd) as additional_reward,
        Adtnl_Rwd_Flag as have_additional_reward
    from PDATA_N.T99_DERI_COMP_BASE_COEF_REF
    where src_tbl = 'ODATA_N_OIS.O_CONTRACT_BASE_RATE' and Del_Flag = '0' and Agt_Id != ''
)
,
-- T99_DERI_COMP_TYPE_BASE_COEF_REF：合约类型基准系数。
type_baseline_days AS (
    select
        CONTRACT_TYPE,
        CONTRACT_TYPE_NAME,
        BASE_CALCULATION,
        BASE_AWARD_RATE,
        date_add(strt_date, pos) as busi_date
    from (
        select
            Src_Comp_Type_Cd as CONTRACT_TYPE,
            Src_Comp_Type_Desc as CONTRACT_TYPE_NAME,
            Calc_Type as BASE_CALCULATION,
            Base_Yield as BASE_AWARD_RATE,
            if(Bgng_Prcg_Date_Llmt = '1900-01-01','2019-01-01',Bgng_Prcg_Date_Llmt) as strt_date,
            if(Bgng_Prcg_Date_Ulmt = '2999-12-31','${yyyy-MM-dd}',Bgng_Prcg_Date_Ulmt) as end_Date
        from PDATA_N.T99_DERI_COMP_TYPE_BASE_COEF_REF
        where src_tbl = 'ODATA_N_OIS.O_BUS_TYPE_BASE_RATE' and Del_Flag = '0' and Src_Dept_No = 'OTC'
        ) x
    lateral view posexplode(split(space(datediff(end_date, strt_date)), ' ')) y as pos, val
)
,
-- T99_DERI_COMP_TYPE_FND_COST_REF：合约类型资金成本。
type_cost_days AS (
    select
        CONTRACT_TYPE,
        CAPITAL_COST,
        date_add(strt_date, pos) as busi_date
    from (
        select
            Src_Comp_Type_Cd as CONTRACT_TYPE,
            Fnd_Cost as CAPITAL_COST,
            if(Intr_Strt_Date = '1900-01-01','2019-01-01',Intr_Strt_Date) as strt_date,
            if(Intr_End_Date = '2999-12-31','${yyyy-MM-dd}',Intr_End_Date) as end_Date
        from PDATA_N.T99_DERI_COMP_TYPE_FND_COST_REF
        where src_tbl = 'ODATA_N_OIS.G_BUS_TYPE_CAPITAL_COST' and Del_Flag = '0' and Src_Dept_No = 'OTC'
        ) x
    lateral view posexplode(split(space(datediff(end_date, strt_date)), ' ')) y as pos, val
)

,
/*
本模块实际把输入接成一张逐日计算底表 contract_day_inputs，后面不再回头JOIN这些源表。

合约info ─INNER→ det逐日明细：决定有哪些合约日
          LEFT→ s_sp/c_sp：两级价差
          LEFT→ s_ba/c_ba：两级基准
          LEFT→ cc：资金成本
          LEFT→ m：人员及分配
          WHERE：机构范围 / 指定合约例外
                    ↓
每行带齐“日期、本金、计算参数、人员资料”

目标理解单位是合约×计提日，但原SQL没有去重：多匹配会放大行数。
字段保留来源前缀，如det_Dyna_Nom_Prin就是det.Dyna_Nom_Prin，不是另算的新本金。
下方源字段注释来自Hive元数据快照；参数别名解释来自本任务SQL。
*/
contract_day_inputs AS (
    SELECT
        -- 合约资料（01）；日期、初始本金和业务身份
        info.Agt_Id AS info_Agt_Id, -- 合约编号
        info.Busi_Type AS info_Busi_Type, -- 业务类型
        info.Cutp_Pty_Id AS info_Cutp_Pty_Id, -- 交易对手客户编号
        info.Cutp_Pty_Shor_Name AS info_Cutp_Pty_Shor_Name, -- 交易对手当事人简称
        info.Cutp_Pty_Full_Name AS info_Cutp_Pty_Full_Name, -- 交易对手当事人名称
        info.Sign_Prd_Name AS info_Sign_Prd_Name, -- 代签产品名称
        info.Contr_Type_Cd AS info_Contr_Type_Cd, -- 合约类型代码
        info.Contr_Type_Desc AS info_Contr_Type_Desc, -- 合约类型描述
        info.Src_Contr_Type AS info_Src_Contr_Type, -- 源合约类型
        info.Src_Contr_Type_Desc AS info_Src_Contr_Type_Desc, -- 源合约类型描述
        info.Src_Sub_Contr_Type AS info_Src_Sub_Contr_Type, -- 源合约子类型
        info.Src_Sub_Contr_Type_Desc AS info_Src_Sub_Contr_Type_Desc, -- 源合约子类型描述
        info.Undrl_Wd_Cd AS info_Undrl_Wd_Cd, -- 标的万得代码
        info.Undrl_Name AS info_Undrl_Name, -- 标的名称
        info.Undrl_Type AS info_Undrl_Type, -- 标的类型
        info.Src_Undrl_Type AS info_Src_Undrl_Type, -- 源标的类型
        info.Init_Nom_Prin AS info_Init_Nom_Prin, -- 初始名义本金
        info.Strt_Pric_Date AS info_Strt_Pric_Date, -- 期初定价日
        info.Early_Term_Date AS info_Early_Term_Date, -- 提前终止日
        info.End_Pric_Date AS info_End_Pric_Date, -- 期末定价日
        info.grp_id AS info_grp_id, -- 并行分组标识
        info.Marg_Agt_Id AS info_Marg_Agt_Id, -- 保证金合约编号
        info.Earn_Pymt_Date AS info_Earn_Pymt_Date, -- 收益兑付日
        info.Agt_Stat_Cd AS info_Agt_Stat_Cd, -- 协议状态代码
        info.Init_Marg_Prop AS info_Init_Marg_Prop, -- 初始保证金比例
        info.Intr_Marg AS info_Intr_Marg, -- 利差
        info.Res_Flag AS info_Res_Flag, -- 限售标志
        info.Opt_Fee_Rate AS info_Opt_Fee_Rate, -- 期权费率
        info.Ex_Rate_Model AS info_Ex_Rate_Model, -- 汇率模式
        Ddct_Ptrn AS info_Ddct_Ptrn, -- 抵扣模式
        Base_Marg_Rate AS info_Base_Marg_Rate, -- 基础保证金率
        -- 逐日金额（107491）；本脚本不重算持仓或事件本金
        det.Dyna_Nom_Prin AS det_Dyna_Nom_Prin, -- 动态名义本金
        det.busi_date AS det_busi_date, -- 业务日期
        det.fee_rate AS det_fee_rate, -- 费率
        det.Inta AS det_Inta, -- 应计利息
        det.Trd_Cms AS det_Trd_Cms, -- 交易佣金收入
        det.Trd_Cms_Cost AS det_Trd_Cms_Cost, -- 交易佣金成本
        det.Fnd_Cost AS det_Fnd_Cost, -- 用资成本
        -- 合约级价差（02）
        s_sp.Spread_Calculation AS s_sp_Spread_Calculation,
        s_sp.Annualized_Spread AS s_sp_Annualized_Spread,
        s_sp.Absolute_Spread AS s_sp_Absolute_Spread,
        -- 客户级价差（02）
        c_sp.Spread_Calculation AS c_sp_Spread_Calculation,
        c_sp.Annualized_Spread AS c_sp_Annualized_Spread,
        c_sp.Absolute_Spread AS c_sp_Absolute_Spread,
        -- 合约级基准（03）
        s_ba.BASE_CALCULATION AS s_ba_BASE_CALCULATION,
        s_ba.BASE_AWARD_RATE AS s_ba_BASE_AWARD_RATE,
        Additional_Reward AS s_ba_Additional_Reward,
        -- 类型级基准（03）
        c_ba.BASE_CALCULATION AS c_ba_BASE_CALCULATION,
        c_ba.BASE_AWARD_RATE AS c_ba_BASE_AWARD_RATE,
        -- 类型资金成本（03）
        cc.capital_cost AS cc_capital_cost,
        -- 人员与机构资料（01）
        m.Main_Oper_User_Id AS m_Main_Oper_User_Id, -- 主经办人ID
        m.Main_Oper_Name AS m_Main_Oper_Name, -- 主经办人姓名
        m.Main_Oper_Emp_Id AS m_Main_Oper_Emp_Id, -- 主经办人员工编号
        m.Intro_Oper_User_Id AS m_Intro_Oper_User_Id, -- 引入经办人ID
        m.Intro_Oper_Name AS m_Intro_Oper_Name, -- 引入经办人姓名
        m.Intro_Oper_Emp_Id AS m_Intro_Oper_Emp_Id, -- 引入经办人员工编号
        m.Inr_Org_Id_1 AS m_Inr_Org_Id_1, -- 引入部门ID_1
        m.Inr_Org_Name_1 AS m_Inr_Org_Name_1, -- 引入部门名称_1
        m.Div_Org_Id_1 AS m_Div_Org_Id_1, -- 所属分公司ID_1
        m.Div_Org_Name_1 AS m_Div_Org_Name_1, -- 所属分公司名称_1
        m.Cust_Mngr_User_Id_1 AS m_Cust_Mngr_User_Id_1, -- 客户经理USER_ID_1
        m.Cust_Mngr_Name_1 AS m_Cust_Mngr_Name_1, -- 客户经理姓名_1
        m.Cust_Mngr_Emp_Id_1 AS m_Cust_Mngr_Emp_Id_1, -- 客户经理员工编号_1
        m.Allo_Prop_1 AS m_Allo_Prop_1, -- 分配比例_1
        m.Inr_Org_Id_2 AS m_Inr_Org_Id_2, -- 引入部门ID_2
        m.Inr_Org_Name_2 AS m_Inr_Org_Name_2, -- 引入部门名称_2
        m.Div_Org_Id_2 AS m_Div_Org_Id_2, -- 所属分公司ID_2
        m.Div_Org_Name_2 AS m_Div_Org_Name_2, -- 所属分公司名称_2
        m.Cust_Mngr_User_Id_2 AS m_Cust_Mngr_User_Id_2, -- 客户经理USER_ID_2
        m.Cust_Mngr_Name_2 AS m_Cust_Mngr_Name_2, -- 客户经理姓名_2
        m.Cust_Mngr_Emp_Id_2 AS m_Cust_Mngr_Emp_Id_2, -- 客户经理员工编号_2
        m.Allo_Prop_2 AS m_Allo_Prop_2, -- 分配比例_2
        m.Inr_Org_Id_3 AS m_Inr_Org_Id_3, -- 引入部门ID_3
        m.Inr_Org_Name_3 AS m_Inr_Org_Name_3, -- 引入部门名称_3
        m.Div_Org_Id_3 AS m_Div_Org_Id_3, -- 所属分公司ID_3
        m.Div_Org_Name_3 AS m_Div_Org_Name_3, -- 所属分公司名称_3
        m.Cust_Mngr_User_Id_3 AS m_Cust_Mngr_User_Id_3, -- 客户经理USER_ID_3
        m.Cust_Mngr_Name_3 AS m_Cust_Mngr_Name_3, -- 客户经理姓名_3
        m.Cust_Mngr_Emp_Id_3 AS m_Cust_Mngr_Emp_Id_3, -- 客户经理员工编号_3
        m.Allo_Prop_3 AS m_Allo_Prop_3, -- 分配比例_3
        m.Cust_Mngr_Emp_Stat_Desc_1 AS m_Cust_Mngr_Emp_Stat_Desc_1, -- 客户经理员工状态描述_1
        m.Cust_Mngr_Emp_Stat_Desc_2 AS m_Cust_Mngr_Emp_Stat_Desc_2, -- 客户经理员工状态描述_2
        m.Cust_Mngr_Emp_Stat_Desc_3 AS m_Cust_Mngr_Emp_Stat_Desc_3, -- 客户经理员工状态描述_3
    
        -- 供05、06使用的计算参数；与上方展示用源字段分开。
        coalesce(s_sp.Spread_Calculation, c_sp.Spread_Calculation, 'ABSOLUTE') AS spread_mode, -- 收入计算方式：合约优先，客户其次；两侧空才默认绝对方式
        coalesce(s_ba.BASE_CALCULATION, c_ba.BASE_CALCULATION) AS base_mode, -- 基准计算方式：合约优先、类型其次；两侧空不设默认
        coalesce(s_sp.Annualized_Spread, c_sp.Annualized_Spread, 0) AS annual_spread_rate, -- 年化价差：合约优先、客户其次；两侧空补0
        coalesce(s_sp.Absolute_Spread, c_sp.Absolute_Spread, 0) AS absolute_spread_rate, -- 绝对价差：合约优先、客户其次；两侧空补0
        coalesce(s_ba.BASE_AWARD_RATE, c_ba.BASE_AWARD_RATE, 0) AS base_rate, -- 基准比例：合约优先、类型其次；两侧空补0
        coalesce(info.Early_Term_Date, info.End_Pric_Date) AS income_end_date -- 收入结束日：提前终止日优先，否则期末定价日
    
    -- 主体：加工日合约快照。
    from sale_contracts info
    
    -- INNER JOIN：必须有逐日附加明细；仅按Agt_Id连接，不额外筛加工日或grp_id。
    inner join PDATA_N.T98_OTC_DERI_COMP_SALE_ADTNL_DET det
    on info.agt_id = det.agt_id
    
    -- 合约价差随计提日匹配。
    left join contract_spread_days s_sp
    on s_sp.CONTRACT_CODE = info.Agt_Id and s_sp.busi_date = det.busi_date
    
    -- 客户价差按合约开始日匹配。
    left join customer_spread_days c_sp
    on c_sp.CLIENT_ID = info.Cutp_Pty_Id and c_sp.CONTRACT_TYPE = info.Contr_Type_Cd and c_sp.busi_date = info.Strt_Pric_Date
    
    -- 合约基准仅按合约号匹配。
    left join contract_baselines s_ba
    on s_ba.CONTRACT_CODE = info.Agt_Id
    
    -- 类型基准按合约开始日匹配。
    left join type_baseline_days c_ba
    on c_ba.CONTRACT_TYPE = info.Contr_Type_Cd and c_ba.busi_date = info.Strt_Pric_Date
    
    -- 成本按合约开始日匹配。
    left join type_cost_days cc
    on cc.CONTRACT_TYPE = info.Contr_Type_Cd and cc.busi_date = info.Strt_Pric_Date
    
    -- 经营关系按合约号匹配；最终WHERE会进一步限制机构范围。
    left join sale_management m
    on m.Agt_Id = info.Agt_Id
    
    -- 空机构按8846处理；三个机构均不满足时，仅下列指定合约例外保留。
    where coalesce(if(m.Inr_Org_Id_1 = '', '8846', m.Inr_Org_Id_1), '8846') != '8846' or coalesce(if(m.Inr_Org_Id_2 = '', '8846', m.Inr_Org_Id_2), '8846') != '8846' or coalesce(if(m.Inr_Org_Id_3 = '', '8846', m.Inr_Org_Id_3), '8846') != '8846'
    or info.agt_id in ('OPT-OTC20220163','OPT-OTC20220128','OPT-OTC20220148','OPT-OTC20220162','OPT-OTC20220153','OPT-OTC20220089-1','OPT-OTC20220155','OPT-OTC20220126','OPT-OTC20220147','OPT-OTC20220129')
)

,
/*
输入：04的contract_day_inputs；输出：ordinary_income_rows，增加ordinary_daily_income。
先只读前四段期权，四种组合看懂后，互换使用同样的组合。

年化项 = 当日动态本金 × 年化比例 / 365（开始日至结束日，含两端）
绝对项 = 初始本金 × 绝对比例（只在开始日）
普通当日收入 = 价差收入 + 基准收入
计提是把收入归到某一天，不是这一天已经收款或发奖。

关键来源：
  det_Dyna_Nom_Prin / det_busi_date ← 107491附加明细的动态本金 / 计提日
  info_Init_Nom_Prin / info_Strt_Pric_Date ← 合约主信息的初始本金 / 期初定价日
  spread_mode、base_mode、各比例、income_end_date ← 04下方的计算参数
这里用的是原始动态本金；展示字段补0不等于公式也补0。

本结果是普通公式候选值。06仍先判断气囊、保证金长期互换、金仕达，再使用它。
未匹配基准方式或业务类型时仍为NULL，不能自行补成0。
*/
ordinary_income_rows AS (
    SELECT
        inputs.*,
        CASE
            -- 期权：年化价差 + 年化基准；只在计提区间内逐日计算。
            WHEN info_Busi_Type = 'OPTION' and spread_mode = 'ANNUALIZED' and base_mode = 'ANNUALIZED'
                THEN IF(det_busi_date BETWEEN info_Strt_Pric_Date AND income_end_date, det_Dyna_Nom_Prin *
                    annual_spread_rate / 365 + det_Dyna_Nom_Prin * base_rate / 365, 0)
    
            -- 期权：年化价差逐日算；绝对基准只在开始日算。
            WHEN info_Busi_Type = 'OPTION' and spread_mode = 'ANNUALIZED' and base_mode = 'ABSOLUTE'
                THEN IF(det_busi_date BETWEEN info_Strt_Pric_Date AND income_end_date, det_Dyna_Nom_Prin *
                    annual_spread_rate / 365, 0) + IF(det_busi_date = info_Strt_Pric_Date, info_Init_Nom_Prin *
                    base_rate, 0)
    
            -- 期权：绝对价差只在开始日算；年化基准逐日算。
            WHEN info_Busi_Type = 'OPTION' and spread_mode = 'ABSOLUTE' and base_mode = 'ANNUALIZED'
                THEN IF(det_busi_date = info_Strt_Pric_Date, info_Init_Nom_Prin * absolute_spread_rate, 0) +
                    IF(det_busi_date BETWEEN info_Strt_Pric_Date AND income_end_date, det_Dyna_Nom_Prin * base_rate
                    / 365, 0)
    
            -- 期权：价差、基准都只在开始日算。
            WHEN info_Busi_Type = 'OPTION' and spread_mode = 'ABSOLUTE' and base_mode = 'ABSOLUTE'
                THEN IF(det_busi_date = info_Strt_Pric_Date, info_Init_Nom_Prin * absolute_spread_rate, 0) +
                    IF(det_busi_date = info_Strt_Pric_Date, info_Init_Nom_Prin * base_rate, 0)
    
            -- 普通互换：年化 + 年化。
            WHEN info_Busi_Type = 'TRS' and spread_mode = 'ANNUALIZED' and base_mode = 'ANNUALIZED'
                THEN IF(det_busi_date BETWEEN info_Strt_Pric_Date AND income_end_date, det_Dyna_Nom_Prin *
                    annual_spread_rate / 365 + det_Dyna_Nom_Prin * base_rate / 365, 0)
    
            -- 普通互换：年化 + 绝对。
            WHEN info_Busi_Type = 'TRS' and spread_mode = 'ANNUALIZED' and base_mode = 'ABSOLUTE'
                THEN IF(det_busi_date BETWEEN info_Strt_Pric_Date AND income_end_date, det_Dyna_Nom_Prin *
                    annual_spread_rate / 365, 0) + IF(det_busi_date = info_Strt_Pric_Date, info_Init_Nom_Prin *
                    base_rate, 0)
    
            -- 普通互换：绝对 + 年化。
            WHEN info_Busi_Type = 'TRS' and spread_mode = 'ABSOLUTE' and base_mode = 'ANNUALIZED'
                THEN IF(det_busi_date = info_Strt_Pric_Date, info_Init_Nom_Prin * absolute_spread_rate, 0) +
                    IF(det_busi_date BETWEEN info_Strt_Pric_Date AND income_end_date, det_Dyna_Nom_Prin * base_rate
                    / 365, 0)
    
            -- 普通互换：绝对 + 绝对。
            WHEN info_Busi_Type = 'TRS' and spread_mode = 'ABSOLUTE' and base_mode = 'ABSOLUTE'
                THEN IF(det_busi_date = info_Strt_Pric_Date, info_Init_Nom_Prin * absolute_spread_rate, 0) +
                    IF(det_busi_date = info_Strt_Pric_Date, info_Init_Nom_Prin * base_rate, 0)
        END AS ordinary_daily_income
    FROM contract_day_inputs inputs
)

,
/*
输入：05带普通公式候选值的逐日行；输出：raw_daily_income。
本模块是原始收入的最终选择点：特殊业务优先；否则取ordinary_daily_income。
尚未做期权保底、金仕达系统费用分摊，也尚未按人员分配。

本金累计窗口在04完成全部连接、机构筛选后才计算，保持原SQL位置。
Accum_Absl_Nom_Prin在原SQL也累计动态本金，并非对Absl_Nom_Prin求和；不改口径。

特殊公式中的来源：
  info_Ddct_Ptrn = 抵扣模式；info_Init_Marg_Prop = 初始保证金比例
  info_Base_Marg_Rate = 基础保证金率；info_Marg_Agt_Id = 保证金合约编号
  det_Inta / det_Trd_Cms / det_Trd_Cms_Cost / det_Fnd_Cost = 107491的利息 / 交易收入 / 交易成本 / 用资成本源字段
  cc_capital_cost = 类型资金成本参数（03→04），不是另一个当天现金支出
*/
raw_daily_income AS (
    SELECT
    
        -- 合约、客户与标的
        info_Agt_Id AS Agt_Id,
        info_Busi_Type AS Busi_Type,
        info_Cutp_Pty_Id AS Cutp_Pty_Id,
        info_Cutp_Pty_Shor_Name AS Cutp_Pty_Shor_Name,
        info_Cutp_Pty_Full_Name AS Cutp_Pty_Full_Name,
        info_Sign_Prd_Name AS Sign_Prd_Name,
        info_Contr_Type_Cd AS Contr_Type_Cd,
        info_Contr_Type_Desc AS Contr_Type_Desc,
        info_Src_Contr_Type AS Src_Contr_Type,
        info_Src_Contr_Type_Desc AS Src_Contr_Type_Desc,
        info_Src_Sub_Contr_Type AS Src_Sub_Contr_Type,
        info_Src_Sub_Contr_Type_Desc AS Src_Sub_Contr_Type_Desc,
        '' as Undrl_Ins_Id,
        info_Undrl_Wd_Cd AS Undrl_Wd_Cd,
        info_Undrl_Name AS Undrl_Name,
        info_Undrl_Type AS Undrl_Type,
        info_Src_Undrl_Type AS Src_Undrl_Type,
    
        -- 展示的价差、基准：仍保留原来的空串规则，与计算补0分开。
        IF(coalesce(s_sp_Spread_Calculation, c_sp_Spread_Calculation) = 'ANNUALIZED' ,
            coalesce(s_sp_Annualized_Spread, c_sp_Annualized_Spread), '' ) AS Annu_Sprd,
        IF(coalesce(s_sp_Spread_Calculation, c_sp_Spread_Calculation) = 'ABSOLUTE' , coalesce(s_sp_Absolute_Spread,
            c_sp_Absolute_Spread), '' ) AS Absl_Sprd,
        IF(base_mode = 'ANNUALIZED' , coalesce(s_ba_BASE_AWARD_RATE, c_ba_BASE_AWARD_RATE), '' ) AS Annu_Base,
        IF(base_mode = 'ABSOLUTE' , coalesce(s_ba_BASE_AWARD_RATE, c_ba_BASE_AWARD_RATE), '' ) AS Absl_Base,
    
        -- 本金及按日累计
        info_Init_Nom_Prin AS Init_Nom_Prin,
        coalesce(det_Dyna_Nom_Prin, 0) as Dyna_Nom_Prin,
        sum(if(det_busi_date BETWEEN info_Strt_Pric_Date AND income_end_date, coalesce(det_Dyna_Nom_Prin, 0),0))
            over(partition by info_Agt_Id,info_Contr_Type_Cd order by det_busi_date) as Accum_Dyna_Nom_Prin,
        if(info_grp_id = '01' , det_Dyna_Nom_Prin, 0) as Absl_Nom_Prin,
        sum(if(det_busi_date BETWEEN info_Strt_Pric_Date AND income_end_date, coalesce(det_Dyna_Nom_Prin, 0),0))
            over(partition by info_Agt_Id,info_Contr_Type_Cd order by det_busi_date) as Accum_Absl_Nom_Prin,
    
        -- 原始当日收入：严格保留特殊业务优先级。
        CASE
                -- 气囊且抵扣：收入为0。
                WHEN info_Src_Contr_Type in ('AIRBAGX','AIRBAGM','AIRBAGL') and info_Ddct_Ptrn = 'DEDUCTION'
                    THEN 0
        
                -- 气囊、非抵扣且无保证金合约：按融资比例、费率和成本算。
                WHEN info_Src_Contr_Type in ('AIRBAGX','AIRBAGM','AIRBAGL') and coalesce(info_Ddct_Ptrn,'') !=
                    'DEDUCTION' and coalesce(info_Marg_Agt_Id,'') = ''
                    THEN det_Dyna_Nom_Prin * (1 - info_Init_Marg_Prop) * (det_fee_rate/1.06 - cc_capital_cost) / 365 *
                        0.3
        
                -- 气囊、非抵扣且有关联保证金合约：使用基础保证金率调整。
                WHEN info_Src_Contr_Type in ('AIRBAGX','AIRBAGM','AIRBAGL') and coalesce(info_Ddct_Ptrn,'') !=
                    'DEDUCTION' and coalesce(info_Marg_Agt_Id,'') != ''
                    THEN det_Dyna_Nom_Prin * (1 - info_Base_Marg_Rate) * (det_fee_rate*(1 - info_Init_Marg_Prop)/(1 -
                        info_Base_Marg_Rate)/1.06 - cc_capital_cost) /365 *0.3
        
                -- 长期持有互换有关联保证金合约：收入为0。
                WHEN info_Src_Contr_Type = 'LONG_HOLD_SWAP' and coalesce(info_Marg_Agt_Id,'') != ''
                    THEN 0
        
                -- 金仕达：利息折算 + 交易收入 - 交易成本 - 用资金额对应成本，再乘50%。
                WHEN info_Contr_Type_Cd = 'TRS_KINGSTAR_SWAP'
                    THEN (det_Inta * 0.94 + det_Trd_Cms - det_Trd_Cms_Cost - det_Fnd_Cost * cc_capital_cost/365) * 0.5
                -- 不属于以上特殊业务，才使用05算出的普通公式。
                ELSE ordinary_daily_income
            END AS Curr_Prvs_Sales_Income,
    
        -- 日期、状态及人员资料
        info_Strt_Pric_Date AS Strt_Pric_Date,
        income_end_date as End_Pric_Date,
        info_Strt_Pric_Date as Accrued_Strt_Date,
        income_end_date as Accrued_End_Date,
        info_Early_Term_Date AS Early_Term_Date,
        info_Earn_Pymt_Date AS Earn_Pymt_Date,
        info_Agt_Stat_Cd AS Agt_Stat_Cd,
        m_Main_Oper_User_Id AS Main_Oper_User_Id,
        m_Main_Oper_Name AS Main_Oper_Name,
        m_Main_Oper_Emp_Id AS Main_Oper_Emp_Id,
        m_Intro_Oper_User_Id AS Intro_Oper_User_Id,
        m_Intro_Oper_Name AS Intro_Oper_Name,
        m_Intro_Oper_Emp_Id AS Intro_Oper_Emp_Id,
        m_Inr_Org_Id_1 as Intro_Inr_Org_Id_1,
        m_Inr_Org_Name_1 as Intro_Inr_Org_Name_1,
        m_Div_Org_Id_1 AS Div_Org_Id_1,
        m_Div_Org_Name_1 AS Div_Org_Name_1,
        m_Cust_Mngr_User_Id_1 AS Cust_Mngr_User_Id_1,
        m_Cust_Mngr_Name_1 AS Cust_Mngr_Name_1,
        m_Cust_Mngr_Emp_Id_1 AS Cust_Mngr_Emp_Id_1,
        m_Allo_Prop_1 AS Allo_Prop_1,
        m_Inr_Org_Id_2 as Intro_Inr_Org_Id_2,
        m_Inr_Org_Name_2 as Intro_Inr_Org_Name_2,
        m_Div_Org_Id_2 AS Div_Org_Id_2,
        m_Div_Org_Name_2 AS Div_Org_Name_2,
        m_Cust_Mngr_User_Id_2 AS Cust_Mngr_User_Id_2,
        m_Cust_Mngr_Name_2 AS Cust_Mngr_Name_2,
        m_Cust_Mngr_Emp_Id_2 AS Cust_Mngr_Emp_Id_2,
        m_Allo_Prop_2 AS Allo_Prop_2,
        m_Inr_Org_Id_3 as Intro_Inr_Org_Id_3,
        m_Inr_Org_Name_3 as Intro_Inr_Org_Name_3,
        m_Div_Org_Id_3 AS Div_Org_Id_3,
        m_Div_Org_Name_3 AS Div_Org_Name_3,
        m_Cust_Mngr_User_Id_3 AS Cust_Mngr_User_Id_3,
        m_Cust_Mngr_Name_3 AS Cust_Mngr_Name_3,
        m_Cust_Mngr_Emp_Id_3 AS Cust_Mngr_Emp_Id_3,
    
        -- 计提日与附加资料
        m_Allo_Prop_3 AS Allo_Prop_3,
        det_busi_date as Accrued_Date,
        coalesce(s_ba_Additional_Reward,0) as Adtnl_Rwd,
        det_fee_rate AS fee_rate,
        1 - info_Init_Marg_Prop as Fin_Rati,
        info_Intr_Marg AS Intr_Marg,
        info_Res_Flag AS Res_Flag,
        info_Opt_Fee_Rate AS Opt_Fee_Rate,
        if(info_Ex_Rate_Model in
            ('SHENZHEN_HONGKONG_STOCK_CONNECT','SHANGHAI_HONGKONG_STOCK_CONNECT'),info_Ex_Rate_Model,null) as
            Ex_Rate_Model,
        if(nvl(m_Cust_Mngr_Emp_Stat_Desc_1, '' ) = '' , m_Cust_Mngr_Emp_Stat_Desc_1, if(m_Cust_Mngr_Emp_Stat_Desc_1
            = '在职' , '是' , '否' )) as Cust_Mngr_Is_Actv_1,
        if(nvl(m_Cust_Mngr_Emp_Stat_Desc_2, '' ) = '' , m_Cust_Mngr_Emp_Stat_Desc_2, if(m_Cust_Mngr_Emp_Stat_Desc_2
            = '在职' , '是' , '否' )) as Cust_Mngr_Is_Actv_2,
        if(nvl(m_Cust_Mngr_Emp_Stat_Desc_3, '' ) = '' , m_Cust_Mngr_Emp_Stat_Desc_3, if(m_Cust_Mngr_Emp_Stat_Desc_3
            = '在职' , '是' , '否' )) as Cust_Mngr_Is_Actv_3
    FROM ordinary_income_rows inputs
)

,
/*
输入：raw_daily_income（原始收入）+ paid_reward_by_contract（已发奖励汇总）。
输出：adjusted_daily_income；新增Curr_Prvs_Sales_Income_n，原始收入列仍保留。

两条调整路：
  金仕达 → 同类同日原始收入占比 × 150万 / 365 × 50%，从该行收入扣除。
  个股/指数ETF期权 → 仅结束日检查累计原始收入是否低于初始本金×0.1%。
    满足时，当天改为：保底总额 - 已发奖励 - 截止日后整段原始收入 + 当天原始收入。
    最后一项是加回当天，避免当天被减两次。
其他行不调整。它不是“每天至少赚0.1%”。

注意两类累计：触发条件是截至该日的窗口；扣减项是合约整段窗口（没有ORDER BY）。
原SQL的默认截止日2025-03-31、结算期下限202502都原样保留。
*/
-- T98_OTC_DERI_UNDRL_INCOME_RWD_SUM：奖励汇总输入；按当前加工日取历史结算期记录。
paid_reward_by_contract AS (
    -- 累计实发收入
    select
        Contr_Id,
        sum(Dev_Dept_Rwd) as Dev_Dept_Rwd,
        max(Sett_End_Date) as Qtr_End_Date
    from PDATA_N.T98_OTC_DERI_UNDRL_INCOME_RWD_SUM
    where busi_date = '${yyyy-MM-dd}' and src_tbl = 'ODATA_N_OIS.G_CROSS_INCOME_REWARD'
        and Sett_Time >= '202502' and Sett_Time < concat('${yyyy}0', quarter('${yyyy-MM-dd}'))
    group by Contr_Id
)
,
adjusted_daily_income AS (
    select T.*,
        case
            --金仕达分摊150万的系统费用
            when Contr_Type_Cd = 'TRS_KINGSTAR_SWAP' then Curr_Prvs_Sales_Income - Curr_Prvs_Sales_Income/sum(Curr_Prvs_Sales_Income) over(partition by Contr_Type_Cd, Accrued_Date) * 1500000 / 365 * 0.5
            -- 个股期权、指数/ETF期权考虑保底，保底系数0.1%
            -- 累计实发+当季应发 < 保底应发，取保底应发-累计实发
            when Contr_Type_Cd in('OPTION_STOCK', 'OPTION_IDX_ETF')
                and End_Pric_Date = Accrued_Date
                and coalesce(sum(Curr_Prvs_Sales_Income) over(partition by Agt_Id order by Accrued_Date),0) < Init_Nom_Prin * 0.001
                    then Init_Nom_Prin * 0.001 - coalesce(actl.Dev_Dept_Rwd, 0) - sum(if(Accrued_Date > coalesce(actl.Qtr_End_Date,'2025-03-31'), Curr_Prvs_Sales_Income,0)) over(partition by Agt_Id) + Curr_Prvs_Sales_Income
            else Curr_Prvs_Sales_Income
            end as Curr_Prvs_Sales_Income_n
    from raw_daily_income T
    left joinpaid_reward_by_contract actl
    on t.Agt_Id = actl.Contr_Id and actl.Qtr_End_Date < t.End_Pric_Date
)

,
/*
输入：07调整后的当日收入；输出：allocated_daily_report。
两种分配不是一回事：
  本金：有引入经办人 → 主办40%、引入60%；否则主办100%、引入0%。
  收入：调整后收入 × Allo_Prop_1/2/3（经营关系中的三个客户经理分配比例）。
不把40/60套到收入，也不在这里把三个比例重新归一化。

累计使用调整后的收入；窗口按合约+合约类型、计提日排序。
保留原default.gfgreatest调用；未在生产引擎验证其NULL/类型细节。
Accrued_Date是收入归属日；末尾busi_date是这次加工日，不要混用。
*/
allocated_daily_report AS (
    SELECT
    
        -- 合约及参数展示
        Agt_Id,
        Busi_Type,
        Cutp_Pty_Id,
        Cutp_Pty_Shor_Name,
        Cutp_Pty_Full_Name,
        Sign_Prd_Name,
        Contr_Type_Cd,
        Contr_Type_Desc,
        Src_Contr_Type,
        Src_Contr_Type_Desc,
        Src_Sub_Contr_Type,
        Src_Sub_Contr_Type_Desc,
        Undrl_Ins_Id,
        Undrl_Wd_Cd,
        Undrl_Name,
        Undrl_Type,
        Src_Undrl_Type,
        Annu_Sprd,
        Absl_Sprd,
        Annu_Base,
        Absl_Base,
    
        -- 本金：主办/引入分配，与客户经理收入分配不同。
        Init_Nom_Prin,
        IF(Intro_Oper_User_Id IS NULL or Intro_Oper_User_Id = '' , Init_Nom_Prin * 1, Init_Nom_Prin * 0.4) AS
            Init_Nom_Prin_Main,
        IF(Intro_Oper_User_Id IS NULL or Intro_Oper_User_Id = '' , Init_Nom_Prin * 0, Init_Nom_Prin * 0.6) AS
            Init_Nom_Prin_Intro,
        Dyna_Nom_Prin,
        IF(Intro_Oper_User_Id IS NULL or Intro_Oper_User_Id = '' , Dyna_Nom_Prin * 1, Dyna_Nom_Prin * 0.4) AS
            Dyna_Nom_Prin_Main,
        IF(Intro_Oper_User_Id IS NULL or Intro_Oper_User_Id = '' , Dyna_Nom_Prin * 0, Dyna_Nom_Prin * 0.6) AS
            Dyna_Nom_Prin_Intro,
        Accum_Dyna_Nom_Prin,
        Absl_Nom_Prin,
        IF(Intro_Oper_User_Id IS NULL or Intro_Oper_User_Id = '' , Absl_Nom_Prin * 1, Absl_Nom_Prin * 0.4) AS
            Absl_Nom_Prin_Main,
        IF(Intro_Oper_User_Id IS NULL or Intro_Oper_User_Id = '' , Absl_Nom_Prin * 0, Absl_Nom_Prin * 0.6) AS
            Absl_Nom_Prin_Intro,
        Accum_Absl_Nom_Prin,
    
        -- 调整后当日收入与三个客户经理份额
        Curr_Prvs_Sales_Income_n as Curr_Prvs_Sales_Income,
        Curr_Prvs_Sales_Income_n * Allo_Prop_1 AS Curr_Prvs_Sales_Income_1,
        Curr_Prvs_Sales_Income_n * Allo_Prop_2 AS Curr_Prvs_Sales_Income_2,
        Curr_Prvs_Sales_Income_n * Allo_Prop_3 AS Curr_Prvs_Sales_Income_3,
        Strt_Pric_Date,
        End_Pric_Date,
        Strt_Pric_Date as Accrued_Strt_Date,
        Accrued_End_Date,
        Earn_Pymt_Date,
    
        -- 计提天数包含开始日，结束后封顶到结束日。
        datediff(if(Accrued_Date > End_Pric_Date, End_Pric_Date, Accrued_Date), Strt_Pric_Date) + 1 AS Actl_Days,
        IF(Early_Term_Date IS NULL OR Early_Term_Date = '' , '0' , '1' ) AS Is_Preterm_Flag,
        Early_Term_Date,
        Agt_Stat_Cd,
        Main_Oper_User_Id,
        Main_Oper_Name,
        Main_Oper_Emp_Id,
        Intro_Oper_User_Id,
        Intro_Oper_Name,
        Intro_Oper_Emp_Id,
        Intro_Inr_Org_Id_1,
        Intro_Inr_Org_Name_1,
        Div_Org_Id_1,
        Div_Org_Name_1,
        Cust_Mngr_User_Id_1,
        Cust_Mngr_Name_1,
        Cust_Mngr_Emp_Id_1,
        Allo_Prop_1,
        Intro_Inr_Org_Id_2,
        Intro_Inr_Org_Name_2,
        Div_Org_Id_2,
        Div_Org_Name_2,
        Cust_Mngr_User_Id_2,
        Cust_Mngr_Name_2,
        Cust_Mngr_Emp_Id_2,
        Allo_Prop_2,
        Intro_Inr_Org_Id_3,
        Intro_Inr_Org_Name_3,
        Div_Org_Id_3,
        Div_Org_Name_3,
        Cust_Mngr_User_Id_3,
        Cust_Mngr_Name_3,
        Cust_Mngr_Emp_Id_3,
        Allo_Prop_3,
        Accrued_Date,
    
        -- 按计提日累计：采用调整后收入，不是06的原始收入。
        from_unixtime(unix_timestamp(),'yyyy-MM-dd HH:mm:ss') AS Data_Time,
        default.gfgreatest(sum(coalesce(Curr_Prvs_Sales_Income_n, 0)) over(partition by agt_id,Contr_Type_Cd order
            by accrued_date),0) as Accum_prvs_sales_income,
        default.gfgreatest(sum(coalesce(Curr_Prvs_Sales_Income_n * Allo_Prop_1, 0)) over(partition by
            agt_id,Contr_Type_Cd order by accrued_date),0) as Accum_prvs_sales_income_1,
        default.gfgreatest(sum(coalesce(Curr_Prvs_Sales_Income_n * Allo_Prop_2, 0)) over(partition by
            agt_id,Contr_Type_Cd order by accrued_date),0) as Accum_prvs_sales_income_2,
    
        -- 附加奖励只带出展示，本段没有再加到收入中。
        default.gfgreatest(sum(coalesce(Curr_Prvs_Sales_Income_n * Allo_Prop_3, 0)) over(partition by
            agt_id,Contr_Type_Cd order by accrued_date),0) as Accum_prvs_sales_income_3,
        Adtnl_Rwd,
        if(Src_Contr_Type in ('AIRBAGX','AIRBAGM','AIRBAGL'), fee_rate, null) as fee_rate,
        if(Src_Contr_Type in ('AIRBAGX','AIRBAGM','AIRBAGL'), Fin_Rati, null) as Fin_Rati,
        Intr_Marg,
        Res_Flag,
        Opt_Fee_Rate,
        Ex_Rate_Model,
        Cust_Mngr_Is_Actv_1,
        Cust_Mngr_Is_Actv_2,
        Cust_Mngr_Is_Actv_3,
        '${yyyy-MM-dd}' as busi_date
    FROM adjusted_daily_income X
)


/*
输入：08的allocated_daily_report；输出：原118141的92列，字段顺序不变。
这里主要做原有String转换，不新增业务计算，也不再筛选计提日。
原任务快照仅提供SELECT；下游目标为dm_otc_n.otc_sale_daily_rpt。
*/
SELECT
    CAST( Agt_Id AS String ) Agt_Id,
    CAST( Busi_Type AS String ) Busi_Type,
    CAST( Cutp_Pty_Id AS String ) Cutp_Pty_Id,
    CAST( Cutp_Pty_Shor_Name AS String ) Cutp_Pty_Shor_Name,
    CAST( Cutp_Pty_Full_Name AS String ) Cutp_Pty_Full_Name,
    CAST( Sign_Prd_Name AS String ) Sign_Prd_Name,
    CAST( Contr_Type_Cd AS String ) Contr_Type_Cd,
    CAST( Contr_Type_Desc AS String ) Contr_Type_Desc,
    CAST( Src_Contr_Type AS String ) Src_Contr_Type,
    CAST( Src_Contr_Type_Desc AS String ) Src_Contr_Type_Desc,
    CAST( Src_Sub_Contr_Type AS String ) Src_Sub_Contr_Type,
    CAST( Src_Sub_Contr_Type_Desc AS String ) Src_Sub_Contr_Type_Desc,
    CAST( Undrl_Ins_Id AS String ) Undrl_Ins_Id,
    CAST( Undrl_Wd_Cd AS String ) Undrl_Wd_Cd,
    CAST( Undrl_Name AS String ) Undrl_Name,
    CAST( Undrl_Type AS String ) Undrl_Type,
    CAST( Src_Undrl_Type AS String ) Src_Undrl_Type,
    CAST( Annu_Sprd AS String ) Annu_Sprd,
    CAST( Absl_Sprd AS String ) Absl_Sprd,
    CAST( Annu_Base AS String ) Annu_Base,
    CAST( Absl_Base AS String ) Absl_Base,
    CAST( Init_Nom_Prin AS String ) Init_Nom_Prin,
    CAST( Init_Nom_Prin_Main AS String ) Init_Nom_Prin_Main,
    CAST( Init_Nom_Prin_Intro AS String ) Init_Nom_Prin_Intro,
    CAST( Dyna_Nom_Prin AS String ) Dyna_Nom_Prin,
    CAST( Dyna_Nom_Prin_Main AS String ) Dyna_Nom_Prin_Main,
    CAST( Dyna_Nom_Prin_Intro AS String ) Dyna_Nom_Prin_Intro,
    CAST( Accum_Dyna_Nom_Prin AS String ) Accum_Dyna_Nom_Prin,
    CAST( Absl_Nom_Prin AS String ) Absl_Nom_Prin,
    CAST( Absl_Nom_Prin_Main AS String ) Absl_Nom_Prin_Main,
    CAST( Absl_Nom_Prin_Intro AS String ) Absl_Nom_Prin_Intro,
    CAST( Accum_Absl_Nom_Prin AS String ) Accum_Absl_Nom_Prin,
    CAST( Curr_Prvs_Sales_Income AS String ) Curr_Prvs_Sales_Income,
    CAST( Curr_Prvs_Sales_Income_1 AS String ) Curr_Prvs_Sales_Income_1,
    CAST( Curr_Prvs_Sales_Income_2 AS String ) Curr_Prvs_Sales_Income_2,
    CAST( Curr_Prvs_Sales_Income_3 AS String ) Curr_Prvs_Sales_Income_3,
    CAST( Strt_Pric_Date AS String ) Strt_Pric_Date,
    CAST( End_Pric_Date AS String ) End_Pric_Date,
    CAST( Accrued_Strt_Date AS String ) Accrued_Strt_Date,
    CAST( Accrued_End_Date AS String ) Accrued_End_Date,
    CAST( Earn_Pymt_Date AS String ) Earn_Pymt_Date,
    CAST( Actl_Days AS String ) Actl_Days,
    CAST( Is_Preterm_Flag AS String ) Is_Preterm_Flag,
    CAST( Early_Term_Date AS String ) Early_Term_Date,
    CAST( Agt_Stat_Cd AS String ) Agt_Stat_Cd,
    CAST( Main_Oper_User_Id AS String ) Main_Oper_User_Id,
    CAST( Main_Oper_Name AS String ) Main_Oper_Name,
    CAST( Main_Oper_Emp_Id AS String ) Main_Oper_Emp_Id,
    CAST( Intro_Oper_User_Id AS String ) Intro_Oper_User_Id,
    CAST( Intro_Oper_Name AS String ) Intro_Oper_Name,
    CAST( Intro_Oper_Emp_Id AS String ) Intro_Oper_Emp_Id,
    CAST( Intro_Inr_Org_Id_1 AS String ) Intro_Inr_Org_Id_1,
    CAST( Intro_Inr_Org_Name_1 AS String ) Intro_Inr_Org_Name_1,
    CAST( Div_Org_Id_1 AS String ) Div_Org_Id_1,
    CAST( Div_Org_Name_1 AS String ) Div_Org_Name_1,
    CAST( Cust_Mngr_User_Id_1 AS String ) Cust_Mngr_User_Id_1,
    CAST( Cust_Mngr_Name_1 AS String ) Cust_Mngr_Name_1,
    CAST( Cust_Mngr_Emp_Id_1 AS String ) Cust_Mngr_Emp_Id_1,
    CAST( Allo_Prop_1 AS String ) Allo_Prop_1,
    CAST( Intro_Inr_Org_Id_2 AS String ) Intro_Inr_Org_Id_2,
    CAST( Intro_Inr_Org_Name_2 AS String ) Intro_Inr_Org_Name_2,
    CAST( Div_Org_Id_2 AS String ) Div_Org_Id_2,
    CAST( Div_Org_Name_2 AS String ) Div_Org_Name_2,
    CAST( Cust_Mngr_User_Id_2 AS String ) Cust_Mngr_User_Id_2,
    CAST( Cust_Mngr_Name_2 AS String ) Cust_Mngr_Name_2,
    CAST( Cust_Mngr_Emp_Id_2 AS String ) Cust_Mngr_Emp_Id_2,
    CAST( Allo_Prop_2 AS String ) Allo_Prop_2,
    CAST( Intro_Inr_Org_Id_3 AS String ) Intro_Inr_Org_Id_3,
    CAST( Intro_Inr_Org_Name_3 AS String ) Intro_Inr_Org_Name_3,
    CAST( Div_Org_Id_3 AS String ) Div_Org_Id_3,
    CAST( Div_Org_Name_3 AS String ) Div_Org_Name_3,
    CAST( Cust_Mngr_User_Id_3 AS String ) Cust_Mngr_User_Id_3,
    CAST( Cust_Mngr_Name_3 AS String ) Cust_Mngr_Name_3,
    CAST( Cust_Mngr_Emp_Id_3 AS String ) Cust_Mngr_Emp_Id_3,
    CAST( Allo_Prop_3 AS String ) Allo_Prop_3,
    CAST( Accrued_Date AS String ) Accrued_Date,
    CAST( Data_Time AS String ) Data_Time,
    CAST( Accum_prvs_sales_income AS String ) Accum_prvs_sales_income,
    CAST( Accum_prvs_sales_income_1 AS String ) Accum_prvs_sales_income_1,
    CAST( Accum_prvs_sales_income_2 AS String ) Accum_prvs_sales_income_2,
    CAST( Accum_prvs_sales_income_3 AS String ) Accum_prvs_sales_income_3,
    CAST( Adtnl_Rwd AS String ) Adtnl_Rwd,
    CAST( fee_rate AS String ) fee_rate,
    CAST( Fin_Rati AS String ) Fin_Rati,
    Intr_Marg,
    Res_Flag,
    Opt_Fee_Rate,
    Ex_Rate_Model,
    Cust_Mngr_Is_Actv_1,
    Cust_Mngr_Is_Actv_2,
    Cust_Mngr_Is_Actv_3,
    CAST( busi_date AS String ) busi_date
FROM allocated_daily_report castTable

