-- GENERATED by render.mjs; edit 00_主脚本.sql and 01–07 modules instead.
-- 105743 销售管理归属：阅读版入口，原SQL见 ../99_证据/105743-query.sql。
-- 要回答：一份合约带上哪三组介绍关系，以及哪些普通／内部／TIT经办角色？
-- 介绍关系带分配比例；经办角色另行选人。本任务不计算收入或本金分摊。
--
-- 第一段：介绍关系 → 01各自排序 + 02补人员机构 → 03横排成三组 → otc_div_temp
-- 第二段：04销售合约 + 上述合约级／客户级关系 → 07逐字段选择介绍关系
--                     + 05普通／内部经办 + 06TIT角色 → 同一行并列输出
--
-- 先读README中合约A1的贯穿例，再对照03和07；其余模块按来源需要回查。
-- 保留原SQL两次写入、字段顺序和取值规则；CTE只是当前语句内的命名输入。
-- @include不是Hive语法：用render.mjs生成完整SQL.sql后才能得到完整语句。

-- 第一段：中间表，没有显式分区；覆盖范围沿用原SQL。
set hive.merge.mapfiles=true ;
set hive.merge.mapredfiles=true;
set hive.merge.size.per.task=1073741824;
set hive.merge.smallfiles.avgsize=1073741824;
set hive.merge.orcfile.stripe.level=false;
set hive.input.format=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat;
set mapreduce.input.fileinputformat.split.maxsize=1073741824;
set mapreduce.input.fileinputformat.split.minsize=1073741824;
with
-- 01：把“谁介绍了客户／合约”整理成同一结构，并在各来源内部排名。
-- 输出一行仍是一条介绍关系，不是合约宽表；没有在这里截断到3条。
-- client_id=客户号，Contract_Code=合约号：本分支不用的身份填空串，不填NULL。
-- Introduction_Department=部门；Customer_Manager=开发人员／引入人；
-- Allocation_Proportion=分配比例（转double）；seq=本SQL重新计算的名次。
-- OIS两表的表名及上述中文字段释义来自【AI】元数据；香港表来自普通元数据。
-- OIS客户、OIS合约、香港客户先各自排名，再UNION ALL，不做跨来源重排。
-- 比例相同用人员编号排序；两项都相同没有额外决胜键。
-- 后续03_介绍关系横排按身份合组，因此同客户在两来源出现时可能同有seq=1。
introduction_ranked as (
    select
        client_id, -- 客户号
        '' as Contract_Code, -- 客户级关系不填合约号
        lpad(Introduction_Department,4,'0') as Introduction_Department, -- 部门号左补0到4位
        Customer_Manager, -- 开发人员，后续按OA账号查员工
        cast(Allocation_Proportion as double) as Allocation_Proportion, -- 分配比例
        row_number() over(partition by client_id order by cast(Allocation_Proportion as double) desc, Customer_Manager) as seq
    from odata_n_ois.o_counterparty_introduction -- 【AI】开发关系表（客户级）
    where busi_Date = '${data_day_str}' and Is_Deleted = 'N'
    union all
    select
        '' as client_id, -- 合约级关系不填客户号
        Contract_Code, -- 合约号
        lpad(Introduction_Department,4,'0') as Introduction_Department,
        Customer_Manager,
        cast(Allocation_Proportion as double) as Allocation_Proportion,
        row_number() over(partition by Contract_Code order by cast(Allocation_Proportion as double) desc, Customer_Manager) as seq
    from odata_n_ois.o_contract_introduction -- 【AI】合约开发关系分成表（合约级）
    where busi_Date = '${data_day_str}' and Is_Deleted = 'N'
    union all
    select
        client_id,
        '' as Contract_Code,
        lpad(department,4,'0') as Introduction_Department, -- 引入部门
        introductor as Customer_Manager, -- 引入人，统一成客户经理字段
        cast(Allocation_Proportion as double) as Allocation_Proportion,
        row_number() over(partition by client_id order by cast(Allocation_Proportion as double) desc, introductor) as seq
    from odata_n_oom.g_hk_counterparty_introduction -- 香港交易对手引入信息（客户级）
    where busi_Date = '${data_day_str}'
)

,
-- 02：介绍关系用到的人员与机构。别把“引入部门”当成“员工当前所属部门”。
-- A.Customer_Manager ──OA用户编号──> introduction_employee D：姓名／员工号／状态
-- A.Introduction_Department ──4位部门号──> oa_department org：部门名称
--                                         └──> branch_division dept：所属分公司
-- 分公司通过org再连接；不是直接拿A.Introduction_Department查dept。
-- D：PDATA_N.T98_ORG_EMP_BASE_INFO（T98_员工基本信息），参数日快照。
-- Emp_Id=员工编号；OA_User_Id=OA用户编号；Emp_Name=员工姓名；
-- Emp_Stat_Cd／Emp_Stat_Desc=员工状态代码／描述。未筛在职状态，也未去重。
introduction_employee as (
    SELECT Emp_Id, OA_User_Id, Emp_Name, Emp_Stat_Cd, Emp_Stat_Desc
    FROM PDATA_N.T98_ORG_EMP_BASE_INFO
    WHERE busi_date = '${data_day_str}'
),

-- org：pdata_n.T04_OAS_INR_ORG（OA内部机构）。
-- dept_no=部门编号；unif_org_id=统一机构编码；inr_org_lvl=内部机构层级；
-- dn的元数据释义为“DOMINO中的DN”，SQL取按“=”拆分的第2段作为ORGNAME。
-- 只保留指定来源表且dept_flag=1。部门号不为''用自身，否则截统一机构码第2～5位。
-- 每个处理后的部门号按层级升序取rk=1；同层级无额外排序键。
-- 注意原SQL没有busi_date条件，不能描述成“当日OA机构快照”。
oa_department as (
    select * from (
        select
            if(dept_no != '', dept_no, substring(unif_org_id,2,4)) as dept_no,
            split(dn,'=')[1] as ORGNAME,
            row_number() over(partition by if(dept_no != '', dept_no, substring(unif_org_id,2,4)) order by inr_org_lvl) as rk
        from pdata_n.T04_OAS_INR_ORG
        where src_tbl = 'ODATA_N_OAS.P_GF_DEPARTMENT' and dept_flag = '1'
        ) t
    where rk = 1
),

-- dept：PDATA_N.T98_ORG_BRCH_DIV_INFO（分支机构及所属分公司，每天一份快照）。
-- Inr_Org_Id=内部机构编号；Inr_Org_Name=内部机构简称；
-- Brch_Bel_Div_Org_Id／Name=营业部所属分公司编号／名称。
-- 保留原日期函数。先参数日+1再pretradedate(...,1)，不是直接参数日-1。
-- 本地函数目录仅查到内部Presto签名，不能据此确认此Hive UDF的交易日边界。
branch_division as (
    SELECT Inr_Org_Id, Inr_Org_Name, Brch_Bel_Div_Org_Id, Brch_Bel_Div_Org_Name
    FROM PDATA_N.T98_ORG_BRCH_DIV_INFO
    WHERE Busi_Date = default.pretradedate(date_add('${data_day_str}', 1), 1)
)


-- 03：把同一客户／合约的多行介绍关系，放进一行的第1、2、3组列。
-- 例：客户C1两行张三0.6、李四0.4 → C1一行：[张三0.6] [李四0.4] [空串0]。
-- 合约A1的关系另成一行；这里不把客户关系和合约关系合为一套，最终选择在07。
-- A来自01_介绍关系排序；D/org/dept来自02_人员与机构。
insert overwrite table otc_div_temp
select
    A.Contract_Code, -- 合约号；客户级关系填空串
    A.client_id, -- 客户号；合约级关系填空串
    -- 第1组：seq=1的关系提供值，其余行提供空串／0，再逐字段MAX合成一行。
    -- 下方分公司编号／名称分别回退到引入部门编号／OA名称；员工号NULL才回退OA号。
    max(case when A.seq = '1' then A.Introduction_Department else '' end) as Inr_Org_Id_1, -- 引入部门编号_1
    max(case when A.seq = '1' then org.ORGNAME else '' end) as Inr_Org_Name_1, -- 引入部门名称_1
    max(case when A.seq = '1' then coalesce(dept.Brch_Bel_Div_Org_Id,A.Introduction_Department) else '' end) as Div_Org_Id_1, -- 所属分公司编号_1
    max(case when A.seq = '1' then coalesce(dept.Brch_Bel_Div_Org_Name,org.ORGNAME) else '' end) as Div_Org_Name_1, -- 所属分公司名称_1
    max(case when A.seq = '1' then A.Customer_Manager else '' end) as Cust_Mngr_Id_1, -- 客户经理OA账号（源开发人员／引入人）_1
    max(case when A.seq = '1' then D.Emp_Name else '' end) as Cust_Mngr_Name_1, -- 客户经理姓名_1
    max(case when A.seq = '1' then COALESCE(D.Emp_Id, D.OA_User_Id, '') else '' end) as Cust_Mngr_Emp_Id_1, -- 客户经理员工编号_1
    max(case when A.seq = '1' then A.Allocation_Proportion else '0' end) as Allo_Prop_1, -- 分配比例_1

    -- 第2组：同一套公式，仅名次换为2；没有第2名时，已有关系行会贡献空串／0。
    max(case when A.seq = '2' then A.Introduction_Department else '' end) as Inr_Org_Id_2, -- 引入部门编号_2
    max(case when A.seq = '2' then org.ORGNAME else '' end) as Inr_Org_Name_2, -- 引入部门名称_2
    max(case when A.seq = '2' then coalesce(dept.Brch_Bel_Div_Org_Id,A.Introduction_Department) else '' end) as Div_Org_Id_2, -- 所属分公司编号_2
    max(case when A.seq = '2' then coalesce(dept.Brch_Bel_Div_Org_Name,org.ORGNAME) else '' end) as Div_Org_Name_2, -- 所属分公司名称_2
    max(case when A.seq = '2' then A.Customer_Manager else '' end) as Cust_Mngr_Id_2, -- 客户经理OA账号（源开发人员／引入人）_2
    max(case when A.seq = '2' then D.Emp_Name else '' end) as Cust_Mngr_Name_2, -- 客户经理姓名_2
    max(case when A.seq = '2' then COALESCE(D.Emp_Id, D.OA_User_Id, '') else '' end) as Cust_Mngr_Emp_Id_2, -- 客户经理员工编号_2
    max(case when A.seq = '2' then A.Allocation_Proportion else '0' end) as Allo_Prop_2, -- 分配比例_2

    -- 第3组：名次换为3。三组比例原样横排，不重新归一到1。
    max(case when A.seq = '3' then A.Introduction_Department else '' end) as Inr_Org_Id_3, -- 引入部门编号_3
    max(case when A.seq = '3' then org.ORGNAME else '' end) as Inr_Org_Name_3, -- 引入部门名称_3
    max(case when A.seq = '3' then coalesce(dept.Brch_Bel_Div_Org_Id,A.Introduction_Department) else '' end) as Div_Org_Id_3, -- 所属分公司编号_3
    max(case when A.seq = '3' then coalesce(dept.Brch_Bel_Div_Org_Name,org.ORGNAME) else '' end) as Div_Org_Name_3, -- 所属分公司名称_3
    max(case when A.seq = '3' then A.Customer_Manager else '' end) as Cust_Mngr_Id_3, -- 客户经理OA账号（源开发人员／引入人）_3
    max(case when A.seq = '3' then D.Emp_Name else '' end) as Cust_Mngr_Name_3, -- 客户经理姓名_3
    max(case when A.seq = '3' then COALESCE(D.Emp_Id, D.OA_User_Id, '') else '' end) as Cust_Mngr_Emp_Id_3, -- 客户经理员工编号_3
    max(case when A.seq = '3' then A.Allocation_Proportion else '0' end) as Allo_Prop_3, -- 分配比例_3

    -- 三组人员的员工状态：跟随对应名次，不用于筛除离职人员；列序沿用原表。
    max(case when A.seq = '1' then D.Emp_Stat_Cd else '' end) as Cust_Mngr_Emp_Stat_Cd_1, -- 客户经理员工状态代码_1
    max(case when A.seq = '1' then D.Emp_Stat_Desc else '' end) as Cust_Mngr_Emp_Stat_Desc_1, -- 客户经理员工状态描述_1
    max(case when A.seq = '2' then D.Emp_Stat_Cd else '' end) as Cust_Mngr_Emp_Stat_Cd_2, -- 客户经理员工状态代码_2
    max(case when A.seq = '2' then D.Emp_Stat_Desc else '' end) as Cust_Mngr_Emp_Stat_Desc_2, -- 客户经理员工状态描述_2
    max(case when A.seq = '3' then D.Emp_Stat_Cd else '' end) as Cust_Mngr_Emp_Stat_Cd_3, -- 客户经理员工状态代码_3
    max(case when A.seq = '3' then D.Emp_Stat_Desc else '' end) as Cust_Mngr_Emp_Stat_Desc_3 -- 客户经理员工状态描述_3
-- 补资料：账号 → 员工；引入部门号 → OA部门 → 分公司。缺资料仍保留源关系。
from introduction_ranked A
LEFT JOIN introduction_employee D
ON A.Customer_Manager = D.OA_User_Id
left join oa_department org
on A.Introduction_Department = org.dept_no
left join branch_division dept
on org.dept_no = dept.Inr_Org_Id
-- 客户级／合约级分别成行。没有来源系统分组：同客户跨来源的同名次可能竞争MAX。
-- MAX按每列独立取值，不是选择整条关系；超过第3名的行仍参与ELSE空串／0。
group by A.client_id, A.Contract_Code
;


-- 第二段：最终管理归属，按参数日写busi_date分区。
-- WITH只对当前语句生效；第二段所用员工资料在其自身模块重新定义。
set hive.merge.mapfiles=true ;
set hive.merge.mapredfiles=true;
set hive.merge.size.per.task=1073741824;
set hive.merge.smallfiles.avgsize=1073741824;
set hive.merge.orcfile.stripe.level=false;
set hive.input.format=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat;
set mapreduce.input.fileinputformat.split.maxsize=1073741824;
set mapreduce.input.fileinputformat.split.minsize=1073741824;
with
-- 04：第二段从哪些合约出发，以及客户关系用哪个客户号查。
-- info：PDATA_N.T98_OTC_DERI_COMP_SALE_INFO（场外衍生品合约销售收入基本信息表）。
-- Agt_Id=合约编号，Cutp_Pty_Id=交易对手客户编号，Inr_Seri_No=内部流水号，
-- Book_Bel_Dept=账簿所属部门；这些编号不是同一个键。
-- DISTINCT针对这四字段的组合，不保证Agt_Id唯一；不额外筛grp_id或合约状态。
sale_contract as (
    select distinct Agt_Id, Cutp_Pty_Id, Inr_Seri_No, Book_Bel_Dept
    from PDATA_N.T98_OTC_DERI_COMP_SALE_INFO
    where busi_Date = '${data_day_str}' and Book_Bel_Dept in ('OTC','OTC_HK')
),

-- ci：读取本任务第一段生成的otc_div_temp，选择合约级关系。
-- 07_管理归属输出中按ci.Contract_Code=info.Agt_Id连接，作为逐字段优先来源。
contract_introduction as (
    select * from otc_div_temp
    where Contract_Code != ''
),

-- fl：pdata_news_n.t02_fin_float_income_vchr_info（浮动收益凭证台账信息）。
-- comp_no=合约编号；prin_prtc_prop=本金保障比例；deal_cutp_no=交易对手编号。
-- 参数日、OIS来源、01分组且本金保障比例<1，才有资格参与客户号切换。
-- 07_管理归属输出还要求info.Cutp_Pty_Id='DEV1100100652'且fl匹配成功。
-- 条件满足时用fl.deal_cutp_no查cpi和cp；其为NULL也不回退到原客户号。
-- 输出Pty_Id仍是info.Cutp_Pty_Id，不会随关系查找键一起改写。
floating_voucher as (
    select * from pdata_news_n.t02_fin_float_income_vchr_info
    where busi_Date = '${data_day_str}' and src_id = 'OIS' and grp_id = '01'
        and cast(prin_prtc_prop as double) < 1
),

-- cpi：同一个otc_div_temp中的客户级关系，供合约字段为NULL时回退。
-- 此处只划分关系类型；客户号选择、JOIN和COALESCE都留在07_管理归属输出中。
customer_introduction as (
    select * from otc_div_temp
    where client_id != ''
)

,
-- 05：普通／内部经办角色。不要与三槽位客户经理或TIT角色混成一套关系。
-- cp：客户层面经办回退来源。OIS客户资料与香港引入资料UNION ALL，不做优先择一。
-- OIS o_otc_derivative_counterparty（衍生品交易对手维护表）：
-- client_id=客户编号，operator=经办人，introduction_operator=【AI】引入经办人；
-- 只取参数日且delete_flag='0'。这是字符0，不是介绍关系表的Is_Deleted='N'。
-- 香港g_hk_counterparty_introduction（香港交易对手引入信息）：
-- 这里用源表seq='1'，把introductor同时作为两个经办角色。
-- 与01_介绍关系排序重新按比例计算seq完全不同；这里没有读取源表operator字段。
customer_operator as (
    --关联经办人
    select client_id, operator, introduction_operator
    from odata_n_ois.o_otc_derivative_counterparty
    where busi_Date = '${data_day_str}' and delete_flag = '0'
    union all
    select client_id, introductor as operator, introductor as introduction_operator
    from odata_n_oom.g_hk_counterparty_introduction
    where busi_Date = '${data_day_str}' and seq = '1'
),

-- s_ba：odata_n_ois.o_contract_base_rate（【AI】合约基础系数表）。
-- CONTRACT_CODE=【AI】合约编号；operator_name→Main_Oper（主经办）；
-- introduction_operator_name→Intro_Oper（引入经办）。
-- 后者元数据写【AI】“主经办人”，与目标字段角色不一致；此处按实际SQL流向解释。
-- 07连接还限定info.Book_Bel_Dept='OTC'；香港合约不能从这一侧取得普通经办参数。
-- 两角色分别COALESCE到cp，NULL才回退；保留所有符合条件的参数行，不选“最新一条”。
contract_operator as (
    select *
    from odata_n_ois.o_contract_base_rate
    where busi_date = '${data_day_str}' and Is_Deleted = 'N'
),

-- is_ba：odata_n_ois.g_inr_contract_base_rate（内部销售合约基础系数表）。
-- operator_name=主经办人；introduction_operator_name=引入经办人。
-- 内部角色单独写Inr_Main_Oper／Inr_Intro_Oper；同样逐字段回退cp。
-- 与s_ba不同：07连接没有再限定Book_Bel_Dept='OTC'。
internal_contract_operator as (
    select *
    from odata_n_ois.g_inr_contract_base_rate
    where busi_date = '${data_day_str}' and Is_Deleted = 'N'
),

-- Main／Intro／i_Main／i_Intro共同读取这份员工资料，各自按选定OA账号连接。
-- PDATA_N.T98_ORG_EMP_BASE_INFO：Emp_Id员工编号，OA_User_Id OA用户编号，Emp_Name员工姓名。
-- 这些角色的输出Emp_Id直接取员工资料；没有介绍关系横排中的“员工号NULL回退OA号”。
-- 选择账号后若找不到员工，不会再试另一个账号；姓名和员工号保持NULL。
operator_employee as (
    SELECT Emp_Id, OA_User_Id, Emp_Name
    FROM PDATA_N.T98_ORG_EMP_BASE_INFO
    WHERE busi_date = '${data_day_str}'
)

,
-- 06：TIT系统记录的经办人／客户经理，独立于介绍关系与OIS经办参数。
-- tit：odata_n_tit.d_trd_otc_contr_props（【AI】交易-场外合约结构-其他属性表）。
-- key_otc_trade_id元数据为“trs合约id”；本SQL用它连接info.Inr_Seri_No（内部流水号），
-- 不是Agt_Id合约编号。property_name／value为属性名／属性值。
-- operator→Tit_Oper_User_Id；customerManager→Tit_Cust_Mngr_User_Id。
-- 一个交易键横排成一行；同属性多值时取MAX，不是按时间取最新，也没按有效状态选。
-- 不存在某属性时，另一属性行的ELSE ''可能使对应输出为空串。
tit_role as (
    select key_otc_trade_id,
        max(case when property_name = 'operator' then property_value else '' end) as Tit_Oper_User_Id,
        max(case when property_name = 'customerManager' then property_value else '' end) as Tit_Cust_Mngr_User_Id
    from odata_n_tit.d_trd_otc_contr_props
    where busi_Date = '${data_day_str}' and property_name in ('operator','customerManager')
    group by key_otc_trade_id
),

-- t_op／t_cm：按各自TIT账号查PDATA_N.T98_ORG_EMP_BASE_INFO（员工基本信息）。
-- Bel_Inr_Org_Id_Len4=所属内部机构编号_4位长度；Bel_Inr_Org_Name=所属内部机构名称。
-- 这里输出员工所属部门；三槽位的Inr_Org则来自源介绍关系的部门，是不同口径。
-- 员工参数日快照，不去重、不筛在职、不向OIS或客户关系回退。
tit_role_employee as (
    SELECT Emp_Id, OA_User_Id, Emp_Name, Bel_Inr_Org_Id_Len4, Bel_Inr_Org_Name
    FROM PDATA_N.T98_ORG_EMP_BASE_INFO
    WHERE busi_date = '${data_day_str}'
)


-- 07：以销售合约为起点，把两条独立的人员线并排写入管理归属表。
-- 介绍关系：合约号找ci、客户号找cpi → 每个字段优先ci，NULL才取cpi。
-- 经办角色：普通、内部各自选账号；TIT按内部流水号取属性 → 分别补员工资料。
-- info/ci/fl/cpi来自04_合约与客户关系；cp/s_ba/is_ba及经办员工来自05_普通与内部经办；
-- tit及其员工资料来自06_TIT经办与客户经理。输入实际表与关键字段注释见对应文件。
-- 例：A1合约关系只有王五1.0，则第2/3组已是空串/0，不会再用客户的李四补齐。
-- SELECT DISTINCT去重全部59个输出值，不是每合约只取一行；此任务不计算收入分摊。
insert overwrite table T98_OTC_COMP_MNG_RELA_INFO partition(busi_date = '${data_day_str}')
select distinct
    info.Agt_Id, -- 合约编号
    info.Cutp_Pty_Id as Pty_Id, -- 客户编号；保留销售基础原客户号
    -- 一、介绍关系第1组：机构、人员、比例分别选择；不是整套关系一起回退。
    coalesce(ci.Inr_Org_Id_1, cpi.Inr_Org_Id_1) as Inr_Org_Id_1, -- 引入部门编号_1
    coalesce(ci.Inr_Org_Name_1, cpi.Inr_Org_Name_1) as Inr_Org_Name_1, -- 引入部门名称_1
    coalesce(ci.Div_Org_Id_1, cpi.Div_Org_Id_1) as Div_Org_Id_1, -- 所属分公司编号_1
    coalesce(ci.Div_Org_Name_1, cpi.Div_Org_Name_1) as Div_Org_Name_1, -- 所属分公司名称_1
    coalesce(ci.Cust_Mngr_Id_1, cpi.Cust_Mngr_Id_1) as Cust_Mngr_User_Id_1, -- 客户经理OA账号_1
    coalesce(ci.Cust_Mngr_Name_1, cpi.Cust_Mngr_Name_1) as Cust_Mngr_Name_1, -- 客户经理姓名_1
    coalesce(ci.Cust_Mngr_Emp_Id_1, cpi.Cust_Mngr_Emp_Id_1) as Cust_Mngr_Emp_Id_1, -- 客户经理员工编号_1
    coalesce(ci.Allo_Prop_1, cpi.Allo_Prop_1) as Allo_Prop_1, -- 分配比例_1

    -- 介绍关系第2组：与第1组同样逐字段选择；空串、0都不触发回退。
    coalesce(ci.Inr_Org_Id_2, cpi.Inr_Org_Id_2) as Inr_Org_Id_2, -- 引入部门编号_2
    coalesce(ci.Inr_Org_Name_2, cpi.Inr_Org_Name_2) as Inr_Org_Name_2, -- 引入部门名称_2
    coalesce(ci.Div_Org_Id_2, cpi.Div_Org_Id_2) as Div_Org_Id_2, -- 所属分公司编号_2
    coalesce(ci.Div_Org_Name_2, cpi.Div_Org_Name_2) as Div_Org_Name_2, -- 所属分公司名称_2
    coalesce(ci.Cust_Mngr_Id_2, cpi.Cust_Mngr_Id_2) as Cust_Mngr_User_Id_2, -- 客户经理OA账号_2
    coalesce(ci.Cust_Mngr_Name_2, cpi.Cust_Mngr_Name_2) as Cust_Mngr_Name_2, -- 客户经理姓名_2
    coalesce(ci.Cust_Mngr_Emp_Id_2, cpi.Cust_Mngr_Emp_Id_2) as Cust_Mngr_Emp_Id_2, -- 客户经理员工编号_2
    coalesce(ci.Allo_Prop_2, cpi.Allo_Prop_2) as Allo_Prop_2, -- 分配比例_2

    -- 介绍关系第3组。
    coalesce(ci.Inr_Org_Id_3, cpi.Inr_Org_Id_3) as Inr_Org_Id_3, -- 引入部门编号_3
    coalesce(ci.Inr_Org_Name_3, cpi.Inr_Org_Name_3) as Inr_Org_Name_3, -- 引入部门名称_3
    coalesce(ci.Div_Org_Id_3, cpi.Div_Org_Id_3) as Div_Org_Id_3, -- 所属分公司编号_3
    coalesce(ci.Div_Org_Name_3, cpi.Div_Org_Name_3) as Div_Org_Name_3, -- 所属分公司名称_3
    coalesce(ci.Cust_Mngr_Id_3, cpi.Cust_Mngr_Id_3) as Cust_Mngr_User_Id_3, -- 客户经理OA账号_3
    coalesce(ci.Cust_Mngr_Name_3, cpi.Cust_Mngr_Name_3) as Cust_Mngr_Name_3, -- 客户经理姓名_3
    coalesce(ci.Cust_Mngr_Emp_Id_3, cpi.Cust_Mngr_Emp_Id_3) as Cust_Mngr_Emp_Id_3, -- 客户经理员工编号_3
    coalesce(ci.Allo_Prop_3, cpi.Allo_Prop_3) as Allo_Prop_3, -- 分配比例_3

    -- 二、普通经办：账号逐项回退客户资料；姓名／员工号按选定账号查员工表。
    coalesce(s_ba.operator_name, cp.operator) as Main_Oper_User_Id, -- 主经办人OA账号
    Main.Emp_Name as Main_Oper_Name, -- 主经办人姓名
    Main.Emp_Id as Main_Oper_Emp_Id, -- 主经办人员工编号
    coalesce(s_ba.introduction_operator_name, cp.introduction_operator) as Intro_Oper_User_Id, -- 引入经办人OA账号
    Intro.Emp_Name as Intro_Oper_Name, -- 引入经办人姓名
    Intro.Emp_Id as Intro_Oper_Emp_Id, -- 引入经办人员工编号

    -- 加工标记：不参与人员选择，保留原表字段位置。
    'TIT' AS Data_Src_Cd, -- 数据来源代码；原SQL固定TIT，不代表每个字段均来自TIT
    UPPER('${filename}') AS Task_Name, -- 任务名
    '${data_day_str}' AS Data_Etl_Date, -- 数据加载日期
    '${data_day_str}' AS Data_Upt_Date, -- 数据更新日期
    '${data_today}' AS Data_Time, -- 数据时间

    -- 三、内部经办：独立参数，不与普通经办合并。
    coalesce(is_ba.operator_name, cp.operator) as Inr_Main_Oper_User_Id, -- 内部主经办人OA账号
    i_Main.Emp_Name as Inr_Main_Oper_Name, -- 内部主经办人姓名
    i_Main.Emp_Id as Inr_Main_Oper_Emp_Id, -- 内部主经办人员工编号
    coalesce(is_ba.introduction_operator_name, cp.introduction_operator) as Inr_Intro_Oper_User_Id, -- 内部引入经办人OA账号
    i_Intro.Emp_Name as Inr_Intro_Oper_Name, -- 内部引入经办人姓名
    i_Intro.Emp_Id as Inr_Intro_Oper_Emp_Id, -- 内部引入经办人员工编号

    -- 四、TIT角色：账号来自合约属性，部门来自员工资料，无OIS回退。
    tit.Tit_Oper_User_Id, -- TIT经办人OA账号
    t_op.Emp_Name as Tit_Oper_Name, -- TIT经办人姓名
    t_op.Emp_Id as Tit_Oper_Emp_Id, -- TIT经办人员工编号
    t_op.Bel_Inr_Org_Id_Len4 as Tit_Oper_Inr_Org_Id, -- TIT经办人所属部门编号
    t_op.Bel_Inr_Org_Name as Tit_Oper_Inr_Org_Name, -- TIT经办人所属部门名称
    tit.Tit_Cust_Mngr_User_Id, -- TIT客户经理OA账号
    t_cm.Emp_Name as Tit_Cust_Mngr_Name, -- TIT客户经理姓名
    t_cm.Emp_Id as Tit_Cust_Mngr_Emp_Id, -- TIT客户经理员工编号
    t_cm.Bel_Inr_Org_Id_Len4 as Tit_Cust_Mngr_Inr_Org_Id, -- TIT客户经理所属部门编号
    t_cm.Bel_Inr_Org_Name as Tit_Cust_Mngr_Inr_Org_Name, -- TIT客户经理所属部门名称

    -- 五、三槽位员工状态（与前面客户经理同样逐字段选择，保持原字段顺序）。
    coalesce(ci.Cust_Mngr_Emp_Stat_Cd_1, cpi.Cust_Mngr_Emp_Stat_Cd_1) as Cust_Mngr_Emp_Stat_Cd_1, -- 客户经理员工状态代码_1
    coalesce(ci.Cust_Mngr_Emp_Stat_Desc_1, cpi.Cust_Mngr_Emp_Stat_Desc_1) as Cust_Mngr_Emp_Stat_Desc_1, -- 客户经理员工状态描述_1
    coalesce(ci.Cust_Mngr_Emp_Stat_Cd_2, cpi.Cust_Mngr_Emp_Stat_Cd_2) as Cust_Mngr_Emp_Stat_Cd_2, -- 客户经理员工状态代码_2
    coalesce(ci.Cust_Mngr_Emp_Stat_Desc_2, cpi.Cust_Mngr_Emp_Stat_Desc_2) as Cust_Mngr_Emp_Stat_Desc_2, -- 客户经理员工状态描述_2
    coalesce(ci.Cust_Mngr_Emp_Stat_Cd_3, cpi.Cust_Mngr_Emp_Stat_Cd_3) as Cust_Mngr_Emp_Stat_Cd_3, -- 客户经理员工状态代码_3
    coalesce(ci.Cust_Mngr_Emp_Stat_Desc_3, cpi.Cust_Mngr_Emp_Stat_Desc_3) as Cust_Mngr_Emp_Stat_Desc_3 -- 客户经理员工状态描述_3
-- 以下依次接上资料；均为LEFT JOIN，缺少某侧资料不直接剔除销售合约。
-- ① 介绍关系：Agt_Id找合约关系ci；客户号找客户关系cpi。
from sale_contract info
left join contract_introduction ci
on ci.Contract_Code = info.Agt_Id
left join floating_voucher fl
on fl.comp_no = info.Agt_Id
-- 满足特殊客户+凭证匹配才换查找键；Pty_Id输出不变，NULL替代键也不回原客户。
left join customer_introduction cpi
on cpi.client_id = if(info.Cutp_Pty_Id = 'DEV1100100652' and fl.comp_no is not null, fl.deal_cutp_no, info.Cutp_Pty_Id)

-- ② 客户经办cp：普通、内部经办共同使用的回退账号来源，不是介绍关系中的客户经理。
left join customer_operator cp
on cp.client_id = if(info.Cutp_Pty_Id = 'DEV1100100652' and fl.comp_no is not null, fl.deal_cutp_no, info.Cutp_Pty_Id)

-- ③ 普通经办：普通合约参数s_ba优先，NULL账号才回退cp，再查员工。
-- 参数仅匹配OTC；选中账号但查不到员工时，不会再换cp账号。
left join contract_operator s_ba
on info.agt_id = s_ba.CONTRACT_CODE and info.Book_Bel_Dept = 'OTC'
LEFT JOIN operator_employee Main
ON coalesce(s_ba.operator_name, cp.operator) = Main.OA_User_Id
LEFT JOIN operator_employee Intro
ON coalesce(s_ba.introduction_operator_name, cp.introduction_operator) = Intro.OA_User_Id

-- ④ 内部经办：内部参数is_ba独立选择，也可回退cp；无上面的OTC部门限制。
left join internal_contract_operator is_ba
on info.agt_id = is_ba.CONTRACT_CODE
LEFT JOIN operator_employee i_Main
ON coalesce(is_ba.operator_name, cp.operator) = i_Main.OA_User_Id
LEFT JOIN operator_employee i_Intro
ON coalesce(is_ba.introduction_operator_name, cp.introduction_operator) = i_Intro.OA_User_Id

-- ⑤ TIT角色：内部流水号Inr_Seri_No → 属性角色 → 员工；不按合约号，也不回退cp。
left join tit_role tit
on tit.key_otc_trade_id = info.Inr_Seri_No
left join tit_role_employee t_op
ON tit.Tit_Oper_User_Id = t_op.OA_User_Id
left join tit_role_employee t_cm
ON tit.Tit_Cust_Mngr_User_Id = t_cm.OA_User_Id
;

