// Reader-facing interpretations of the fixed 2026-09-06 investigation.
// Counts and task membership are loaded from the snapshot, never authored here.
import { loadTaskKnowledge } from "../knowledge/task-knowledge.mjs";

export const sharedKnowledge = {
  107491: await loadTaskKnowledge("107491"),
};
export const snapshotVersion =
  "4f61cee7134b1cba7686191bc0e8606ab28cc4d673935a50298e7ba792babf9a";
export const saleTable = "pdata_n.t98_otc_deri_comp_sale_info";
export const taskNotes = {
  144134: [
    "来源采集",
    "读取交易源并补采集时间；_p 表来自平台目标声明。",
    "没有证明它与后续 h15 读取属于同一次批次。",
  ],
  144141: [
    "批次与日期整理",
    "筛选 h15 批次，将原 busi_date 转为 grp_id，再写日期分区。",
    "已核代表 SQL；不能推广为所有 _pb 任务的规则。",
  ],
  41540: [
    "保证金参数合并",
    "合并 TITANS 与 OTC 两套保证金参数，并保留 sys_area_code。",
    "UNION ALL 不等于业务记录已经去重。",
  ],
  103941: [
    "互换合约规范入模",
    "补合约标识、属性、审核信息及代码转换，形成合约实体。",
    "与下游固定 SQL 日期不同，尚未确认运行批次接续。",
  ],
  107018: [
    "合约、腿与持仓整合",
    "合约与结构腿、持仓、证券及汇率结合，选择更新日期或最近交易日。",
    "尚未验证 Join 后唯一性；不能只理解为当日快照。",
  ],
  86840: [
    "期权 · grp_id = 01",
    "期权原始本金乘分支汇率，形成统一销售基础字段。",
    "原始计价币种、汇率方向及最终金额单位仍需确认。",
  ],
  86841: [
    "互换 · grp_id = 02",
    "每腿与标的取最早可见历史，汇总期初价格 × 数量，再乘分支汇率。",
    "汇率 CASE 没有 ELSE；尚未证明真实记录会落入未命中情况。",
  ],
  86842: [
    "金仕达互换 · grp_id = 03",
    "每确认编号选择最新记录；多空互换取动态本金，否则取名义本金。",
    "本层无汇率乘法，不能推断上游未折算。",
  ],
  220650: [
    "极速互换 · grp_id = 04",
    "每 instrument 与标的选择最早可见 EOD 持仓，再按 instrument 汇总动态本金。",
    "没有证明所选日期就是合约成立日；本层无汇率乘法。",
  ],
  107491: [
    sharedKnowledge[107491].title,
    sharedKnowledge[107491].summary,
    sharedKnowledge[107491].boundary,
  ],
  103457: [
    "合约本金的真实消费",
    "读取销售基础表，经客户及管理关系筛选后，计算 sum(coalesce(Init_Nom_Prin, 0))。",
    "目标来自配置；聚合保留产品等维度，不能描述为四产品已混加。",
  ],
  223867: [
    "金仕达多空收入明细",
    "销售基础、日序列明细与业务补充来源共同形成收入明细。",
    "已核代表 SQL，未验证落地或正式收入口径。",
  ],
  230202: [
    "期权收入分支",
    "销售基础、附加明细及证券材料指向收入日报。",
    "目前只有表级关系及任务名称证据，尚未详读公式。",
  ],
  227701: [
    "年度创收汇总",
    "按公司、年汇总创收并补交叉销售金额，输出处除以 10,000。",
    "当天分区含去年年初以来的计提日期；未验证正式业务口径。",
  ],
  231146: [
    "客户标签输出",
    "收入日报参与客户标签形成。",
    "已观察表级路线，标签规则待详读。",
  ],
  229121: [
    "客户指标输出",
    "收入日报与客户标签共同参与客户指标输出。",
    "已观察表级路线，指标规则待详读。",
  ],
  93338: [
    "年度动态本金指标",
    "销售基础、日序列明细、管理关系与组合身份参与年度指标加工。",
    "已阅读代表表达式，尚非全链口径验收。",
  ],
  200369: [
    "形成并延续组合身份",
    "从合约类型派生身份，并利用已有组合编号延续身份。",
    "两处关键读取来自 SQL 补证，当前表网络没有完整表示。",
  ],
  148763: [
    "月度资产折算",
    "多个来源的指标经过分支系数和规则，形成折算后资产。",
    "已核加工形状，未确认正式资产口径。",
  ],
  149048: [
    "年度口径输出",
    "读取月度折算后资产，形成年度输出。",
    "目前是表级路线，未详读公式。",
  ],
  202091: [
    "组织员工管理指标",
    "结合多项员工与团队指标、员工身份和组合身份，求和、平均并组织输出。",
    "未确认正式绩效口径。",
  ],
  103230: [
    "标准证券身份整理",
    "证券编码、中间整理、代码替换及去重形成标准证券基础。",
    "SQL 内部写入并未全部出现在表级网络中。",
  ],
  103234: [
    "补 TIT 证券属性",
    "标准证券身份与源内部编号关联，补充 TIT 属性。",
    "同时直接读取源证券，不能画成只读标准证券基础表。",
  ],
  119640: [
    "历史持仓供应",
    "按业务分区读取并写出历史持仓字段；本样本无 Join、聚合或选最新窗口。",
    "其余同区域任务未逐个核验，不能全部归为原样搬运。",
  ],
  202219: [
    "业务数据交付",
    "按日期窗口筛选业务行，并补交付时间；输出由目标配置声明。",
    "没有核验目标送达或目标系统后续消费。",
  ],
  226677: [
    "推送统计日志",
    "计算源表 count / max 并写日志常量。",
    "日志中的 success 常量不能证明业务数据已经送达。",
  ],
  159182: [
    "下游字段与枚举适配",
    "转换字段、枚举及状态，形成面向下游的交付数据。",
    "目标来自配置，未验证数据送达。",
  ],
  196894: [
    "文件导出",
    "SELECT 读取 DM 数据并处理空值文本和时间。",
    "图中该表的输出关联不能视为写表；文件目的地尚未确认。",
  ],
};

const node = (id, title, subtitle, x, y, extra = {}) => ({
  id,
  title,
  subtitle,
  x,
  y,
  ...extra,
});
const task = (id, subtitle, x, y) =>
  node(id, taskNotes[id][0], subtitle, x, y, { tasks: [id], kind: "task" });
const table = (id, title, name, x, y, extra = {}) =>
  node(id, title, name.split(".").at(-1), x, y, {
    table: name,
    kind: "table",
    ...extra,
  });
const edge = (from, to, label = "", extra = {}) => ({
  from,
  to,
  label,
  ...extra,
});
const region = (id, title, subtitle, schemas, x, y, view) =>
  node(id, title, subtitle, x, y, { schemas, view, kind: "region" });

export const views = {
  overview: {
    title: "主流向、并行路线与交付边界",
    subtitle: "从区域看全貌，进入节点看内部加工；点击连线数字查看对应任务。",
    width: 1560,
    height: 665,
    source: "skeleton",
    stages: [
      [30, "01  来源"],
      [300, "02  采集与整理"],
      [640, "03  模型与主题"],
      [1010, "04  应用加工"],
      [1330, "05  交付"],
    ],
    boundary:
      "数字为同一任务的来源与输出区域关联数，各方向可重叠。输出可能来自平台配置，未核验运行落地。",
    nodes: [
      region(
        "S",
        "Titans 可见来源",
        "titans_dm / titans_refdata",
        ["titans_dm", "titans_refdata"],
        30,
        195,
      ),
      region("X", "其他已见来源", "OIS、客户、参考数据等", [], 30, 380),
      region(
        "O",
        "odata_n_tit",
        "采集 · 批次整理 · 部分合并",
        ["odata_n_tit"],
        300,
        270,
        "odata",
      ),
      region(
        "P",
        "pdata_n",
        "实体关系 · 主题整合",
        ["pdata_n"],
        745,
        250,
        "pdata",
      ),
      region(
        "N",
        "pdata_news_n",
        "证券身份 · 市场 / 定价支撑",
        ["pdata_news_n"],
        530,
        420,
        "news",
      ),
      region(
        "D",
        "pdata_nds",
        "直接取数供应 · 职责待细分",
        ["pdata_nds"],
        755,
        535,
        "nds",
      ),
      region(
        "HK",
        "dm_hk_n",
        "交易 / 合约等输出组织",
        ["dm_hk_n"],
        1030,
        65,
        "delivery",
      ),
      region(
        "OTC",
        "dm_otc_n",
        "业务视图 · 收入明细 · BI",
        ["dm_otc_n"],
        1030,
        235,
        "otc",
      ),
      region(
        "IDX",
        "dm_index_n",
        "组合身份 · 多级指标",
        ["dm_index_n"],
        1030,
        400,
        "index",
      ),
      region(
        "RF",
        "dm_rsk_n / dm_fin_n",
        "风险与财务相关输出",
        ["dm_rsk_n", "dm_fin_n"],
        1030,
        570,
      ),
      region(
        "ST",
        "StarRocks 配置目标",
        "ods_titans",
        ["ods_titans"],
        1335,
        40,
      ),
      region(
        "LOG",
        "推送监控日志",
        "ods_gf1.hq_data_push_log",
        ["ods_gf1"],
        1335,
        155,
      ),
      region("DEST", "MySQL / Oracle 目标", "gf_otc", ["gf_otc"], 1335, 280),
      region(
        "OM",
        "dm_om_n",
        "指标组织为管理用途输出",
        ["dm_om_n"],
        1335,
        400,
        "index",
      ),
    ],
    edges: [
      edge("S", "O", "", {
        pairs: [
          ["titans_dm", "odata_n_tit"],
          ["titans_refdata", "odata_n_tit"],
        ],
      }),
      edge("X", "O", "", { otherSources: true }),
      edge("O", "P", "", { pairs: [["odata_n_tit", "pdata_n"]] }),
      edge("O", "N", "", { pairs: [["odata_n_tit", "pdata_news_n"]] }),
      edge("O", "D", "", { pairs: [["odata_n_tit", "pdata_nds"]] }),
      edge("N", "P", "", {
        pairs: [["pdata_news_n", "pdata_n"]],
        labelOffset: [0, -15],
      }),
      edge("P", "HK", "", { pairs: [["pdata_n", "dm_hk_n"]] }),
      edge("O", "HK", "", {
        pairs: [["odata_n_tit", "dm_hk_n"]],
        viaY: 150,
        suffix: "跨区域直读",
      }),
      edge("P", "OTC", "", { pairs: [["pdata_n", "dm_otc_n"]] }),
      edge("N", "OTC", "", {
        pairs: [["pdata_news_n", "dm_otc_n"]],
        viaY: 380,
        labelOffset: [-8, -8],
      }),
      edge("D", "OTC", "", { pairs: [["pdata_nds", "dm_otc_n"]] }),
      edge("P", "IDX", "", { pairs: [["pdata_n", "dm_index_n"]] }),
      edge("IDX", "OM", "", { pairs: [["dm_index_n", "dm_om_n"]] }),
      edge("P", "RF", "", {
        pairs: [
          ["pdata_n", "dm_rsk_n"],
          ["pdata_n", "dm_fin_n"],
        ],
        labelOffset: [-28, 18],
      }),
      edge("N", "RF", "", {
        pairs: [["pdata_news_n", "dm_rsk_n"]],
        viaY: 655,
        labelOffset: [95, 28],
      }),
      edge("HK", "ST", "", {
        pairs: [["dm_hk_n", "ods_titans"]],
        suffix: "交付",
      }),
      edge("HK", "LOG", "", {
        pairs: [["dm_hk_n", "ods_gf1"]],
        suffix: "日志",
        dashed: true,
      }),
      edge("OTC", "DEST", "", {
        pairs: [["dm_otc_n", "gf_otc"]],
        suffix: "交付",
      }),
    ],
  },
  odata: {
    title: "odata_n_tit · 进入仓库后还要整理",
    subtitle: "采集、批次整理和跨来源合并并存，下游不一定经过同一套整理步骤。",
    schemas: ["odata_n_tit"],
    source: "skeleton",
    width: 1320,
    height: 640,
    boundary:
      "代表链包含图关系与 SQL 补充解释。采集目标分区与后续 h15 读取尚未匹配为同一次运行。",
    nodes: [
      table("src", "交易源", "titans_dm.trd_otc_trade", 20, 160),
      task("144134", "采集 SELECT ＋时间", 280, 160),
      table("p", "原始采集目标", "odata_n_tit.d_trd_otc_trade_p", 540, 160),
      task("144141", "h15 → grp_id ＋日期", 800, 160),
      table("pb", "批次整理结果", "odata_n_tit.d_trd_otc_trade_pb", 1060, 160),
      table(
        "mt",
        "TITANS 保证金参数",
        "odata_n_tit.d_v_margin_param_for_risk",
        280,
        390,
      ),
      table(
        "mo",
        "OTC 保证金参数",
        "odata_n_ois.o_v_margin_parameter",
        280,
        530,
      ),
      task("41540", "UNION ALL ＋来源标识", 650, 445),
      table(
        "margin",
        "统一保证金参数",
        "odata_n_tit.otc_o_margin_parameter",
        1010,
        445,
      ),
    ],
    edges: [
      edge("src", "144134"),
      edge("144134", "p", "配置目标"),
      edge("p", "144141"),
      edge("144141", "pb"),
      edge("mt", "41540"),
      edge("mo", "41540"),
      edge("41540", "margin"),
    ],
  },
  pdata: {
    title: "pdata_n · 两条并行的加工路线",
    subtitle: "一条经实体模型再整合；另一条直接形成销售宽表，再展开日序列。",
    schemas: ["pdata_n"],
    source: "skeleton",
    width: 1370,
    height: 680,
    boundary:
      "连线表示表身份上的路线。固定 SQL 日期不完全相同，运行接续和 Join 唯一性仍未确认。",
    nodes: [
      table("r", "源互换合约", "odata_n_tit.d_ref_trs", 20, 130),
      task("103941", "合约标识 · 属性 · 转码", 285, 130),
      table("e", "互换合约实体", "pdata_n.t03_otc_swap_comp_info", 550, 130),
      task("107018", "合约 ＋腿 ＋持仓", 830, 130),
      table(
        "w",
        "交易标的主题",
        "pdata_n.t98_otc_swap_comp_trd_undrl_info",
        1120,
        130,
      ),
      node("legs", "结构腿与持仓", "模型实体与关系", 550, 300, {
        tasks: ["107018"],
      }),
      node("ref", "证券身份与汇率", "横向补充依赖", 830, 300, { view: "news" }),
      node("products", "四产品源材料", "期权 / 互换 / 金仕达 / 极速", 20, 490, {
        view: "principal",
      }),
      node(
        "writers",
        "四产品独立装载",
        "86840 / 86841 / 86842 / 220650",
        285,
        490,
        {
          view: "principal",
          tasks: ["86840", "86841", "86842", "220650"],
          kind: "task",
        },
      ),
      table("sale", "合约销售基础宽表", saleTable, 550, 490, {
        view: "principal",
        accent: true,
      }),
      task("107491", "快照 → 计提日期序列", 830, 490),
      table(
        "daily",
        "销售附加明细",
        "pdata_n.t98_otc_deri_comp_sale_adtnl_det",
        1120,
        490,
      ),
    ],
    edges: [
      edge("r", "103941"),
      edge("103941", "e"),
      edge("e", "107018"),
      edge("legs", "107018"),
      edge("ref", "107018", "证券 / 汇率", { dashed: true }),
      edge("107018", "w"),
      edge("products", "writers"),
      edge("writers", "sale", "产品分区"),
      edge("sale", "107491"),
      edge("107491", "daily"),
    ],
  },
  news: {
    title: "pdata_news_n · 共享证券身份，支撑多个分支",
    subtitle: "标准证券与源系统属性共同供应市场、定价及合约主题。",
    schemas: ["pdata_news_n"],
    source: "skeleton",
    width: 1320,
    height: 650,
    boundary:
      "代表 SQL 中的中间整理和去重并未全部出现在表级网络；不把全部输出统称为行情。",
    nodes: [
      table("i", "源证券", "odata_n_tit.d_ref_instrument", 20, 230),
      task("103230", "编码 · 中间整理 · 去重", 280, 230),
      table("s", "标准证券身份", "pdata_news_n.t02_scr_base_info", 540, 230),
      task("103234", "按源内部编号补属性", 800, 230),
      table(
        "t",
        "TIT 证券属性",
        "pdata_news_n.t02_tit_scr_base_info",
        1060,
        230,
      ),
      node("k", "公共转换常量", "横向参考", 280, 470, { tasks: ["103230"] }),
      node(
        "market",
        "市场 / 定价材料",
        "曲线、波动率、产品、计算结果",
        800,
        500,
        { schemas: ["pdata_news_n"] },
      ),
      node("contracts", "合约主题整合", "pdata_n", 1060, 500, {
        view: "pdata",
      }),
    ],
    edges: [
      edge("i", "103230"),
      edge("103230", "s"),
      edge("s", "103234"),
      edge("i", "103234", "直接读源", { viaY: 120 }),
      edge("103234", "t"),
      edge("k", "103230", "参考", { dashed: true }),
      edge("s", "market"),
      edge("t", "market"),
      edge("t", "contracts"),
    ],
  },
  nds: {
    title: "pdata_nds · 直接取数供应",
    subtitle: "67 个输出关联任务中，66 个读取 odata，另 1 个读取 pdata_n。",
    schemas: ["pdata_nds"],
    source: "skeleton",
    width: 1130,
    height: 580,
    boundary:
      "本批未见本区域内部读写链。只有 119640 样本核验了简单分区取数，其余 66 个不能据此认定为原样搬运。",
    nodes: [
      region(
        "o",
        "odata_n_tit",
        "主要直接来源",
        ["odata_n_tit"],
        30,
        180,
        "odata",
      ),
      task("119640", "历史持仓 · 按分区取数", 380, 180),
      node("out", "持仓历史输出", "点击查看本任务输入与输出", 760, 180, {
        tasks: ["119640"],
      }),
      region(
        "all",
        "其余供应任务",
        "持仓、参考、交易、财务、账户",
        ["pdata_nds"],
        380,
        410,
      ),
      region(
        "otc",
        "dm_otc_n",
        "直接读取该区材料",
        ["dm_otc_n"],
        760,
        410,
        "otc",
      ),
    ],
    edges: [
      edge("o", "119640"),
      edge("119640", "out"),
      edge("o", "all", "区域关系"),
      edge("all", "otc", "", { pairs: [["pdata_nds", "dm_otc_n"]] }),
    ],
  },
  otc: {
    title: "dm_otc_n · 收入明细仍是后续加工的起点",
    subtitle: "先看收入代表链；区域的其他输出族保留在成员清单中。",
    schemas: ["dm_otc_n"],
    source: "skeleton",
    width: 1390,
    height: 680,
    boundary:
      "期权分支、客户标签和客户指标仍以表级关系为主，尚未逐项核实业务公式。",
    nodes: [
      table("sale", "销售基础宽表", saleTable, 20, 130, {
        view: "principal",
        accent: true,
      }),
      table(
        "daily",
        "日序列附加明细",
        "pdata_n.t98_otc_deri_comp_sale_adtnl_det",
        20,
        320,
      ),
      task("223867", "产品分支形成收入", 330, 130),
      task("230202", "表级路线 · 公式待详读", 330, 320),
      table("rev", "收入明细", "dm_otc_n.otc_rev_daily_rpt", 660, 220),
      task("227701", "公司 × 年 · 金额 / 10,000", 960, 100),
      table("bi", "年度创收", "dm_otc_n.bi_otc_year_revenue", 1190, 100),
      task("231146", "规则待详读", 960, 350),
      task("229121", "规则待详读", 1190, 350),
      task("103457", "sum(coalesce(初始本金, 0))", 330, 550),
      table("trade", "交易明细配置目标", "dm_otc_n.wt_otc_trade_dtl", 660, 550),
    ],
    edges: [
      edge("sale", "223867"),
      edge("daily", "223867"),
      edge("sale", "230202"),
      edge("daily", "230202"),
      edge("223867", "rev"),
      edge("230202", "rev"),
      edge("rev", "227701"),
      edge("227701", "bi"),
      edge("rev", "231146"),
      edge("231146", "229121"),
      edge("rev", "229121", "直接输入", { viaY: 455 }),
      edge("sale", "103457", "本金消费", { viaY: 450 }),
      edge("103457", "trade", "配置目标"),
    ],
  },
  index: {
    title: "dm_index_n → dm_om_n · 身份关联与指标加工",
    subtitle:
      "组合身份是共享支撑；年度本金、资产折算和员工管理指标各有自己的路线。",
    schemas: ["dm_index_n", "dm_om_n"],
    source: "skeleton",
    width: 1330,
    height: 680,
    boundary:
      "虚线包含身份依赖及 SQL 补证。200369 的两条关键读取在本批表网络中缺失，未补成图快照中的边。",
    nodes: [
      table("sale", "销售基础 / 日明细", saleTable, 20, 100, {
        view: "principal",
      }),
      task("93338", "年度动态本金与管理分配", 550, 100),
      table(
        "idx",
        "年度动态本金",
        "dm_index_n.index_avg_dyna_nom_prin_year",
        1050,
        100,
      ),
      task("200369", "合约类型 → 组合身份", 280, 310),
      table("grp", "共享组合身份", "dm_index_n.grp_def", 550, 310),
      task("148763", "多源规则 · 月度折算", 20, 525),
      task("149048", "年度输出 · 公式待详读", 310, 525),
      task("202091", "员工 / 团队指标与身份", 800, 480),
      table(
        "emp",
        "管理用途输出",
        "dm_om_n.wt_emp_indi_data_mana_veal",
        1080,
        480,
      ),
    ],
    edges: [
      edge("sale", "93338"),
      edge("93338", "idx"),
      edge("sale", "200369", "SQL 补证", { dashed: true }),
      edge("200369", "grp"),
      edge("grp", "200369", "身份延续 / SQL 补证", { dashed: true, viaY: 420 }),
      edge("grp", "93338", "身份", { dashed: true }),
      edge("148763", "149048", "月度资产"),
      edge("grp", "202091", "身份", { dashed: true }),
      edge("202091", "emp"),
    ],
  },
  delivery: {
    title: "dm_hk_n 与出口 · 交付、日志、导出",
    subtitle: "同样指向下游区域，承载的可能是业务行、监控统计或文件输出。",
    schemas: ["dm_hk_n"],
    source: "skeleton",
    width: 1270,
    height: 660,
    boundary:
      "区域输出关联包含 43 个 hive2file，不能全部算作写表。此处展示出口代表链，dm_hk_n 内部各表族尚未全部还原。",
    nodes: [
      table(
        "src",
        "DM 业务数据",
        "dm_hk_n.otc_trd_trs_underlying_deal",
        30,
        220,
      ),
      task("202219", "业务行筛选 ＋交付时间", 460, 100),
      table(
        "dest",
        "StarRocks 配置目标",
        "ods_titans.otc_trd_trs_underlying_deal",
        950,
        100,
      ),
      task("226677", "源表 count / max ＋常量", 460, 330),
      table("log", "推送监控日志", "ods_gf1.hq_data_push_log", 950, 330),
      task("196894", "SELECT ＋空值文本处理", 460, 535),
      node("file", "文件目的地待确认", "不能据声明认作源表写者", 950, 535, {
        tasks: ["196894"],
      }),
    ],
    edges: [
      edge("src", "202219"),
      edge("202219", "dest", "配置目标"),
      edge("src", "226677", "源表统计", { dashed: true }),
      edge("226677", "log", "日志", { dashed: true }),
      edge("196894", "file", "独立导出分支"),
    ],
  },
  principal: {
    title: "合约销售基础宽表 · 四产品共同装载",
    subtitle:
      "同一张表保留四条产品加工路径；点击“本金字段族”查看公式与日期选择。",
    schemas: ["pdata_n"],
    source: "principal",
    width: 1370,
    height: 740,
    boundary:
      "按业务日期与 grp_id 覆盖写入。候选粒度 (busi_date, grp_id, agt_id) 尚未验证唯一，四路最终金额单位仍待确认。",
    nodes: [
      task("86840", "期权交易与结构", 30, 80),
      task("86841", "互换合约、腿与历史持仓", 30, 250),
      task("86842", "金仕达确认 · 最新记录", 30, 420),
      task("220650", "极速互换 · 最早 EOD 持仓", 30, 590),
      table("sale", "合约销售基础宽表", saleTable, 420, 300, {
        accent: true,
        principal: true,
      }),
      node("family", "本金字段族", "初始 / 动态 / 绝对本金 / 汇率", 420, 550, {
        principal: true,
        accent: true,
      }),
      task("107491", "合约快照 → 计提日序列", 780, 100),
      table(
        "daily",
        "销售附加明细",
        "pdata_n.t98_otc_deri_comp_sale_adtnl_det",
        1100,
        100,
      ),
      task("103457", "初始本金 → 聚合金额", 780, 300),
      table(
        "trade",
        "交易明细配置目标",
        "dm_otc_n.wt_otc_trade_dtl",
        1100,
        300,
      ),
      node("readers", "其他表级消费者", "点击宽表查看完整读者集合", 780, 550, {
        table: saleTable,
      }),
      node("otc", "收入与 BI 加工", "继续进入 dm_otc_n", 1100, 550, {
        view: "otc",
      }),
    ],
    edges: [
      edge("86840", "sale", "01"),
      edge("86841", "sale", "02"),
      edge("86842", "sale", "03"),
      edge("220650", "sale", "04"),
      edge("sale", "family", "字段解释", { dashed: true }),
      edge("sale", "107491"),
      edge("107491", "daily"),
      edge("sale", "103457", "已核本金消费"),
      edge("103457", "trade", "配置目标"),
      edge("sale", "readers"),
      edge("readers", "otc", "代表方向"),
    ],
  },
};
