-- GENERATED by render.mjs; edit 00_主脚本.sql and 01–06 modules instead.
/*
107491 / 合约销售收入附加明细：按计提日组织本金、利息、交易收入成本和费率
入口说明：README.md；原始基准：../99_证据/107491-query.sql。

当前合约快照 → 展开计提日info
  ├─ 期权事件evt       → 累计名本变化
  ├─ 互换历史持仓his_dy → 当日价格×数量
  ├─ 金仕达ks / ks_t   → 延续金额 / 当日交易收入成本
  ├─ FAST持仓nd        → 当日源本金
  └─ 风控prop / 费率fee → 按区间延续的比例、费率
                        ↓
              下方CASE选择最终动态本金

@include由render.mjs展开，不是Hive原生语法。这里只整理SQL，不连接或执行生产库。
*/
set hive.merge.mapfiles=true ;
set hive.merge.mapredfiles=true;
set hive.merge.size.per.task=1073741824;
set hive.merge.smallfiles.avgsize=1073741824;
set hive.merge.orcfile.stripe.level=false;

set hive.input.format=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat;
set mapreduce.input.fileinputformat.split.maxsize=1073741824;
set mapreduce.input.fileinputformat.split.minsize=1073741824;

WITH
/*
01 / 一份当前合约资料，怎样变成多天的计提记录？
把一张当前合约快照展开成“每日计提明细”，生成合约每天一行的 Accrued_Date。

输入：T98_OTC_DERI_COMP_SALE_INFO（合约销售主信息）的本次加工日快照。
不是每天读取对应的历史快照；类型、客户、初始本金、汇率等会随当前资料带到展开的各天。

① 先确定结束边界：有提前终止日就取提前终止日，否则取期末定价日。
② 选结束边界晚于2021-09-30、且期初不晚于结束边界的记录。
③ 从“期初定价日、本次加工日前150天”中较晚一天展开到加工日，首尾都包括。
   例如加工日为9月21日、合约9月18日开始，就生成18、19、20、21日四行。

为什么没有在终止日停止展开？
  原SQL的展开终点是加工日；期权、普通互换在主脚本的金额CASE中把终止日之后置0。
  金仕达、FAST的CASE没有相同的归零判断，不能一概解释为只生成存续期记录。

输出contract_days在主脚本中别名为info；Accrued_Date是计提日，
最终写到目标表分区busi_date。150日是回看跨度，含端点时可覆盖151个日期。
*/

/*
【用途】
将当前合约快照展开为每日计提记录，生成 contract × Accrued_Date 粒度数据。

【输入】
T98_OTC_DERI_COMP_SALE_INFO（加工日快照）。
不读取历史快照，展开后的记录沿用当前快照中的合约属性。

【逻辑】
1. 结束日期：
   Early_Term_Date 存在时取提前终止日，否则取 End_Pric_Date。

2. 合约筛选：
   结束日期 > 2021-09-30；
   Strt_Pric_Date <= 结束日期。

3. 日期展开：
   起始日期 = max(Strt_Pric_Date, 加工日前150天)；
   结束日期 = 加工日；
   生成包含首尾日期的每日记录。

   示例：
   加工日 9月21日，开始日 9月18日：
   生成 9月18日~9月21日。

【注意】
- 展开终点不是终止日，而是加工日。。
- 后续金额计算模块根据终止日期判断是否计入：
    存续期 → 正常计算；
    终止后 → 金额置0。
- 输出 contract_days，Accrued_Date 为计提日。
*/

-- ① 合约范围：只读当日快照，不另筛状态、源类型或grp_id；四类业务都参与。
contract_scope AS (
    select *, coalesce(Early_Term_Date, End_Pric_Date) as End_Pric_Date_n
    from T98_OTC_DERI_COMP_SALE_INFO -- 场外衍生品合约销售主信息
    where busi_date = '${data_day_str}'
        and coalesce(Early_Term_Date, End_Pric_Date) > '2021-09-30'
        and Strt_Pric_Date <= coalesce(Early_Term_Date, End_Pric_Date)
    ),

-- ② 日期展开：按“起始日 ~ 加工日”生成每日计提日期。
-- 起始日 = max(Strt_Pric_Date, 加工日前150天)；
-- posexplode生成日偏移pos，date_add逐日展开。
-- 输出Accrued_Date（一行=合约×计提日）。
contract_days AS (
    select *,
        date_add(default.gfgreatest(Strt_Pric_Date,date_sub('${data_day_str}',150)), pos) as Accrued_Date
    from contract_scope opt
    lateral view posexplode(split(space(datediff('${data_day_str}', default.gfgreatest(Strt_Pric_Date,date_sub('${data_day_str}',150)))), ' ')) t as pos, val
    )

,
/*
02 / 核心问题：期权没有像 TRS 那样的逐日持仓表，如何知道每天还剩多少名义本金？
解决思路：期权动态本金：通过存续期事件还原每日名义本金变化。

【背景】
期权无逐日持仓，通过事件表记录本金调整。
    【与互换对比】
    普通互换：初始持仓+每日持仓变化 → 当天本金
    期权：初始本金 + 存续期事件变化 → 每天本金 （部分终止、提前锁盈等事件）

【逻辑】
事件表来源：odata_n_tit.d_trd_option_event（交易-OTC OPTION存续期事件表）。
只选本次快照中已生效EFFECTIVE的部分终止PARTIAL_TERMINATION、提前锁盈EARLY_LOCK_PL事件。
这里只算累计名本变化，不直接输出最终本金。

【处理流程】：
(同合约同事件)日汇总→判断本金增减方向→累计名义本金变化→展开到下一事件日前一天
【主脚本】：
动态本金 = 初始本金 + 累计变化 × 合约主信息中的Cny_Ex_Rate

【示例】
初始本金1000：
9月19日减少200 → 累计变化-200，本金800
9月20日减少100 → 累计变化-300，本金700

【注意】
- notional_delta为名本变动金额，不是事件后余额。
- 没有事件日期时，本模块不生成记录，主逻辑回退初始本金。
- 期末/终止后的有效性由主脚本判断。
- 增减方向由notional_after与notional_before比较后决定，不是直接累加原始delta。
*/

/*
① 【同合约同事件日汇总事件】，得到调整前后本金及变动金额。
    主要处理终止/锁盈类事件导致的本金调整。【只考虑会影响本金规模的事件】
    按同合约、同事件日汇总：
    最大调整前本金 = 当日事件开始前本金；
    最小调整后本金 = 当日事件完成后本金；
    delta求和 = 当日累计变动金额。
    同日多事件合并，不逐笔计算事件顺序。
*/
option_event_daily AS (
    select
        key_option_deal_id, -- 场外期权合约ID；接合约主信息的Inr_Seri_No
        max(cast(notional_before as double)) as notional_before, -- 调整前名义本金（事件最开始的名本）
        min(cast(notional_after as double)) as notional_after, -- 调整后名义本金（事件最后的名本）
        sum(notional_delta) as notional_delta, -- 名义本金变动金额之和
        event_date -- 事件日期
    from odata_n_tit.d_trd_option_event toe -- 交易-OTC OPTION存续期事件表
    where busi_Date = '${data_day_str}' and event_status = 'EFFECTIVE' 
    and event_type in ('PARTIAL_TERMINATION','EARLY_LOCK_PL')--（部分终止、提前锁盈等事件）
    group by key_option_deal_id, event_date
    ),

-- ② 判断方向并累计：调整后<调整前时取负delta，其余取正delta；不额外取ABS或限制为非负。
-- next_date是下一事件日；最后一个事件的默认终点是加工日次日，不是合约终止日。
option_event_balances AS (
    select
        key_option_deal_id,
        sum(case when cast(notional_after as double) < cast(notional_before as double) then - notional_delta else notional_delta end) over(partition by key_option_deal_id order by event_date) as notional_change,
        lead(event_date, 1, date_add('${data_day_str}',1)) over(partition by key_option_deal_id order by event_date) as next_date,
        event_date
    from option_event_daily x
    ),

-- ③ 延续到每天：[本事件日，下一事件日前一天]使用同一个累计变化。
-- 没有事件的日期不会在本模块补行；主脚本LEFT JOIN缺失时回退初始本金。
option_event_days AS (
    select
        key_option_deal_id,
        notional_change,
        date_format(date_add(event_date, pos),'yyyy-MM-dd') as Accrued_Date
    from option_event_balances t
    lateral view posexplode(split(space(datediff(next_date, event_date)-1), ' ')) t as pos, val
    )

,
/*
03 / 普通互换每个历史日的金额，怎样从腿的持仓汇总到合约？

  结构腿d_ref_trs_leg：内部交易键key_otc_trade_id、腿键key_leg_id
    └─按腿键接d_pos_trs_leg_his_pos：源业务日、期初价、初始数量、当日数量
         └─按“内部交易键＋源业务日期”汇总 → 主脚本别名his_dy

两张源表都取加工日快照，持仓另限源业务日期在加工日前150天至加工日。
每个计提日直接匹配该日持仓，不自动延续前一天；缺失金额在最终CASE中按0处理。

本模块产出两个金额：
  Init_Nom_Prin_Org = Σ(Init_Price × Init_Quantity)，原SQL保留但最终SELECT未使用。
  Dyna_Nom_Prin_Org = Σ(Init_Price × Quantity)，用于“历史日金额 × 汇率”。
主脚本的初始本金始终取合约主信息，期初定价日也优先取它，不改取本模块的初始金额。
*/

-- ① 结构腿：leg_type为结构腿类型；不是把所有固定/浮动利率腿都纳入。
trs_structure_legs AS (
    select * from odata_n_tit.d_ref_trs_leg -- 场外交易-TRS-leg基本信息
    where busi_Date = '${data_day_str}' and leg_type = 'STRUCTURE_LEG_TYPE'
    ),

-- ② 历史持仓：src_busi_date为【AI】源业务日期；这里只裁日期窗口，不选“最新一条”。
trs_position_history AS (
    SELECT *
    FROM odata_n_tit.d_pos_trs_leg_his_pos -- 【AI】持仓-TRS浮动及结构化腿历史持仓
    where busi_Date = '${data_day_str}'
        and substring(src_busi_date,1,10) between date_sub('${data_day_str}',150) and '${data_day_str}'
    ),

-- ③ 按交易、日期汇总：同一交易的多条结构腿在这里合并；腿或持仓重复匹配仍参与求和。
trs_daily_positions AS (
    SELECT
        rtl.key_otc_trade_id, -- TRADEFLOW内部交易流水号，接info.Inr_Seri_No
        sum(his.Init_Price * his.Init_Quantity) as Init_Nom_Prin_Org,
        sum(his.Init_Price * his.Quantity) as Dyna_Nom_Prin_Org, -- 【AI】期初交易价×数量，尚未乘汇率
        substring(his.src_busi_date,1,10) as Accrued_Date
    FROM trs_structure_legs rtl
    inner join trs_position_history his
    ON his.key_leg_id = rtl.key_leg_id
    group by rtl.key_otc_trade_id, substring(his.src_busi_date,1,10)
    )

,
/*
04 / 金仕达的本金、利息、交易收入，是否都按同一天取值？

不是。本文件有三条并行取数线，在主脚本分别连接：
  ks   金额与用资：确认记录按业务日形成区间，延续到下一条记录前一天。
  ks_t 交易收入成本：直接匹配业务日，不延续；最终缺失补0。
  prop 保证金比例：风控记录先按合约、生成日取一条，再形成延续区间。

确认信息源表：odata_n_tit.d_ks_trade_comfirm_info（交易确认书信息表）。
  key_trade_comfirm_id=金仕达交易确认书id，接合约主信息的Agt_Id。
  dynamic_notional=动态名义本金；accrued_interest=当日应记利息；occupy_cost=用资成本。
  profit=股票交易收入，输出到Trd_Cms（交易佣金收入）；
  fee_cost=股票交易成本，输出到Trd_Cms_Cost（交易佣金成本）。
源字段原义与目标字段名不同，不能反过来用“佣金”解释源表所有股票交易收入。

例：18日记录本金1000、利息10、用资成本2，20日有新记录。
  18/19日都可使用18日的这三个值，利息在主脚本乘-1后输出为-10；
  18日profit不会因此延续到19日，19日没对应记录时交易收入输出0。
所以Inta虽取源字段“当日应记利息”，消费结果也可能来自更早的业务日。
*/

-- A① 确认记录划区间：取本次快照的历史；不先筛最近150天，以保留窗口前仍有效的记录。
-- 同确认键、同业务日若有多条，本分支没有去重，也没有稳定的同日先后裁决。
ks_amount_intervals AS (
    select key_trade_comfirm_id, business_date, accrued_interest, occupy_cost, dynamic_notional,
        lead(business_date, 1, date_add('${data_day_str}',1)) over(partition by key_trade_comfirm_id order by business_date) as next_date
    from odata_n_tit.d_ks_trade_comfirm_info -- 交易确认书信息表
    where busi_date = '${data_day_str}'
    ),

-- A② 延续金额：[本业务日，下一业务日前一天]；最后一条以加工日次日作右边界。
ks_amount_days AS (
    select *, date_add(business_date, pos) as Accrued_Date
    from ks_amount_intervals t
    lateral view posexplode(split(space(datediff(next_date, business_date)-1), ' ')) t as pos, val
    ),

-- B 交易收入/成本：仅取最近150天至加工日，直接按business_date匹配；不延续、不求和、不去重。
ks_trade_days AS (
    select key_trade_comfirm_id, profit, fee_cost, business_date as Accrued_Date
    from odata_n_tit.d_ks_trade_comfirm_info -- 交易确认书信息表
    where busi_date = '${data_day_str}'
        and business_date between date_sub('${data_day_str}',150) and '${data_day_str}'
    ),

-- C① 风控比例：GEN_DATE=【AI】业务日期，CONTRACT_ID=【AI】合约编号，GUARANTEE_RATIO=【AI】履约保证比例。
-- datekey2date将日期键转成日期字符串，例如20160101→2016-01-01。
-- 窗口按原GEN_DATE分组，组内又按同一个值排序，不能理解为选中“当天最新版本”。
ks_margin_ranked AS (
    select
        default.datekey2date(GEN_DATE) as GEN_DATE,
        CONTRACT_ID,
        GUARANTEE_RATIO as Marg_Prop,
        row_number() over(partition by CONTRACT_ID, GEN_DATE order by GEN_DATE) as rk
    from odata_n_tit.d_ks_trs_for_risk -- 【AI】TRS风控数据表
    where busi_date = '${data_day_str}'
    ),

-- C② 每个合约、生成日取一条，再用下一日期形成比例的有效区间。
ks_margin_intervals AS (
    select *, lead(GEN_DATE, 1, date_add('${data_day_str}',1)) over(partition by CONTRACT_ID order by GEN_DATE) as next_date
    from ks_margin_ranked a
    where rk = 1
    ),

-- C③ 延续比例；主脚本实际写CONTRACT_ID=info.Agt_Id，不改连Inr_Seri_No。
-- 这个字段叫“合约编号”，却与金仕达确认键相连；编号是否实际匹配仍需数据核验。
ks_margin_days AS (
    select *, date_add(GEN_DATE, pos) as Accrued_Date
    from ks_margin_intervals b
    lateral view posexplode(split(space(datediff(next_date, GEN_DATE)-1), ' ')) t as pos, val
    )

,
/*
05 / FAST在各历史日的金额是多少？

来源：odata_n_tit.d_pos_fast_trs_leg_his_pos（北上极速腿历史持仓表）。
取加工日快照中的EOD_POSITION（日终持仓），源持仓日期限加工日前150天至加工日。
按“合约工具键＋源持仓日期”汇总dynamic_notional，主脚本用Otc_Seri_No和计提日连接。

dynamic_notional注释为“动态名义本金（标的币种）”，本模块只求和；
主脚本仍乘合约主信息的Cny_Ex_Rate，缺金额或汇率导致乘积为NULL时补0。
不按标的选最早记录、不延续前日、不统一在合约终止后归零。

04号合约主信息分支的汇率固定为1，因此不能仅凭乘过该字段就确认金额是人民币。
本模块未单独筛N_CROSS_DMA_SWAP，业务范围由驱动它的合约主信息决定。
*/
fast_daily_positions AS (
    select
        key_instrument_id, -- 本表注释“合约ID”，对应合约主信息Otc_Seri_No
        sum(dynamic_notional) as dynamic_notional,
        substring(src_busi_date,1,10) as Accrued_Date -- 持仓日期：源头的busi_date
    from odata_n_tit.d_pos_fast_trs_leg_his_pos -- 北上极速腿历史持仓表
    where busi_date = '${data_day_str}' and position_type = 'EOD_POSITION'
        and substring(src_busi_date,1,10) between date_sub('${data_day_str}',150) and '${data_day_str}'
    group by key_instrument_id, substring(src_busi_date,1,10)
    )

,
/*
06 / 某次计提费率，在哪些日期继续使用？

来源：odata_n_tit.d_trd_daily_accrual_fee（【AI】按日应计提费用表）。
只读加工日快照、fee_type='ACCRUAL_PREMIUM_FEE'；输出的是fee_rate（费率），不是费用金额。
按KEY_INSTRUMENT_ID（场外合约主数据代码）找下一计提日期CALC_DATE，
把本条费率延续到下一计提日前一天；最后一条延续到加工日。

  18日费率a、20日费率b → 18/19日用a，20日起用b。
主脚本按info.Otc_Seri_No＋计提日连接，缺记录时fee_rate保持NULL。
原SQL没有限制只用于某个grp_id，也没有按同工具、同计提日去重。
*/

fee_intervals AS (
    SELECT *, lead(CALC_DATE, 1, date_add('${data_day_str}',1)) over(partition by KEY_INSTRUMENT_ID order by CALC_DATE) as next_date
    FROM odata_n_tit.d_trd_daily_accrual_fee -- 【AI】按日应计提费用表
    where busi_Date = '${data_day_str}' and fee_type = 'ACCRUAL_PREMIUM_FEE'
    ),

-- Accrued_Date为延续后的计提日；CALC_DATE仍是原记录的计提日期。
fee_days AS (
    select *, date_format(date_add(CALC_DATE, pos),'yyyy-MM-dd') as Accrued_Date
    from fee_intervals t
    lateral view posexplode(split(space(datediff(next_date, CALC_DATE)-1), ' ')) t as pos, val
    )


-- 按展开后的计提日、业务分组写动态分区；不是把所有行写到加工日分区。
insert overwrite table T98_OTC_DERI_COMP_SALE_ADTNL_DET PARTITION(busi_date,grp_id)
select
    info.Agt_Id, -- 合约编号；TIT分支为主合约编号，金仕达为确认书id
    info.Busi_Type, -- 业务类型
    info.Cutp_Pty_Id, -- 交易对手客户编号
    info.Undrl_Ins_Id, -- 标的ID
    info.Undrl_Wd_Cd, -- 标的万得代码
    info.Undrl_Name, -- 标的名称；以上资料跟随当前合约快照，不按历史日重取
    info.Strt_Pric_Date, -- 期初定价日
    info.End_Pric_Date_n as End_Pric_Date, -- 优先提前终止日，否则期末定价日
    info.Init_Nom_Prin, -- 四个分组均直接取合约主信息的初始本金

    -- 最终动态本金：先看业务分组，再看分组内部的日期规则。
    case
         -- 01 期权：开始日用初始本金；结束边界后为0；中间按累计事件变化调整。
         when grp_id = '01' then
             if(info.Accrued_Date = info.Strt_Pric_Date, info.Init_Nom_Prin,
                if(info.Accrued_Date > info.End_Pric_Date_n, 0,
                   coalesce(evt.notional_change * info.Cny_Ex_Rate + info.Init_Nom_Prin, info.Init_Nom_Prin, 0)))
         -- 02 普通互换：开始日同样优先初始本金；其他存续日用该日持仓金额×汇率，缺失补0。
         when grp_id = '02' then
             if(info.Accrued_Date = info.Strt_Pric_Date, info.Init_Nom_Prin,
                if(info.Accrued_Date > info.End_Pric_Date_n, 0,
                   coalesce(his_dy.Dyna_Nom_Prin_Org * info.Cny_Ex_Rate, 0)))
         -- 03 金仕达：直接取延续后的源本金；无汇率乘法、无结束后归零、无缺失补0。
         when grp_id = '03' then ks.dynamic_notional
         -- 04 FAST：历史日源本金×汇率，乘积为NULL时补0；无开始日特判或结束后归零。
         when grp_id = '04' then coalesce(nd.dynamic_notional * info.Cny_Ex_Rate,0)
         end as Dyna_Nom_Prin,

    fee.fee_rate, -- 费率：按工具、计提日期延续；不是已计算的费用金额，缺失保持NULL
    ks.accrued_interest * (-1) as Inta, -- 源“当日应记利息”取反；可能从更早业务日延续而来
    ks.occupy_cost as Fnd_Cost, -- 源用资成本，同样按确认记录区间延续
    coalesce(ks_t.profit,0) as Trd_Cms, -- 源股票交易收入；只匹配实际业务日，缺失补0
    coalesce(ks_t.fee_cost,0) as Trd_Cms_Cost, -- 源股票交易成本；只匹配实际业务日，缺失补0
    prop.Marg_Prop, -- 源履约保证比例，按生成日期延续
    'TIT' AS Data_Src_Cd,
    UPPER('${filename}') AS Task_Name,
    '${data_day_str}' AS Data_Etl_Date, -- 本次加工日
    '${data_day_str}' AS Data_Upt_Date,
    '${data_today}' AS Data_Time,
    info.Accrued_Date as Busi_Date, -- 计提日：目标分区日期，不是上面的加工日
    info.Grp_Id -- 业务分组：目标分区值

-- 以下LEFT JOIN保留没有金额/费率资料的合约日；各连接都没有额外grp_id条件。
-- CASE选择哪笔金额，并不消除其他连接产生的多条匹配；这里不做最终去重。
from contract_days info
left join option_event_days evt
on evt.key_option_deal_id = info.Inr_Seri_No and evt.Accrued_Date = info.Accrued_Date
left join trs_daily_positions his_dy
on his_dy.key_otc_trade_id = info.Inr_Seri_No and his_dy.Accrued_Date = info.Accrued_Date
left join ks_amount_days ks
on info.Agt_Id = ks.key_trade_comfirm_id and info.Accrued_Date = ks.Accrued_Date
left join ks_trade_days ks_t
on info.Agt_Id = ks_t.key_trade_comfirm_id and info.Accrued_Date = ks_t.Accrued_Date
left join fast_daily_positions nd
on nd.key_instrument_id = info.Otc_Seri_No and info.Accrued_Date = nd.Accrued_Date
left join ks_margin_days prop
on prop.Accrued_Date = info.Accrued_Date and prop.CONTRACT_ID = info.agt_id
left join fee_days fee
on fee.key_instrument_id = info.Otc_Seri_No and fee.Accrued_Date = info.Accrued_Date
;
