-- 四条语句分别执行、分别导出；每份最多 500 条。
-- 日期暂填 2026-09-15，请统一换成四张表均有数据的业务日期。
-- 若某张表该日为空，请保留“该日无数据”的结果，不要自行换日混在一起。
-- 按类型、外部来源、账户组轮流取样，服务业务理解，不用于估计总体分布。
-- 保留原始英文列名，便于与加工 SQL 对照；名称可按需要脱敏，但 ID 与关系对应请一致保留。
-- 字段已核对本地 ODATA_N_TIT 元数据；语句尚未在平台执行。

-- 01 主体：系统静态数据。按类型、内部标识、账户组标识轮流取样。
WITH ranked AS (
    SELECT
        ID, LONG_NAME, SHORT_NAME, CTPTY_TYPE, CTPTY_LEGAL_ENTITY,
        NAME_ABBREVIATION, UNIFIEDSOCIAL_CODE, DEPARTMENT,
        IS_DELETED, IS_INNER, GROUP_FLAG,
        CREATED_DATETIME, UPDATED_DATETIME, DATA_TIME, BUSI_DATE,
        ROW_NUMBER() OVER (
            PARTITION BY CTPTY_TYPE, IS_INNER, GROUP_FLAG
            ORDER BY ID, UPDATED_DATETIME, LONG_NAME
        ) AS SAMPLE_ROUND
    FROM ODATA_N_TIT.D_REF_COUNTERPARTY
    WHERE BUSI_DATE = '2026-09-15'
)
SELECT
    ID, LONG_NAME, SHORT_NAME, CTPTY_TYPE, CTPTY_LEGAL_ENTITY,
    NAME_ABBREVIATION, UNIFIEDSOCIAL_CODE, DEPARTMENT,
    IS_DELETED, IS_INNER, GROUP_FLAG,
    CREATED_DATETIME, UPDATED_DATETIME, DATA_TIME, BUSI_DATE
FROM ranked
ORDER BY SAMPLE_ROUND, CTPTY_TYPE, IS_INNER, GROUP_FLAG, ID
LIMIT 500;

-- 02 主体：交易参数来源。独立取样，不预设与上表互相替代。
WITH ranked AS (
    SELECT
        ID, LONG_NAME, SHORT_NAME, CTPTY_TYPE, CTPTY_LEGAL_ENTITY,
        NAME_ABBREVIATION, UNIFIEDSOCIAL_CODE, DEPARTMENT,
        IS_DELETED, IS_INNER, DEALER_LEVEL, APTITUDE,
        CREATED_DATETIME, UPDATED_DATETIME, DATA_TIME, BUSI_DATE,
        ROW_NUMBER() OVER (
            PARTITION BY CTPTY_TYPE, IS_INNER
            ORDER BY ID, UPDATED_DATETIME, LONG_NAME
        ) AS SAMPLE_ROUND
    FROM ODATA_N_TIT.D_REF_COUNTER_PARTY
    WHERE BUSI_DATE = '2026-09-15'
)
SELECT
    ID, LONG_NAME, SHORT_NAME, CTPTY_TYPE, CTPTY_LEGAL_ENTITY,
    NAME_ABBREVIATION, UNIFIEDSOCIAL_CODE, DEPARTMENT,
    IS_DELETED, IS_INNER, DEALER_LEVEL, APTITUDE,
    CREATED_DATETIME, UPDATED_DATETIME, DATA_TIME, BUSI_DATE
FROM ranked
ORDER BY SAMPLE_ROUND, CTPTY_TYPE, IS_INNER, ID
LIMIT 500;

-- 03 外部身份映射：按外部来源轮流取样。
-- 先按主体 ID 汇总名称及匹配条数，避免同日主体重复把关系行放大。
-- 匹配数 > 1 时名称不选任意一条，保留 NULL 以待核对。
WITH party_names AS (
    SELECT ID, COUNT(*) AS MATCH_ROWS,
           CASE WHEN COUNT(*) = 1 THEN MAX(LONG_NAME) END AS LONG_NAME
    FROM ODATA_N_TIT.D_REF_COUNTERPARTY
    WHERE BUSI_DATE = '2026-09-15'
    GROUP BY ID
), ranked AS (
    SELECT KEY_CTPTY_ID, OUTSIDE_SOURCE, OUTSIDE_CTPTY_CODE,
           CREATED_DATETIME, UPDATED_DATETIME, DATA_TIME, BUSI_DATE,
           ROW_NUMBER() OVER (
               PARTITION BY OUTSIDE_SOURCE
               ORDER BY KEY_CTPTY_ID, OUTSIDE_CTPTY_CODE, CREATED_DATETIME
           ) AS SAMPLE_ROUND
    FROM ODATA_N_TIT.D_REF_CTPTY_MAPPING
    WHERE BUSI_DATE = '2026-09-15'
)
SELECT M.KEY_CTPTY_ID, P.LONG_NAME AS CTPTY_NAME,
       COALESCE(P.MATCH_ROWS, 0) AS CTPTY_MATCH_ROWS,
       M.OUTSIDE_SOURCE, M.OUTSIDE_CTPTY_CODE,
       M.CREATED_DATETIME, M.UPDATED_DATETIME, M.DATA_TIME, M.BUSI_DATE
FROM ranked M
LEFT JOIN party_names P ON M.KEY_CTPTY_ID = P.ID
ORDER BY M.SAMPLE_ROUND, M.OUTSIDE_SOURCE, M.KEY_CTPTY_ID, M.OUTSIDE_CTPTY_CODE
LIMIT 500;

-- 04 账户组绑定：按账户组轮流取样，保留两端名称和同日匹配数。
-- 500 条上限可能截断某个组的成员，不能据此宣布一个组只有样本内这些成员。
WITH party_names AS (
    SELECT ID, COUNT(*) AS MATCH_ROWS,
           CASE WHEN COUNT(*) = 1 THEN MAX(LONG_NAME) END AS LONG_NAME,
           CASE WHEN COUNT(*) = 1 THEN MAX(CTPTY_TYPE) END AS CTPTY_TYPE,
           CASE WHEN COUNT(*) = 1 THEN MAX(GROUP_FLAG) END AS GROUP_FLAG
    FROM ODATA_N_TIT.D_REF_COUNTERPARTY
    WHERE BUSI_DATE = '2026-09-15'
    GROUP BY ID
), ranked AS (
    SELECT ID, KEY_CTPTY_ID, CREATED_DATETIME, UPDATED_DATETIME, DATA_TIME, BUSI_DATE,
           ROW_NUMBER() OVER (
               PARTITION BY ID
               ORDER BY KEY_CTPTY_ID, CREATED_DATETIME
           ) AS SAMPLE_ROUND
    FROM ODATA_N_TIT.D_REF_CTPTY_TRADE_GROUP
    WHERE BUSI_DATE = '2026-09-15'
)
SELECT R.ID AS GROUP_CTPTY_ID, G.LONG_NAME AS GROUP_CTPTY_NAME,
       G.CTPTY_TYPE AS GROUP_CTPTY_TYPE, G.GROUP_FLAG,
       COALESCE(G.MATCH_ROWS, 0) AS GROUP_MATCH_ROWS,
       R.KEY_CTPTY_ID AS MEMBER_CTPTY_ID, P.LONG_NAME AS MEMBER_CTPTY_NAME,
       P.CTPTY_TYPE AS MEMBER_CTPTY_TYPE,
       COALESCE(P.MATCH_ROWS, 0) AS MEMBER_MATCH_ROWS,
       R.CREATED_DATETIME, R.UPDATED_DATETIME, R.DATA_TIME, R.BUSI_DATE
FROM ranked R
LEFT JOIN party_names G ON R.ID = G.ID
LEFT JOIN party_names P ON R.KEY_CTPTY_ID = P.ID
ORDER BY R.SAMPLE_ROUND, R.ID, R.KEY_CTPTY_ID
LIMIT 500;
