with MARGIN_ACCOUNT as (
    select
    a.Agt_Id as KEY_MRG_ACCT_ID,
    substr(Agt_Holder,8) as KEY_CTPTY_ID,
    Crrc_Cd as CURRENCY,
    nvl(b.SRC_CD_VAL,Agt_Stat_Cd) as ENABLED,
    c.Stati_Qty_Info as mg_acct_code,
    d.Shor_Name_Ch as ctpty_short_name,
    d.Full_Name_Ch as ctpty_long_name,
    f.Stati_Cont_Desc as CTPTY_DEPARTMENT
    from
    (select Agt_Id,Agt_Holder,Crrc_Cd,Agt_Stat_Cd
    from pdata_n.T03_AGT
    where SRC_TBL = 'ODATA_N_TIT.D_MARGIN_ACCOUNT' and del_flag != '1') a
    left join (
    SELECT SRC_CD_VAL,DW_CD_VAL
     FROM PDATA_N.REF_CD_CVT_MAP
     WHERE TGT_TAB_NAME = 'T03_AGT'
        AND TGT_TAB_FLD  = 'Agt_Stat_Cd'
        AND SRC_TAB_NAME = 'MARGIN_ACCOUNT'
        AND SRC_FLD_NAME = 'ENABLED'
        AND SRC_SYS_NAME='TIT'
    ) b on Agt_Stat_Cd = DW_CD_VAL
    join (
        select Agt_Id, Stati_Qty_Info
        from PDATA_N.T03_AGT_STATI_INFO_H
        where Strt_Date <= '${yyyy-MM-dd}' and End_Date > '${yyyy-MM-dd}'
        and src_tbl = 'ODATA_N_TIT.D_MARGIN_ACCOUNT'
    ) c on a.Agt_Id = c.Agt_Id
    join (
        select  Pty_Id, Shor_Name_Ch,Full_Name_Ch from PDATA_N.T01_PTY_NAME
        where SRC_TBL='ODATA_N_TIT.D_REF_COUNTER_PARTY' and BUSI_DATE='${yyyy-MM-dd}'
    ) d on a.Agt_Holder = d.Pty_Id
    join (
        select Pty_Id,Stati_Cont_Desc
        from PDATA_N.T01_PTY_STATI_INFO_H
        where SRC_TBL = 'ODATA_N_TIT.D_REF_COUNTER_PARTY'
        and Strt_Date <= '${yyyy-MM-dd}' and End_Date > '${yyyy-MM-dd}'
        and Pty_Stati_Info_Type_Cd='36'
    ) f on a.Agt_Holder = f.Pty_Id
),
TRD_BUNDLE_INFO as (
select Agt_Grp_Id AS BUNDLE_ID
from PDATA_N.T03_OTC_DERI_COMP_COMB_ADTNL_INFO
where SRC_TBL='ODATA_N_TIT.D_TRD_BUNDLE_INFO'
),
MARGIN_ACCT_BUNDLE_MAPPING as (
select  Agt_Grp_Id AS BUNDLE_ID,Marg_Acct_Agt_Id AS KEY_MRG_ACCT_ID
from PDATA_N.T03_OTC_DERI_AGT_AGT_GRP_RELA_ADTNL_INFO
where SRC_TBL = 'ODATA_N_TIT.D_MARGIN_ACCT_BUNDLE_MAPPING'
and BUSI_DATE='${yyyy-MM-dd}'
),
REF_RMB_MIDRATE as (
select src_crrc_cd CURRENCY,default.datekey2date(trd_dt) QUOTE_DATE, mid_price MIDRATE
from pdata_news_n.t02_fxr_cfets_quot
where src_id='TIT' and grp_id = '01' and src_tbl= 'odata_n_tit.d_ref_rmb_midrate'
),
TRD_OTC_TRADE as (
    select a.Agt_Id KEY_OTC_TRADE_ID,a.Stati_Cont_Desc as INTERNAL_TRADE_ID,b.Rela_Agt_Id as KEY_BOOK_ID
    from (
        select Agt_Id ,Stati_Cont_Desc
        from PDATA_N.T03_AGT_STATI_INFO_H
        where SRC_TBL  = 'ODATA_N_TIT.D_TRD_OTC_TRADE'
        and Strt_Date <= '${yyyy-MM-dd}' and End_Date > '${yyyy-MM-dd}'
    ) a join (
        select Agt_Id,Rela_Agt_Id
        from PDATA_N.T03_AGT_RELA_H
        where SRC_TBL = 'ODATA_N_TIT.D_TRD_OTC_TRADE'
        and Strt_Date <= '${yyyy-MM-dd}' and End_Date > '${yyyy-MM-dd}'
    ) b on a.Agt_Id = b.Agt_Id
),
REF_BOOK as (
    select Book_Agt_Id KEY_BOOK_ID,Bel_Dept DEPARTMENT
    from PDATA_N.T03_OTC_DERI_BOOK_ADTNL_INFO
    where SRC_TBL='ODATA_N_TIT.D_REF_BOOK' and BUSI_DATE='${yyyy-MM-dd}'
),
-- NDS
MARGIN_BUNDLE_ACCT as (
    select
    Portfl_Id as BUNDLE_ID,
    Mtm_Crrc as MTM_CURRENCY,
    Key_Cutp_Id as KEY_CTPTY_ID,
    Key_Plan_Id as KEY_PLAN_ID,
    Portfl_Compnt as TRD_COMPOSITION
    from PDATA_NDS.MARGIN_BUNDLE_ACCT
    where busi_date='${yyyy-MM-dd}'
),
MARGIN_ACCT_CURRENT_BALANCE as (
select KEY_MRG_ACCT_ID AS KEY_MRG_ACCT_ID,BALANCE AS BALANCE
from PDATA_NDS.MARGIN_ACCT_CURRENT_BALANCE
where busi_date='${yyyy-MM-dd}'
),
BUNDLE_MARGIN_DAILY_RESULT as (
    select
     src_BUSI_DATE BUSI_DATE
    ,BUNDLE_ID
    ,DYNAMIC_NOTIONAL
    ,MGR_BALANCE
    ,MRG_WITHDRAWED
    ,MRG_RATE
    ,MGR_STATUS
    ,MGR_REMARGINABLE
    ,ADVANCE_AMOUNT
    ,IS_CALC
    ,UPDATED_DATETIME
    ,BUSI_TYPE
    ,SUPPORT_MARGIN
    ,MARGIN_GREEKS
    ,CALL_REQUIRE
    ,WITHDRAW_REQUIRE
    from PDATA_NDS.BUNDLE_MARGIN_DAILY_RESULT
    where busi_date = '${yyyy-MM-dd}' -- and IS_CALC = 'Y'
),
BUNDLE_DAILY_CONTR_PARAM as (
select
Portfl_Id as BUNDLE_ID,
Src_Busi_Ddate as BUSI_DATE,
Key_Otc_Trd_Id as KEY_OTC_TRADE_ID,
Key_Inst_Id as KEY_INSTRUMENT_ID,
Marg_Init_Line as INITIAL_MARGIN,
Marg_Warn_Line as WARNING,
Marg_Call_Line as MARGIN_CALL,
Marg_Wthdr_Line as WITHDRAW,
Marg_Wthdr_Flr as WITHDRAW_FLOOR,
Marg_Call_Flr as MARGIN_CALL_FLOOR,
Float_Pal as FLOAT_PNL,
Inr_Val as INNER_VALUE,
Undrl_Info as UNDERLYING_INFO,
Fee as FEE,
Accrued_Intr as ACCRUED_INTEREST,
Mval as MARKET_VALUE,
Is_Portfl_View as IS_BUNDLE_VIEW,
Bsc_Marg_Rate as BASIC_MARGIN_RATE,
Present_Val as PV,
Present_Val_1 as PV1,
Present_Val_2 as PV2,
Present_Val_3 as PV3,
Present_Val_4 as PV4,
Present_Val_5 as PV5,
Present_Val_6 as PV6
from PDATA_NDS.BUNDLE_DAILY_CONTR_PARAM
where busi_date = '${yyyy-MM-dd}'
),
MARGIN_PLAN as (
select Plan_Id as ID,Cust_Rati as CUSTOM_RATIO
from PDATA_NDS.MARGIN_PLAN
WHERE BUSI_DATE='${yyyy-MM-dd}'
),
CURRENT_BALANCE_T AS (
SELECT
T.BUNDLE_ID ,
T.MTM_CURRENCY,
SUM(T.CURRENT_BALANCE * NVL(rrm1.MIDRATE,1) / NVL(rrm2.MIDRATE,1)) AS CURRENT_BALANCE
FROM (
    SELECT
    TBI.BUNDLE_ID ,
    MB.BUSI_DATE,
    BM.KEY_MRG_ACCT_ID ,
    MB.CURRENCY,
    BA.MTM_CURRENCY,
    MB.balance AS CURRENT_BALANCE
    FROM TRD_BUNDLE_INFO tbi
    JOIN MARGIN_ACCT_BUNDLE_MAPPING BM
    ON TBI.BUNDLE_ID = BM.BUNDLE_ID
    JOIN MARGIN_BUNDLE_ACCT BA
    ON TBI.BUNDLE_ID = BA.BUNDLE_ID
    JOIN (
    SELECT
        MA.KEY_MRG_ACCT_ID,
        default.pretradedate(date_add('${yyyy-MM-dd}',1),1) AS BUSI_DATE,-- 取当前日期的最近一天交易日,这里变更为业务时间的最近交易日
        MA.mg_acct_code,
        MA.key_ctpty_id,
        MA.CURRENCY,
        NVL(CB.balance,0) AS balance
        FROM MARGIN_ACCOUNT ma
        LEFT JOIN MARGIN_ACCT_CURRENT_BALANCE CB
        ON MA.KEY_MRG_ACCT_ID = CB.KEY_MRG_ACCT_ID
        WHERE MA.ENABLED = 'Y'
    ) MB ON BM.KEY_MRG_ACCT_ID  = MB.KEY_MRG_ACCT_ID
) T
LEFT JOIN REF_RMB_MIDRATE rrm1
ON T.CURRENCY = RRM1.CURRENCY
AND T.BUSI_DATE = RRM1.QUOTE_DATE
LEFT JOIN REF_RMB_MIDRATE RRM2
ON T.BUSI_DATE = RRM2.QUOTE_DATE
AND T.MTM_CURRENCY = RRM2.CURRENCY
GROUP BY T.BUNDLE_ID ,T.MTM_CURRENCY
),
BUNDLE_UNDERLYING as (
    select
    BUNDLE_ID,BUSI_DATE,
    SUBSTRING(
        CONCAT_WS(' ',
          SORT_ARRAY(
            COLLECT_LIST(trim(UNDERLYING_INFO)),
            TRUE
          )
        ),1,2000) AS UNDERLYING_INFO
    from (
    select BUNDLE_ID,BUSI_DATE,UNDERLYING_INFO
    from BUNDLE_DAILY_CONTR_PARAM
    where UNDERLYING_INFO != '-'
    group by BUNDLE_ID,BUSI_DATE,UNDERLYING_INFO
    ) group by BUNDLE_ID,BUSI_DATE
),
BUNDLE_UNDERLYING_TYPE as (
SELECT
  BUNDLE_ID,
  CONCAT_WS(
    ';',
    SORT_ARRAY(COLLECT_LIST(INTEROTC_CODE))
  ) AS UNDERLYING_TYPE
FROM (
  SELECT DISTINCT
    Portfl_Id BUNDLE_ID,
    CASE WHEN In_OTC_Cd = 'CODE_00' THEN '00:上海主板股票'
    WHEN In_OTC_Cd = 'CODE_01' THEN '01:深圳主板股票'
    WHEN In_OTC_Cd = 'CODE_02' THEN '02:深圳中小板股票'
    WHEN In_OTC_Cd = 'CODE_03' THEN '03:创业板股票'
    WHEN In_OTC_Cd = 'CODE_04' THEN '04:新三板挂牌股票'
    WHEN In_OTC_Cd = 'CODE_05' THEN '05:港股股票'
    WHEN In_OTC_Cd = 'CODE_06' THEN '06:北美市场股票'
    WHEN In_OTC_Cd = 'CODE_07' THEN '07:欧洲市场股票'
    WHEN In_OTC_Cd = 'CODE_08' THEN '08:其他境外股票'
    WHEN In_OTC_Cd = 'CODE_09' THEN '09:Shibor'
    WHEN In_OTC_Cd = 'CODE_10' THEN '10:银行间回购定盘利率（FixingRepoRate）'
    WHEN In_OTC_Cd = 'CODE_11' THEN '11:其他利率'
    WHEN In_OTC_Cd = 'CODE_12' THEN '12:期货'
    WHEN In_OTC_Cd = 'CODE_13' THEN '13:基金及基金专户'
    WHEN In_OTC_Cd = 'CODE_14' THEN '14:地方性交易场所挂牌交易产品'
    WHEN In_OTC_Cd = 'CODE_15' THEN '15:沪深300指数'
    WHEN In_OTC_Cd = 'CODE_16' THEN '16:中证100指数'
    WHEN In_OTC_Cd = 'CODE_17' THEN '17:中证200指数'
    WHEN In_OTC_Cd = 'CODE_18' THEN '18:中证500指数'
    WHEN In_OTC_Cd = 'CODE_19' THEN '19:中证700指数'
    WHEN In_OTC_Cd = 'CODE_20' THEN '20:上证180指数'
    WHEN In_OTC_Cd = 'CODE_21' THEN '21:上证50指数'
    WHEN In_OTC_Cd = 'CODE_22' THEN '22:上证380指数'
    WHEN In_OTC_Cd = 'CODE_23' THEN '23:超大盘指数'
    WHEN In_OTC_Cd = 'CODE_24' THEN '24:上证中盘指数'
    WHEN In_OTC_Cd = 'CODE_25' THEN '25:深证成份指数'
    WHEN In_OTC_Cd = 'CODE_26' THEN '26:中小板指数'
    WHEN In_OTC_Cd = 'CODE_27' THEN '27:创业板指数'
    WHEN In_OTC_Cd = 'CODE_28' THEN '28:深证100指数'
    WHEN In_OTC_Cd = 'CODE_29' THEN '29:深证300指数'
    WHEN In_OTC_Cd = 'CODE_30' THEN '30:中创500指数'
    WHEN In_OTC_Cd = 'CODE_31' THEN '31:其他指数'
    WHEN In_OTC_Cd = 'CODE_32' THEN '32:汇率'
    WHEN In_OTC_Cd = 'CODE_33' THEN '33:贵金属'
    WHEN In_OTC_Cd = 'CODE_34' THEN '34:大宗商品'
    WHEN In_OTC_Cd = 'CODE_35' THEN '35:可转债'
    WHEN In_OTC_Cd = 'CODE_36' THEN '36:期权'
    WHEN In_OTC_Cd = 'CODE_37' THEN '37:其他衍生品'
    WHEN In_OTC_Cd = 'CODE_38' THEN '38:恒生大型成分股'
    WHEN In_OTC_Cd = 'CODE_39' THEN '39:除恒生大型成分股外的港股'
    WHEN In_OTC_Cd = 'CODE_40' THEN '40:北京主板股票'
    WHEN In_OTC_Cd = 'CODE_99' THEN '99:其他标的'
    ELSE In_OTC_Cd  END INTEROTC_CODE
  FROM PDATA_NDS.BUNDLE_MARGIN_UNDERLYING_TYPE
  WHERE BUSI_DATE = '${yyyy-MM-dd}'
) distinct_data
GROUP BY BUNDLE_ID
)

SELECT src_busi_date,
	BUNDLE_ID,
	INTERNAL_TRADE_ID,
	UNDERLYING_INFO,
	INTEROTC_NAME,
	BUSI_TYPE,
	MTM_CURRENCY,
	CTPTY_SHORT_NAME,
	DYNAMIC_NOTIONAL,
	MGR_BALANCE,
	CURRENT_BALANCE,
	MRG_WITHDRAWED,
	MRG_RATE,
	MGR_STATUS,
	MGR_REMARGINABLE,
	INITIAL_MARGIN,
	WARNING,
	MARGIN_CALL,
	WITHDRAW,
	WITHDRAW_FLOOR,
	MARGIN_CALL_FLOOR,
	BASIC_MARGIN_RATE,
	NOTIONAL1,
	FLOAT_PNL,
	INNER_VALUE,
	MARK_INNER_VALUE,
	UNPAY_FEE,
	FEE,
	ACCRUED_INTEREST,
	NOTIONAL_OR_VALUE,
	NOTIONAL2,
	MARKET_VALUE,
	UPDATED_DATETIME,
	ADVANCE_AMOUNT,
	ADD_REMARGINABLE,
	ADVANCE_STATUS,
	SUPPORT_MARGIN,
	MARGIN_GREEKS,
	CUSTOM_RATIO,
	CALL_REQUIRE,
	MARGIN_REQUIRE,
	WITHDRAW_REQUIRE,
	PV,
	PV1,
	PV2,
	PV3,
	PV4,
	PV5,
	PV6,
	IS_CALC,
	TRD_COMPOSITION,
	DEPARTMENT,
	CTPTY_LONG_NAME,
	KEY_CTPTY_ID,
	busi_date FROM (
	 


SELECT
DR.BUSI_DATE as src_busi_date, --日期
DR.BUNDLE_ID, --组合编号
TOT.INTERNAL_TRADE_ID, --合约编号
BU.UNDERLYING_INFO AS UNDERLYING_INFO, --标的证券
BUT.UNDERLYING_TYPE AS INTEROTC_NAME, --标的类型
CASE WHEN DR.BUSI_TYPE = 'DIGITAL' THEN '二值'
WHEN DR.BUSI_TYPE = 'EUROPEAN_VANILLA' THEN '欧式香草'
WHEN DR.BUSI_TYPE = 'SPREAD' THEN '价差'
WHEN DR.BUSI_TYPE = 'SHARKFIN' THEN '鲨鱼鳍'
WHEN DR.BUSI_TYPE = 'BUTTERFLY' THEN '蝶式'
WHEN DR.BUSI_TYPE = 'STRADDLE' THEN '跨式'
WHEN DR.BUSI_TYPE = 'BARRIER' THEN '障碍'
WHEN DR.BUSI_TYPE = 'DAILYRANGEACCRUAL' THEN '区间累积'
WHEN DR.BUSI_TYPE = 'AUTOCALL' THEN '自动赎回'
WHEN DR.BUSI_TYPE = 'AIRBAG' THEN '安全气囊'
WHEN DR.BUSI_TYPE = 'RISKY' THEN 'Risky'
WHEN DR.BUSI_TYPE = 'AMERICAN_VANILLA' THEN '美式香草'
WHEN DR.BUSI_TYPE = 'PARTICIPATORY' THEN '参与型看涨'
WHEN DR.BUSI_TYPE = 'AIRBAGX' THEN '安全气囊X'
WHEN DR.BUSI_TYPE = 'LADDER_CALL' THEN '阶梯看涨'
WHEN DR.BUSI_TYPE = 'ACCUMULATOR' THEN '累购'
WHEN DR.BUSI_TYPE = 'DECCUMULATOR' THEN '累沽'
WHEN DR.BUSI_TYPE = 'AIRBAGL' THEN '安全气囊L'
WHEN DR.BUSI_TYPE = 'KIPUT' THEN '敲入看跌'
WHEN DR.BUSI_TYPE = 'AIRBAGM' THEN '安全气囊M'
WHEN DR.BUSI_TYPE = 'CUSTOMISED' THEN '自定义'
WHEN DR.BUSI_TYPE = 'CALL_SWAP' THEN '多头互换'
WHEN DR.BUSI_TYPE = 'PUT_SWAP' THEN '空头互换'
WHEN DR.BUSI_TYPE = 'LEND_SWAP' THEN '借券互换'
WHEN DR.BUSI_TYPE = 'INDEX_ENHANCE_SWAP' THEN '指数增强'
WHEN DR.BUSI_TYPE = 'S_CROSS_SWAP' THEN '南下跨境'
WHEN DR.BUSI_TYPE = 'N_CROSS_SWAP' THEN '北上跨境'
WHEN DR.BUSI_TYPE = 'CROSS_LEND_SWAP' THEN '跨境借券'
WHEN DR.BUSI_TYPE = 'AB_LONG_SWAP' THEN '项目多头'
WHEN DR.BUSI_TYPE = 'AB_SHORT_SWAP' THEN '项目空头'
WHEN DR.BUSI_TYPE = 'LONG_HOLD_SWAP' THEN '多头持券'
WHEN DR.BUSI_TYPE = 'N_CROSS_QFII_SWAP' THEN '北上QFII'
WHEN DR.BUSI_TYPE = 'N_CROSS_FUTURE_SWAP' THEN '北上跨境(期货)'
WHEN DR.BUSI_TYPE = 'S_CROSS_FUTURE_SWAP' THEN '南下跨境(期货)'
WHEN DR.BUSI_TYPE = 'CHN_FUTURE_SWAP' THEN '境内互换(期货)'
WHEN DR.BUSI_TYPE = 'FEE_SWAP' THEN '互换费用'
WHEN DR.BUSI_TYPE = 'HK_LONG_HOLD_SWAP' THEN '香港多头持券'
WHEN DR.BUSI_TYPE = 'S_CROSS_OPTION_SWAP' THEN '南下跨境(场内期权)'
WHEN DR.BUSI_TYPE = 'SBL' THEN 'SBL'
WHEN DR.BUSI_TYPE = 'LONG_SHORT_SWAP' THEN '多空互换'
WHEN DR.BUSI_TYPE = 'N_CROSS_DMA_SWAP' THEN '北上极速'
WHEN DR.BUSI_TYPE = 'FLAT_LONG_SHORT_SWAP' THEN '平层多空'
WHEN DR.BUSI_TYPE = 'DOMESTIC_DMA_SHORT_SWAP' THEN '境内空头(极速)'
WHEN DR.BUSI_TYPE = 'DOMESTIC_DMA_LONG_SWAP' THEN '境内多头(极速)'
WHEN DR.BUSI_TYPE = 'S_CROSS_DMA_SHORT_SWAP' THEN '南下空头(极速)'
WHEN DR.BUSI_TYPE = 'S_CROSS_DMA_LONG_SWAP' THEN '南下多头(极速)'
WHEN DR.BUSI_TYPE = 'CHN_BOND_SWAP' THEN '境内互换(债券)'
WHEN DR.BUSI_TYPE = 'Regular' THEN '普通组合'
WHEN DR.BUSI_TYPE = 'ShortNORMAL' THEN '普通借券'
WHEN DR.BUSI_TYPE = 'ShortDT' THEN '可转债套利'
WHEN DR.BUSI_TYPE = 'LSDMA' THEN '多空互换'
WHEN DR.BUSI_TYPE = 'CSTLendswap' THEN '多空组合'
WHEN DR.BUSI_TYPE = 'CSTLLSnoowball' THEN '券抵不追保雪球'
WHEN DR.BUSI_TYPE = 'CSTOption' THEN '券抵期权'
WHEN DR.BUSI_TYPE = 'N_CROSS_AB_SWAP' THEN '北上产品'
WHEN DR.BUSI_TYPE = 'S_CROSS_FUTURE_SWAP' THEN '南下跨境期货'
WHEN DR.BUSI_TYPE = 'SPDTRS' THEN '互换极速'
WHEN DR.BUSI_TYPE = 'NSPDTRS' THEN '北上极速'
WHEN DR.BUSI_TYPE = 'N_CROSS_FUTURE_SWAP' THEN '北上跨境期货'
When DR.BUSI_TYPE = 'OTHERS' THEN '其它'
ELSE DR.BUSI_TYPE END AS BUSI_TYPE, --业务类型!
BA.MTM_CURRENCY, --盯市币种
CTPTY.CTPTY_SHORT_NAME, --交易对手
DR.DYNAMIC_NOTIONAL, --名义本金
DR.MGR_BALANCE, --批次保证金余额
CB.CURRENT_BALANCE, --实时保证金余额
DR.MRG_WITHDRAWED, --可提取保证金
DR.MRG_RATE, --履约保障比例(%)
CASE WHEN DR.MGR_STATUS = 0 THEN '正常'
WHEN DR.MGR_STATUS = '1' THEN '预警'
WHEN DR.MGR_STATUS = '2' THEN '追保'
WHEN DR.MGR_STATUS = '3' THEN '未知'
WHEN DR.MGR_STATUS = '4' THEN '平仓'
ELSE DR.MGR_STATUS END AS MGR_STATUS,--履保状态
DR.MGR_REMARGINABLE, --需追加金额
CP.INITIAL_MARGIN,--保证金初始线(%)
CP.WARNING, --保证金预警线(%)
CP.MARGIN_CALL, --保证金追保线(%)
CP.WITHDRAW, --保证金提取线(%)
CP.WITHDRAW_FLOOR, --保证金提取维持线(%)
CP.MARGIN_CALL_FLOOR, --保证金追保维持线(%)
CP.BASIC_MARGIN_RATE, --基础保证金率(%)
DR.DYNAMIC_NOTIONAL AS NOTIONAL1, --名义本金1
CP.FLOAT_PNL, --收益
CP.INNER_VALUE, --内在价值
CP.INNER_VALUE AS MARK_INNER_VALUE, --盯市价值
CP.FEE AS UNPAY_FEE, --应付未付费用
CP.FEE, --费用
CP.ACCRUED_INTEREST, --累计应计利息
DR.DYNAMIC_NOTIONAL AS NOTIONAL_OR_VALUE, --分母的动态名义本金或市值
'0' AS NOTIONAL2, --名义本金2
CP.MARKET_VALUE, --浮动市值
DR.UPDATED_DATETIME, --最近一次计算时间
DR.ADVANCE_AMOUNT, --垫资金额
DR.MGR_REMARGINABLE + NVL(DR.ADVANCE_AMOUNT,0) AS ADD_REMARGINABLE, --合计应追加金额
CASE WHEN DR.ADVANCE_AMOUNT > 0 THEN '是'
WHEN DR.ADVANCE_AMOUNT <= 0 THEN '否' END AS ADVANCE_STATUS, --垫资状态
DR.SUPPORT_MARGIN, --履保类型
DR.MARGIN_GREEKS, --保证金敞口
MP.CUSTOM_RATIO, --客户系数
DR.CALL_REQUIRE,--履约保障要求
DR.CALL_REQUIRE AS MARGIN_REQUIRE,--追保维持要求
DR.WITHDRAW_REQUIRE, --提取维持要求
CP.PV, -- pv
CP.PV1, -- pv1
CP.PV2, -- pv2
CP.PV3, -- pv3
CP.PV4, -- pv4
CP.PV5, -- pv5
CP.PV6, -- pv6
DR.IS_CALC, -- 是否履保
BA.TRD_COMPOSITION, -- 用途
RB.DEPARTMENT, -- 所属部门
CTPTY.CTPTY_LONG_NAME, -- 交易对手长名
BA.KEY_CTPTY_ID,  --交易对手ID
'${yyyy-MM-dd}' as busi_date
FROM
BUNDLE_MARGIN_DAILY_RESULT DR
left JOIN (select *
from BUNDLE_DAILY_CONTR_PARAM
where IS_BUNDLE_VIEW = 'Y'
-- AND KEY_INSTRUMENT_ID <> '-'
) CP
ON DR.BUNDLE_ID = CP.BUNDLE_ID
AND to_date(DR.BUSI_DATE) = to_date(CP.BUSI_DATE)
INNER JOIN MARGIN_BUNDLE_ACCT BA ON DR.BUNDLE_ID = BA.BUNDLE_ID AND BA.TRD_COMPOSITION IN ('OPTION','TRS','MIXTURE','N_CROSS_DMA')
INNER JOIN (SELECT DISTINCT BUNDLE_ID FROM MARGIN_ACCT_BUNDLE_MAPPING) MCB ON MCB.BUNDLE_ID = DR.BUNDLE_ID
LEFT JOIN (
SELECT KEY_CTPTY_ID,MAX(CTPTY_SHORT_NAME) CTPTY_SHORT_NAME,max(CTPTY_LONG_NAME) CTPTY_LONG_NAME, MAX(CTPTY_DEPARTMENT) CTPTY_DEPARTMENT
FROM MARGIN_ACCOUNT ma
GROUP BY KEY_CTPTY_ID
) CTPTY ON CTPTY.KEY_CTPTY_ID = BA.KEY_CTPTY_ID
LEFT JOIN TRD_OTC_TRADE TOT
ON CP.KEY_OTC_TRADE_ID = TOT.KEY_OTC_TRADE_ID
LEFT JOIN REF_BOOK RB
ON TOT.KEY_BOOK_ID = RB.KEY_BOOK_ID
LEFT JOIN MARGIN_PLAN MP
ON BA.KEY_PLAN_ID = MP.ID
LEFT JOIN CURRENT_BALANCE_T CB
ON DR.BUNDLE_ID = CB.BUNDLE_ID
LEFT JOIN BUNDLE_UNDERLYING BU
ON DR.BUNDLE_ID = BU.BUNDLE_ID and DR.BUSI_DATE = BU.BUSI_DATE
LEFT JOIN BUNDLE_UNDERLYING_TYPE BUT
ON DR.BUNDLE_ID = BUT.BUNDLE_ID 
	) castTable