-- GENERATED by ../render.mjs; edit the branch main SQL and its includes.
-- 230202 期权客户创收：下面SELECT先列输出，FROM之后显示这些字段来自哪里。
-- 阅读主线：01合约日 → 02费用客户／03对冲盈亏／04市场利率汇率／05成本参数（并列）→ 06当日创收、07NPV → 09输出。
-- CASE先判断气囊，再动态、静态；07的NPV独立判断柜台，并非06的剩余分支。
-- 只按原查询位置抽取片段；不新增CTE、去重、提前过滤或生产视图。
-- 外层只按目标表顺序投影74列；字段清单不遮住下面的加工主线。
-- 目标表74列的外层投影，不计算收入。末尾打开内层FROM，主脚本结尾闭合为castTable。
SELECT Agt_Id,
	Busi_Type,
	Cutp_Pty_Id,
	Cutp_Pty_Shor_Name,
	Cutp_Pty_Full_Name,
	Sign_Prd_Name,
	USCC,
	Contr_Type_Cd,
	Contr_Type_Desc,
	Src_Contr_Type,
	Src_Contr_Type_Desc,
	Src_Sub_Contr_Type,
	Src_Sub_Contr_Type_Desc,
	Undrl_Wd_Cd,
	Undrl_Name,
	Init_Nom_Prin,
	Dyna_Nom_Prin,
	Curr_Rev,
	Opt_Npv_Curr_Rev,
	Strt_Pric_Date,
	End_Pric_Date,
	Is_Preterm_Flag,
	Early_Term_Date,
	Agt_Stat_Cd,
	Accrued_Date,
	Inr_Seri_No,
	otc_seri_no,
	Book_Agt_Id,
	Cntr,
	Cros_Crrc_Type_Cd,
	fixed_rate,
	Flot_Intrt_Ulmt,
	Float_Base_Rate,
	Intr_Marg,
	Float_Undrl_Cd,
	Undrl_Curr,
	Bgng_Npv,
	prop_group,
	Opt_Fee_Rate,
	Init_Marg_Prop,
	Base_Marg_Rate,
	Marg_Agt_Id,
	FUND_COST_RATE,
	MARGIN_FIXED_RATE,
	COMMISSION_COST,
	SPREAD,
	LONG_FIXED_RATE,
	CAPITAL_COST,
	Cms_Mode_Cd,
	Trd_Fee_Rate,
	Bgng_Vol,
	Peshr_Cms,
	Nom_Prin_Chg_Delta,
	Occu_Qty,
	Divd_Tax_Amt,
	intrt,
	ir,
	Tdy_Yield,
	Simu_Hedg_Pal,
	prop_ratio,
	Map_Undrl_Cd,
	Undrl_Tdy_Yield,
	Undrl_Simu_Hedg_Pal,
	Sett_Crrc_Cd,
	mid_price,
	OTHER_Prvs_Fee,
	PREMIUM_Prvs_Fee,
	Data_Time,
	Trd_Cms,
	Rev_Contr_Type_Cd,
	Agt_Clas_Cd,
	Src_Undrl_Type,
	busi_date,
	grp_id FROM (

select
-- SELECT前17列：info来自01合约主信息；cp公司客户、det逐日明细的实际查询与连接在00。
-- 初始本金输出info.Init_Nom_Prin；动态本金输出COALESCE(det.Dyna_Nom_Prin,0)。
-- 这个动态本金补0只作用展示列，06气囊公式仍直接读det.Dyna_Nom_Prin，不能把两者混同。
    info.Agt_Id,  --合约编号
    info.Busi_Type,  --业务类型
    info.Cutp_Pty_Id,  --交易对手客户编号
    info.Cutp_Pty_Shor_Name,  --交易对手当事人简称
    info.Cutp_Pty_Full_Name,  --交易对手当事人名称
    info.Sign_Prd_Name,  --代签产品名称
    cp.USCC,  --统一社会信用代码
    info.Contr_Type_Cd,  --合约类型代码
    info.Contr_Type_Desc,  --合约类型描述
    info.Src_Contr_Type,  --源合约类型
    info.Src_Contr_Type_Desc,  --源合约类型描述
    info.Src_Sub_Contr_Type,  --源合约子类型
    info.Src_Sub_Contr_Type_Desc,  --源合约子类型描述
    info.Undrl_Wd_Cd,  --标的万得代码
    info.Undrl_Name,  --标的名称
    info.Init_Nom_Prin,  --初始名义本金
    coalesce(det.Dyna_Nom_Prin, 0) as Dyna_Nom_Prin,  --动态名义本金

-- SELECT表达式片段；info=01主合约；det=00直接连接的逐日明细；fee=02每日费用。
-- u=03标的盈亏池，cr=04参考利率，co/co_c=05/05.1成本；pe/pd模拟对冲/持仓、mid汇率的来源和全部ON均在00。
-- 优先顺序：三种气囊 → 动态柜台 → 静态柜台 → 0。窗口仍基于FROM全部连接结果，不因CASE分支提前缩小行集。
case
    -- 1. 气囊人民币标的，或HKD标的且COMPOSITE：按预估期权费率扣CNY成本。
    -- 无关联合约时校正因子=1；有关联时=(1-初保线)/(1-基保线)。不是按本金直接扣365天成本。
    when info.Src_Contr_Type in ('RISKY','AIRBAGX')
        and (info.Undrl_Curr = 'CNY' or (info.Cros_Crrc_Type_Cd = 'COMPOSITE' and info.Undrl_Curr = 'HKD'))
    then (
        fee.OTHER_Prvs_Fee
        + if(cast(fee.PREMIUM_Prvs_Fee as double) <= 0, 0,
            fee.PREMIUM_Prvs_Fee * (
                1 - 1 / info.Opt_Fee_Rate * co_c.CAPITAL_COST
                    / if(coalesce(info.Marg_Agt_Id,'') = '', 1,
                        (1 - info.Init_Marg_Prop)/(1 - info.Base_Marg_Rate))
            )
        )
    ) * coalesce(mid.mid_price,1)

    -- 2. 其余气囊且FLEXO：期权费减去逐日本金×净成本/365。
    -- cr.ir/100=百分数转比例；净成本=参考利率+非CNY成本-保证金比例×CNY成本。
    -- 无关联用初保线，有关联用基保线；直接读det.Dyna_Nom_Prin，不用08展示列的补0值。
    when info.Src_Contr_Type in ('RISKY','AIRBAGX') and info.Cros_Crrc_Type_Cd = 'FLEXO'
    then (
        fee.OTHER_Prvs_Fee
        + if(cast(fee.PREMIUM_Prvs_Fee as double) <= 0, 0,
            fee.PREMIUM_Prvs_Fee
            - det.Dyna_Nom_Prin * (
                coalesce(cr.ir/100,0) + co.CAPITAL_COST
                - if(coalesce(info.Marg_Agt_Id,'') = '', info.Init_Marg_Prop, info.Base_Marg_Rate)
                    * co_c.CAPITAL_COST
            ) / 365
        )
    ) * coalesce(mid.mid_price,1)

    -- 3. 剩余气囊：固定0.035替代“参考利率+非CNY成本”，再减保证金抵减部分。
    -- 0.035与365按程序保留，制度来源待确认；不推断是当前市场报价或真实天数制。
    when info.Src_Contr_Type in ('RISKY','AIRBAGX')
    then (
        fee.OTHER_Prvs_Fee
        + if(cast(fee.PREMIUM_Prvs_Fee as double) <= 0, 0,
            fee.PREMIUM_Prvs_Fee
            - det.Dyna_Nom_Prin * (
                0.035 - if(coalesce(info.Marg_Agt_Id,'') = '', info.Init_Marg_Prop, info.Base_Marg_Rate)
                    * co_c.CAPITAL_COST
            ) / 365
        )
    ) * coalesce(mid.mid_price,1)

    -- 4. 动态对冲：本合约模拟对冲盈亏＋本合约持仓盈亏＋delta权重×标的残差，再按本行汇率转换。
    -- 权重=abs(delta)/组内abs(delta)合计；残差=u标的盈亏-组内模拟盈亏。
    -- 组键pe.Undrl_Sum_Compr+pe.busi_date；绝对delta合计为0时没有保护条件。
    when info.Cntr = 'DYNAMIC_HEDGING'
    then (
        coalesce(pe.Simu_Hedg_Pal,0) + coalesce(pd.Tdy_Yield,0)
        + abs(coalesce(pe.delta,0))
            / sum(abs(coalesce(pe.delta,0))) over(partition by pe.Undrl_Sum_Compr, pe.busi_date)
            * (
                coalesce(u.Tdy_Yield,0)
                - sum(coalesce(pe.Simu_Hedg_Pal,0)) over(partition by pe.Undrl_Sum_Compr, pe.busi_date)
            )
    ) * coalesce(mid.mid_price,1)

    -- 5. 静态对冲：det初始本金/组内info初始本金 × 组内已换成人民币的持仓盈亏。
    -- 三个指定客户只在分母置0，分子和盈亏合计未同样剔除，不能声称所有输出加总必守恒。
    when info.Cntr = 'STATIC_HEDGING'
    then coalesce(det.Init_Nom_Prin, 0)
        / sum(if(info.Cutp_Pty_Id in ('DEV1100101715','DEV1100103266','DEV1100105899'),0,
            coalesce(info.Init_Nom_Prin, 0))) over(partition by info.prop_group, det.busi_date)
        * sum(coalesce(coalesce(pd.Tdy_Yield,0) * coalesce(mid.mid_price,1), 0))
            over(partition by info.prop_group, det.busi_date)
    else 0
end AS Curr_Rev,

-- 独立于06的另一列，不自动加回Curr_Rev。只在本行期初定价日=det计提日时确认。
-- 动态柜台取info.Bgng_Npv×本日汇率；静态柜台按同组本金权重分配组内已换算的期初NPV。
-- 即使06先命中气囊，只要本行柜台符合，07仍会计算；不能把“气囊优先”误解成整行跳过NPV。
case
    when info.Cntr = 'DYNAMIC_HEDGING'
    then if(info.Strt_Pric_Date = det.busi_date,
        info.Bgng_Npv * coalesce(mid.mid_price,1), 0)
    when info.Cntr = 'STATIC_HEDGING'
    then if(info.Strt_Pric_Date = det.busi_date,
        coalesce(det.Init_Nom_Prin, 0)
            / sum(if(info.Cutp_Pty_Id in ('DEV1100101715','DEV1100103266','DEV1100105899'),0,
                coalesce(info.Init_Nom_Prin, 0))) over(partition by info.prop_group, det.busi_date)
            * sum(coalesce(info.Bgng_Npv * coalesce(mid.mid_price,1), 0))
                over(partition by info.prop_group, det.busi_date),
        0)
    else 0
end as Opt_Npv_Curr_Rev,

-- SELECT其余输出：保持原字段顺序，空占位也是当前程序行为，不等于已有相关业务计算。
-- End_Pric_Date使用COALESCE(提前终止日,原期末日)；空串不回退，虽然是否终止标志将空串判为0。
-- Accrued_Date=det.busi_date，busi_date=报告日快照，grp_id固定01；一份快照包含多个计提日。
-- prop_ratio/标的模拟对冲盈亏仍按pe标的组+日计算，非动态行也输出这些表达式，不宜解释为普适分摊比。
-- 展示CAPITAL_COST取co_c的CNY值；06 FLEXO公式另有co的非CNY成本，两者不能互相替代。
-- 当前平台新增Agt_Clas_Cd与Src_Undrl_Type已保留，外层共74列（含两个分区列）。
    info.Strt_Pric_Date,  --期初定价日
    coalesce(info.Early_Term_Date, info.End_Pric_Date) as End_Pric_Date,  --期末定价日
    IF(info.Early_Term_Date IS NULL OR info.Early_Term_Date = '', '0', '1') AS Is_Preterm_Flag,  --是否终止标志
    info.Early_Term_Date,  --提前终止日
    info.Agt_Stat_Cd,  --协议状态代码
    det.busi_date as Accrued_Date,  --计提日期
    info.Inr_Seri_No,  --内部流水号
    info.otc_seri_no,  --场外合约流水号
    info.Book_Agt_Id,  --账簿协议编号
    info.Cntr,  --柜台
    info.Cros_Crrc_Type_Cd,  --跨币种类型代码
    info.fixed_rate,  --固定腿利率
    info.Flot_Intrt_Ulmt,  --浮动利率上限
    info.Float_Base_Rate,  --浮动基础利率
    info.Intr_Marg,  --利差
    info.Float_Undrl_Cd,  --浮动腿标的代码
    info.Undrl_Curr,  --标的币种
    info.Bgng_Npv,  --期初NPV
    info.prop_group,  --关联合约分组
    info.Opt_Fee_Rate,  --期权预估期权费率
    info.Init_Marg_Prop,  --初保线
    info.Base_Marg_Rate,  --基保线
    info.Marg_Agt_Id,  --拆货基合约编号
    null as FUND_COST_RATE,  --资金成本利率
    null as MARGIN_FIXED_RATE,  --保证金固定利率
    null as COMMISSION_COST,  --佣金成本
    null as SPREAD,  --利差
    null as LONG_FIXED_RATE,  --多头持券固定利率成本
    co_c.CAPITAL_COST,  --CNY用资利率
    null as Cms_Mode_Cd,  --佣金模式代码
    null as Trd_Fee_Rate,  --交易费率
    null as Bgng_Vol,  --期初数量
    null as Peshr_Cms,  --每股佣金（标的币种）
    null as Nom_Prin_Chg_Delta,  --名义本金变动（结算币种）
    null as Occu_Qty,  --发生数量（结算币种）
    null as Divd_Tax_Amt,  --分红税金额（结算币种）
    null as intrt,  --浮动利率
    cr.ir/100 as ir,  --资金成本浮动利率
    pd.Tdy_Yield,  --当日盈亏（结算币种）
    pe.Simu_Hedg_Pal,  --模拟对冲盈亏（结算币种）
    abs(coalesce(pe.delta,0))/sum(abs(coalesce(pe.delta,0))) over(partition by pe.Undrl_Sum_Compr, pe.busi_date) as prop_ratio,  --分摊比例
    u.Map_Undrl_Cd,  --匹配标的代码
    coalesce(u.Tdy_Yield,0) as Undrl_Tdy_Yield,  --标的当日盈亏（结算币种）
    sum(coalesce(pe.Simu_Hedg_Pal,0)) over(partition by pe.Undrl_Sum_Compr, pe.busi_date) as Undrl_Simu_Hedg_Pal,  --标的模拟对冲盈亏（结算币种）
    info.Sett_Crrc_Cd,  --结算币种
    coalesce(mid.mid_price,1) as mid_price,  --人民币中间汇率
    fee.OTHER_Prvs_Fee,  --按日计提其他费
    fee.PREMIUM_Prvs_Fee,  --按日计提期权费
    from_unixtime(unix_timestamp(),'yyyy-MM-dd HH:mm:ss') AS Data_Time,  --数据时间
    null as Trd_Cms,  --交易佣金收入
    case when info.Src_Contr_Type in ('RISKY','AIRBAGX') then 'AIRBAGX'
         when info.Cntr in ('DYNAMIC_HEDGING','STATIC_HEDGING') then 'OPT_HEDGING'
         end as Rev_Contr_Type_Cd,
    info.Agt_Clas_Cd,  --协议类型代码
    info.Src_Undrl_Type,  --源标的类型
    '${yyyy-MM-dd}' as busi_date,  --业务日期
    '01' as grp_id  --分组标识

-- 连接主线：FROM / JOIN / ON直接保留在这里；复杂输入在括号内引用查询体。
-- 合约快照info：读取范围在01；与逐日明细det按合约号相接才形成合约日。
from (
-- 本文件选info（报告日合约主信息）；00再INNER JOIN逐日明细det，决定哪些合约日实际出现。
-- 普通/动态入口过滤OTC、grp_id=01、结束日不早于2022，并排除STATIC_HEDGING与TRS_INNER。
-- 静态入口另造prop_group：拆开自身号+关联合约号，按字符串排序取第一项；不是图连通分量。
-- 注意静态入口未写TRS_INNER排除；z回连只按报告日读取，没有重加外层筛选。
-- det只用自己的Strt_Pric_Date/End_Pric_Date限制自身busi_date；此任务未额外写det.busi_date<=报告日。
-- 本文件输出合约资料与静态组号；00连接det后才输出合约×明细日。两处都不擅自去重。
-- 本文件提供info查询体；外层JOIN与ON在00主脚本，实际公式继续在收入模块。
select *, null as prop_group from PDATA_N.T98_OTC_DERI_COMP_SALE_INFO
    where busi_date = '${yyyy-MM-dd}' and Book_Bel_Dept = 'OTC' and coalesce(Early_Term_Date, End_Pric_Date) >= '2022-01-01'
        and grp_id = '01' and Cntr != 'STATIC_HEDGING'
        and Agt_Clas_Cd != 'TRS_INNER'
    union all
    select  --静态对冲期权
        z.*, x.prop_group
    from (
        select agt_id, x.rel_agt_id as prop_group, row_number() over(partition by agt_id order by x.rel_agt_id) as rk
        from (
            select agt_id, concat(agt_id,',',coalesce(rel_agt_id,agt_id)) as rel_agt_id from PDATA_N.T98_OTC_DERI_COMP_SALE_INFO
            where busi_date = '${yyyy-MM-dd}' and Book_Bel_Dept = 'OTC' and coalesce(Early_Term_Date, End_Pric_Date) >= '2022-01-01'
                and grp_id = '01' and Cntr = 'STATIC_HEDGING'
            ) t
        lateral view explode(split(rel_agt_id,',')) x as rel_agt_id
        ) x
    left join (
        select * from PDATA_N.T98_OTC_DERI_COMP_SALE_INFO
        where busi_date = '${yyyy-MM-dd}'
        ) z
    on x.agt_id = z.agt_id
    where x.rk = 1

) info

-- 逐日本金det：只用明细自身起止日过滤；缺明细不生成合约日。
inner join (
    select * from PDATA_N.T98_OTC_DERI_COMP_SALE_ADTNL_DET
    where busi_date between Strt_Pric_Date and End_Pric_Date
    ) det
on info.agt_id = det.agt_id

-- 计提费用fee：场外流水号＋计提日；费用分类汇总见02。
left join (
-- 本文件提供fee每日费用汇总；cp客户资料查询另在00。两路LEFT JOIN，不重新决定合约日范围。
-- fee读期权合约每日计提费用表：37类汇为期权费，非37类汇为其他费；按源产品号+计提日汇总。
-- 用info.Otc_Seri_No（场外合约流水号）+det.Busi_Date连接fee；不是info.Agt_Id。
-- cp读公司客户表OIS来源、报告日、未删除资料，按交易对手客户编号取USCC；缺失不丢合约。
-- fee无命中时两费用为NULL，收入公式没有统一补0；cp多条命中会扩行并影响后续窗口。
-- 本文件提供fee查询体；外层JOIN与ON在00主脚本，实际公式继续在收入模块。
SELECT
        Src_Prd_Id,
        sum(if(Fee_Type_Cd = '37',  Tdy_Prvs_Fee, 0)) as PREMIUM_Prvs_Fee,
        sum(if(Fee_Type_Cd != '37', Tdy_Prvs_Fee, 0)) as OTHER_Prvs_Fee,
        Busi_Date
    FROM PDATA_N.T98_OTC_OPT_COMP_EDAY_PRVS_FEE
    where src_tbl = 'ODATA_N_TIT.D_TRD_DAILY_ACCRUAL_FEE'
    group by Src_Prd_Id, Busi_Date

) fee
on fee.Src_Prd_Id = info.Otc_Seri_No and fee.Busi_Date = det.Busi_Date

-- 客户cp：T01_CORP_CUST法人客户，交易对手客户编号取USCC；多匹配仍会扩行。
left join (
    select * from PDATA_N.T01_CORP_CUST
    where src_tbl = 'ODATA_N_OIS.O_OTC_DERIVATIVE_COUNTERPARTY' and busi_date = '${yyyy-MM-dd}' and DEL_FLAG = '0'
    ) cp
on cp.pty_id = info.Cutp_Pty_Id

-- 动态对冲pe：产品号＋账簿＋计提日，且本合约为动态柜台。
left join (
    select * from PDATA_N.T98_SB_TIT_DAY_HOLD_INDX
    where src_tbl = 'ODATA_N_TIT.D_POS_EOD_CALC_METRICS' and busi_date >= '2022-01-01'
    ) pe
on info.otc_seri_no = pe.Src_Prd_Id and det.busi_date = pe.busi_date and info.Book_Agt_Id = pe.Book_Agt_Id and info.Cntr = 'DYNAMIC_HEDGING'

-- 标的盈亏池u：复杂账簿／标的归集留在模块，下方ON保留实际领取范围。
left join (
-- 本文件只生产u标的盈亏池；并列的pe/pd查询直接在00主脚本，不在本模块计算。
-- pe：T98_SB_TIT_DAY_HOLD_INDX，每日持仓指标中的模拟对冲盈亏与delta。
-- pd：T98_OTC_BOOK_HOLD_SUM，合约当日持仓盈亏；pe/pd都按场外流水号+账簿+明细日匹配。
-- pe额外限制DYNAMIC_HEDGING，pd没有柜台限制，所以静态组也使用pd。
-- u：动态对冲账簿的标的日总盈亏。先用账簿映射标的，空串/NULL才回退工具undrl_clas，再按标的+日汇总。
-- u并非从pe聚合；它独立读取账簿持仓，经过交易产品关系→互换结构腿→腿持仓→证券基础资料确定备用标的。
-- info标的代码+明细日连接u；动态窗口则按pe.Undrl_Sum_Compr+pe.busi_date分组，两者键不能混称相同。
-- 本文件提供u查询体；外层JOIN与ON在00主脚本，实际公式继续在收入模块。
select
        nvl(if(rb.Map_Undrl_Cd='',null,rb.Map_Undrl_Cd),ins.undrl_clas) as Map_Undrl_Cd,
        sum(b.Tdy_Yield) as Tdy_Yield,
        b.busi_date
    from (
        select * from PDATA_N.T98_OTC_BOOK_HOLD_SUM
        where src_tbl = 'ODATA_N_TIT.D_POS_POSITION_DAILY' and busi_date >= '2022-01-01'
        ) b
    inner join (
        select * from PDATA_N.T03_OTC_DERI_BOOK_ADTNL_INFO
        where src_tbl = 'ODATA_N_TIT.D_REF_BOOK' and busi_date = '${yyyy-MM-dd}' and Cntr = 'DYNAMIC_HEDGING'
        ) rb
    on rb.Book_Agt_Id = b.Book_Agt_Id
    left join (
        select * from PDATA_N.T03_AGT_PRD_RELA_H
        where SRC_TBL = 'ODATA_N_TIT.D_TRD_OTC_TRADE' and Agt_Prd_Rela_Type_Cd = '01'
            and strt_date <= '${yyyy-MM-dd}' and end_date > '${yyyy-MM-dd}'
        ) tot
    on b.Src_Prd_Id = tot.Src_Prd_Id
    left join (
        select *
        from PDATA_N.T03_OTC_SWAP_COMP_LEG_INFO
        where src_tbl = 'ODATA_N_TIT.D_REF_TRS_LEG' and busi_date = '${yyyy-MM-dd}' and Swap_Comp_Leg_Type_Cd = 'STRUCTURE_LEG_TYPE'
        ) leg
    on leg.Swap_Comp_Agt_Id = tot.Agt_Id 
    left join (
        select * from PDATA_N.T03_OTC_SWAP_COMP_HOLD_INFO
        where src_tbl = 'ODATA_N_TIT.D_POS_TRS_LEG_HIS_POS' and busi_date >= '2022-01-01'
        ) leg_pos
    on leg_pos.Leg_Glbl_Seq_No = leg.Leg_Glbl_Seq_No and leg_pos.busi_date = b.busi_date
    left join (
        select * from pdata_news_n.t02_tit_scr_base_info
        where src_id = 'TIT' and grp_id = '01'
        ) ins
    on ins.in_code = coalesce(leg_pos.Src_Prd_Id, b.Src_Prd_Id)
    group by nvl(if(rb.Map_Undrl_Cd='',null,rb.Map_Undrl_Cd),ins.undrl_clas), b.busi_date

) u
on info.undrl_wd_cd = u.Map_Undrl_Cd and det.busi_date = u.busi_date

-- 合约持仓盈亏pd：场外流水号＋账簿＋计提日，供当日创收公式使用。
left join (
    select * from PDATA_N.T98_OTC_BOOK_HOLD_SUM
    where src_tbl = 'ODATA_N_TIT.D_POS_POSITION_DAILY'
    ) pd
on info.otc_seri_no = pd.Src_Prd_Id and det.busi_date = pd.busi_date and info.Book_Agt_Id = pd.Book_Agt_Id

-- 参考利率cr：补日加工留在模块，币种与计提日匹配见下方ON。
left join (
-- 本文件生产cr参考利率；mid汇率查询和两路ON条件均在00主脚本。
-- cr：HKD取HIBOR3M，其余币种取SOFR；日期先选上月末交易日，再从次月1日向后展开。
-- cr.ir原百分数在收入中除100；pretradedate/datekey2date是平台UDF，具体交易日历不在此推定。
-- mid：CFETS人民币中间汇率，按info.Sett_Crrc_Cd（结算币种）+det.busi_date（计提日）匹配。
-- 缺汇率时实际公式COALESCE(...,1)，不是先补汇率或停止计算；不能据此认定源币种就是人民币。
-- 本文件提供cr查询体；外层JOIN与ON在00主脚本，实际公式继续在收入模块。
--安全气囊X，当月取上月最后一个交易日数据
    select Curr, ir, date_add(trd_dt, pos) as trd_dt
    from (
        select
            date_add(last_day(default.datekey2date(trd_dt)),1) as trd_dt, 
            case scr_cd when 'HIBOR3M' then 'HKD'
                        when 'SOFR' then 'OTHER'
                        end as Curr, ir,
            lead(date_add(last_day(default.datekey2date(trd_dt)),1), 1, date_add('${yyyy-MM-dd}',1)) over(partition by scr_cd order by default.datekey2date(trd_dt)) as next_date
        from pdata_news_n.t02_ira_ibor
        where src_id = 'WD' and scr_cd in ('HIBOR3M','SOFR') and trd_dt >= '20201201'
            and default.datekey2date(trd_dt) = default.pretradedate(date_add(last_day(default.datekey2date(trd_dt)),1),1)
        ) t
    lateral view posexplode(split(space(datediff(next_date, trd_dt)-1), ' ')) t as pos, val

) cr
on cr.Curr = if(info.Undrl_Curr = 'HKD', 'HKD', 'OTHER') and cr.trd_dt = det.busi_date

-- 汇率mid：人民币中间汇率报价，按结算币种＋计提日接入。
left join (
    select default.datekey2date(trd_dt) as trd_dt, src_crrc_cd, mid_price
    from pdata_news_n.t02_fxr_cfets_quot
    where src_id = 'TIT' and grp_id = '01'
    ) mid
on mid.src_crrc_cd = info.Sett_Crrc_Cd and mid.trd_dt = det.busi_date

-- 生效成本co：按计提日及实际类型／币种条件匹配；不要统一改成报告日最新参数。
left join (
-- 两路都读取OIS客户创收系数g_client_revenue_coefficient，不是销售经营系数的T99。
-- co：非CNY气囊CAPITAL_COST配置；按币种分组，把生效日到下次生效日前一日展开为逐日参数。
-- co_c人民币配置另见05.1_人民币用资成本.sql；两者独立在00连接，不在本文件合并。
-- 当前报告日快照中is_del=N、contract_type=AIRBAGX；最终按明细日匹配，co还按HKD/OTHER映射匹配。
-- 最后一条配置展开至报告日。生效日当天切到新值，不是沿用旧值到当天结束。
-- 无默认值、无同生效日去重；缺配置会传播NULL，同日多条的先后仍不确定。
-- 本文件提供co查询体；外层JOIN与ON在00主脚本，实际公式继续在收入模块。
--美股、港股安全垫利率
    select
        currency,
        value as CAPITAL_COST,
        date_add(strt_date, pos) as busi_date
    from (
        select
            currency,
            value,
            effective_date as strt_date,
            date_sub(lead(effective_date, 1, date_add('${yyyy-MM-dd}', 1)) over(partition by currency order by effective_date), 1) as end_Date
        from odata_n_ois.g_client_revenue_coefficient
        where busi_date = '${yyyy-MM-dd}' and is_del = 'N' and contract_type = 'AIRBAGX' and coefficient_type = 'CAPITAL_COST' and currency != 'CNY'
        ) x
    lateral view posexplode(split(space(datediff(end_date, strt_date)), ' ')) y as pos, val

) co
on co.busi_date = det.busi_date and co.currency = if(info.Undrl_Curr = 'HKD', 'HKD', 'OTHER') and info.Src_Contr_Type in ('RISKY','AIRBAGX')

-- 人民币用资成本co_c：与co独立匹配，不能把两个参数范围合并。
left join (
-- 人民币用资成本：OIS客户创收系数，取AIRBAGX / CAPITAL_COST / CNY并按生效区间展开。
-- 本文件提供co_c查询体；外层JOIN与ON在00主脚本，实际公式继续在收入模块。
--人民币用资利率
    select
        value as CAPITAL_COST,
        date_add(strt_date, pos) as busi_date
    from (
        select
            value,
            effective_date as strt_date,
            date_sub(lead(effective_date, 1, date_add('${yyyy-MM-dd}', 1)) over(order by effective_date), 1) as end_Date
        from odata_n_ois.g_client_revenue_coefficient
        where busi_date = '${yyyy-MM-dd}' and is_del = 'N' and contract_type = 'AIRBAGX' and coefficient_type = 'CAPITAL_COST' and currency = 'CNY'
        ) x
    lateral view posexplode(split(space(datediff(end_date, strt_date)), ' ')) y as pos, val

) co_c
on co_c.busi_date = det.busi_date and info.Src_Contr_Type in ('RISKY','AIRBAGX')

) castTable
