-- GENERATED by render.mjs; edit 00_主脚本.sql and its includes.
-- 六组阅读路径（各分支并列补充客户，不是前后相乘）：
-- 01 客户/销售底座 ┬─ 02结束创收、03→03.1净收计数 ─ 胜率
--                 ├─ 05→05.1比例、06→06.1追保权重、07额度、08规模 ─ 履保
--                 ├─ 09方案名称资料 ─ 增信展示
--                 ├─ 10天数比、11标签+11.1统计 ─ 追保/垫资
--                 └─ 04月换手、12腿估值、13佣金 ─ 互换活跃与费用
-- 全部分支 → 14统一输出（单位换算/四项NULL占位）→ dm_otc_n.bi_otc_cust_index
-- 229121 客户综合指标：以客户为底座，十三个独立问题并列匹配，不改原SQL计算口径。
-- 阅读路径见README；-- @include由本目录render.mjs展开，不是生产引擎语法。
-- 主连接有两种键：02–06按company_id（USCC）；07–13按company_name（公司全名）。
-- 这些LEFT JOIN保留底座客户；子查询不保证键唯一，因此匹配仍可能扩行。
-- 统一输出：前四项身份，随后各并列专题结果；模块之间不是串行加工。
-- 四项固定NULL：履保分级、风险压测、满意度总分/改进意见。缺数不等于零。
-- perf规模两列同式且补0；quota/fee/commission不补0；万元与亿元在此换算。
SELECT company_name,
	company_id,
	contact_sales,
	sales_login,
	cust_hold_win_rate,
	cust_win_rate,
	margin_ratio,
	margin_call_line,
	margin_grade,
	risk_test_data,
	outst_margin_amount,
	used_quota,
	approved_quota,
	approved_busi_type,
	margin_call_rate,
	cust_advance_info,
	credit_measure,
	cust_satisfaction_score,
	cust_satisfaction_feedback,
	swap_turnover_rate,
	swap_new_principal,
	swap_outst_month_end,
	swap_platform_fee,
	swap_bond_interest,
	swap_commission,
	busi_date FROM (
	 SELECT
    t0.company_name -- 公司全称：01底座
    ,t0.company_id -- USCC：01底座
    ,t0.contact_sales -- 销售姓名清单：01
    ,t0.sales_login -- 经办人登录号清单：01
    ,t1.cust_hold_win_rate -- 02结束合约创收正值占比，非客户投资收益率
    ,t2.cust_win_rate -- 03两期权类别共用分母的净收负值占比
    ,m1.margin_ratio -- 05按组合本金加权的履保比例
    ,m2.margin_call_line -- 06排除NULL追保线后重新加权
    ,null as margin_grade -- 固定NULL：履保分级未实现
    ,null as risk_test_data -- 固定NULL：风险压测未实现
    ,coalesce(perf.perf_dyna_nom_prin, 0) / 10000 as outst_margin_amount -- 08履保动态本金，缺失补0，元→万元
    ,coalesce(perf.perf_dyna_nom_prin, 0) / 10000 as used_quota -- 与上一列完全同式，不是独立额度占用计算
    ,lim.approved_limit / 10000 as approved_quota -- 07有效限额MAX，元→万元，未补0
    ,lim.approved_type as approved_busi_type -- 07原获批业务码值去重串
    ,mc.margin_call_rate -- 10按递延天数之和求比，不是按次数
    ,adv.cust_advance_info -- 11统计量填入硬编码模板
    ,cm.credit_measure -- 09对手方中文简称清单
    ,null as cust_satisfaction_score -- 固定NULL：满意度总分未实现
    ,null as cust_satisfaction_feedback -- 固定NULL：满意度改进意见未实现
    ,t3.swap_turnover_rate -- 04本月新增+平仓 / 上月末本金
    ,t3.swap_new_principal   / 10000     as swap_new_principal -- 04本月起始计提初始本金，元→万元
    ,t3.swap_outst_month_end / 100000000 as swap_outst_month_end -- 04上月末动态本金，元→亿元
    ,fee.swap_platform_fee   / 10000     as swap_platform_fee -- 12当日累计腿收益按类型归属后缩放10000；源币种未核，不等于已换成人民币
    ,fee.swap_bond_interest  / 10000     as swap_bond_interest -- 12借券类累计腿收益缩放10000；目标标签为万元，源币种见12说明
    ,com.swap_commission     / 10000     as swap_commission -- 13限定02/03的区间交易佣金，元→万元
    ,'${yyyy-MM-dd}' as busi_date -- 本次报告日，不是各源业务发生日


-- 一、客户与销售底座：公司名+USCC一行。
from (
-- 客户底座 t0：报告日创收快照中，上一年元旦至报告日出现过的 grp 01/02/03 客户。
-- 一行=公司全称+USCC；不是最近12个月，也不要求当日有持仓或正创收。
-- T01_OTC_DERI_CUST（衍生品客户）的 Oper_User_Id=经办人；按客户当事人号接入。
-- T98_ORG_EMP_BASE_INFO（员工基本信息）按 Oa_User_Id 补 Emp_Name（姓名）；名单去重、顺序不保证。
SELECT
        r.Cutp_Pty_Full_Name as company_name
        ,r.USCC as company_id
        ,concat_ws(';', collect_set(e.Emp_Name)) as contact_sales
        ,concat_ws(';', collect_set(c.Oper_User_Id)) as sales_login
    from DM_OTC_N.OTC_REV_DAILY_RPT r
    left join pdata_n.T01_OTC_DERI_CUST c
        on r.Cutp_Pty_Id = c.Pty_Id
        and c.BUSI_DATE = '${yyyy-MM-dd}'
        and c.SRC_TBL = 'ODATA_N_OIS.O_OTC_DERIVATIVE_COUNTERPARTY'
    left join pdata_n.T98_ORG_EMP_BASE_INFO e
        on c.Oper_User_Id = e.Oa_User_Id
        and e.BUSI_DATE = '${yyyy-MM-dd}'
    where r.busi_date = '${yyyy-MM-dd}'
    and r.grp_id in('01','02','03')
    and r.Accrued_Date between '${yyyy,-1y}-01-01' and '${yyyy-MM-dd}'
    group by r.Cutp_Pty_Full_Name, r.USCC

) t0

-- 二、胜率（USCC）：结束合约区间创收正值占比，不是客户投资收益率。
left join (
-- 结束合约创收正值占比 t1（输出沿用 cust_hold_win_rate 名称）。
-- 先按公司名+USCC+合约 Agt_Id 汇总区间 Curr_Rev（我司创收），再数合计>0的组/全部组。
-- 结束日=COALESCE(提前终止日,到期计价日)，<=报告日即入围；不查状态，也不是客户投资盈亏。
-- 本模块不筛 grp；NULL创收不算正，但该合约组仍进COUNT。按名+证件分组，外层却只按USCC连接。
    -- 阶段三：客户级正值合约组数 / 全部结束合约组数 → 14统一输出。
    SELECT
        t.company_name
        ,t.company_id
        ,sum(case when t.contract_rev > 0 then 1 else 0 end) / count(*) as cust_hold_win_rate
    from (
        -- 阶段二：同公司名+USCC+合约跨计提日累加，得到一份合约的区间创收。
        SELECT
            Cutp_Pty_Full_Name as company_name
            ,USCC as company_id
            ,Agt_Id
            ,sum(cast(Curr_Rev as double)) as contract_rev
        from DM_OTC_N.OTC_REV_DAILY_RPT
        -- 阶段一：从报告日创收快照选择区间内、结束日期不晚于报告日的样本。
        where busi_date = '${yyyy-MM-dd}'
          and Accrued_Date between '${yyyy,-1y}-01-01' and '${yyyy-MM-dd}'
          and coalesce(Early_Term_Date, End_Pric_Date) <= '${yyyy-MM-dd}'
        group by USCC, Cutp_Pty_Full_Name, Agt_Id
    ) t
    group by t.company_name, t.company_id

) t1 on t0.company_id = t1.company_id

-- 期权起始样本的净收负值占比：欧式/气囊共用同USCC总分母。
left join (
-- 期权净收为负占比 t2：仅欧式香草/安全气囊的起始计提行，接报告日01销售合约主信息。
-- net_coll=交易净收；SQL以<0计数，但币种、收付符号业务解释须另核。
-- 每个类别分子 / 同USCC两类别全部匹配行数；不是各类别自己的胜率，也未数DISTINCT合约。
-- 内连接按 Agt_Id；重复主信息可增加分子/分母。输出类别串顺序不保证。
    SELECT
        USCC as company_id
        ,concat_ws(',', collect_list(concat(category, ':', win_ratio))) as cust_win_rate
    from (
-- 输入：创收快照的起始计提行 + 当日报告期权销售主信息（Agt_Id连接）。
-- 输出：每USCC+原始期权类别一行category/win_ratio → 03模块拼展示串。
-- 先连接筛样本，再按类别计数；窗口将类别COUNT相加作同USCC共同分母。
SELECT
    r.USCC
    ,case
        when r.Src_Contr_Type_Desc = '欧式香草' then '欧式期权'
        else '安全气囊'
     end as category
    ,sum(case when cast(s.net_coll as double) < 0 then 1 else 0 end)
     / sum(count(*)) over(partition by r.USCC) as win_ratio -- 该类别净收负行数 / 两类别全部匹配行数
-- 身份与输入来源（保持原连接后记录，不预先合并）：
from DM_OTC_N.OTC_REV_DAILY_RPT r -- 客户创收明细：报告日快照包含历史计提日
inner join pdata_n.T98_OTC_DERI_COMP_SALE_INFO s -- 销售合约主信息
    on r.Agt_Id = s.Agt_Id
    and s.busi_date = '${yyyy-MM-dd}'
    and s.grp_id = '01'
where r.busi_date = '${yyyy-MM-dd}'
  and r.Accrued_Date between '${yyyy,-1y}-01-01' and '${yyyy-MM-dd}'
  and r.Accrued_Date = r.Strt_Pric_Date
  and r.Src_Contr_Type_Desc in ('欧式香草', '安全气囊')
group by r.USCC, r.Src_Contr_Type_Desc

    ) t
    group by USCC

) t2 on t0.company_id = t2.company_id

-- 三、互换月换手（USCC）：本月新增+平仓，除上月末动态本金。
left join (
-- 互换月换手 t3：本月起始日初始本金+本月事件本金变动 / 上月末动态本金。
-- 创收快照按USCC+内部合约号 Inr_Seri_No归集：只取TRS、本月起始行或上月末行。
-- T05_OTC_COMP_DURA_CHG_EVT（合约存续变动事件）：Otc_Comp_Agt_Id接内部合约号。
-- 三类平仓/终止事件按 Evt_Date筛月，Nom_Prin_Chg_Delta原符号相加；没有ABS/汇率换算/事件快照筛选。
-- 只有先进入s的合约才能带入事件；零分母未保护，方言行为不在这里修正。
    SELECT
        s.USCC as company_id
        ,(sum(s.new_principal) + sum(coalesce(c.close_amount, 0))) / sum(s.outst_amount) as swap_turnover_rate
        ,sum(s.new_principal) as swap_new_principal
        ,sum(s.outst_amount) as swap_outst_month_end
    from (
        SELECT
            USCC
            ,Inr_Seri_No
            ,sum(case when Accrued_Date between '${yyyy-MM}-01' and '${yyyy-MM-dd}'
                      then Init_Nom_Prin else 0 end) as new_principal
            ,sum(case when Accrued_Date = last_day('${yyyy-MM-dd,-1M}')
                      then Dyna_Nom_Prin else 0 end) as outst_amount
        from DM_OTC_N.OTC_REV_DAILY_RPT
        where busi_date = '${yyyy-MM-dd}'
          and Busi_Type = 'TRS'
          and(
            Accrued_Date between '${yyyy-MM}-01' and '${yyyy-MM-dd}' and Accrued_Date = Strt_Pric_Date
            or
            Accrued_Date = last_day('${yyyy-MM-dd,-1M}')
          )
        group by USCC, Inr_Seri_No
    ) s
    left join (
        SELECT
            Otc_Comp_Agt_Id
            ,sum(Nom_Prin_Chg_Delta) as close_amount
        from pdata_n.T05_OTC_COMP_DURA_CHG_EVT
        where src_tbl = 'ODATA_N_TIT.D_TRD_TRS_EVENT'
          and Evt_Date between '${yyyy-MM}-01' and '${yyyy-MM-dd}'
          and Evt_Type_Cd in (
                'CLOSE_STOCKS'
              , 'EARLY_TERMINATION'
              , 'TERMINATION'
              )
        group by Otc_Comp_Agt_Id
    ) c on s.Inr_Seri_No = c.Otc_Comp_Agt_Id
    group by s.USCC

) t3 on t0.company_id = t3.company_id

-- 四、履保（USCC）：NULL履保比例的本金仍参与权重。
left join (
-- 履保比例 m1：以组合动态本金加权，映射链见下。
-- 履保结果m.Comb_Agt_Grp_Id → 组合附加资料comb.Agt_Grp_Id → 对手方comb.Cutp_Pty_Id
-- → 有效当事人关系h.Pty_Id→h.Rela_Pty_Id → 当日对公客户c.PTY_ID→c.USCC。
-- 只要履保标志1、动态本金>0就参与权重；Marg_Perf_Prtc_Rati为NULL的本金仍占分母。
-- 组合表未筛BUSI_DATE、映射未去重：窗口在这些INNER JOIN之后计算，不保证一组合一行。
    SELECT
        t.company_id

        ,sum(t.marg_ratio * t.nom_weight) as margin_ratio
    from (

-- 输入：组合履保结果 + 组合附加资料 + 有效当事人关系 + 当日对公客户。
-- 输出：每条连接后的正本金履保记录及nom_weight → 05模块SUM(比例×权重)。
-- 原组合/身份链不去重；名本窗口按连接后的USCC分组，NULL比例的本金仍占权重。
SELECT
    c.USCC as company_id -- 统一社会信用代码，客户权重分组键
    ,comb.Cutp_Pty_Id as counterparty_id -- 组合归属的内部交易对手编号
    ,m.Comb_Agt_Grp_ID -- 组合协议组编号，接comb.Agt_Grp_Id
    ,cast(m.Dyna_Nom_Prin as double) as dyna_nom_prin -- 组合动态名义本金
    ,cast(m.Marg_Perf_Prtc_Rati as double) as marg_ratio -- 履约保障比例

    ,cast(m.Dyna_Nom_Prin as double)
     / sum(cast(m.Dyna_Nom_Prin as double)) over(partition by c.USCC) as nom_weight -- 本行本金 / 同USCC符合本模块条件的全部本金
-- 身份与输入来源（保持原连接后记录，不预先合并）：
from pdata_n.T03_OTC_CUTP_MARG_ACCT_PERF_GUAR_RSLT m -- 组合履保结果
inner join pdata_n.T03_OTC_DERI_COMP_COMB_ADTNL_INFO comb -- 衍生品合约组合附加信息
    on m.Comb_Agt_Grp_Id = comb.Agt_Grp_Id
    and comb.SRC_TBL = 'ODATA_N_TIT.D_TRD_BUNDLE_INFO'
    and comb.Comb_Compnt_Cd in ('TRS', 'OPTION', 'MIXTURE')
inner join pdata_n.T01_PTY_RELA_H h -- 当事人关系历史：内部对手方→OIS客户
    on comb.Cutp_Pty_Id = h.Pty_Id
    and h.SRC_TBL = 'ODATA_N_TIT.D_REF_CTPTY_MAPPING'
    and h.STRT_DATE <= '${yyyy-MM-dd}'
    and h.END_DATE > '${yyyy-MM-dd}'
inner join pdata_n.T01_CORP_CUST c -- 对公客户：取USCC/公司全名
    on h.Rela_Pty_Id = c.PTY_ID
    and c.BUSI_DATE = '${yyyy-MM-dd}'
    and c.SRC_TBL = 'ODATA_N_OIS.O_OTC_DERIVATIVE_COUNTERPARTY'
where m.busi_date = '${yyyy-MM-dd}'
  and m.src_tbl = 'ODATA_N_TIT.D_BUNDLE_MARGIN_DAILY_RESULT'
  and m.Perf_Marg_Flag = '1'
  and cast(m.Dyna_Nom_Prin as double) > 0

    ) t
    group by t.company_id

) m1 on t0.company_id = m1.company_id

-- 追保线（USCC）：先排NULL追保线，再计算权重；分母不同于上一项。
left join (
-- 追保线 m2：沿与m1相同的组合→当事人→对公客户链，按本币动态本金加权。
-- T03_OTC_COMP_PERF_MARG_REF（合约履保参数）：Bail_Apd_Marg_Line=保证金追保线；Lcrrc_Dyna_Nom_Prin=本币动态本金。
-- 与m1关键不同：先排除NULL追保线再计算权重；未要求m1的履保标志。
-- 组合附加资料仍不筛快照、仍未去重；不是先按组合汇总再加权。
    SELECT
        t.company_id

        ,sum(t.margin_call_line * t.nom_weight) as margin_call_line
    from (

-- 输入：组合每日履保参数 + 组合附加资料 + 有效当事人关系 + 当日对公客户。
-- 输出：每条连接后、追保线非NULL且正本金记录的nom_weight → 06模块汇总贡献。
-- 与05.1不同：先排除NULL追保线再分本金；不能复用同一分母。
SELECT
    c.USCC as company_id -- 统一社会信用代码，客户权重分组键
    ,comb.Cutp_Pty_Id as counterparty_id -- 组合归属的内部交易对手编号
    ,r.Comb_Agt_Grp_Id
    ,cast(r.Lcrrc_Dyna_Nom_Prin as double) as dyna_nom_prin -- 组合本币动态名义本金
    ,cast(r.Bail_Apd_Marg_Line as double) as margin_call_line -- 保证金追保线

    ,cast(r.Lcrrc_Dyna_Nom_Prin as double)
     / sum(cast(r.Lcrrc_Dyna_Nom_Prin as double)) over(partition by c.USCC) as nom_weight -- 本行本金 / 同USCC符合本模块条件的全部本金
-- 身份与输入来源（保持原连接后记录，不预先合并）：
from pdata_n.T03_OTC_COMP_PERF_MARG_REF r -- 合约履保参数，来源由src_tbl区分
inner join pdata_n.T03_OTC_DERI_COMP_COMB_ADTNL_INFO comb -- 衍生品合约组合附加信息
    on r.Comb_Agt_Grp_Id = comb.Agt_Grp_Id
    and comb.SRC_TBL = 'ODATA_N_TIT.D_TRD_BUNDLE_INFO'
    and comb.Comb_Compnt_Cd in ('TRS', 'OPTION', 'MIXTURE')
inner join pdata_n.T01_PTY_RELA_H h -- 当事人关系历史：内部对手方→OIS客户
    on comb.Cutp_Pty_Id = h.Pty_Id
    and h.SRC_TBL = 'ODATA_N_TIT.D_REF_CTPTY_MAPPING'
    and h.STRT_DATE <= '${yyyy-MM-dd}'
    and h.END_DATE > '${yyyy-MM-dd}'
inner join pdata_n.T01_CORP_CUST c -- 对公客户：取USCC/公司全名
    on h.Rela_Pty_Id = c.PTY_ID
    and c.BUSI_DATE = '${yyyy-MM-dd}'
    and c.SRC_TBL = 'ODATA_N_OIS.O_OTC_DERIVATIVE_COUNTERPARTY'
where r.busi_date = '${yyyy-MM-dd}'
  and r.src_tbl = 'ODATA_N_TIT.D_BUNDLE_DAILY_CONTR_PARAM'
  and r.Bail_Apd_Marg_Line is not null
  and cast(r.Lcrrc_Dyna_Nom_Prin as double) > 0

    ) t
    group by t.company_id

) m2 on t0.company_id = m2.company_id

-- 五、额度/规模/资料（公司全名）：有效管理人额度取MAX。
left join (
-- 获批额度 lim：有效管理人限额→有效当事人映射→当日对公客户，按公司中文全名归集。
-- T01_PTY_LMT_H（当事人限额历史）：Lmt取MAX，不是SUM；Perm_Busi_Type去重拼接，不翻译码值。
-- 有效期均含开始、不含结束；外层按名称而非USCC连接，缺失额度保持NULL。
    SELECT
        c.ORG_FULL_NAME_CH as company_name
        ,max(cast(l.Lmt as double)) as approved_limit
        ,concat_ws(';', collect_set(l.Perm_Busi_Type)) as approved_type
    from pdata_n.T01_PTY_LMT_H l
    inner join pdata_n.T01_PTY_RELA_H h
        on l.Pty_Id = h.Pty_Id
        and h.SRC_TBL = 'ODATA_N_TIT.D_REF_CTPTY_MAPPING'
        and h.STRT_DATE <= '${yyyy-MM-dd}'
        and h.END_DATE > '${yyyy-MM-dd}'
    inner join pdata_n.T01_CORP_CUST c
        on h.Rela_Pty_Id = c.PTY_ID
        and c.BUSI_DATE = '${yyyy-MM-dd}'
        and c.SRC_TBL = 'ODATA_N_OIS.O_OTC_DERIVATIVE_COUNTERPARTY'
    where l.SRC_TBL = 'ODATA_N_TIT.D_RISK_CTPTY_LIMIT_THRESHOLD'
        and l.Strt_Date <= '${yyyy-MM-dd}'
        and l.End_Date > '${yyyy-MM-dd}'
        and l.Pty_Lmt_Type_Cd = 'ADMINISTRATORLIMIT'
    group by c.ORG_FULL_NAME_CH

) lim on t0.company_name = lim.company_name

-- 履保动态本金：同时供14的规模与已用额度，两列同式。
left join (
-- 履保规模 perf：当日履保参数中STATIC/DYNAMIC，按内部合约号接当日01/02/03销售合约。
-- 取销售合约 Dyna_Nom_Prin（动态名义本金），排除Contr_Type_Desc=南下期货；NULL类型也不满足<>。
-- 按公司全名求和，没有DISTINCT/状态/正本金过滤；重复参数会重复金额。
-- 最终“存续履保交易规模”和“已用额度”使用同一个结果，不是两个独立事实；缺失按0展示。
    SELECT
        s.Cutp_Pty_Full_Name as company_name
        ,sum(cast(s.Dyna_Nom_Prin as double)) as perf_dyna_nom_prin
    from pdata_n.T03_OTC_COMP_PERF_MARG_REF r
    inner join pdata_n.T98_OTC_DERI_COMP_SALE_INFO s
        on r.Otc_Comp_Agt_Id = s.Inr_Seri_No
        and s.busi_date = '${yyyy-MM-dd}'
        and s.grp_id in ('01','02','03')
        and s.Contr_Type_Desc <> '南下期货'
    where r.busi_date = '${yyyy-MM-dd}'
      and r.src_tbl = 'ODATA_N_TIT.D_REF_OTC_CONTR_MARGIN_PARAM'
      and r.Enable_Perf_Marg_Type_Cd in ('STATIC', 'DYNAMIC')
    group by s.Cutp_Pty_Full_Name

) perf on t0.company_name = perf.company_name

-- 增信展示资料：履保方案关联对手方简称，并非担保措施条款。
left join (
-- 增信资料 cm：履保方案→当日对手方名称资料，按 Full_Name_En 与客户中文全名直接匹配。
-- T01_CUTP_PERF_MARG_PLAN_INFO来源D_MARGIN_PLAN；T01_PTY_NAME来源D_REF_COUNTER_PARTY。
-- 输出 Shor_Name_Ch（中文简称）去重拼接，SQL没有提取担保品、担保方式或方案条款。
    SELECT
        n.Full_Name_En as company_name
        ,concat_ws(';', collect_set(n.Shor_Name_Ch)) as credit_measure
    from pdata_n.T01_CUTP_PERF_MARG_PLAN_INFO p
    inner join pdata_n.T01_PTY_NAME n
        on p.Pty_Id = n.Pty_Id
        and n.src_tbl = 'ODATA_N_TIT.D_REF_COUNTER_PARTY'
        and n.busi_date = '${yyyy-MM-dd}'
    where p.busi_date = '${yyyy-MM-dd}'
      and p.src_tbl = 'ODATA_N_TIT.D_MARGIN_PLAN'
    group by n.Full_Name_En

) cm on t0.company_name = cm.company_name

-- 六、追保/垫资（公司全名）：及时天数和 / 全部递延天数和。
left join (
-- 追保及时率 mc：当日追保设置快照、履保日期上一年元旦至报告日。
-- Defr_Days=递延天数；分子是<=2的天数之和，分母是全部天数之和；不是及时笔数/总笔数。
-- 以有效当事人映射补公司名，按名称连接；NULL在SUM中跳过，零/负数未过滤，分母零未保护。
    SELECT
        c.ORG_FULL_NAME_CH as company_name
        ,sum(case when cast(m.Defr_Days as int) <= 2 then cast(m.Defr_Days as int) else 0 end)
         / sum(cast(m.Defr_Days as int)) as margin_call_rate
    from PDATA_N.T03_OTC_DERI_COMP_COMB_MARG_CALL_INFO m
    inner join pdata_n.T01_PTY_RELA_H h
        on m.Pty_Id = h.Pty_Id
        and h.SRC_TBL = 'ODATA_N_TIT.D_REF_CTPTY_MAPPING'
        and h.STRT_DATE <= '${yyyy-MM-dd}'
        and h.END_DATE > '${yyyy-MM-dd}'
    inner join pdata_n.T01_CORP_CUST c
        on h.Rela_Pty_Id = c.PTY_ID
        and c.BUSI_DATE = '${yyyy-MM-dd}'
        and c.SRC_TBL = 'ODATA_N_OIS.O_OTC_DERIVATIVE_COUNTERPARTY'
    where m.Busi_Date = '${yyyy-MM-dd}'
      and m.Perf_Marg_Date >= '${yyyy,-1y}-01-01'
      and m.Perf_Marg_Date <= '${yyyy-MM-dd}'
      and m.Src_Tbl = 'ODATA_N_TIT.G_MARGIN_CALL_SETTING'
    group by c.ORG_FULL_NAME_CH

) mc on t0.company_name = mc.company_name

-- 有垫资标签作为门槛，11.1统计量装入固定文字；模板不是外部证据。
left join (
-- 垫资文字 adv：先要当日客户标签存在“有垫资”，再汇总区间内递延>=2天的追保记录。
-- 标签来源231146的判断见同级专题；此处不重新证明标签条件，qual也未去重。
-- 最近季度取MAX履保日期；频次=不同履保日期数×7/区间天数，时长=每行递延天数平均。
-- 所谓日均金额=追保金额SUM/递延天数SUM/10000，不是日历逐日垫资本金平均。
-- “托管行资金流水及券商对账单回溯”“持续但规模可控”均是硬编码模板，不是本SQL查证的事实。
    SELECT
        ind.company_name
        ,concat(
            '根据托管行资金流水及券商对账单回溯，客户于',
            ind.freq_quarter,
            '存在垫资行为'
            ,'。客户近一年存在持续但规模可控的垫资行为，平均每周约',
            cast(round(ind.weekly_freq, 1) as string),
            '次、单次时长',
            round(ind.avg_duration, 0),
            '天左右，日均垫资金额集中在',
            round(ind.daily_amt_wan, 0),
            '万元。'
        ) as cust_advance_info
    from (
        select company_name from dm_otc_n.bi_otc_cust_tag
        where busi_date = '${yyyy-MM-dd}'
          and tag_name = '有垫资'
    ) qual
    inner join (
-- 输入：当日追保设置快照 → 有效对手方关系 → 当日对公客户全名。
-- 输出：每公司全名一行最近季度/周频/平均递延/金额天数比 → 11模块拼固定文字。
-- 仅上一年元旦至报告日、递延>=2的记录；是统计材料，不是托管流水核验。
SELECT
    c.ORG_FULL_NAME_CH as company_name -- 公司中文全名，此处最终按名称关联
    ,case
        when substr(max(m.Perf_Marg_Date), 6, 2) in ('01','02','03')
             then concat(substr(max(m.Perf_Marg_Date), 1, 4), '年第一季度')
        when substr(max(m.Perf_Marg_Date), 6, 2) in ('04','05','06')
             then concat(substr(max(m.Perf_Marg_Date), 1, 4), '年第二季度')
        when substr(max(m.Perf_Marg_Date), 6, 2) in ('07','08','09')
             then concat(substr(max(m.Perf_Marg_Date), 1, 4), '年第三季度')
        when substr(max(m.Perf_Marg_Date), 6, 2) in ('10','11','12')
             then concat(substr(max(m.Perf_Marg_Date), 1, 4), '年第四季度')
     end as freq_quarter -- 最大履保日期所属季度，并非覆盖的全部季度
    ,count(distinct m.Perf_Marg_Date) * 7.0
        / (datediff('${yyyy-MM-dd}', '${yyyy,-1y}-01-01') + 1)
     as weekly_freq -- 不同履保日期数折算周频，不是追保记录条数
    ,avg(cast(m.Defr_Days as double)) as avg_duration -- 合格追保记录的平均递延天数
    ,sum(cast(m.Marg_Call_Amt as double))
     / nullif(sum(cast(m.Defr_Days as int)), 0) / 10000
     as daily_amt_wan -- 追保金额 / 递延天数 / 10000
-- 身份与输入来源（保持原连接后记录，不预先合并）：
from PDATA_N.T03_OTC_DERI_COMP_COMB_MARG_CALL_INFO m -- 组合追保信息：递延天数/追保金额
inner join pdata_n.T01_PTY_RELA_H h -- 当事人关系历史：内部对手方→OIS客户
    on m.Pty_Id = h.Pty_Id
    and h.SRC_TBL = 'ODATA_N_TIT.D_REF_CTPTY_MAPPING'
    and h.STRT_DATE <= '${yyyy-MM-dd}'
    and h.END_DATE > '${yyyy-MM-dd}'
inner join pdata_n.T01_CORP_CUST c -- 对公客户：取USCC/公司全名
    on h.Rela_Pty_Id = c.PTY_ID
    and c.BUSI_DATE = '${yyyy-MM-dd}'
    and c.SRC_TBL = 'ODATA_N_OIS.O_OTC_DERIVATIVE_COUNTERPARTY'
where m.Busi_Date = '${yyyy-MM-dd}'
  and m.Perf_Marg_Date >= '${yyyy,-1y}-01-01'
  and m.Perf_Marg_Date <= '${yyyy-MM-dd}'
  and m.Src_Tbl = 'ODATA_N_TIT.G_MARGIN_CALL_SETTING'
  and cast(m.Defr_Days as int) >= 2
group by c.ORG_FULL_NAME_CH

    ) ind on qual.company_name = ind.company_name

) adv on t0.company_name = adv.company_name

-- 七、互换费用（公司全名）：当日累计腿收益，按合约类型分平台费/券息。
left join (
-- 平台费与券息 fee：当日互换腿估值接当日02销售合约，真实键是 Exp_Comp_No=Agt_Id。
-- T98_OTC_SWAP_COMP_LEG_VALU_INFO：Accum_Unrlz_Yield累计未实现收益+Accum_Rlz_Yield累计已实现收益。
-- FLOAT与FIXED两类腿都进来；由合约类型决定平台费或券息，不是按浮动/固定腿分别归属。
-- 只看当日累计估值，不是上一年元旦以来逐日求和；一项收益NULL使本行加法NULL。无币种换算/反号。
    SELECT
        s.Cutp_Pty_Full_Name as company_name

        ,sum(
            case when s.Src_Contr_Type_Desc in (
                '南下跨境','南下跨境（场内期权）','南下跨境（期货）','多头持券'
            ) then
                cast(v.Accum_Unrlz_Yield as double)
              + cast(v.Accum_Rlz_Yield as double)
            else 0 end
        ) as swap_platform_fee

        ,sum(
            case when s.Src_Contr_Type_Desc in (
                '跨境借券','借券互换'
            ) then
                cast(v.Accum_Unrlz_Yield as double)
              + cast(v.Accum_Rlz_Yield as double)
            else 0 end
        ) as swap_bond_interest
    from PDATA_N.T98_OTC_SWAP_COMP_LEG_VALU_INFO v
    inner join pdata_n.T98_OTC_DERI_COMP_SALE_INFO s
        on v.Exp_Comp_No = s.Agt_Id
        and s.busi_date = '${yyyy-MM-dd}'
        and s.grp_id = '02'
    where v.busi_date = '${yyyy-MM-dd}'
      and v.src_tbl = 'ODATA_N_TIT.D_POS_TRS_LEG_VALUATION'
      and v.Swap_Comp_Leg_Type_Cd in ('FLOAT_LEG_TYPE', 'FIXED_LEG_TYPE')
    group by s.Cutp_Pty_Full_Name

) fee on t0.company_name = fee.company_name

-- 区间佣金：grp03或符合指定南下条件的grp02；不是所有普通互换。
left join (
-- 互换佣金 com：报告日创收快照、上一年元旦至报告日的 trd_cms（交易佣金）求和。
-- grp03全取；grp02仅Agt_Clas_Cd=TRS_SAC_OTC且指定南下类型（普通南下还必须标的EQUITY）。
-- 不是所有普通互换，也未加Busi_Type过滤；逐行NULL佣金补0，无匹配公司仍保持NULL。
-- 最终统一除10000；不能将本佣金再与已含佣金的Curr_Rev相加当总创收。
    SELECT
        s.Cutp_Pty_Full_Name as company_name
        ,sum(coalesce(cast(s.trd_cms as double), 0)) as swap_commission
    from DM_OTC_N.OTC_REV_DAILY_RPT s
    where s.busi_date = '${yyyy-MM-dd}'
      and(
        s.grp_id = '03'
        or

        s.grp_id = '02'
        and s.Agt_Clas_Cd = 'TRS_SAC_OTC'
        and ((s.Src_Contr_Type = 'S_CROSS_SWAP' and s.Src_Undrl_Type = 'EQUITY') or s.Src_Contr_Type in ('S_CROSS_OPTION_SWAP','S_CROSS_FUTURE_SWAP'))
      )
      and s.Accrued_Date between '${yyyy,-1y}-01-01' and '${yyyy-MM-dd}'
    group by s.Cutp_Pty_Full_Name

) com on t0.company_name = com.company_name

) castTable
