-- GENERATED by ../render.mjs; edit the branch main SQL and its includes.
-- 227869持仓盈亏：结算资金与当日估值两路并列，按客户名+标的合并，再左接当日持仓主体。
-- 01结算资金内部引用02资金快照/客户及03标的识别；04估值不依赖01输出。
-- 06结果内部引用05当日持仓，只有底座持仓行能进入最终报表。
-- UNION保留原始去重语义，不擅改UNION ALL；整段未做汇率换算或统一盈亏正负方向。
with pnl as(
  SELECT
    busi_date,
    ctpty_legal_entity,
    wind_code,
    SUM(cap_amount) AS profit_loss
  FROM (
-- 结算一路：02选择资金快照并取得客户/交易身份，03补标的代码，最后按客户名+标的累计资金。
-- 代码优先资金流水自身vr_cap_undrly_code，其次期权结构，再回退互换多标的拼串；只在NULL时回退，空串保留。
-- 资金日期先截10位，再与下方含时间的起始字面量比较；保留原写法，边界日期类型行为需引擎复核。
-- 结果日期强制写成报告日，金额却是筛选历史资金的合计，不是当天新增资金。
    SELECT
      '${yyyy-MM-dd}' AS busi_date,
      ctpty_legal_entity,
      wind_code,
      SUM(CAST(vr_cap_amount AS DOUBLE)) AS cap_amount
    FROM (
      SELECT
        vrcf.key_ctpty_id,
        vrcf.vr_cap_busidate,
        vrcf.vr_cap_type,
        vrcf.vr_cap_remark,
        vrcf.vr_cap_undrly_code,
        vrcf.vr_cap_amount,
        vrcf.ctpty_legal_entity,
        vrcf.key_otc_trade_id,
        CASE
          WHEN vrcf.vr_cap_undrly_code IS NULL THEN
            CASE
              WHEN ods.underlying_wind_code IS NULL THEN trsp.trs_wind_code
              ELSE ods.underlying_wind_code
            END
          ELSE vrcf.vr_cap_undrly_code
        END AS wind_code
      FROM (
-- rcf=资金流水；先在busi_date='h15'内按src_busi_date计数，再在行数>100000的日期中取MAX。
-- 不是取行数最多的日期，也不能由阈值证明完整性；计数发生在结算类型/备注过滤之前。
-- 此MAX没有限制<=报告日，选源快照的日期与随后限制资金发生日期是两件事。
-- LIKE '%结算%'是文字包含匹配，也能命中“未结算”；IS NOT NULL仍允许空备注，不等于状态/格式验证。
-- cp=交易对手映射，INNER JOIN缺失会丢资金；DISTINCT只消除相同id+名称，不能保证id唯一。
-- tot=OTC交易，LEFT JOIN以资金备注精确等于内部交易号补交易键，不从备注字符串中提取编号。
        SELECT
          rcf.key_ctpty_id,
          rcf.vr_cap_busidate,
          rcf.vr_cap_type,
          rcf.vr_cap_remark,
          rcf.vr_cap_undrly_code,
          rcf.vr_cap_amount,
          cp.ctpty_legal_entity,
          tot.key_otc_trade_id
        FROM (
          SELECT
            key_ctpty_id,
            SUBSTR(vr_cap_busidate, 1, 10) AS vr_cap_busidate,
            vr_cap_type,
            vr_cap_remark,
            vr_cap_undrly_code,
            CAST(vr_cap_amount AS DOUBLE) AS vr_cap_amount
          FROM odata_n_tit.d_value_report_cap_flow_p
          WHERE busi_date = 'h15'
            AND src_busi_date = (
              SELECT MAX(src_busi_date)
              FROM (
                SELECT
                  src_busi_date,
                  COUNT(*) AS row_num
                FROM odata_n_tit.d_value_report_cap_flow_p
                WHERE busi_date = 'h15'
                GROUP BY src_busi_date
              )
              WHERE row_num > 100000
            )
            AND vr_cap_type LIKE '%结算%'
            AND vr_cap_remark IS NOT NULL
        ) rcf
        INNER JOIN (
          SELECT DISTINCT
            id,
            ctpty_legal_entity
          FROM odata_n_tit.d_ref_counter_party_p
          WHERE busi_date = 'h15'
        ) cp ON rcf.key_ctpty_id = cp.id
        LEFT JOIN (
          SELECT
            key_otc_trade_id,
            internal_trade_id
          FROM odata_n_tit.d_trd_otc_trade_p
          WHERE busi_date = 'h15'
        ) tot ON rcf.vr_cap_remark = tot.internal_trade_id

      ) vrcf
-- ods=期权结构，按交易键取underlying_wind_code；固定读取h13分区，不是报告日分区。
-- trsp=互换当前持仓+互换腿，持仓KEY_LEG_ID关联腿，再按交易键收集标的代码。
-- COLLECT_SET去重、SORT_ARRAY排序、CONCAT_WS逗号拼串；AAA,BBB整体是一个匹配值，不自动拆成两个标的分摊。
-- 这些LEFT JOIN可能扩行；最终01再聚合不能消除被复制资金的金额影响。
      LEFT JOIN (
        SELECT
          key_otc_trade_id,
          underlying_wind_code
        FROM odata_n_tit.d_ref_option_deal_structure_p
        WHERE busi_date = 'h13'
      ) ods ON vrcf.key_otc_trade_id = ods.key_otc_trade_id
      LEFT JOIN (
        SELECT
          tl.key_otc_trade_id,
          CONCAT_WS(',', SORT_ARRAY(COLLECT_SET(pos.wind_code))) AS trs_wind_code
        FROM (
          SELECT KEY_LEG_ID,wind_code
          FROM odata_n_tit.d_pos_trs_leg_current_pos_p
          WHERE busi_date = 'h13'
        ) pos
        LEFT JOIN (
          SELECT KEY_LEG_ID,key_otc_trade_id
          FROM odata_n_tit.d_ref_trs_leg_p
          WHERE busi_date = 'h13'
        ) tl ON tl.KEY_LEG_ID = pos.KEY_LEG_ID
        GROUP BY tl.key_otc_trade_id
      ) trsp ON vrcf.key_otc_trade_id = trsp.key_otc_trade_id

    )
    WHERE wind_code IS NOT NULL
      AND vr_cap_busidate >= '2021-01-22 00:00:00'
      AND vr_cap_busidate <= '${yyyy-MM-dd}'
    GROUP BY ctpty_legal_entity,wind_code

    UNION
-- 与结算一路并列：估值源d_value_report_element_result_pb，同时限定grp_id=h15、分区日及business_date=报告日。
-- 只取vr_opt_contractPV_eur（期权合约现值）和vr_trs_floatIncome_eur（互换浮动收益）两个要素。
-- rcf.remark用于INNER JOIN交易对手ID；rcf.business_key直接连接交易键，不走资金侧备注→内部交易号链。
-- 代码优先期权结构，否则互换多标的拼串；本路没有与01相同的wind_code非NULL筛选。
-- SUM(result)保持源符号，没有汇率转换；要素名eur不足以证明币种或客户/我司盈亏方向。
    SELECT
      SUBSTR(business_date, 1, 10) AS busi_date,
      ctpty_legal_entity,
      wind_code,
      SUM(CAST(result AS DOUBLE)) AS cap_amount
    FROM (
-- 标的识别：输入为04.1带客户名称的估值记录；输出保留原估值明细并补wind_code。
-- business_key=交易键，先取期权结构代码，NULL才回退互换持仓去重排序后的拼串；空串不回退。
-- ods：期权交易结构表；trsp：互换当前腿持仓＋腿资料，固定h13分区，不是报告日。
      SELECT
        vrer.*,
        CASE
          WHEN underlying_wind_code IS NULL THEN trs_wind_code
          ELSE underlying_wind_code
        END AS wind_code
      FROM (
-- 当日估值输入 → 客户身份：本文件只取估值明细并补法律主体名称，不识别标的、不求和。
-- d_value_report_element_result_pb：估值要素结果；result为要素结果值。指定两个要素，分区日和业务日都限报告日。
-- d_ref_counter_party_p：交易对手资料；remark与id匹配，取得ctpty_legal_entity（法律主体名称）。
-- INNER JOIN意味着身份缺失的估值退出；DISTINCT(id,名称)不保证一id只对应一名称。
        SELECT
          rcf.*,
          ctpty_legal_entity
        FROM (
          SELECT *
          FROM odata_n_tit.d_value_report_element_result_pb
          WHERE grp_id = 'h15'
            AND busi_date = '${yyyy-MM-dd}'
            AND substr(business_date, 1, 10) = '${yyyy-MM-dd}'
            AND element_id IN ('vr_opt_contractPV_eur', 'vr_trs_floatIncome_eur')
        ) rcf
        INNER JOIN (
          SELECT DISTINCT
            id,
            ctpty_legal_entity
          FROM odata_n_tit.d_ref_counter_party_p
          WHERE busi_date = 'h15'
        ) rcp ON rcf.remark = rcp.id

      ) vrer
      LEFT JOIN (
        SELECT
          key_otc_trade_id,
          underlying_wind_code
        FROM odata_n_tit.d_ref_option_deal_structure_p
        WHERE busi_date = 'h13'
      ) ods ON vrer.business_key = ods.key_otc_trade_id
      LEFT JOIN (
        SELECT
          key_otc_trade_id,
           CONCAT_WS(',', SORT_ARRAY(COLLECT_SET(wind_code))) AS trs_wind_code
        FROM (
          SELECT *
          FROM odata_n_tit.d_pos_trs_leg_current_pos_p
          WHERE busi_date = 'h13'
        ) pos
        LEFT JOIN (
          SELECT *
          FROM odata_n_tit.d_ref_trs_leg_p
          WHERE busi_date = 'h13'
        ) tl ON tl.KEY_LEG_ID = pos.KEY_LEG_ID
        GROUP BY key_otc_trade_id
      ) trsp ON vrer.business_key = trsp.key_otc_trade_id

    )
    GROUP BY ctpty_legal_entity,SUBSTR(business_date, 1, 10), wind_code

  )
  GROUP BY busi_date, ctpty_legal_entity, wind_code
)
-- 最终将pnl按公司名称+标的代码接到持仓底座，不按USCC、合同或标的名称匹配。
-- current_pnl缺匹配补0后/10000；0既可能是真零，也可能是缺资料/名称不符/拼串无法匹配。
-- 比例=本行原盈亏 / 本公司名下连接结果的盈亏绝对值之和，不除本金，非投资收益率。
-- 窗口仅PARTITION BY公司名称：不同USCC同名共用分母；同代码异标的名会重复接同一盈亏。
-- 只有底座仍有的标的进入窗口；已退出持仓的历史盈亏不展示，也不进分母。
SELECT company_name,
	company_id,
	underlying_code,
	underlying_name,
	hold_amount,
	current_pnl,
	pnl_ratio,
	busi_date FROM (
SELECT
    t.company_name
    ,t.company_id
    ,t.underlying_code
    ,t.underlying_name
    ,t.hold_amount / 10000   as hold_amount
    ,COALESCE(pnl.profit_loss, 0) / 10000 as current_pnl
    ,CASE
        WHEN SUM(ABS(pnl.profit_loss)) OVER (PARTITION BY t.company_name) = 0
             OR pnl.profit_loss IS NULL
        THEN 0
        ELSE pnl.profit_loss / NULLIF(SUM(ABS(pnl.profit_loss)) OVER (PARTITION BY t.company_name), 0)
     END                                    as pnl_ratio
    ,'${yyyy-MM-dd}'                        as busi_date
from (
-- 最终输出主体：创收日报的报告日快照，grp_id=01/02/03且计提日=报告日。
-- 按USCC+公司全称+标的代码+名称汇总动态本金；无正本金条件，零/负/NULL组也可能保留。
-- 不读取Curr_Rev来代替盈亏，亦不按业务类型分组；同公司同标的可合并期权/互换本金。
-- 同标的不同名称会分开，同名不同USCC也分开；这与06仅按公司名称计算窗口分母不同。
    SELECT
        Cutp_Pty_Full_Name          as company_name
        ,USCC                       as company_id
        ,Undrl_Wd_Cd                as underlying_code
        ,Undrl_Name                 as underlying_name
        ,sum(Dyna_Nom_Prin)  as hold_amount
    from DM_OTC_N.OTC_REV_DAILY_RPT
    where busi_date = '${yyyy-MM-dd}'
      and grp_id in ('01', '02', '03')
      and Accrued_Date = '${yyyy-MM-dd}'
    group by USCC, Cutp_Pty_Full_Name, Undrl_Wd_Cd, Undrl_Name

) t
LEFT JOIN pnl ON t.company_name = pnl.ctpty_legal_entity
              AND t.underlying_code = pnl.wind_code
	) castTable

