-- GENERATED by ../render.mjs; edit the branch main SQL and its includes.
-- 223867 金仕达客户创收：主线只组织原有来源与连接，不创建生产视图。
-- 阅读：合约日 → 利息/佣金/占资/成交/报盘费/成本率 → 02创收表达式 → 74列输出。
-- info=合约主信息，det=逐日明细；其他别名实际表与键在下方就地说明。
-- 保留外层74列（含2分区）及内层字段顺序。金额公式由02模块真实引用，不另抄一份。
-- info来自T98_OTC_DERI_COMP_SALE_INFO；det来自T98_OTC_DERI_COMP_SALE_ADTNL_DET；cp来自T01_CORP_CUST。
-- Trd_Cms=co.ks_long_fee（当日毛佣金），不是净创收；Accrued_Date=det.busi_date，busi_date=报告日快照。
SELECT Agt_Id,
	Busi_Type,
	Cutp_Pty_Id,
	Cutp_Pty_Shor_Name,
	Cutp_Pty_Full_Name,
	Sign_Prd_Name,
	USCC,
	Contr_Type_Cd,
	Contr_Type_Desc,
	Src_Contr_Type,
	Src_Contr_Type_Desc,
	Src_Sub_Contr_Type,
	Src_Sub_Contr_Type_Desc,
	Undrl_Wd_Cd,
	Undrl_Name,
	Init_Nom_Prin,
	Dyna_Nom_Prin,
	Curr_Rev,
	Opt_Npv_Curr_Rev,
	Strt_Pric_Date,
	End_Pric_Date,
	Is_Preterm_Flag,
	Early_Term_Date,
	Agt_Stat_Cd,
	Accrued_Date,
	Inr_Seri_No,
	otc_seri_no,
	Book_Agt_Id,
	Cntr,
	Cros_Crrc_Type_Cd,
	fixed_rate,
	Flot_Intrt_Ulmt,
	Float_Base_Rate,
	Intr_Marg,
	Float_Undrl_Cd,
	Undrl_Curr,
	Bgng_Npv,
	prop_group,
	Opt_Fee_Rate,
	Init_Marg_Prop,
	Base_Marg_Rate,
	Marg_Agt_Id,
	FUND_COST_RATE,
	MARGIN_FIXED_RATE,
	COMMISSION_COST,
	SPREAD,
	LONG_FIXED_RATE,
	CAPITAL_COST,
	Cms_Mode_Cd,
	Trd_Fee_Rate,
	Bgng_Vol,
	Peshr_Cms,
	Nom_Prin_Chg_Delta,
	Occu_Qty,
	Divd_Tax_Amt,
	intrt,
	ir,
	Tdy_Yield,
	Simu_Hedg_Pal,
	prop_ratio,
	Map_Undrl_Cd,
	Undrl_Tdy_Yield,
	Undrl_Simu_Hedg_Pal,
	Sett_Crrc_Cd,
	mid_price,
	OTHER_Prvs_Fee,
	PREMIUM_Prvs_Fee,
	Data_Time,
	Trd_Cms,
	Rev_Contr_Type_Cd,
	Agt_Clas_Cd,
	Src_Undrl_Type,
	busi_date,
	grp_id FROM (
	 select
    info.Agt_Id,  --合约编号
    info.Busi_Type,  --业务类型
    info.Cutp_Pty_Id,  --交易对手客户编号
    info.Cutp_Pty_Shor_Name,  --交易对手当事人简称
    info.Cutp_Pty_Full_Name,  --交易对手当事人名称
    info.Sign_Prd_Name,  --代签产品名称
    cp.USCC,  --统一社会信用代码
    info.Contr_Type_Cd,  --合约类型代码
    info.Contr_Type_Desc,  --合约类型描述
    info.Src_Contr_Type,  --源合约类型
    info.Src_Contr_Type_Desc,  --源合约类型描述
    info.Src_Sub_Contr_Type,  --源合约子类型
    info.Src_Sub_Contr_Type_Desc,  --源合约子类型描述
    info.Undrl_Wd_Cd,  --标的万得代码
    info.Undrl_Name,  --标的名称
    info.Init_Nom_Prin,  --初始名义本金
    coalesce(det.Dyna_Nom_Prin, 0) as Dyna_Nom_Prin,  --动态名义本金
-- 用途：在01结果投影的SELECT层计算Curr_Rev（当日计提创收），最后的逗号接下一输出列。
-- co.ks_other_profit / ks_long_fee ← S_V_CONFIRMATION_OVERVIEW 累计资料按清算日差分（见03）。
-- bc.actual_occupy_amt / remain_contract ← S_GF_BK_CONTRACT 最近交易日记录；后者具体经济释义待确认，不猜为保证金。
-- fc.fund_cost_rate ← G_CLIENT_REVENUE_COEFFICIENT按生效日展开（见06），没有NULL回退。
-- tc.long_trade_amount ← S_GF_BK_CONTRACT当日成交差分（见04）；cas.cust_total_fee ← M_T_CMP_AGENT_STAT费用差分（见05）。
-- 正常多空互换：利息－非负净占资×年成本率/365＋毛佣金－成交扣费－报盘费；其他类型返回0。
-- 0.0000641和365是本次实际SQL固定值，制度依据未确认；本任务没有118141的跨合约系统费用二次分摊。
if(
    info.Src_Contr_Type = 'B_LONG_SHORT_SWAP',
    coalesce(co.ks_other_profit,0)
    - default.gfgreatest(
        coalesce(bc.actual_occupy_amt,0)-coalesce(bc.remain_contract,0),
        0
      ) * fc.fund_cost_rate / 365
    + coalesce(co.ks_long_fee,0)
    - coalesce(tc.long_trade_amount,0) * 0.0000641
    - coalesce(cas.cust_total_fee,0),
    0
) AS Curr_Rev,


  --当日计提创收
    0 as Opt_Npv_Curr_Rev,  --当日期权NPV计提创收
    info.Strt_Pric_Date,  --期初定价日
    coalesce(info.Early_Term_Date, info.End_Pric_Date) as End_Pric_Date,  --期末定价日
    IF(info.Early_Term_Date IS NULL OR info.Early_Term_Date = '', '0', '1') AS Is_Preterm_Flag,  --是否终止标志
    info.Early_Term_Date,  --提前终止日
    info.Agt_Stat_Cd,  --协议状态代码
    det.busi_date as Accrued_Date,  --计提日期
    info.Inr_Seri_No,  --内部流水号
    info.otc_seri_no,  --场外合约流水号
    info.Book_Agt_Id,  --账簿协议编号
    info.Cntr,  --柜台
    info.Cros_Crrc_Type_Cd,  --跨币种类型代码
    info.fixed_rate,  --固定腿利率
    info.Flot_Intrt_Ulmt,  --浮动利率上限
    info.Float_Base_Rate,  --浮动基础利率
    info.Intr_Marg,  --利差
    info.Float_Undrl_Cd,  --浮动腿标的代码
    info.Undrl_Curr,  --标的币种
    info.Bgng_Npv,  --期初NPV
    info.prop_group,  --关联合约分组
    info.Opt_Fee_Rate,  --期权预估期权费率
    info.Init_Marg_Prop,  --初保线
    info.Base_Marg_Rate,  --基保线
    null as Marg_Agt_Id,  --拆货基合约编号
    fc.FUND_COST_RATE,  --资金成本利率
    null as MARGIN_FIXED_RATE,  --保证金固定利率
    null as COMMISSION_COST,  --佣金成本
    null as SPREAD,  --利差
    null as LONG_FIXED_RATE,  --多头持券固定利率成本
    null as CAPITAL_COST,  --用资利率
    null as Cms_Mode_Cd,  --佣金模式代码
    null as Trd_Fee_Rate,  --交易费率
    null as Bgng_Vol,  --期初数量
    null as Peshr_Cms,  --每股佣金（标的币种）
    null as Nom_Prin_Chg_Delta,  --名义本金变动（结算币种）
    null as Occu_Qty,  --发生数量（结算币种）
    null as Divd_Tax_Amt,  --分红税金额（结算币种）
    null as intrt,  --浮动利率
    null as ir,  --资金成本浮动利率
    null as Tdy_Yield,  --当日盈亏（结算币种）
    null as Simu_Hedg_Pal,  --模拟对冲盈亏（结算币种）
    null as prop_ratio,  --分摊比例
    null as Map_Undrl_Cd,  --匹配标的代码
    null as Undrl_Tdy_Yield,  --标的当日盈亏（结算币种）
    null as Undrl_Simu_Hedg_Pal,  --标的模拟对冲盈亏（结算币种）
    null as Sett_Crrc_Cd,  --结算币种
    null as mid_price,  --人民币中间汇率
    null as OTHER_Prvs_Fee,  --按日计提其他费
    null as PREMIUM_Prvs_Fee,  --按日计提期权费
    from_unixtime(unix_timestamp(),'yyyy-MM-dd HH:mm:ss') AS Data_Time,  --数据时间
    co.ks_long_fee as Trd_Cms,  --交易佣金收入
    info.Src_Contr_Type as Rev_Contr_Type_Cd,  --创收合约类型
    info.Agt_Clas_Cd,  --协议类型代码
    info.Src_Undrl_Type,  --源标的类型
    '${yyyy-MM-dd}' as busi_date,  --业务日期
    '03' as grp_id  --分组标识



-- 合约主表 info：报告日OTC金仕达，排除原SQL三个客户；结束日期仍可覆盖历史合约。
from (
    select *, null as prop_group from PDATA_N.T98_OTC_DERI_COMP_SALE_INFO
    where busi_date = '${yyyy-MM-dd}' and Book_Bel_Dept = 'OTC' and coalesce(Early_Term_Date, End_Pric_Date) >= '2022-01-01'
        and grp_id = '03' and Cutp_Pty_Id not in ('DEV1100103598','DEV1100103339','DEV1100100652')
    ) info

-- 日明细 det：自身起止日期内的逐日本金；INNER JOIN按合约号，不限只取报告日。
inner join (
    select * from PDATA_N.T98_OTC_DERI_COMP_SALE_ADTNL_DET
    where busi_date between Strt_Pric_Date and End_Pric_Date
    ) det
on info.agt_id = det.agt_id

-- 客户 cp：报告日有效对公客户，用交易对手客户编号补USCC，缺失仍保留合约日。
left join (
    select * from PDATA_N.T01_CORP_CUST
    where src_tbl = 'ODATA_N_OIS.O_OTC_DERIVATIVE_COUNTERPARTY' and busi_date = '${yyyy-MM-dd}' and DEL_FLAG = '0'
    ) cp
on cp.pty_id = info.Cutp_Pty_Id

-- 利息／佣金 co：内部合约号＋计提日；只对多空互换补入。
left join (
-- 来源：ODATA_N_LSS.S_V_CONFIRMATION_OVERVIEW，金仕达合约确认汇总。
-- contract_code=合约内部编号，clear_date=清算日期；按合约、清算日排序后差分。
-- ks_other_profit：前一行累计值－本行累计值；ks_long_fee：本行累计值－前一行累计值。
-- 第一行的前值默认0；不是统一用本行－前行。这里没有限定报告日，不能先截掉历史再差分。
-- 输出 co，由主脚本按 info.Inr_Seri_No＋det.busi_date 连接。
select contract_code, clear_date,
        lead(coalesce(ks_other_profit,0), -1, 0) over(partition by contract_code order by clear_date) - coalesce(ks_other_profit,0) as ks_other_profit,  --当日利息收入
        coalesce(ks_long_fee,0) - lead(coalesce(ks_long_fee,0), -1, 0) over(partition by contract_code order by clear_date) as ks_long_fee  --当日交易佣金
    from odata_n_lss.s_v_confirmation_overview


) co
on co.contract_code = info.Inr_Seri_No and default.datekey2date(co.clear_date) = det.busi_date and info.Src_Contr_Type = 'B_LONG_SHORT_SWAP'

-- 占资 bc：同一内部合约号，按计提日当天或之前最近交易日取资料。
-- 净占资=max(actual_occupy_amt实际占资－remain_contract保留原字段,0)。remain_contract经济含义待核元数据。
left join odata_n_lss.s_gf_bk_contract bc  --实际占资，非交易日取上个交易日
on bc.contract_code = info.Inr_Seri_No and default.datekey2date(bc.clear_date) = default.pretradedate(date_add(det.busi_date,1),1) and info.Src_Contr_Type = 'B_LONG_SHORT_SWAP'

-- 成交 tc：按计提日精确匹配，不能套用bc的最近交易日规则。
left join (
-- 来源：ODATA_N_LSS.S_GF_BK_CONTRACT，金仕达合约资金／成交资料。
-- long_trade_amount：本行累计成交金额－前一清算行累计成交金额，第一行前值默认0。
-- 输出 tc.long_trade_amount；主脚本按内部合约编号＋计提日精确连接，再乘0.0000641进入创收扣减。
-- 不使用上一交易日回退；非交易日匹配规则与主脚本中的占资 bc 不同。
select contract_code, clear_date,
        coalesce(long_trade_amount,0) - lead(coalesce(long_trade_amount,0), -1, 0) over(partition by contract_code order by clear_date) as long_trade_amount  --当日成交金额
    from odata_n_lss.s_gf_bk_contract


) tc
on tc.contract_code = info.Inr_Seri_No and default.datekey2date(tc.clear_date) = det.busi_date and info.Src_Contr_Type = 'B_LONG_SHORT_SWAP'

-- 报盘费 cas：按交易日期精确匹配，源快照已限定报告日。
left join (
-- 来源：ODATA_N_LSS.M_T_CMP_AGENT_STAT，金仕达客户报盘费用资料。
-- 先取报告日快照，按 合约＋交易日期＋累计费用 三列 DISTINCT，再按合约、交易日差分。
-- cust_total_fee：本行累计报盘费用－前行累计费用。DISTINCT不是保证合约＋日期唯一。
-- 输出 cas.cust_total_fee；主脚本按内部合约编号＋计提日连接，不做非交易日回填。
-- 元数据称cust_total_fee为“交易对手方报盘费用总计”；原行注释称“未结”有冲突，不据此改成cust_unsettle_fee。
select contract_code,trade_date,
        coalesce(cust_total_fee,0) - lead(coalesce(cust_total_fee,0), -1, 0) over(partition by contract_code order by trade_date) as cust_total_fee  --当日未结报盘费
    from (select distinct contract_code,trade_date,cust_total_fee from odata_n_lss.m_t_cmp_agent_stat
    where busi_date = '${yyyy-MM-dd}') t

) cas
on cas.contract_code = info.Inr_Seri_No and cas.trade_date = det.busi_date and info.Src_Contr_Type = 'B_LONG_SHORT_SWAP'

-- 成本率 fc：按计提日取展开参数；缺失利率会传播NULL，保持LEFT JOIN。
left join (
-- 来源：ODATA_N_OIS.G_CLIENT_REVENUE_COEFFICIENT，客户创收参数；不是销售资金成本参数表。
-- 取报告日快照中未删除的 KS_LONG_SHORT_SWAP / FUND_COST_RATE 配置。
-- 本次 effective_date 起，覆盖至下次生效日前一天；最后一条截止报告日，展开成每天的 fc.fund_cost_rate。
-- 原窗口仅 order by effective_date，没有币种分组、同日去重或对重复日期的次级排序。
-- 缺少整条日期参数时，LEFT JOIN后的利率是NULL；创收公式没有把利率补成0。
select
        value as fund_cost_rate,
        date_add(strt_date, pos) as busi_date
    from (
        select
            value,
            effective_date as strt_date,
            date_sub(lead(effective_date, 1, date_add('${yyyy-MM-dd}', 1)) over(order by effective_date), 1) as end_Date
        from odata_n_ois.g_client_revenue_coefficient
        where busi_date = '${yyyy-MM-dd}' and is_del = 'N' and contract_type = 'KS_LONG_SHORT_SWAP' and coefficient_type = 'FUND_COST_RATE'
        ) x
    lateral view posexplode(split(space(datediff(end_date, strt_date)), ' ')) y as pos, val


) fc
on fc.busi_date = det.busi_date and info.Src_Contr_Type = 'B_LONG_SHORT_SWAP' 
	
) castTable

