-- GENERATED by ../render.mjs; edit the branch main SQL and its includes.
-- 232556部门协同：客户范围×四栏目，三路资料并列LEFT JOIN，再按栏目选说明与金额。
-- 01底座决定出现谁，02托管/研究、03财富代销、04商机转介并列补充，05负责最终展示。
-- 四栏目不是互斥金额桶；商机转介可包含其他三栏的同一批奖励，不能直接加总。
-- 原SQL token不变，仅拆引用并补中文；最终行数可能被03的USCC连接扩增，不保证恰好四行。
-- 六列输出：公司名称、USCC、协同栏目、说明、金额、报告日。
-- 托管说明固定NULL；研究说明检查02是否匹配；财富说明来自指标判断；商机说明来自部门集合。
-- cross_sale_amount按栏目取对应奖励汇总，未除10000、未COALESCE；不擅自标成万元或实付现金。
SELECT company_name,
	company_id,
	coop_dept,
	summary,
	cross_sale_amount,
	busi_date FROM (
SELECT
    t_base.company_name
    ,t_base.company_id
    ,d.coop_dept
    ,case d.coop_dept
        when '托管'     then null
        when '财富代销' then t_cfmx.summary
        when '研究服务' then if(t_tg_yjfw.company_name is not null, '有研究服务关系', '无研究服务关系')
        when '商机转介' then t_sjjz.summary
     end as summary
    ,case d.coop_dept
        when '托管'     then t_tg_yjfw.cross_sale_amount
        when '财富代销' then t_cfmx.cross_sale_amount
        when '研究服务' then t_tg_yjfw.cross_sale_amount
        when '商机转介' then t_sjjz.cross_sale_amount
     end    as cross_sale_amount
    ,'${yyyy-MM-dd}' as busi_date

-- 创收日报只提供客户范围：报告日快照、grp_id=01/02/03、上一年元旦至报告日的计提记录。
-- DISTINCT按公司全称+USCC去重，不按USCC单独统一名称，不另限Busi_Type/期初日/正创收。
-- CROSS JOIN固定展开托管/财富代销/研究服务/商机转介，先有栏目不代表实际合作发生。
-- 奖励表中有但创收客户底座没有的公司，不会反向新增到本表。
from (
    select distinct
        Cutp_Pty_Full_Name as company_name
        ,USCC as company_id
    from DM_OTC_N.OTC_REV_DAILY_RPT
    where busi_date = '${yyyy-MM-dd}'
      and grp_id in ('01','02','03')
      and Accrued_Date between '${yyyy,-1y}-01-01' and '${yyyy-MM-dd}'
) t_base
cross join (
    select '托管' as coop_dept union all
    select '财富代销' union all
    select '研究服务' union all
    select '商机转介'
) d

-- 交叉收入奖励汇总表：只取OIS交叉收入奖励来源，报告日快照，上年Q1到本年报告季度。
-- 资产托管部映为托管，发展研究中心映为研究服务；按公司名称+部门汇总Dev_Dept_Rwd。
-- 名称+栏目连接到底座。研究服务“有关系”仅检查是否命中记录，不要求金额>0，也不是独立合同核验。
-- 没有记录则金额NULL；有记录但金额NULL也可能显示“有研究服务关系”，原公式不补0。
left join (
    SELECT
        Pty_Cutp_Name as company_name
        ,if(Bel_Inr_Org_Name='资产托管部', '托管', '研究服务') as coop_dept
        ,sum(Dev_Dept_Rwd) as cross_sale_amount
    from pdata_n.T98_OTC_DERI_UNDRL_INCOME_RWD_SUM
    where busi_date = '${yyyy-MM-dd}'
      and src_tbl = 'ODATA_N_OIS.G_CROSS_INCOME_REWARD'
      and Sett_Time between '${yyyy,-1y}01' and concat('${yyyy}0', quarter('${yyyy-MM-dd}'))
      and Bel_Inr_Org_Name in ('资产托管部', '发展研究中心')
    group by Pty_Cutp_Name, Bel_Inr_Org_Name
) t_tg_yjfw
  on t_base.company_name = t_tg_yjfw.company_name
  and d.coop_dept = t_tg_yjfw.coop_dept

-- 两套独立判断：wei决定“有无财富代销”，t_rwd提供财富部门奖励；有代销不等于有奖励，反之亦然。
-- r：底座范围内按合约+公司全称+USCC+代签产品去重；Sign_Prd_Name关联wei的代签产品名称。
-- wei：季度指标经证券组合/营业部组合约束、产品代码→代签产品名映射，先按代签产品名SUM，再判断汇总>0。
-- 所以一个季度为正仍可能被其他季度负值抵消；index_val是判断指标，不作奖励金额/到账金额。
-- t_rwd：按公司名称汇总财富管理与经纪业务总部的Dev_Dept_Rwd，不从index_val计算奖励。
-- 子结果按名称+USCC+奖励金额分组，外层却只按USCC连接且未限栏目；同USCC异名可扩增全部四栏目。
left join (
    SELECT
        r.Cutp_Pty_Full_Name as company_name
        ,r.USCC as company_id
        ,case
            when sum(case when coalesce(wei.index_val, 0) > 0 then 1 else 0 end) > 0
             then '有财富代销'
             else '无财富代销'
         end as summary
        ,t_rwd.cross_sale_amount
    from (
        select distinct Agt_Id, Cutp_Pty_Full_Name, USCC,Sign_Prd_Name
        from DM_OTC_N.OTC_REV_DAILY_RPT
        where busi_date = '${yyyy-MM-dd}'
          and grp_id in ('01','02','03')
          and Accrued_Date between '${yyyy,-1y}-01-01' and '${yyyy-MM-dd}'
    ) r
    left join (
        select
            prd.signature_name
            ,sum(cast(idx.index_val as double)) as index_val
        from dm_index_n.index_grp2_TnrAmtProp_Season idx -- 产品×营业部&分公司&总部各部门_保有金额占比_剔除内部户&场外衍生品_季
        JOIN (
            SELECT grp_id, split(grp_val,'\\\.')[2] as prod_code
            FROM dm_index_n.grp_def WHERE grp_type_code IN ('NEWS_SECU')
        ) grp1 on idx.grp_id1 = grp1.grp_id
        JOIN (SELECT * FROM dm_index_n.grp_def WHERE grp_type_code IN ('BUSINESSOFFICE')) grp2
        on idx.grp_id2 = grp2.grp_id
        join(
            select distinct prod_code, signature_name
            from ODATA_N_OIS.O_OTC_DERIVATIVE_COUNTERPARTY
            where Busi_Date = '${yyyy-MM-dd}'
        ) prd on grp1.prod_code = prd.prod_code
        where idx.busi_quat between '${yyyy,-1y}Q1' and concat('${yyyy}Q', quarter('${yyyy-MM-dd}')) -- busi_quat=业务季度；index_val=指标值，非奖励金额
          and idx.tag_id = 'tag999999999'
        group by prd.signature_name
    ) wei
    on r.Sign_Prd_Name = wei.signature_name
    left join (
        SELECT
            Pty_Cutp_Name
            ,sum(Dev_Dept_Rwd) as cross_sale_amount
        from pdata_n.T98_OTC_DERI_UNDRL_INCOME_RWD_SUM
        where busi_date = '${yyyy-MM-dd}'
          and src_tbl = 'ODATA_N_OIS.G_CROSS_INCOME_REWARD'
          and Sett_Time between '${yyyy,-1y}01' and concat('${yyyy}0', quarter('${yyyy-MM-dd}'))
          and Bel_Inr_Org_Name = '财富管理与经纪业务总部'
        group by Pty_Cutp_Name
    ) t_rwd on r.Cutp_Pty_Full_Name = t_rwd.Pty_Cutp_Name
    group by r.Cutp_Pty_Full_Name, r.USCC, t_rwd.cross_sale_amount
) t_cfmx on t_base.company_id = t_cfmx.company_id

-- 同一奖励来源和季度范围，排除股权衍生品业务部后，按公司名称汇总所有剩余部门。
-- 托管、研究、财富部门并未排除，所以与02/03奖励重叠；不是“其他部门”的互斥余项。
-- summary对部门名称COLLECT_SET去重再用中文分号拼接，未SORT_ARRAY，展示顺序无保证。
-- 部门为NULL时!=条件不成立；奖励金额NULL不会在此统一补0。外层按公司名称连接。
left join (
    SELECT
        t.Pty_Cutp_Name as company_name
        ,concat_ws('；', collect_set(t.Bel_Inr_Org_Name)) as summary
        ,sum(t.Dev_Dept_Rwd) as cross_sale_amount
    from pdata_n.T98_OTC_DERI_UNDRL_INCOME_RWD_SUM t
    where t.busi_date = '${yyyy-MM-dd}'
      and t.src_tbl = 'ODATA_N_OIS.G_CROSS_INCOME_REWARD'
      and t.Sett_Time between '${yyyy, -1y}01' and concat('${yyyy}0', quarter('${yyyy-MM-dd}'))
      and t.Bel_Inr_Org_Name != '股权衍生品业务部'
    group by t.Pty_Cutp_Name
) t_sjjz on t_base.company_name = t_sjjz.company_name

) castTable
