-- GENERATED by render.mjs; edit 00–06 SQL modules.
/*
114013 / 从合约日金额到对内销售收入日报。

01 当前合约、对内重分类 ── 与逐日明细dy、客户范围cp汇合
      ├─ 02 映射mp → 类型基准b；合约价差sp；合约基准cb
      └─ 03 自身与关联合约期初估值npv（仅B2B期权收入使用）
                              ↓
04 contract_day_income：按B2B、特殊类型、普通绝对/年化顺序选收入公式
                              ↓
05 allocated_day_income：接内部经办人m，分配当日收入并按合约累计
                              ↓
06 日报52列：保持原顺序，转换原来需要转换的列

这是原嵌套查询的阅读层次，不声明数据库物理执行顺序。
每个CTE只替代原位置的一段子查询，不重新按合约号拼接中间结果。
@include由render.mjs展开，不是Hive原生语法；没有执行生产SQL。
*/
WITH contract_info AS (
-- 用途：保留当前加工日的合约资料，补对内经营分类与用于映射的标的分类。
-- 输出contract_info，在04中作为info：先与逐日明细、客户范围INNER JOIN，再补参数。
-- End_Pric_Date_n优先提前终止日，仅NULL回退；空串不会回退到期末日。
-- 原主信息Contr_Type_Cd没有被改写：本层另产生Inr_Contr_Type_Cd，04才选择日报分类。
-- 构造例INR_DEMO：EQUITY且Res_Flag=0 → CIR_STOCK；非B2B/同业/跨境 → 显式经营分类NULL。
-- 04再让mp映射到演示配置CD017，类型基准据此匹配；不是在本层就选完参数。
select *, coalesce(Early_Term_Date, End_Pric_Date) as End_Pric_Date_n,
    -- 标的分类：此特殊互换留空用于匹配；其输出文字在04另处理。
    case when Src_Contr_Type = 'B_LONG_SHORT_SWAP' then ''
         when (Src_Undrl_Type in ('EQUITY', 'BASKET') and Res_Flag = '1') or Src_Undrl_Type = 'GDR' then 'PRI_STOCK'
         when Src_Undrl_Type in ('EQUITY', 'BASKET') and Res_Flag = '0' then 'CIR_STOCK'
         when Src_Undrl_Type = 'BOND' then 'BOND'
         when Src_Undrl_Type = 'FUTURE' then 'FUTURE'
         when Src_Undrl_Type = 'INDEX' then 'INDEX'
         when Src_Undrl_Type = 'QIS' then 'QIS'
         when Src_Undrl_Type in ('FUND','HEDGE_FUND') then 'FUND'
         else 'OTHER'
         end as Undrl_Type_n,
    case when Src_Contr_Type = 'B_LONG_SHORT_SWAP' then ''
         when (Src_Undrl_Type in ('EQUITY', 'BASKET') and Res_Flag = '1') or Src_Undrl_Type = 'GDR' then '限售股'
         when Src_Undrl_Type in ('EQUITY', 'BASKET') and Res_Flag = '0' then '流通股'
         when Src_Undrl_Type = 'BOND' then '债券'
         when Src_Undrl_Type = 'FUTURE' then '期货'
         when Src_Undrl_Type = 'INDEX' then '股指'
         when Src_Undrl_Type = 'QIS' then '策略指数'
         when Src_Undrl_Type in ('FUND','HEDGE_FUND') then '基金'
         else '其他'
         end as Undrl_Type_Desc_n,
    -- 分类优先顺序：2026港股通特殊类型 → 同业 → B2B → 跨境 → 其余QIS/互换。
    -- 没有ELSE：本层未命中为NULL，映射与CD017兜底留在04，不提前覆盖公共分类。
    case when Strt_Pric_Date >= '2026-01-01' and Ex_Rate_Model in ('SHENZHEN_HONGKONG_STOCK_CONNECT','SHANGHAI_HONGKONG_STOCK_CONNECT')
            and Src_Contr_Type in ('RISKY','AIRBAGX','S_CROSS_SWAP') then 'CD025'
         when Busi_Type = 'OPTION' and Indt_Cd in ('11','13') and coalesce(hedg_type_cd,'') != 'B2B'
            and Src_Undrl_Type not in ('EQUITY','GDR','QIS') and Src_Contr_Type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then 'CD002'
         when Busi_Type = 'OPTION' and Indt_Cd in ('11','13') and coalesce(hedg_type_cd,'') != 'B2B'
            and Src_Undrl_Type = 'QIS' and Src_Contr_Type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then 'CD020'
         when Busi_Type = 'OPTION' and hedg_type_cd = 'B2B' then 'CD001'
         when Busi_Type = 'OPTION' and Book_Bel_Dept = 'OTC' and Src_Undrl_Type not in ('EQUITY','GDR','QIS')
            and Undrl_Curr != 'CNY' and Src_Contr_Type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then 'CD023'
         when Busi_Type = 'OPTION' and (Cutp_Pty_Id like 'HK%' or Cutp_Pty_Full_Name = '廣發全球資本有限公司') and Src_Undrl_Type not in ('EQUITY','GDR','QIS')
            and Undrl_Curr = 'CNY' and Src_Contr_Type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then 'CD023'
         when Busi_Type = 'OPTION' and Book_Bel_Dept = 'OTC' and Src_Undrl_Type in ('EQUITY','GDR')
            and Undrl_Curr != 'CNY' and Src_Contr_Type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then 'CD024'
         when Busi_Type = 'OPTION' and (Cutp_Pty_Id like 'HK%' or Cutp_Pty_Full_Name = '廣發全球資本有限公司') and Src_Undrl_Type in ('EQUITY','GDR')
            and Undrl_Curr = 'CNY' and Src_Contr_Type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then 'CD024'
         when Busi_Type = 'OPTION' and Book_Bel_Dept = 'OTC' and Src_Undrl_Type = 'QIS'
            and Undrl_Curr != 'CNY' and Src_Contr_Type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then 'CD021'
         when Busi_Type = 'OPTION' and (Cutp_Pty_Id like 'HK%' or Cutp_Pty_Full_Name = '廣發全球資本有限公司') and Src_Undrl_Type = 'QIS'
            and Undrl_Curr = 'CNY' and Src_Contr_Type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then 'CD021'
         when Busi_Type = 'OPTION' and Src_Undrl_Type = 'QIS' then 'CD022'
         when Busi_Type = 'TRS' and (Cutp_Pty_Id like 'HK%' or Cutp_Pty_Full_Name = '廣發全球資本有限公司')
            and Undrl_Curr = 'CNY' then 'CD018'
         when Busi_Type = 'TRS' and Src_Undrl_Type = 'QIS' then 'CD019'
         end as Inr_Contr_Type_Cd,
    case when Strt_Pric_Date >= '2026-01-01' and Ex_Rate_Model in ('SHENZHEN_HONGKONG_STOCK_CONNECT','SHANGHAI_HONGKONG_STOCK_CONNECT')
            and Src_Contr_Type in ('RISKY','AIRBAGX','S_CROSS_SWAP') then '特殊气囊（港股通）'
         when Busi_Type = 'OPTION' and Indt_Cd in ('11','13') and coalesce(hedg_type_cd,'') != 'B2B'
            and Src_Undrl_Type not in ('EQUITY','GDR','QIS') and Src_Contr_Type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then '同业自主对冲真期权（非个股）'
         when Busi_Type = 'OPTION' and Indt_Cd in ('11','13') and coalesce(hedg_type_cd,'') != 'B2B'
            and Src_Undrl_Type = 'QIS' and Src_Contr_Type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then '策略指数-同业期权'
         when Busi_Type = 'OPTION' and hedg_type_cd = 'B2B' then '真期权背靠背'
         when Busi_Type = 'OPTION' and Book_Bel_Dept = 'OTC' and Src_Undrl_Type not in ('EQUITY','GDR','QIS')
            and Undrl_Curr != 'CNY' and Src_Contr_Type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then '跨境期权（非个股）'
         when Busi_Type = 'OPTION' and (Cutp_Pty_Id like 'HK%' or Cutp_Pty_Full_Name = '廣發全球資本有限公司') and Src_Undrl_Type not in ('EQUITY','GDR','QIS')
            and Undrl_Curr = 'CNY' and Src_Contr_Type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then '跨境期权（非个股）'
         when Busi_Type = 'OPTION' and Book_Bel_Dept = 'OTC' and Src_Undrl_Type in ('EQUITY','GDR')
            and Undrl_Curr != 'CNY' and Src_Contr_Type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then '跨境期权（个股）'
         when Busi_Type = 'OPTION' and (Cutp_Pty_Id like 'HK%' or Cutp_Pty_Full_Name = '廣發全球資本有限公司') and Src_Undrl_Type in ('EQUITY','GDR')
            and Undrl_Curr = 'CNY' and Src_Contr_Type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then '跨境期权（个股）'
         when Busi_Type = 'OPTION' and Book_Bel_Dept = 'OTC' and Src_Undrl_Type = 'QIS'
            and Undrl_Curr != 'CNY' and Src_Contr_Type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then '策略指数-跨境期权'
         when Busi_Type = 'OPTION' and (Cutp_Pty_Id like 'HK%' or Cutp_Pty_Full_Name = '廣發全球資本有限公司') and Src_Undrl_Type = 'QIS'
            and Undrl_Curr = 'CNY' and Src_Contr_Type not in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then '策略指数-跨境期权'
         when Busi_Type = 'OPTION' and Src_Undrl_Type = 'QIS' then '策略指数-其他期权'
         when Busi_Type = 'TRS' and (Cutp_Pty_Id like 'HK%' or Cutp_Pty_Full_Name = '廣發全球資本有限公司')
            and Undrl_Curr = 'CNY' then '北上跨境互换'
         when Busi_Type = 'TRS' and Src_Undrl_Type = 'QIS' then '策略指数-互换'
         end as Inr_Contr_Type_Desc
-- T98场外衍生品合约销售收入基本信息：保留原资料，再追加本消费的分类。
from PDATA_N.T98_OTC_DERI_COMP_SALE_INFO
-- 筛选边界是提前终止日优先的结束日期；当前快照保留历史合约，不等于只看当日新签。
where busi_date = '${yyyy-MM-dd}' and coalesce(Early_Term_Date, End_Pric_Date) >= '2023-01-01'
    and Cutp_Pty_Id not in ('DEV1100101715','DEV1100103266')
    and grp_id != '04'

),
-- 02定义四路并列参数查询。实际JOIN及所有ON条件统一保留在04。
-- 用途：给04提供四路并列资料；不是执行四次收入加工。
-- 映射mp决定类型基准b的匹配分类；价差sp和合约基准cb按合约身份进入。
-- 本文件只组织114013实际消费的查询，参数生产见公共加工/05_经营系数_基准/06_对内与香港基准.md。

-- INR_DEMO的例子：NORMAL＋CIR_STOCK匹配演示CD017；b在9/18取9/1生效段。
-- cb取系数2/收益率0.003，sp按每天取年化0.002；最终计算方式却由b年化优先。

-- 分类映射：一条配置中的标的代码串先展开，一行代表一个适用标的类别。
inr_type_mapping AS (
select
    otc_contract_type,
    otc_contract_type_name,
    t.Undrl_Type,
    Src_Contr_Type,
    Src_Sub_Contr_Type
from (
    select
        Op_Mng_Comp_Type_Id as otc_contract_type, -- 运管合约类型编号；供04选择最终经营分类
        Op_Mng_Comp_Type_Desc as otc_contract_type_name,
        -- 代码串为空表示八类均适用；ALL_STOCK/NON_STOCK先展开含义，再按逗号拆行。
        case when Src_Agt_Type_Cd = 'B_LONG_SHORT_SWAP' then ''
             when coalesce(Src_Undrl_Type_Cd_Str,'') = '' then 'PRI_STOCK,CIR_STOCK,INDEX,QIS,BOND,FUTURE,FUND,OTHER'
             else replace(replace(Src_Undrl_Type_Cd_Str,'ALL_STOCK','PRI_STOCK,CIR_STOCK'),'NON_STOCK','INDEX,QIS,BOND,FUTURE,FUND,OTHER')
             end as Undrl_Type,
        Src_Agt_Type_Cd as Src_Contr_Type,
        Src_Agt_Sub_Type_Cd as Src_Sub_Contr_Type
    -- 对内基础参数分类映射，生产来源G_INR_CONTRACT_MAPPING；当前日、未删除。
    from PDATA_N.T99_OTC_DERI_INR_BASE_MAPPING
    where src_tbl = 'ODATA_N_OIS.G_INR_CONTRACT_MAPPING' and busi_date = '${yyyy-MM-dd}' and Src_Deleted_Flag = '0'
    ) x
lateral view explode(split(Undrl_Type,',')) t as Undrl_Type
),

-- INR合约价差：Vld_Date至下一生效日前一日逐日展开，04按计提日匹配。
inr_spread_days AS (
select
    Contract_Code,
    Spread_Calculation,
    Annualized_Spread,
    Absolute_Spread,
    date_add(strt_date, pos) as busi_date
from (
    select
        Inr_Comp_No as Contract_Code, -- 元数据：内部合约编号；实际用于匹配日报主合约号
        if(Sprd_Calc_Type = '', null, Sprd_Calc_Type) as Spread_Calculation,
        Annu_Sprd_Coef as Annualized_Spread, -- 年化价差系数，不是已算好的收入
        Absl_Sprd_Coef as Absolute_Spread, -- 绝对价差系数，绝对分支仍乘本金和基础系数
        Vld_Date as strt_date, -- 生效日期；下一生效日前一天为本段右边界
        date_sub(lead(Vld_Date, 1, date_add('${yyyy-MM-dd}', 1)) over(partition by Inr_Comp_No order by Vld_Date), 1) as end_Date
    -- 合约价差系数参考信息：只取OIS合约价差来源、未删除且系数类型INR。
    -- Agt_Id非空只用于身份筛选，实际连接用Inr_Comp_No；本查询不按加工日再过滤T99。
    from PDATA_N.T99_DERI_COMP_SPRD_COEF_REF
    where SRC_TBL = 'ODATA_N_OIS.O_CONTRACT_SPREAD_RATE' and Del_Flag = '0' and coalesce(Coef_Type,'') = 'INR' and Agt_Id != ''
    ) x
lateral view posexplode(split(space(datediff(end_date, strt_date)), ' ')) y as pos, val
),

-- 类型基准：实际生效日至下一生效日前一日逐日展开，但04按期初定价日匹配。
inr_type_base_days AS (
select
    OTC_CONTRACT_TYPE,
    Dft_Base_Coef as Base_Coef, -- 拟定基础系数；公式里的乘数
    Base_Yield as Base_Rate, -- 基础收益率；与选中价差相加
    Adtnl_Yield as Spread_Rate, -- 附加收益率；合约价差缺值时回退到它
    base_calculation,
    date_add(strt_date, pos) as busi_date
from (
    select
        Op_Mng_Comp_Type_Id as OTC_CONTRACT_TYPE,
        Base_Yield,
        Dft_Base_Coef,
        Adtnl_Yield,
        Calc_Way as base_calculation, -- 计算方式；普通收入分支先取这一项
        Actl_Vld_Day as strt_date, -- 实际生效日；按运管类型编号分别延续
        date_sub(lead(Actl_Vld_Day, 1, date_add('${yyyy-MM-dd}', 1)) over(partition by Op_Mng_Comp_Type_Id order by Actl_Vld_Day), 1) as end_Date
    -- 对内基础参数表：来源G_INR_BASE_RATE，当前日且未删除；不是合约级参数。
    from PDATA_N.T99_OTC_DERI_INR_BASE_REF
    where src_tbl = 'ODATA_N_OIS.G_INR_BASE_RATE' and busi_date = '${yyyy-MM-dd}' and Src_Deleted_Flag = '0'
    ) x
lateral view posexplode(split(space(datediff(end_date, strt_date)), ' ')) y as pos, val
),

-- 合约基准：简单取原合约号、基础系数、基础收益率、计算类型；本查询没有日期选版。
inr_contract_base AS (
select
    Inr_Comp_No as CONTRACT_CODE,
    Dft_Base_Coef as Base_Coef,
    Base_Yield as Base_Rate,
    Calc_Type as base_calculation
-- 合约基础系数参考信息：这里来源G_INR_CONTRACT_BASE_RATE决定是对内配置。
-- 不另加Coef_Type或生效日条件，不能照抄价差筛选。
from PDATA_N.T99_DERI_COMP_BASE_COEF_REF
where SRC_TBL = 'ODATA_N_OIS.G_INR_CONTRACT_BASE_RATE' and Del_Flag = '0' and Agt_Id != ''
)


,
b2b_initial_value AS (
-- 用途：为B2B期权计算可在期初记一次的估值收入；不是逐日本金，也不使用基础系数。
-- 输入：当前合约主信息中的Bgng_Npv（元数据：期初NPV）、Rel_Agt_Id（关联合约编号）。
-- 输出b2b_initial_value，每个x.agt_id聚合一行；04按合约号LEFT JOIN为npv。
-- 先拆关联编号，再取MAX自身估值+SUM关联估值，避免自身值随关联数重复加。
-- MAX/SUM都没有补0；关联全部缺失时SUM为NULL，最终initial_npv仍为NULL。
-- INR_DEMO变为B2B：自身1200，关联REL_A=-200、REL_B=-100 → initial_npv=900。
-- 04仅在期初日输出900，05分给主360/引入540，随后累计保持这些值。
select
    x.agt_id,
    -- 拆关系后的两行自身1200取MAX一次；两行关联分别-200/-100再SUM。
    max(x.Bgng_Npv) + sum(z.Bgng_Npv) as initial_npv
-- 第一步：从当前主信息中的B2B合约拆关联合约号，不trim、不去重。
from (
    select agt_id, x.rel_agt_id, Bgng_Npv
    from (
        select agt_id, rel_agt_id, Bgng_Npv from PDATA_N.T98_OTC_DERI_COMP_SALE_INFO
        where busi_date = '${yyyy-MM-dd}' and coalesce(Early_Term_Date, End_Pric_Date) >= '2023-01-01' and hedg_type_cd = 'B2B'
        ) t
    lateral view explode(split(rel_agt_id,',')) x as rel_agt_id
    ) x
-- 第二步：关联合约只要求当前加工日；不要求它也属于B2B或也通过主体范围条件。
left join (
    select
        agt_id,
        Bgng_Npv
    from PDATA_N.T98_OTC_DERI_COMP_SALE_INFO
    where busi_date = '${yyyy-MM-dd}'
    ) z
on x.rel_agt_id = z.agt_id
-- 第三步：按自身合约汇总。仅REL_A命中时1200-200=1000；全部不命中则NULL。
-- 若关系REL_A重复两次，SUM会重复计入；MAX自身值不能替关联关系去重。
group by x.agt_id

),
contract_day_income AS (
-- 用途：把合约、合约日金额、客户范围和参数接起来，算尚未分配的当日收入。
-- 输入info来自01；mp/sp/b/cb来自02；npv来自03。dy由107491提供，cp仅限定客户范围。
-- 输出contract_day_income，05直接接为t；LEFT JOIN多条命中可能扩行，本层不去重。
-- 本段会覆盖日报Contr_Type_Cd，源类型Src_Contr_Type仍保留用于特殊公式判断。
select
    info.Agt_Id, -- 主信息合约编号；dy、cb、npv及外层经办关系均用它连接
    info.Busi_Type,
    info.Cutp_Pty_Id,
    info.Cutp_Pty_Shor_Name,
    info.Cutp_Pty_Full_Name,
    info.Sign_Prd_Name,
    -- 日报分类：本任务01的显式分类 → mp运管分类 → CD017/其他；代码、描述独立回退。
    coalesce(info.Inr_Contr_Type_Cd, mp.otc_contract_type, 'CD017') as Contr_Type_Cd,
    coalesce(info.Inr_Contr_Type_Desc, mp.otc_contract_type_name, '其他') as Contr_Type_Desc,
    info.Src_Contr_Type,
    info.Src_Contr_Type_Desc,
    info.Src_Sub_Contr_Type,
    info.Src_Sub_Contr_Type_Desc,
    info.Rel_Agt_Id,
    info.Undrl_Wd_Cd,
    info.Undrl_Name,
    -- 此特殊类型匹配参数时用空标的类别，输出才把EQUITY文字替成CIR_STOCK。
    if(info.Src_Contr_Type = 'B_LONG_SHORT_SWAP', replace(info.src_undrl_type,'EQUITY','CIR_STOCK'), info.Undrl_Type_n) as Undrl_Type,
    if(info.Src_Contr_Type = 'B_LONG_SHORT_SWAP', replace(info.src_undrl_type_desc,'股票','流通股'), info.Undrl_Type_Desc_n) as Undrl_Type_Desc,
    info.Src_Undrl_Type,
    info.Src_Undrl_Type_Desc,
    info.Indt_Cd,
    info.Hedg_Type_Cd,
    -- 展示字段：主信息实际费率 → 日报成交费率，仅四类特殊期权展示。
    if(info.Src_Contr_Type in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL'), info.fee_rate, null) as fee_rate,
    -- Fin_Rati（融资比例）是展示值：保证金dy当日→info初始→0，大于1封顶。
    if(info.Src_Contr_Type in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL','B_LONG_SHORT_SWAP'),
        1 - if(cast(coalesce(dy.Marg_Prop, info.Init_Marg_Prop,0) as double) > 1,
            1, coalesce(dy.Marg_Prop, info.Init_Marg_Prop,0)), null) as Fin_Rati,
    -- 报表展示不补0；公式会另补0。cb.Base_Coef源字段为“拟定基础系数”。
    coalesce(cb.Base_Coef,b.Base_Coef) as Base_Coef,
    coalesce(cb.Base_Rate,b.Base_Rate) as Base_Rate,
    -- 展示价差由sp自己的计算类型挑选；普通收入由b优先的计算类型挑选，可能不一致。
    coalesce(if(sp.Spread_Calculation = 'ABSOLUTE', sp.Absolute_Spread, sp.Annualized_Spread), b.Spread_Rate) as Sprd_Rate,
    info.Strt_Pric_Date,
    info.End_Pric_Date_n as End_Pric_Date,
    info.Term_Days as Actl_Days, -- 源“期限天数”直接显示为“实际天数”，不是本查询重算天数
    IF(info.Early_Term_Date IS NULL OR info.Early_Term_Date = '', '0', '1') AS Is_Preterm_Flag,
    info.Early_Term_Date,
    info.Agt_Stat_Cd,
    dy.Init_Nom_Prin, -- 初始本金取107491附加明细，非直接取本次主信息
    dy.Dyna_Nom_Prin,
    -- 收入优先级独立于分类CASE：先B2B，再两组特殊类型，最后普通绝对/年化。
    case
        -- A. B2B期权：只在期初日（或旧合约2023-01-01）记一次合并估值。
        when info.Busi_Type = 'OPTION' and info.hedg_type_cd = 'B2B' then
            if((info.Strt_Pric_Date < '2023-01-01' and dy.busi_date = '2023-01-01')
                or info.Strt_Pric_Date = dy.busi_date,
                npv.initial_npv, 0)

        -- B. 四类特殊期权：用info初始保证金比例，不取上面展示的Fin_Rati。
        -- 初始比例NULL或恰为1 → 此乘数为1；大于1没有封顶，可能得到负收入。
        -- info.fee_rate虽展示在日报，但这里没有参加收入乘法。
        when info.Src_Contr_Type in ('RISKY','AIRBAGX','AIRBAGM','AIRBAGL') then
            coalesce(dy.Dyna_Nom_Prin, 0)
            * (1 - if(coalesce(info.Init_Marg_Prop,1) = 1, 0, info.Init_Marg_Prop))
            * coalesce(cb.Base_Coef,b.Base_Coef,0)
            * (coalesce(cb.Base_Rate,b.Base_Rate,0)
                + coalesce(sp.Annualized_Spread, b.Spread_Rate,0)) / 365

        -- C. B_LONG_SHORT_SWAP：用dy当日保证金比例；缺失回0，大于1封顶为1。
        -- 本公式不回退info.Init_Marg_Prop，和上面展示Fin_Rati的取法不同。
        when info.Src_Contr_Type in ('B_LONG_SHORT_SWAP') then
            coalesce(dy.Dyna_Nom_Prin, 0)
            * (1 - if(cast(coalesce(dy.Marg_Prop,0) as double) > 1,
                1, coalesce(dy.Marg_Prop,0)))
            * coalesce(cb.Base_Coef,b.Base_Coef,0)
            * (coalesce(cb.Base_Rate,b.Base_Rate,0)
                + coalesce(sp.Annualized_Spread, b.Spread_Rate,0)) / 365

        -- D. 普通绝对：计算方式优先b类型参数；系数、收益率却优先cb合约参数。
        -- ABSOLUTE仍是“初始本金×系数×收益率”，不是直接取一个绝对金额。
        when coalesce(b.base_calculation, cb.base_calculation,
            sp.Spread_Calculation, 'ABSOLUTE') = 'ABSOLUTE' then
            if((info.Strt_Pric_Date < '2023-01-01' and dy.busi_date = '2023-01-01')
                or info.Strt_Pric_Date = dy.busi_date,
                coalesce(dy.Init_Nom_Prin, 0)
                * coalesce(cb.Base_Coef,b.Base_Coef,0)
                * (coalesce(cb.Base_Rate,b.Base_Rate,0)
                    + coalesce(sp.Absolute_Spread, b.Spread_Rate,0)), 0)

        -- E. 普通年化：用107491给出的逐日本金，不再加期初/期末日期IF。
        -- 类型计算方式为空串时不会触发COALESCE回退；非两种已知值时CASE结果NULL。
        when coalesce(b.base_calculation, cb.base_calculation,
            sp.Spread_Calculation, 'ABSOLUTE') = 'ANNUALIZED' then
            coalesce(dy.Dyna_Nom_Prin, 0)
            * coalesce(cb.Base_Coef,b.Base_Coef,0)
            * (coalesce(cb.Base_Rate,b.Base_Rate,0)
                + coalesce(sp.Annualized_Spread, b.Spread_Rate,0)) / 365
    end as Sales_Income,
    dy.busi_date as Accrued_Date, -- 附加明细业务日转为日报计提日期
    info.Intr_Marg,
    if(info.Ex_Rate_Model in ('SHENZHEN_HONGKONG_STOCK_CONNECT','SHANGHAI_HONGKONG_STOCK_CONNECT'),info.Ex_Rate_Model,null) as Ex_Rate_Model,
    '${yyyy-MM-dd}' as busi_date
from contract_info info
-- 107491销售收入附加明细：本金来自每个合约日；只按合约号接，不再限定grp_id。
inner join (
    select * from PDATA_N.T98_OTC_DERI_COMP_SALE_ADTNL_DET
    where busi_date >= '2023-01-01'
    ) dy
on info.agt_id = dy.agt_id
-- OTC衍生品客户：删除标志0且监控标志1，或两个指定客户例外；限定加工日来源。
-- INNER JOIN无DISTINCT：无客户命中则丢行，多条客户记录也可扩行。
inner join (
    select Pty_Id
    from PDATA_N.T01_OTC_DERI_CUST
    where Src_Tbl in ('ODATA_N_OIS.O_OTC_DERIVATIVE_COUNTERPARTY') and busi_date = '${yyyy-MM-dd}'
        and ((Del_Flag = '0' and Montr_Flag = '1') or Pty_Id in ('DEV1100100652','DEV1100101701'))
    ) cp
on info.Cutp_Pty_Id = cp.Pty_Id
-- B2B辅助估值按主合约号匹配；其他收入分支不使用npv。
left join b2b_initial_value npv
on npv.Agt_Id = info.Agt_Id
-- 映射用标的类别＋源类型＋源子类型；映射子类型NULL表示可回退主体值，空串不同。
-- 即使info已有显式经营分类仍然连接mp，CASE优先取info不能消除mp多匹配扩行。
left join inr_type_mapping mp
on coalesce(mp.Undrl_Type,'') = coalesce(info.Undrl_Type_n,'')
    and mp.Src_Contr_Type = info.Src_Contr_Type
    and coalesce(mp.Src_Sub_Contr_Type,info.Src_Sub_Contr_Type,'') = coalesce(info.Src_Sub_Contr_Type,'')
-- sp：原合约号＋计提日，价差可在同一合约存续中切换。
left join inr_spread_days sp
on sp.CONTRACT_CODE = dy.Agt_Id and sp.busi_date = dy.busi_date
-- b：最终经营分类＋期初日；配置在后来更新不自动让老合约改用新生效段。
left join inr_type_base_days b
on b.OTC_CONTRACT_TYPE = coalesce(info.Inr_Contr_Type_Cd, mp.otc_contract_type, 'CD017') and b.busi_date = info.Strt_Pric_Date
-- cb：原合约号，无日期或最新一条选择；缺参保留行，多参数行会扩行。
left join inr_contract_base cb
on cb.CONTRACT_CODE = info.agt_id

),
allocated_day_income AS (
-- 用途：接04的每条合约日收入t，补当前内部经办人，按100/0或40/60分配收入并累计。
-- 不按40/60拆本金；不使用交叉介绍关系Allo_Prop_1/2/3。
-- 输出allocated_day_income，06按冻结字段顺序写出。
-- 窗口按合约号分区、计提日排序，未明确ROWS框架；同日多条可能作为同日组一起累计。
-- INR_DEMO承接04：每日100/80/50/0；有内部引入 → 主40/32/20/0、引入60/48/30/0。
-- 本例末日累计收入230、主92、引入138；累计本金8395000是每日金额之和，不是日均。
select
    t.Agt_Id,
    t.Busi_Type,
    t.Cutp_Pty_Id,
    t.Cutp_Pty_Shor_Name,
    t.Cutp_Pty_Full_Name,
    t.Sign_Prd_Name,
    t.Contr_Type_Cd,
    t.Contr_Type_Desc,
    t.Src_Contr_Type,
    t.Src_Contr_Type_Desc,
    t.Src_Sub_Contr_Type,
    t.Src_Sub_Contr_Type_Desc,
    t.Rel_Agt_Id,
    t.Undrl_Wd_Cd,
    t.Undrl_Name,
    t.Undrl_Type,
    t.Undrl_Type_Desc,
    t.Src_Undrl_Type,
    t.Src_Undrl_Type_Desc,
    t.Indt_Cd,
    t.Hedg_Type_Cd,
    t.fee_rate,
    t.Fin_Rati,
    t.Base_Coef,
    t.Base_Rate,
    t.Sprd_Rate,
    t.Strt_Pric_Date,
    t.End_Pric_Date,
    t.Actl_Days,
    t.Is_Preterm_Flag,
    t.Early_Term_Date,
    t.Agt_Stat_Cd,

    -- 金额在这一层才补0；原始收入NULL可来自B2B关联缺失或未知计算类型。
    coalesce(t.Init_Nom_Prin,0) as Init_Nom_Prin,
    coalesce(t.Dyna_Nom_Prin,0) as Dyna_Nom_Prin,
    coalesce(t.Sales_Income,0) as Sales_Income,
    -- NULL或空串内部引入ID → 100/0；非空 → 40/60，不额外校验主经办ID。
    IF(coalesce(m.Inr_Intro_Oper_User_Id,'') = '',
        coalesce(t.Sales_Income,0) * 1, coalesce(t.Sales_Income,0) * 0.4) AS Sales_Income_Main,
    IF(coalesce(m.Inr_Intro_Oper_User_Id,'') = '',
        coalesce(t.Sales_Income,0) * 0, coalesce(t.Sales_Income,0) * 0.6) AS Sales_Income_Intro,

    -- 源字段明确是内部经办人，输出列去掉Inr前缀但没有切换到交叉经办关系。
    m.Inr_Main_Oper_User_Id as Main_Oper_User_Id,
    m.Inr_Main_Oper_Name as Main_Oper_Name,
    m.Inr_Main_Oper_Emp_Id as Main_Oper_Emp_Id,
    m.Inr_Intro_Oper_User_Id as Intro_Oper_User_Id,
    m.Inr_Intro_Oper_Name as Intro_Oper_Name,
    m.Inr_Intro_Oper_Emp_Id as Intro_Oper_Emp_Id,
    t.Accrued_Date,
    from_unixtime(unix_timestamp(),'yyyy-MM-dd HH:mm:ss') as Data_Time,
    t.Intr_Marg,

    -- 累计本金仅计起止日内，End_Pric_Date已经是01提前终止日优先的边界。
    sum(if(t.Accrued_Date BETWEEN Strt_Pric_Date AND End_Pric_Date, coalesce(t.Dyna_Nom_Prin, 0),0))
        over(partition by t.agt_id order by accrued_date) as Accum_Dyna_Nom_Prin,
    -- 累计收入没有上述日期IF，也没有最大值0限制；负收入照常累加。
    sum(coalesce(Sales_Income, 0))
        over(partition by t.agt_id order by accrued_date) as Accum_Sales_Income,
    sum(IF(coalesce(m.Inr_Intro_Oper_User_Id,'') = '',
        coalesce(t.Sales_Income,0) * 1, coalesce(t.Sales_Income,0) * 0.4))
        over(partition by t.agt_id order by accrued_date) as Accum_Sales_Income_Main,
    sum(IF(coalesce(m.Inr_Intro_Oper_User_Id,'') = '',
        coalesce(t.Sales_Income,0) * 0, coalesce(t.Sales_Income,0) * 0.6))
        over(partition by t.agt_id order by accrued_date) as Accum_Sales_Income_Intro,
    t.Ex_Rate_Model,
    '${yyyy-MM-dd}' as busi_date
from contract_day_income t
-- OTC合约管理关系：本次快照的内部经办人连接所有计提日。
-- 缺失仍保留收入行，ID为空且按100/0；多条关系会扩行，并在本层窗口中累计。
left join (
    select * from PDATA_N.T98_OTC_COMP_MNG_RELA_INFO
    where busi_date = '${yyyy-MM-dd}'
    ) m
on m.Agt_Id = t.Agt_Id

)
-- 用途：接05，按原52列顺序输出到dm_otc_n.otc_inr_sale_daily_rpt（由任务配置承接）。
-- 该冻结片段为querySql，本文件不补造INSERT，也不执行写入。
-- Sales_Income是05补0后的当日收入；Accrued_Date是计提日，busi_date是加工日。
-- 只有原CAST列转String；Intr_Marg及四项累计、Ex_Rate_Model保持原写法。
-- INR_DEMO的9/21行：当日收入0，累计收入230、主92、引入138；9/18行当日收入100。
SELECT
    CAST( Agt_Id AS String ) Agt_Id , -- 合约编号
    CAST( Busi_Type AS String ) Busi_Type , -- 业务类型
    CAST( Cutp_Pty_Id AS String ) Cutp_Pty_Id , -- 交易对手客户编号
    CAST( Cutp_Pty_Shor_Name AS String ) Cutp_Pty_Shor_Name , -- 交易对手当事人简称
    CAST( Cutp_Pty_Full_Name AS String ) Cutp_Pty_Full_Name , -- 交易对手当事人名称
    CAST( Sign_Prd_Name AS String ) Sign_Prd_Name , -- 代签产品名称
    CAST( Contr_Type_Cd AS String ) Contr_Type_Cd , -- 合约类型代码；04选出的对内经营分类
    CAST( Contr_Type_Desc AS String ) Contr_Type_Desc , -- 合约类型描述
    CAST( Src_Contr_Type AS String ) Src_Contr_Type , -- 源合约类型
    CAST( Src_Contr_Type_Desc AS String ) Src_Contr_Type_Desc , -- 源合约类型描述
    CAST( Src_Sub_Contr_Type AS String ) Src_Sub_Contr_Type , -- 源合约子类型
    CAST( Src_Sub_Contr_Type_Desc AS String ) Src_Sub_Contr_Type_Desc , -- 源合约子类型描述
    CAST( Rel_Agt_Id AS String ) Rel_Agt_Id , -- 关联合约编号
    CAST( Undrl_Wd_Cd AS String ) Undrl_Wd_Cd , -- 标的WD代码
    CAST( Undrl_Name AS String ) Undrl_Name , -- 标的名称
    CAST( Undrl_Type AS String ) Undrl_Type , -- 标的类型
    CAST( Undrl_Type_Desc AS String ) Undrl_Type_Desc , -- 标的类型描述
    CAST( Src_Undrl_Type AS String ) Src_Undrl_Type , -- 源标的类型
    CAST( Src_Undrl_Type_Desc AS String ) Src_Undrl_Type_Desc , -- 源标的类型描述
    CAST( Indt_Cd AS String ) Indt_Cd , -- 行业代码
    CAST( Hedg_Type_Cd AS String ) Hedg_Type_Cd , -- 对冲类型代码
    CAST( fee_rate AS String ) fee_rate , -- 成交费率
    CAST( Fin_Rati AS String ) Fin_Rati , -- 融资比例；展示值，不直接作为两组特殊公式的统一乘数
    CAST( Base_Coef AS String ) Base_Coef , -- 基础系数
    CAST( Base_Rate AS String ) Base_Rate , -- 基础收益率
    CAST( Sprd_Rate AS String ) Sprd_Rate , -- 价差收益率；展示取法可能与收入实际分支不同
    CAST( Strt_Pric_Date AS String ) Strt_Pric_Date , -- 期初定价日
    CAST( End_Pric_Date AS String ) End_Pric_Date , -- 期末定价日；已优先提前终止日
    CAST( Actl_Days AS String ) Actl_Days , -- 实际天数；直接来自主信息期限天数
    CAST( Is_Preterm_Flag AS String ) Is_Preterm_Flag , -- 是否提前终止标识
    CAST( Early_Term_Date AS String ) Early_Term_Date , -- 提前终止日
    CAST( Agt_Stat_Cd AS String ) Agt_Stat_Cd , -- 协议状态代码
    CAST( Init_Nom_Prin AS String ) Init_Nom_Prin , -- 期初名义本金
    CAST( Dyna_Nom_Prin AS String ) Dyna_Nom_Prin , -- 动态名义本金
    CAST( Sales_Income AS String ) Sales_Income , -- 当日计提销售收入；05已将NULL补0
    CAST( Sales_Income_Main AS String ) Sales_Income_Main , -- 主经办人当日计提销售收入
    CAST( Sales_Income_Intro AS String ) Sales_Income_Intro , -- 引入经办人当日计提销售收入
    CAST( Main_Oper_User_Id AS String ) Main_Oper_User_Id , -- 主经办人USER_ID
    CAST( Main_Oper_Name AS String ) Main_Oper_Name , -- 主经办人姓名
    CAST( Main_Oper_Emp_Id AS String ) Main_Oper_Emp_Id , -- 主经办人ERP编号
    CAST( Intro_Oper_User_Id AS String ) Intro_Oper_User_Id , -- 引入经办人USER_ID
    CAST( Intro_Oper_Name AS String ) Intro_Oper_Name , -- 引入经办人姓名
    CAST( Intro_Oper_Emp_Id AS String ) Intro_Oper_Emp_Id , -- 引入经办人ERP编号
    CAST( Accrued_Date AS String ) Accrued_Date , -- 计提日期
    CAST( Data_Time AS String ) Data_Time , -- 数据时间
    Intr_Marg, -- 利差
    Accum_Dyna_Nom_Prin, -- 累计动态名义本金；起止日内每日本金之和
    Accum_Sales_Income, -- 累计销售收入
    Accum_Sales_Income_Main, -- 主经办人累计计提销售收入
    Accum_Sales_Income_Intro, -- 引入经办人累计销售收入
    Ex_Rate_Model, -- 汇率模式
    CAST( busi_date AS String ) busi_date -- 业务日期；此处固定为加工日
FROM allocated_day_income castTable

